package net.tslat.aoa3.structure.precasia;

import net.minecraft.block.state.IBlockState;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
import net.tslat.aoa3.common.registration.BlockRegister;
import net.tslat.aoa3.structure.AoAStructure;

import java.util.Random;

public class DomiguousTree2 extends AoAStructure { //StructureSize: 11x28x11
	private static final IBlockState domiguousLeaves = BlockRegister.leavesDomiguous.getDefaultState();
	private static final IBlockState domiguousLog = BlockRegister.logDomiguous.getDefaultState();

	public DomiguousTree2() {
		super("DomiguousTree2");
	}

	@Override
	protected void build(World world, Random rand, BlockPos basePos) {
		addBlock(world, basePos, 5, 0, 5, domiguousLog);
		addBlock(world, basePos, 5, 1, 5, domiguousLog);
		addBlock(world, basePos, 5, 2, 5, domiguousLog);
		addBlock(world, basePos, 5, 3, 5, domiguousLog);
		addBlock(world, basePos, 5, 4, 5, domiguousLog);
		addBlock(world, basePos, 5, 5, 5, domiguousLog);
		addBlock(world, basePos, 5, 6, 5, domiguousLog);
		addBlock(world, basePos, 5, 7, 5, domiguousLog);
		addBlock(world, basePos, 5, 8, 5, domiguousLog);
		addBlock(world, basePos, 5, 9, 5, domiguousLog);
		addBlock(world, basePos, 5, 10, 5, domiguousLog);
		addBlock(world, basePos, 5, 11, 5, domiguousLog);
		addBlock(world, basePos, 5, 12, 5, domiguousLog);
		addBlock(world, basePos, 5, 13, 5, domiguousLog);
		addBlock(world, basePos, 5, 14, 5, domiguousLog);
		addBlock(world, basePos, 5, 15, 5, domiguousLog);
		addBlock(world, basePos, 5, 16, 5, domiguousLog);
		addBlock(world, basePos, 5, 17, 5, domiguousLog);
		addBlock(world, basePos, 5, 18, 5, domiguousLog);
		addBlock(world, basePos, 5, 19, 5, domiguousLog);
		addBlock(world, basePos, 5, 20, 5, domiguousLog);
		addBlock(world, basePos, 5, 21, 5, domiguousLog);
		addBlock(world, basePos, 5, 22, 5, domiguousLog);
		addBlock(world, basePos, 4, 23, 5, domiguousLog);
		addBlock(world, basePos, 5, 23, 4, domiguousLog);
		addBlock(world, basePos, 5, 23, 5, domiguousLog);
		addBlock(world, basePos, 5, 23, 6, domiguousLog);
		addBlock(world, basePos, 6, 23, 5, domiguousLog);
		addBlock(world, basePos, 3, 24, 5, domiguousLog);
		addBlock(world, basePos, 5, 24, 3, domiguousLog);
		addBlock(world, basePos, 5, 24, 5, domiguousLog);
		addBlock(world, basePos, 5, 24, 7, domiguousLog);
		addBlock(world, basePos, 7, 24, 5, domiguousLog);
		addBlock(world, basePos, 0, 25, 0, domiguousLeaves);
		addBlock(world, basePos, 0, 25, 1, domiguousLeaves);
		addBlock(world, basePos, 0, 25, 2, domiguousLeaves);
		addBlock(world, basePos, 0, 25, 3, domiguousLeaves);
		addBlock(world, basePos, 0, 25, 4, domiguousLeaves);
		addBlock(world, basePos, 0, 25, 5, domiguousLeaves);
		addBlock(world, basePos, 0, 25, 6, domiguousLeaves);
		addBlock(world, basePos, 0, 25, 7, domiguousLeaves);
		addBlock(world, basePos, 0, 25, 8, domiguousLeaves);
		addBlock(world, basePos, 0, 25, 9, domiguousLeaves);
		addBlock(world, basePos, 0, 25, 10, domiguousLeaves);
		addBlock(world, basePos, 1, 25, 0, domiguousLeaves);
		addBlock(world, basePos, 1, 25, 1, domiguousLeaves);
		addBlock(world, basePos, 1, 25, 2, domiguousLeaves);
		addBlock(world, basePos, 1, 25, 3, domiguousLeaves);
		addBlock(world, basePos, 1, 25, 4, domiguousLeaves);
		addBlock(world, basePos, 1, 25, 5, domiguousLeaves);
		addBlock(world, basePos, 1, 25, 6, domiguousLeaves);
		addBlock(world, basePos, 1, 25, 7, domiguousLeaves);
		addBlock(world, basePos, 1, 25, 8, domiguousLeaves);
		addBlock(world, basePos, 1, 25, 9, domiguousLeaves);
		addBlock(world, basePos, 1, 25, 10, domiguousLeaves);
		addBlock(world, basePos, 2, 25, 0, domiguousLeaves);
		addBlock(world, basePos, 2, 25, 1, domiguousLeaves);
		addBlock(world, basePos, 2, 25, 9, domiguousLeaves);
		addBlock(world, basePos, 2, 25, 10, domiguousLeaves);
		addBlock(world, basePos, 3, 25, 0, domiguousLeaves);
		addBlock(world, basePos, 3, 25, 1, domiguousLeaves);
		addBlock(world, basePos, 3, 25, 5, domiguousLog);
		addBlock(world, basePos, 3, 25, 9, domiguousLeaves);
		addBlock(world, basePos, 3, 25, 10, domiguousLeaves);
		addBlock(world, basePos, 4, 25, 0, domiguousLeaves);
		addBlock(world, basePos, 4, 25, 1, domiguousLeaves);
		addBlock(world, basePos, 4, 25, 9, domiguousLeaves);
		addBlock(world, basePos, 4, 25, 10, domiguousLeaves);
		addBlock(world, basePos, 5, 25, 0, domiguousLeaves);
		addBlock(world, basePos, 5, 25, 1, domiguousLeaves);
		addBlock(world, basePos, 5, 25, 3, domiguousLog);
		addBlock(world, basePos, 5, 25, 5, domiguousLog);
		addBlock(world, basePos, 5, 25, 7, domiguousLog);
		addBlock(world, basePos, 5, 25, 9, domiguousLeaves);
		addBlock(world, basePos, 5, 25, 10, domiguousLeaves);
		addBlock(world, basePos, 6, 25, 0, domiguousLeaves);
		addBlock(world, basePos, 6, 25, 1, domiguousLeaves);
		addBlock(world, basePos, 6, 25, 9, domiguousLeaves);
		addBlock(world, basePos, 6, 25, 10, domiguousLeaves);
		addBlock(world, basePos, 7, 25, 0, domiguousLeaves);
		addBlock(world, basePos, 7, 25, 1, domiguousLeaves);
		addBlock(world, basePos, 7, 25, 5, domiguousLog);
		addBlock(world, basePos, 7, 25, 9, domiguousLeaves);
		addBlock(world, basePos, 7, 25, 10, domiguousLeaves);
		addBlock(world, basePos, 8, 25, 0, domiguousLeaves);
		addBlock(world, basePos, 8, 25, 1, domiguousLeaves);
		addBlock(world, basePos, 8, 25, 9, domiguousLeaves);
		addBlock(world, basePos, 8, 25, 10, domiguousLeaves);
		addBlock(world, basePos, 9, 25, 0, domiguousLeaves);
		addBlock(world, basePos, 9, 25, 1, domiguousLeaves);
		addBlock(world, basePos, 9, 25, 2, domiguousLeaves);
		addBlock(world, basePos, 9, 25, 3, domiguousLeaves);
		addBlock(world, basePos, 9, 25, 4, domiguousLeaves);
		addBlock(world, basePos, 9, 25, 5, domiguousLeaves);
		addBlock(world, basePos, 9, 25, 6, domiguousLeaves);
		addBlock(world, basePos, 9, 25, 7, domiguousLeaves);
		addBlock(world, basePos, 9, 25, 8, domiguousLeaves);
		addBlock(world, basePos, 9, 25, 9, domiguousLeaves);
		addBlock(world, basePos, 9, 25, 10, domiguousLeaves);
		addBlock(world, basePos, 10, 25, 0, domiguousLeaves);
		addBlock(world, basePos, 10, 25, 1, domiguousLeaves);
		addBlock(world, basePos, 10, 25, 2, domiguousLeaves);
		addBlock(world, basePos, 10, 25, 3, domiguousLeaves);
		addBlock(world, basePos, 10, 25, 4, domiguousLeaves);
		addBlock(world, basePos, 10, 25, 5, domiguousLeaves);
		addBlock(world, basePos, 10, 25, 6, domiguousLeaves);
		addBlock(world, basePos, 10, 25, 7, domiguousLeaves);
		addBlock(world, basePos, 10, 25, 8, domiguousLeaves);
		addBlock(world, basePos, 10, 25, 9, domiguousLeaves);
		addBlock(world, basePos, 10, 25, 10, domiguousLeaves);
		addBlock(world, basePos, 2, 26, 2, domiguousLeaves);
		addBlock(world, basePos, 2, 26, 3, domiguousLeaves);
		addBlock(world, basePos, 2, 26, 4, domiguousLeaves);
		addBlock(world, basePos, 2, 26, 5, domiguousLeaves);
		addBlock(world, basePos, 2, 26, 6, domiguousLeaves);
		addBlock(world, basePos, 2, 26, 7, domiguousLeaves);
		addBlock(world, basePos, 2, 26, 8, domiguousLeaves);
		addBlock(world, basePos, 3, 26, 2, domiguousLeaves);
		addBlock(world, basePos, 3, 26, 3, domiguousLeaves);
		addBlock(world, basePos, 3, 26, 4, domiguousLeaves);
		addBlock(world, basePos, 3, 26, 5, domiguousLeaves);
		addBlock(world, basePos, 3, 26, 6, domiguousLeaves);
		addBlock(world, basePos, 3, 26, 7, domiguousLeaves);
		addBlock(world, basePos, 3, 26, 8, domiguousLeaves);
		addBlock(world, basePos, 4, 26, 2, domiguousLeaves);
		addBlock(world, basePos, 4, 26, 3, domiguousLeaves);
		addBlock(world, basePos, 4, 26, 7, domiguousLeaves);
		addBlock(world, basePos, 4, 26, 8, domiguousLeaves);
		addBlock(world, basePos, 5, 26, 2, domiguousLeaves);
		addBlock(world, basePos, 5, 26, 3, domiguousLeaves);
		addBlock(world, basePos, 5, 26, 5, domiguousLog);
		addBlock(world, basePos, 5, 26, 7, domiguousLeaves);
		addBlock(world, basePos, 5, 26, 8, domiguousLeaves);
		addBlock(world, basePos, 6, 26, 2, domiguousLeaves);
		addBlock(world, basePos, 6, 26, 3, domiguousLeaves);
		addBlock(world, basePos, 6, 26, 7, domiguousLeaves);
		addBlock(world, basePos, 6, 26, 8, domiguousLeaves);
		addBlock(world, basePos, 7, 26, 2, domiguousLeaves);
		addBlock(world, basePos, 7, 26, 3, domiguousLeaves);
		addBlock(world, basePos, 7, 26, 4, domiguousLeaves);
		addBlock(world, basePos, 7, 26, 5, domiguousLeaves);
		addBlock(world, basePos, 7, 26, 6, domiguousLeaves);
		addBlock(world, basePos, 7, 26, 7, domiguousLeaves);
		addBlock(world, basePos, 7, 26, 8, domiguousLeaves);
		addBlock(world, basePos, 8, 26, 2, domiguousLeaves);
		addBlock(world, basePos, 8, 26, 3, domiguousLeaves);
		addBlock(world, basePos, 8, 26, 4, domiguousLeaves);
		addBlock(world, basePos, 8, 26, 5, domiguousLeaves);
		addBlock(world, basePos, 8, 26, 6, domiguousLeaves);
		addBlock(world, basePos, 8, 26, 7, domiguousLeaves);
		addBlock(world, basePos, 8, 26, 8, domiguousLeaves);
		addBlock(world, basePos, 4, 27, 4, domiguousLeaves);
		addBlock(world, basePos, 4, 27, 5, domiguousLeaves);
		addBlock(world, basePos, 4, 27, 6, domiguousLeaves);
		addBlock(world, basePos, 5, 27, 4, domiguousLeaves);
		addBlock(world, basePos, 5, 27, 5, domiguousLeaves);
		addBlock(world, basePos, 5, 27, 6, domiguousLeaves);
		addBlock(world, basePos, 6, 27, 4, domiguousLeaves);
		addBlock(world, basePos, 6, 27, 5, domiguousLeaves);
		addBlock(world, basePos, 6, 27, 6, domiguousLeaves);
	}
}
