package net.tslat.aoa3.structure.voxponds;

import net.minecraft.block.state.IBlockState;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
import net.tslat.aoa3.common.registration.BlockRegister;
import net.tslat.aoa3.structure.AoAStructure;

import java.util.Random;

public class DegradedSupportBeam2 extends AoAStructure { //StructureSize: 5x16x5
	private static final IBlockState degradedSteel = BlockRegister.DEGRADED_STEEL.getDefaultState();

	public DegradedSupportBeam2() {
		super("DegradedSupportBeam2");
	}

	@Override
	protected void build(World world, Random rand, BlockPos basePos) {
		addBlock(world, basePos, 0, 0, 0, degradedSteel);
		addBlock(world, basePos, 0, 0, 4, degradedSteel);
		addBlock(world, basePos, 2, 0, 2, degradedSteel);
		addBlock(world, basePos, 4, 0, 0, degradedSteel);
		addBlock(world, basePos, 4, 0, 4, degradedSteel);
		addBlock(world, basePos, 0, 1, 0, degradedSteel);
		addBlock(world, basePos, 0, 1, 4, degradedSteel);
		addBlock(world, basePos, 2, 1, 2, degradedSteel);
		addBlock(world, basePos, 4, 1, 0, degradedSteel);
		addBlock(world, basePos, 4, 1, 4, degradedSteel);
		addBlock(world, basePos, 0, 2, 0, degradedSteel);
		addBlock(world, basePos, 0, 2, 4, degradedSteel);
		addBlock(world, basePos, 2, 2, 2, degradedSteel);
		addBlock(world, basePos, 4, 2, 0, degradedSteel);
		addBlock(world, basePos, 4, 2, 4, degradedSteel);
		addBlock(world, basePos, 0, 3, 0, degradedSteel);
		addBlock(world, basePos, 0, 3, 1, degradedSteel);
		addBlock(world, basePos, 0, 3, 2, degradedSteel);
		addBlock(world, basePos, 0, 3, 3, degradedSteel);
		addBlock(world, basePos, 0, 3, 4, degradedSteel);
		addBlock(world, basePos, 1, 3, 0, degradedSteel);
		addBlock(world, basePos, 1, 3, 2, degradedSteel);
		addBlock(world, basePos, 1, 3, 4, degradedSteel);
		addBlock(world, basePos, 2, 3, 0, degradedSteel);
		addBlock(world, basePos, 2, 3, 1, degradedSteel);
		addBlock(world, basePos, 2, 3, 2, degradedSteel);
		addBlock(world, basePos, 2, 3, 3, degradedSteel);
		addBlock(world, basePos, 2, 3, 4, degradedSteel);
		addBlock(world, basePos, 3, 3, 0, degradedSteel);
		addBlock(world, basePos, 3, 3, 2, degradedSteel);
		addBlock(world, basePos, 3, 3, 4, degradedSteel);
		addBlock(world, basePos, 4, 3, 0, degradedSteel);
		addBlock(world, basePos, 4, 3, 1, degradedSteel);
		addBlock(world, basePos, 4, 3, 2, degradedSteel);
		addBlock(world, basePos, 4, 3, 3, degradedSteel);
		addBlock(world, basePos, 4, 3, 4, degradedSteel);
		addBlock(world, basePos, 0, 4, 0, degradedSteel);
		addBlock(world, basePos, 0, 4, 4, degradedSteel);
		addBlock(world, basePos, 2, 4, 2, degradedSteel);
		addBlock(world, basePos, 4, 4, 0, degradedSteel);
		addBlock(world, basePos, 4, 4, 4, degradedSteel);
		addBlock(world, basePos, 0, 5, 0, degradedSteel);
		addBlock(world, basePos, 0, 5, 4, degradedSteel);
		addBlock(world, basePos, 2, 5, 2, degradedSteel);
		addBlock(world, basePos, 4, 5, 0, degradedSteel);
		addBlock(world, basePos, 4, 5, 4, degradedSteel);
		addBlock(world, basePos, 0, 6, 0, degradedSteel);
		addBlock(world, basePos, 0, 6, 4, degradedSteel);
		addBlock(world, basePos, 2, 6, 2, degradedSteel);
		addBlock(world, basePos, 4, 6, 0, degradedSteel);
		addBlock(world, basePos, 4, 6, 4, degradedSteel);
		addBlock(world, basePos, 0, 7, 0, degradedSteel);
		addBlock(world, basePos, 0, 7, 1, degradedSteel);
		addBlock(world, basePos, 0, 7, 2, degradedSteel);
		addBlock(world, basePos, 0, 7, 3, degradedSteel);
		addBlock(world, basePos, 0, 7, 4, degradedSteel);
		addBlock(world, basePos, 1, 7, 0, degradedSteel);
		addBlock(world, basePos, 1, 7, 2, degradedSteel);
		addBlock(world, basePos, 1, 7, 4, degradedSteel);
		addBlock(world, basePos, 2, 7, 0, degradedSteel);
		addBlock(world, basePos, 2, 7, 1, degradedSteel);
		addBlock(world, basePos, 2, 7, 2, degradedSteel);
		addBlock(world, basePos, 2, 7, 3, degradedSteel);
		addBlock(world, basePos, 2, 7, 4, degradedSteel);
		addBlock(world, basePos, 3, 7, 0, degradedSteel);
		addBlock(world, basePos, 3, 7, 2, degradedSteel);
		addBlock(world, basePos, 3, 7, 4, degradedSteel);
		addBlock(world, basePos, 4, 7, 0, degradedSteel);
		addBlock(world, basePos, 4, 7, 1, degradedSteel);
		addBlock(world, basePos, 4, 7, 2, degradedSteel);
		addBlock(world, basePos, 4, 7, 3, degradedSteel);
		addBlock(world, basePos, 4, 7, 4, degradedSteel);
		addBlock(world, basePos, 0, 8, 0, degradedSteel);
		addBlock(world, basePos, 0, 8, 4, degradedSteel);
		addBlock(world, basePos, 2, 8, 2, degradedSteel);
		addBlock(world, basePos, 4, 8, 0, degradedSteel);
		addBlock(world, basePos, 4, 8, 4, degradedSteel);
		addBlock(world, basePos, 0, 9, 0, degradedSteel);
		addBlock(world, basePos, 0, 9, 4, degradedSteel);
		addBlock(world, basePos, 2, 9, 2, degradedSteel);
		addBlock(world, basePos, 4, 9, 0, degradedSteel);
		addBlock(world, basePos, 4, 9, 4, degradedSteel);
		addBlock(world, basePos, 0, 10, 0, degradedSteel);
		addBlock(world, basePos, 0, 10, 4, degradedSteel);
		addBlock(world, basePos, 2, 10, 2, degradedSteel);
		addBlock(world, basePos, 4, 10, 0, degradedSteel);
		addBlock(world, basePos, 4, 10, 4, degradedSteel);
		addBlock(world, basePos, 0, 11, 0, degradedSteel);
		addBlock(world, basePos, 0, 11, 1, degradedSteel);
		addBlock(world, basePos, 0, 11, 2, degradedSteel);
		addBlock(world, basePos, 0, 11, 3, degradedSteel);
		addBlock(world, basePos, 0, 11, 4, degradedSteel);
		addBlock(world, basePos, 1, 11, 0, degradedSteel);
		addBlock(world, basePos, 1, 11, 2, degradedSteel);
		addBlock(world, basePos, 1, 11, 4, degradedSteel);
		addBlock(world, basePos, 2, 11, 0, degradedSteel);
		addBlock(world, basePos, 2, 11, 1, degradedSteel);
		addBlock(world, basePos, 2, 11, 2, degradedSteel);
		addBlock(world, basePos, 2, 11, 3, degradedSteel);
		addBlock(world, basePos, 2, 11, 4, degradedSteel);
		addBlock(world, basePos, 3, 11, 0, degradedSteel);
		addBlock(world, basePos, 3, 11, 2, degradedSteel);
		addBlock(world, basePos, 3, 11, 4, degradedSteel);
		addBlock(world, basePos, 4, 11, 0, degradedSteel);
		addBlock(world, basePos, 4, 11, 1, degradedSteel);
		addBlock(world, basePos, 4, 11, 2, degradedSteel);
		addBlock(world, basePos, 4, 11, 3, degradedSteel);
		addBlock(world, basePos, 4, 11, 4, degradedSteel);
		addBlock(world, basePos, 0, 12, 0, degradedSteel);
		addBlock(world, basePos, 0, 12, 4, degradedSteel);
		addBlock(world, basePos, 2, 12, 2, degradedSteel);
		addBlock(world, basePos, 4, 12, 0, degradedSteel);
		addBlock(world, basePos, 4, 12, 4, degradedSteel);
		addBlock(world, basePos, 0, 13, 0, degradedSteel);
		addBlock(world, basePos, 0, 13, 4, degradedSteel);
		addBlock(world, basePos, 2, 13, 2, degradedSteel);
		addBlock(world, basePos, 4, 13, 0, degradedSteel);
		addBlock(world, basePos, 4, 13, 4, degradedSteel);
		addBlock(world, basePos, 0, 14, 0, degradedSteel);
		addBlock(world, basePos, 0, 14, 4, degradedSteel);
		addBlock(world, basePos, 2, 14, 2, degradedSteel);
		addBlock(world, basePos, 4, 14, 0, degradedSteel);
		addBlock(world, basePos, 4, 14, 4, degradedSteel);
		addBlock(world, basePos, 0, 15, 0, degradedSteel);
		addBlock(world, basePos, 0, 15, 1, degradedSteel);
		addBlock(world, basePos, 0, 15, 2, degradedSteel);
		addBlock(world, basePos, 0, 15, 3, degradedSteel);
		addBlock(world, basePos, 0, 15, 4, degradedSteel);
		addBlock(world, basePos, 1, 15, 0, degradedSteel);
		addBlock(world, basePos, 1, 15, 2, degradedSteel);
		addBlock(world, basePos, 1, 15, 4, degradedSteel);
		addBlock(world, basePos, 2, 15, 0, degradedSteel);
		addBlock(world, basePos, 2, 15, 1, degradedSteel);
		addBlock(world, basePos, 2, 15, 2, degradedSteel);
		addBlock(world, basePos, 2, 15, 3, degradedSteel);
		addBlock(world, basePos, 2, 15, 4, degradedSteel);
		addBlock(world, basePos, 3, 15, 0, degradedSteel);
		addBlock(world, basePos, 3, 15, 2, degradedSteel);
		addBlock(world, basePos, 3, 15, 4, degradedSteel);
		addBlock(world, basePos, 4, 15, 0, degradedSteel);
		addBlock(world, basePos, 4, 15, 1, degradedSteel);
		addBlock(world, basePos, 4, 15, 2, degradedSteel);
		addBlock(world, basePos, 4, 15, 3, degradedSteel);
		addBlock(world, basePos, 4, 15, 4, degradedSteel);
	}
}
