package net.tslat.aoa3.structure.candyland;

import net.minecraft.block.state.IBlockState;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
import net.tslat.aoa3.common.registration.BlockRegister;
import net.tslat.aoa3.structure.AoAStructure;

import java.util.Random;

public class CottonCandyTree2 extends AoAStructure { //StructureSize: 5x13x5
	private static final IBlockState pinkCottonCandy = BlockRegister.cottonCandyPink.getDefaultState();
	private static final IBlockState plasticPole = BlockRegister.plastic.getDefaultState();

	public CottonCandyTree2() {
		super("CottonCandyTree2");
	}

	@Override
	protected void build(World world, Random rand, BlockPos basePos) {
		addBlock(world, basePos, 2, 0, 2, plasticPole);
		addBlock(world, basePos, 2, 1, 2, plasticPole);
		addBlock(world, basePos, 2, 2, 2, plasticPole);
		addBlock(world, basePos, 2, 3, 2, plasticPole);
		addBlock(world, basePos, 2, 4, 2, plasticPole);
		addBlock(world, basePos, 2, 5, 2, plasticPole);
		addBlock(world, basePos, 1, 6, 1, pinkCottonCandy);
		addBlock(world, basePos, 1, 6, 2, pinkCottonCandy);
		addBlock(world, basePos, 1, 6, 3, pinkCottonCandy);
		addBlock(world, basePos, 2, 6, 1, pinkCottonCandy);
		addBlock(world, basePos, 2, 6, 2, pinkCottonCandy);
		addBlock(world, basePos, 2, 6, 3, pinkCottonCandy);
		addBlock(world, basePos, 3, 6, 1, pinkCottonCandy);
		addBlock(world, basePos, 3, 6, 2, pinkCottonCandy);
		addBlock(world, basePos, 3, 6, 3, pinkCottonCandy);
		addBlock(world, basePos, 0, 7, 0, pinkCottonCandy);
		addBlock(world, basePos, 0, 7, 1, pinkCottonCandy);
		addBlock(world, basePos, 0, 7, 2, pinkCottonCandy);
		addBlock(world, basePos, 0, 7, 3, pinkCottonCandy);
		addBlock(world, basePos, 0, 7, 4, pinkCottonCandy);
		addBlock(world, basePos, 1, 7, 0, pinkCottonCandy);
		addBlock(world, basePos, 1, 7, 1, pinkCottonCandy);
		addBlock(world, basePos, 1, 7, 2, pinkCottonCandy);
		addBlock(world, basePos, 1, 7, 3, pinkCottonCandy);
		addBlock(world, basePos, 1, 7, 4, pinkCottonCandy);
		addBlock(world, basePos, 2, 7, 0, pinkCottonCandy);
		addBlock(world, basePos, 2, 7, 1, pinkCottonCandy);
		addBlock(world, basePos, 2, 7, 2, pinkCottonCandy);
		addBlock(world, basePos, 2, 7, 3, pinkCottonCandy);
		addBlock(world, basePos, 2, 7, 4, pinkCottonCandy);
		addBlock(world, basePos, 3, 7, 0, pinkCottonCandy);
		addBlock(world, basePos, 3, 7, 1, pinkCottonCandy);
		addBlock(world, basePos, 3, 7, 2, pinkCottonCandy);
		addBlock(world, basePos, 3, 7, 3, pinkCottonCandy);
		addBlock(world, basePos, 3, 7, 4, pinkCottonCandy);
		addBlock(world, basePos, 4, 7, 0, pinkCottonCandy);
		addBlock(world, basePos, 4, 7, 1, pinkCottonCandy);
		addBlock(world, basePos, 4, 7, 2, pinkCottonCandy);
		addBlock(world, basePos, 4, 7, 3, pinkCottonCandy);
		addBlock(world, basePos, 4, 7, 4, pinkCottonCandy);
		addBlock(world, basePos, 0, 8, 0, pinkCottonCandy);
		addBlock(world, basePos, 0, 8, 1, pinkCottonCandy);
		addBlock(world, basePos, 0, 8, 2, pinkCottonCandy);
		addBlock(world, basePos, 0, 8, 3, pinkCottonCandy);
		addBlock(world, basePos, 0, 8, 4, pinkCottonCandy);
		addBlock(world, basePos, 1, 8, 0, pinkCottonCandy);
		addBlock(world, basePos, 1, 8, 1, pinkCottonCandy);
		addBlock(world, basePos, 1, 8, 2, pinkCottonCandy);
		addBlock(world, basePos, 1, 8, 3, pinkCottonCandy);
		addBlock(world, basePos, 1, 8, 4, pinkCottonCandy);
		addBlock(world, basePos, 2, 8, 0, pinkCottonCandy);
		addBlock(world, basePos, 2, 8, 1, pinkCottonCandy);
		addBlock(world, basePos, 2, 8, 2, pinkCottonCandy);
		addBlock(world, basePos, 2, 8, 3, pinkCottonCandy);
		addBlock(world, basePos, 2, 8, 4, pinkCottonCandy);
		addBlock(world, basePos, 3, 8, 0, pinkCottonCandy);
		addBlock(world, basePos, 3, 8, 1, pinkCottonCandy);
		addBlock(world, basePos, 3, 8, 2, pinkCottonCandy);
		addBlock(world, basePos, 3, 8, 3, pinkCottonCandy);
		addBlock(world, basePos, 3, 8, 4, pinkCottonCandy);
		addBlock(world, basePos, 4, 8, 0, pinkCottonCandy);
		addBlock(world, basePos, 4, 8, 1, pinkCottonCandy);
		addBlock(world, basePos, 4, 8, 2, pinkCottonCandy);
		addBlock(world, basePos, 4, 8, 3, pinkCottonCandy);
		addBlock(world, basePos, 4, 8, 4, pinkCottonCandy);
		addBlock(world, basePos, 0, 9, 0, pinkCottonCandy);
		addBlock(world, basePos, 0, 9, 1, pinkCottonCandy);
		addBlock(world, basePos, 0, 9, 2, pinkCottonCandy);
		addBlock(world, basePos, 0, 9, 3, pinkCottonCandy);
		addBlock(world, basePos, 0, 9, 4, pinkCottonCandy);
		addBlock(world, basePos, 1, 9, 0, pinkCottonCandy);
		addBlock(world, basePos, 1, 9, 1, pinkCottonCandy);
		addBlock(world, basePos, 1, 9, 2, pinkCottonCandy);
		addBlock(world, basePos, 1, 9, 3, pinkCottonCandy);
		addBlock(world, basePos, 1, 9, 4, pinkCottonCandy);
		addBlock(world, basePos, 2, 9, 0, pinkCottonCandy);
		addBlock(world, basePos, 2, 9, 1, pinkCottonCandy);
		addBlock(world, basePos, 2, 9, 2, pinkCottonCandy);
		addBlock(world, basePos, 2, 9, 3, pinkCottonCandy);
		addBlock(world, basePos, 2, 9, 4, pinkCottonCandy);
		addBlock(world, basePos, 3, 9, 0, pinkCottonCandy);
		addBlock(world, basePos, 3, 9, 1, pinkCottonCandy);
		addBlock(world, basePos, 3, 9, 2, pinkCottonCandy);
		addBlock(world, basePos, 3, 9, 3, pinkCottonCandy);
		addBlock(world, basePos, 3, 9, 4, pinkCottonCandy);
		addBlock(world, basePos, 4, 9, 0, pinkCottonCandy);
		addBlock(world, basePos, 4, 9, 1, pinkCottonCandy);
		addBlock(world, basePos, 4, 9, 2, pinkCottonCandy);
		addBlock(world, basePos, 4, 9, 3, pinkCottonCandy);
		addBlock(world, basePos, 4, 9, 4, pinkCottonCandy);
		addBlock(world, basePos, 1, 10, 1, pinkCottonCandy);
		addBlock(world, basePos, 1, 10, 2, pinkCottonCandy);
		addBlock(world, basePos, 1, 10, 3, pinkCottonCandy);
		addBlock(world, basePos, 2, 10, 1, pinkCottonCandy);
		addBlock(world, basePos, 2, 10, 2, pinkCottonCandy);
		addBlock(world, basePos, 2, 10, 3, pinkCottonCandy);
		addBlock(world, basePos, 3, 10, 1, pinkCottonCandy);
		addBlock(world, basePos, 3, 10, 2, pinkCottonCandy);
		addBlock(world, basePos, 3, 10, 3, pinkCottonCandy);
		addBlock(world, basePos, 1, 11, 1, pinkCottonCandy);
		addBlock(world, basePos, 1, 11, 2, pinkCottonCandy);
		addBlock(world, basePos, 1, 11, 3, pinkCottonCandy);
		addBlock(world, basePos, 2, 11, 1, pinkCottonCandy);
		addBlock(world, basePos, 2, 11, 2, pinkCottonCandy);
		addBlock(world, basePos, 2, 11, 3, pinkCottonCandy);
		addBlock(world, basePos, 3, 11, 1, pinkCottonCandy);
		addBlock(world, basePos, 3, 11, 2, pinkCottonCandy);
		addBlock(world, basePos, 3, 11, 3, pinkCottonCandy);
		addBlock(world, basePos, 1, 12, 1, pinkCottonCandy);
		addBlock(world, basePos, 1, 12, 2, pinkCottonCandy);
		addBlock(world, basePos, 1, 12, 3, pinkCottonCandy);
		addBlock(world, basePos, 2, 12, 1, pinkCottonCandy);
		addBlock(world, basePos, 2, 12, 2, pinkCottonCandy);
		addBlock(world, basePos, 2, 12, 3, pinkCottonCandy);
		addBlock(world, basePos, 3, 12, 1, pinkCottonCandy);
		addBlock(world, basePos, 3, 12, 2, pinkCottonCandy);
		addBlock(world, basePos, 3, 12, 3, pinkCottonCandy);
	}
}
