package net.nevermine.structures.deeplands;

import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenerator;
import net.nevermine.izer.Blockizer;

import java.util.Random;

public class Ribs2 extends WorldGenerator {
	public boolean generate(final World world, final Random rand, final int i, final int j, final int k) {
		world.setBlock(i + 0, j + 0, k + 1, Blockizer.SkeletalBlock);
		world.setBlock(i + 0, j + 0, k + 2, Blockizer.SkeletalBlock);
		world.setBlock(i + 0, j + 0, k + 3, Blockizer.SkeletalBlock);
		world.setBlock(i + 0, j + 0, k + 6, Blockizer.SkeletalBlock);
		world.setBlock(i + 0, j + 0, k + 7, Blockizer.SkeletalBlock);
		world.setBlock(i + 0, j + 0, k + 8, Blockizer.SkeletalBlock);
		world.setBlock(i + 0, j + 1, k + 0, Blockizer.SkeletalBlock);
		world.setBlock(i + 0, j + 1, k + 1, Blockizer.SkeletalBlock);
		world.setBlock(i + 0, j + 1, k + 8, Blockizer.SkeletalBlock);
		world.setBlock(i + 0, j + 1, k + 9, Blockizer.SkeletalBlock);
		world.setBlock(i + 0, j + 2, k + 0, Blockizer.SkeletalBlock);
		world.setBlock(i + 0, j + 2, k + 9, Blockizer.SkeletalBlock);
		world.setBlock(i + 0, j + 3, k + 0, Blockizer.SkeletalBlock);
		world.setBlock(i + 0, j + 3, k + 9, Blockizer.SkeletalBlock);
		world.setBlock(i + 0, j + 4, k + 0, Blockizer.SkeletalBlock);
		world.setBlock(i + 0, j + 4, k + 1, Blockizer.SkeletalBlock);
		world.setBlock(i + 0, j + 4, k + 8, Blockizer.SkeletalBlock);
		world.setBlock(i + 0, j + 4, k + 9, Blockizer.SkeletalBlock);
		world.setBlock(i + 0, j + 5, k + 1, Blockizer.SkeletalBlock);
		world.setBlock(i + 0, j + 5, k + 2, Blockizer.SkeletalBlock);
		world.setBlock(i + 0, j + 5, k + 7, Blockizer.SkeletalBlock);
		world.setBlock(i + 0, j + 5, k + 8, Blockizer.SkeletalBlock);
		world.setBlock(i + 3, j + 0, k + 1, Blockizer.SkeletalBlock);
		world.setBlock(i + 3, j + 0, k + 2, Blockizer.SkeletalBlock);
		world.setBlock(i + 3, j + 0, k + 3, Blockizer.SkeletalBlock);
		world.setBlock(i + 3, j + 0, k + 6, Blockizer.SkeletalBlock);
		world.setBlock(i + 3, j + 0, k + 7, Blockizer.SkeletalBlock);
		world.setBlock(i + 3, j + 0, k + 8, Blockizer.SkeletalBlock);
		world.setBlock(i + 3, j + 1, k + 0, Blockizer.SkeletalBlock);
		world.setBlock(i + 3, j + 1, k + 1, Blockizer.SkeletalBlock);
		world.setBlock(i + 3, j + 1, k + 8, Blockizer.SkeletalBlock);
		world.setBlock(i + 3, j + 1, k + 9, Blockizer.SkeletalBlock);
		world.setBlock(i + 3, j + 2, k + 0, Blockizer.SkeletalBlock);
		world.setBlock(i + 3, j + 2, k + 9, Blockizer.SkeletalBlock);
		world.setBlock(i + 3, j + 3, k + 0, Blockizer.SkeletalBlock);
		world.setBlock(i + 3, j + 3, k + 9, Blockizer.SkeletalBlock);
		world.setBlock(i + 3, j + 4, k + 0, Blockizer.SkeletalBlock);
		world.setBlock(i + 3, j + 4, k + 1, Blockizer.SkeletalBlock);
		world.setBlock(i + 3, j + 4, k + 8, Blockizer.SkeletalBlock);
		world.setBlock(i + 3, j + 4, k + 9, Blockizer.SkeletalBlock);
		world.setBlock(i + 3, j + 5, k + 1, Blockizer.SkeletalBlock);
		world.setBlock(i + 3, j + 5, k + 2, Blockizer.SkeletalBlock);
		world.setBlock(i + 3, j + 5, k + 7, Blockizer.SkeletalBlock);
		world.setBlock(i + 3, j + 5, k + 8, Blockizer.SkeletalBlock);
		world.setBlock(i + 6, j + 0, k + 1, Blockizer.SkeletalBlock);
		world.setBlock(i + 6, j + 0, k + 2, Blockizer.SkeletalBlock);
		world.setBlock(i + 6, j + 0, k + 3, Blockizer.SkeletalBlock);
		world.setBlock(i + 6, j + 0, k + 6, Blockizer.SkeletalBlock);
		world.setBlock(i + 6, j + 0, k + 7, Blockizer.SkeletalBlock);
		world.setBlock(i + 6, j + 0, k + 8, Blockizer.SkeletalBlock);
		world.setBlock(i + 6, j + 1, k + 0, Blockizer.SkeletalBlock);
		world.setBlock(i + 6, j + 1, k + 1, Blockizer.SkeletalBlock);
		world.setBlock(i + 6, j + 1, k + 8, Blockizer.SkeletalBlock);
		world.setBlock(i + 6, j + 1, k + 9, Blockizer.SkeletalBlock);
		world.setBlock(i + 6, j + 2, k + 0, Blockizer.SkeletalBlock);
		world.setBlock(i + 6, j + 2, k + 9, Blockizer.SkeletalBlock);
		world.setBlock(i + 6, j + 3, k + 0, Blockizer.SkeletalBlock);
		world.setBlock(i + 6, j + 3, k + 9, Blockizer.SkeletalBlock);
		world.setBlock(i + 6, j + 4, k + 0, Blockizer.SkeletalBlock);
		world.setBlock(i + 6, j + 4, k + 1, Blockizer.SkeletalBlock);
		world.setBlock(i + 6, j + 4, k + 8, Blockizer.SkeletalBlock);
		world.setBlock(i + 6, j + 4, k + 9, Blockizer.SkeletalBlock);
		world.setBlock(i + 6, j + 5, k + 1, Blockizer.SkeletalBlock);
		world.setBlock(i + 6, j + 5, k + 2, Blockizer.SkeletalBlock);
		world.setBlock(i + 6, j + 5, k + 7, Blockizer.SkeletalBlock);
		world.setBlock(i + 6, j + 5, k + 8, Blockizer.SkeletalBlock);
		world.setBlock(i + 9, j + 0, k + 1, Blockizer.SkeletalBlock);
		world.setBlock(i + 9, j + 0, k + 2, Blockizer.SkeletalBlock);
		world.setBlock(i + 9, j + 0, k + 3, Blockizer.SkeletalBlock);
		world.setBlock(i + 9, j + 0, k + 6, Blockizer.SkeletalBlock);
		world.setBlock(i + 9, j + 0, k + 7, Blockizer.SkeletalBlock);
		world.setBlock(i + 9, j + 0, k + 8, Blockizer.SkeletalBlock);
		world.setBlock(i + 9, j + 1, k + 0, Blockizer.SkeletalBlock);
		world.setBlock(i + 9, j + 1, k + 1, Blockizer.SkeletalBlock);
		world.setBlock(i + 9, j + 1, k + 8, Blockizer.SkeletalBlock);
		world.setBlock(i + 9, j + 1, k + 9, Blockizer.SkeletalBlock);
		world.setBlock(i + 9, j + 2, k + 0, Blockizer.SkeletalBlock);
		world.setBlock(i + 9, j + 2, k + 9, Blockizer.SkeletalBlock);
		world.setBlock(i + 9, j + 3, k + 0, Blockizer.SkeletalBlock);
		world.setBlock(i + 9, j + 3, k + 9, Blockizer.SkeletalBlock);
		world.setBlock(i + 9, j + 4, k + 0, Blockizer.SkeletalBlock);
		world.setBlock(i + 9, j + 4, k + 1, Blockizer.SkeletalBlock);
		world.setBlock(i + 9, j + 4, k + 8, Blockizer.SkeletalBlock);
		world.setBlock(i + 9, j + 4, k + 9, Blockizer.SkeletalBlock);
		world.setBlock(i + 9, j + 5, k + 1, Blockizer.SkeletalBlock);
		world.setBlock(i + 9, j + 5, k + 2, Blockizer.SkeletalBlock);
		world.setBlock(i + 9, j + 5, k + 7, Blockizer.SkeletalBlock);
		world.setBlock(i + 9, j + 5, k + 8, Blockizer.SkeletalBlock);
		world.setBlock(i + 12, j + 0, k + 1, Blockizer.SkeletalBlock);
		world.setBlock(i + 12, j + 0, k + 2, Blockizer.SkeletalBlock);
		world.setBlock(i + 12, j + 0, k + 3, Blockizer.SkeletalBlock);
		world.setBlock(i + 12, j + 0, k + 6, Blockizer.SkeletalBlock);
		world.setBlock(i + 12, j + 0, k + 7, Blockizer.SkeletalBlock);
		world.setBlock(i + 12, j + 0, k + 8, Blockizer.SkeletalBlock);
		world.setBlock(i + 12, j + 1, k + 0, Blockizer.SkeletalBlock);
		world.setBlock(i + 12, j + 1, k + 1, Blockizer.SkeletalBlock);
		world.setBlock(i + 12, j + 1, k + 8, Blockizer.SkeletalBlock);
		world.setBlock(i + 12, j + 1, k + 9, Blockizer.SkeletalBlock);
		world.setBlock(i + 12, j + 2, k + 0, Blockizer.SkeletalBlock);
		world.setBlock(i + 12, j + 2, k + 9, Blockizer.SkeletalBlock);
		world.setBlock(i + 12, j + 3, k + 0, Blockizer.SkeletalBlock);
		world.setBlock(i + 12, j + 3, k + 9, Blockizer.SkeletalBlock);
		world.setBlock(i + 12, j + 4, k + 0, Blockizer.SkeletalBlock);
		world.setBlock(i + 12, j + 4, k + 1, Blockizer.SkeletalBlock);
		world.setBlock(i + 12, j + 4, k + 8, Blockizer.SkeletalBlock);
		world.setBlock(i + 12, j + 4, k + 9, Blockizer.SkeletalBlock);
		world.setBlock(i + 12, j + 5, k + 1, Blockizer.SkeletalBlock);
		world.setBlock(i + 12, j + 5, k + 2, Blockizer.SkeletalBlock);
		world.setBlock(i + 12, j + 5, k + 7, Blockizer.SkeletalBlock);
		world.setBlock(i + 12, j + 5, k + 8, Blockizer.SkeletalBlock);
		return true;
	}
}
