package net.nevermine.structures.lborean;

import net.minecraft.init.Blocks;
import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenerator;
import net.nevermine.izer.Blockizer;

import java.util.Random;

public class Coral6 extends WorldGenerator {
	public boolean generate(final World world, final Random rand, final int i, final int j, final int k) {
		if (world.getBlock(i + 2, j - 1, k + 3) != Blockizer.GrassBorean && world.getBlock(i + 2, j - 1, k + 3) != Blocks.water) {
			return false;
		}
		world.setBlock(i + 0, j + 0, k + 3, Blockizer.CoralWhite);
		world.setBlock(i + 0, j + 0, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 0, j + 0, k + 5, Blockizer.CoralWhite);
		world.setBlock(i + 0, j + 1, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 1, j + 0, k + 1, Blockizer.CoralWhite);
		world.setBlock(i + 1, j + 0, k + 2, Blockizer.CoralWhite);
		world.setBlock(i + 1, j + 0, k + 3, Blockizer.CoralWhite);
		world.setBlock(i + 1, j + 0, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 1, j + 0, k + 5, Blockizer.CoralWhite);
		world.setBlock(i + 1, j + 0, k + 6, Blockizer.CoralWhite);
		world.setBlock(i + 1, j + 0, k + 7, Blockizer.CoralWhite);
		world.setBlock(i + 1, j + 1, k + 2, Blockizer.CoralWhite);
		world.setBlock(i + 1, j + 1, k + 3, Blockizer.CoralWhite);
		world.setBlock(i + 1, j + 1, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 1, j + 1, k + 5, Blockizer.CoralWhite);
		world.setBlock(i + 1, j + 1, k + 6, Blockizer.CoralWhite);
		world.setBlock(i + 1, j + 2, k + 3, Blockizer.CoralWhite);
		world.setBlock(i + 1, j + 2, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 1, j + 2, k + 5, Blockizer.CoralWhite);
		world.setBlock(i + 2, j + 0, k + 1, Blockizer.CoralWhite);
		world.setBlock(i + 2, j + 0, k + 2, Blockizer.CoralWhite);
		world.setBlock(i + 2, j + 0, k + 3, Blockizer.CoralWhite);
		world.setBlock(i + 2, j + 0, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 2, j + 0, k + 5, Blockizer.CoralWhite);
		world.setBlock(i + 2, j + 0, k + 6, Blockizer.CoralWhite);
		world.setBlock(i + 2, j + 0, k + 7, Blockizer.CoralWhite);
		world.setBlock(i + 2, j + 1, k + 1, Blockizer.CoralWhite);
		world.setBlock(i + 2, j + 1, k + 2, Blockizer.CoralWhite);
		world.setBlock(i + 2, j + 1, k + 3, Blockizer.CoralWhite);
		world.setBlock(i + 2, j + 1, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 2, j + 1, k + 5, Blockizer.CoralWhite);
		world.setBlock(i + 2, j + 1, k + 6, Blockizer.CoralWhite);
		world.setBlock(i + 2, j + 1, k + 7, Blockizer.CoralWhite);
		world.setBlock(i + 2, j + 2, k + 2, Blockizer.CoralWhite);
		world.setBlock(i + 2, j + 2, k + 3, Blockizer.CoralWhite);
		world.setBlock(i + 2, j + 2, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 2, j + 2, k + 5, Blockizer.CoralWhite);
		world.setBlock(i + 2, j + 2, k + 6, Blockizer.CoralWhite);
		world.setBlock(i + 2, j + 3, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 3, j + 0, k + 0, Blockizer.CoralWhite);
		world.setBlock(i + 3, j + 0, k + 1, Blockizer.CoralWhite);
		world.setBlock(i + 3, j + 0, k + 2, Blockizer.CoralWhite);
		world.setBlock(i + 3, j + 0, k + 3, Blockizer.CoralWhite);
		world.setBlock(i + 3, j + 0, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 3, j + 0, k + 5, Blockizer.CoralWhite);
		world.setBlock(i + 3, j + 0, k + 6, Blockizer.CoralWhite);
		world.setBlock(i + 3, j + 0, k + 7, Blockizer.CoralWhite);
		world.setBlock(i + 3, j + 0, k + 8, Blockizer.CoralWhite);
		world.setBlock(i + 3, j + 1, k + 1, Blockizer.CoralWhite);
		world.setBlock(i + 3, j + 1, k + 2, Blockizer.CoralWhite);
		world.setBlock(i + 3, j + 1, k + 3, Blockizer.CoralWhite);
		world.setBlock(i + 3, j + 1, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 3, j + 1, k + 5, Blockizer.CoralWhite);
		world.setBlock(i + 3, j + 1, k + 6, Blockizer.CoralWhite);
		world.setBlock(i + 3, j + 1, k + 7, Blockizer.CoralWhite);
		world.setBlock(i + 3, j + 2, k + 1, Blockizer.CoralWhite);
		world.setBlock(i + 3, j + 2, k + 2, Blockizer.CoralWhite);
		world.setBlock(i + 3, j + 2, k + 3, Blockizer.CoralWhite);
		world.setBlock(i + 3, j + 2, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 3, j + 2, k + 5, Blockizer.CoralWhite);
		world.setBlock(i + 3, j + 2, k + 6, Blockizer.CoralWhite);
		world.setBlock(i + 3, j + 2, k + 7, Blockizer.CoralWhite);
		world.setBlock(i + 3, j + 3, k + 3, Blockizer.CoralWhite);
		world.setBlock(i + 3, j + 3, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 3, j + 3, k + 5, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 0, k + 0, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 0, k + 1, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 0, k + 2, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 0, k + 3, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 0, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 0, k + 5, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 0, k + 6, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 0, k + 7, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 0, k + 8, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 1, k + 0, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 1, k + 1, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 1, k + 2, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 1, k + 3, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 1, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 1, k + 5, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 1, k + 6, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 1, k + 7, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 1, k + 8, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 2, k + 1, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 2, k + 2, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 2, k + 3, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 2, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 2, k + 5, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 2, k + 6, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 2, k + 7, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 3, k + 2, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 3, k + 3, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 3, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 3, k + 5, Blockizer.CoralWhite);
		world.setBlock(i + 4, j + 3, k + 6, Blockizer.CoralWhite);
		world.setBlock(i + 5, j + 0, k + 0, Blockizer.CoralWhite);
		world.setBlock(i + 5, j + 0, k + 1, Blockizer.CoralWhite);
		world.setBlock(i + 5, j + 0, k + 2, Blockizer.CoralWhite);
		world.setBlock(i + 5, j + 0, k + 3, Blockizer.CoralWhite);
		world.setBlock(i + 5, j + 0, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 5, j + 0, k + 5, Blockizer.CoralWhite);
		world.setBlock(i + 5, j + 0, k + 6, Blockizer.CoralWhite);
		world.setBlock(i + 5, j + 0, k + 7, Blockizer.CoralWhite);
		world.setBlock(i + 5, j + 0, k + 8, Blockizer.CoralWhite);
		world.setBlock(i + 5, j + 1, k + 1, Blockizer.CoralWhite);
		world.setBlock(i + 5, j + 1, k + 2, Blockizer.CoralWhite);
		world.setBlock(i + 5, j + 1, k + 3, Blockizer.CoralWhite);
		world.setBlock(i + 5, j + 1, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 5, j + 1, k + 5, Blockizer.CoralWhite);
		world.setBlock(i + 5, j + 1, k + 6, Blockizer.CoralWhite);
		world.setBlock(i + 5, j + 1, k + 7, Blockizer.CoralWhite);
		world.setBlock(i + 5, j + 2, k + 1, Blockizer.CoralWhite);
		world.setBlock(i + 5, j + 2, k + 2, Blockizer.CoralWhite);
		world.setBlock(i + 5, j + 2, k + 3, Blockizer.CoralWhite);
		world.setBlock(i + 5, j + 2, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 5, j + 2, k + 5, Blockizer.CoralWhite);
		world.setBlock(i + 5, j + 2, k + 6, Blockizer.CoralWhite);
		world.setBlock(i + 5, j + 2, k + 7, Blockizer.CoralWhite);
		world.setBlock(i + 5, j + 3, k + 3, Blockizer.CoralWhite);
		world.setBlock(i + 5, j + 3, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 5, j + 3, k + 5, Blockizer.CoralWhite);
		world.setBlock(i + 6, j + 0, k + 1, Blockizer.CoralWhite);
		world.setBlock(i + 6, j + 0, k + 2, Blockizer.CoralWhite);
		world.setBlock(i + 6, j + 0, k + 3, Blockizer.CoralWhite);
		world.setBlock(i + 6, j + 0, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 6, j + 0, k + 5, Blockizer.CoralWhite);
		world.setBlock(i + 6, j + 0, k + 6, Blockizer.CoralWhite);
		world.setBlock(i + 6, j + 0, k + 7, Blockizer.CoralWhite);
		world.setBlock(i + 6, j + 1, k + 1, Blockizer.CoralWhite);
		world.setBlock(i + 6, j + 1, k + 2, Blockizer.CoralWhite);
		world.setBlock(i + 6, j + 1, k + 3, Blockizer.CoralWhite);
		world.setBlock(i + 6, j + 1, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 6, j + 1, k + 5, Blockizer.CoralWhite);
		world.setBlock(i + 6, j + 1, k + 6, Blockizer.CoralWhite);
		world.setBlock(i + 6, j + 1, k + 7, Blockizer.CoralWhite);
		world.setBlock(i + 6, j + 2, k + 2, Blockizer.CoralWhite);
		world.setBlock(i + 6, j + 2, k + 3, Blockizer.CoralWhite);
		world.setBlock(i + 6, j + 2, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 6, j + 2, k + 5, Blockizer.CoralWhite);
		world.setBlock(i + 6, j + 2, k + 6, Blockizer.CoralWhite);
		world.setBlock(i + 6, j + 3, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 7, j + 0, k + 1, Blockizer.CoralWhite);
		world.setBlock(i + 7, j + 0, k + 2, Blockizer.CoralWhite);
		world.setBlock(i + 7, j + 0, k + 3, Blockizer.CoralWhite);
		world.setBlock(i + 7, j + 0, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 7, j + 0, k + 5, Blockizer.CoralWhite);
		world.setBlock(i + 7, j + 0, k + 6, Blockizer.CoralWhite);
		world.setBlock(i + 7, j + 0, k + 7, Blockizer.CoralWhite);
		world.setBlock(i + 7, j + 1, k + 2, Blockizer.CoralWhite);
		world.setBlock(i + 7, j + 1, k + 3, Blockizer.CoralWhite);
		world.setBlock(i + 7, j + 1, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 7, j + 1, k + 5, Blockizer.CoralWhite);
		world.setBlock(i + 7, j + 1, k + 6, Blockizer.CoralWhite);
		world.setBlock(i + 7, j + 2, k + 3, Blockizer.CoralWhite);
		world.setBlock(i + 7, j + 2, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 7, j + 2, k + 5, Blockizer.CoralWhite);
		world.setBlock(i + 8, j + 0, k + 3, Blockizer.CoralWhite);
		world.setBlock(i + 8, j + 0, k + 4, Blockizer.CoralWhite);
		world.setBlock(i + 8, j + 0, k + 5, Blockizer.CoralWhite);
		world.setBlock(i + 8, j + 1, k + 4, Blockizer.CoralWhite);
		return true;
	}
}
