package net.nevermine.structures.runandor;

import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenerator;
import net.nevermine.izer.Blockizer;

import java.util.Random;

public class RunicTree2 extends WorldGenerator {
	public boolean generate(final World world, final Random rand, final int i, final int j, final int k) {
		world.setBlock(i + 0, j + 8, k + 3, Blockizer.WoodRunic);
		world.setBlock(i + 0, j + 9, k + 3, Blockizer.WoodRunic);
		world.setBlock(i + 0, j + 10, k + 3, Blockizer.WoodRunic);
		world.setBlock(i + 1, j + 8, k + 3, Blockizer.WoodRunic);
		world.setBlock(i + 1, j + 10, k + 1, Blockizer.RunicLeaves);
		world.setBlock(i + 1, j + 10, k + 2, Blockizer.RunicLeaves);
		world.setBlock(i + 1, j + 10, k + 3, Blockizer.RunicLeaves);
		world.setBlock(i + 1, j + 10, k + 4, Blockizer.RunicLeaves);
		world.setBlock(i + 1, j + 10, k + 5, Blockizer.RunicLeaves);
		world.setBlock(i + 1, j + 11, k + 1, Blockizer.RunicLeaves);
		world.setBlock(i + 1, j + 11, k + 2, Blockizer.RunicLeaves);
		world.setBlock(i + 1, j + 11, k + 3, Blockizer.RunicLeaves);
		world.setBlock(i + 1, j + 11, k + 4, Blockizer.RunicLeaves);
		world.setBlock(i + 1, j + 11, k + 5, Blockizer.RunicLeaves);
		world.setBlock(i + 1, j + 12, k + 1, Blockizer.RunicLeaves);
		world.setBlock(i + 1, j + 12, k + 2, Blockizer.RunicLeaves);
		world.setBlock(i + 1, j + 12, k + 3, Blockizer.RunicLeaves);
		world.setBlock(i + 1, j + 12, k + 4, Blockizer.RunicLeaves);
		world.setBlock(i + 1, j + 12, k + 5, Blockizer.RunicLeaves);
		world.setBlock(i + 2, j + 8, k + 3, Blockizer.WoodRunic);
		world.setBlock(i + 2, j + 9, k + 2, Blockizer.RunicLeaves);
		world.setBlock(i + 2, j + 9, k + 3, Blockizer.RunicLeaves);
		world.setBlock(i + 2, j + 9, k + 4, Blockizer.RunicLeaves);
		world.setBlock(i + 2, j + 10, k + 1, Blockizer.RunicLeaves);
		world.setBlock(i + 2, j + 10, k + 2, Blockizer.RunicLeaves);
		world.setBlock(i + 2, j + 10, k + 3, Blockizer.RunicLeaves);
		world.setBlock(i + 2, j + 10, k + 4, Blockizer.RunicLeaves);
		world.setBlock(i + 2, j + 10, k + 5, Blockizer.RunicLeaves);
		world.setBlock(i + 2, j + 11, k + 1, Blockizer.RunicLeaves);
		world.setBlock(i + 2, j + 11, k + 2, Blockizer.RunicLeaves);
		world.setBlock(i + 2, j + 11, k + 3, Blockizer.RunicLeaves);
		world.setBlock(i + 2, j + 11, k + 4, Blockizer.RunicLeaves);
		world.setBlock(i + 2, j + 11, k + 5, Blockizer.RunicLeaves);
		world.setBlock(i + 2, j + 12, k + 1, Blockizer.RunicLeaves);
		world.setBlock(i + 2, j + 12, k + 2, Blockizer.RunicLeaves);
		world.setBlock(i + 2, j + 12, k + 3, Blockizer.RunicLeaves);
		world.setBlock(i + 2, j + 12, k + 4, Blockizer.RunicLeaves);
		world.setBlock(i + 2, j + 12, k + 5, Blockizer.RunicLeaves);
		world.setBlock(i + 2, j + 13, k + 2, Blockizer.RunicLeaves);
		world.setBlock(i + 2, j + 13, k + 3, Blockizer.RunicLeaves);
		world.setBlock(i + 2, j + 13, k + 4, Blockizer.RunicLeaves);
		world.setBlock(i + 3, j + 0, k + 3, Blockizer.WoodRunic);
		world.setBlock(i + 3, j + 1, k + 3, Blockizer.WoodRunic);
		world.setBlock(i + 3, j + 2, k + 3, Blockizer.WoodRunic);
		world.setBlock(i + 3, j + 3, k + 3, Blockizer.WoodRunic);
		world.setBlock(i + 3, j + 4, k + 3, Blockizer.WoodRunic);
		world.setBlock(i + 3, j + 5, k + 3, Blockizer.WoodRunic);
		world.setBlock(i + 3, j + 6, k + 3, Blockizer.WoodRunic);
		world.setBlock(i + 3, j + 7, k + 3, Blockizer.WoodRunic);
		world.setBlock(i + 3, j + 8, k + 0, Blockizer.WoodRunic);
		world.setBlock(i + 3, j + 8, k + 1, Blockizer.WoodRunic);
		world.setBlock(i + 3, j + 8, k + 2, Blockizer.WoodRunic);
		world.setBlock(i + 3, j + 8, k + 3, Blockizer.WoodRunic);
		world.setBlock(i + 3, j + 8, k + 4, Blockizer.WoodRunic);
		world.setBlock(i + 3, j + 8, k + 5, Blockizer.WoodRunic);
		world.setBlock(i + 3, j + 8, k + 6, Blockizer.WoodRunic);
		world.setBlock(i + 3, j + 9, k + 0, Blockizer.WoodRunic);
		world.setBlock(i + 3, j + 9, k + 2, Blockizer.RunicLeaves);
		world.setBlock(i + 3, j + 9, k + 3, Blockizer.RunicLeaves);
		world.setBlock(i + 3, j + 9, k + 4, Blockizer.RunicLeaves);
		world.setBlock(i + 3, j + 9, k + 6, Blockizer.WoodRunic);
		world.setBlock(i + 3, j + 10, k + 0, Blockizer.WoodRunic);
		world.setBlock(i + 3, j + 10, k + 1, Blockizer.RunicLeaves);
		world.setBlock(i + 3, j + 10, k + 2, Blockizer.RunicLeaves);
		world.setBlock(i + 3, j + 10, k + 3, Blockizer.RunicLeaves);
		world.setBlock(i + 3, j + 10, k + 4, Blockizer.RunicLeaves);
		world.setBlock(i + 3, j + 10, k + 5, Blockizer.RunicLeaves);
		world.setBlock(i + 3, j + 10, k + 6, Blockizer.WoodRunic);
		world.setBlock(i + 3, j + 11, k + 1, Blockizer.RunicLeaves);
		world.setBlock(i + 3, j + 11, k + 2, Blockizer.RunicLeaves);
		world.setBlock(i + 3, j + 11, k + 3, Blockizer.RunicLeaves);
		world.setBlock(i + 3, j + 11, k + 4, Blockizer.RunicLeaves);
		world.setBlock(i + 3, j + 11, k + 5, Blockizer.RunicLeaves);
		world.setBlock(i + 3, j + 12, k + 1, Blockizer.RunicLeaves);
		world.setBlock(i + 3, j + 12, k + 2, Blockizer.RunicLeaves);
		world.setBlock(i + 3, j + 12, k + 3, Blockizer.RunicLeaves);
		world.setBlock(i + 3, j + 12, k + 4, Blockizer.RunicLeaves);
		world.setBlock(i + 3, j + 12, k + 5, Blockizer.RunicLeaves);
		world.setBlock(i + 3, j + 13, k + 2, Blockizer.RunicLeaves);
		world.setBlock(i + 3, j + 13, k + 3, Blockizer.RunicLeaves);
		world.setBlock(i + 3, j + 13, k + 4, Blockizer.RunicLeaves);
		world.setBlock(i + 4, j + 8, k + 3, Blockizer.WoodRunic);
		world.setBlock(i + 4, j + 9, k + 2, Blockizer.RunicLeaves);
		world.setBlock(i + 4, j + 9, k + 3, Blockizer.RunicLeaves);
		world.setBlock(i + 4, j + 9, k + 4, Blockizer.RunicLeaves);
		world.setBlock(i + 4, j + 10, k + 1, Blockizer.RunicLeaves);
		world.setBlock(i + 4, j + 10, k + 2, Blockizer.RunicLeaves);
		world.setBlock(i + 4, j + 10, k + 3, Blockizer.RunicLeaves);
		world.setBlock(i + 4, j + 10, k + 4, Blockizer.RunicLeaves);
		world.setBlock(i + 4, j + 10, k + 5, Blockizer.RunicLeaves);
		world.setBlock(i + 4, j + 11, k + 1, Blockizer.RunicLeaves);
		world.setBlock(i + 4, j + 11, k + 2, Blockizer.RunicLeaves);
		world.setBlock(i + 4, j + 11, k + 3, Blockizer.RunicLeaves);
		world.setBlock(i + 4, j + 11, k + 4, Blockizer.RunicLeaves);
		world.setBlock(i + 4, j + 11, k + 5, Blockizer.RunicLeaves);
		world.setBlock(i + 4, j + 12, k + 1, Blockizer.RunicLeaves);
		world.setBlock(i + 4, j + 12, k + 2, Blockizer.RunicLeaves);
		world.setBlock(i + 4, j + 12, k + 3, Blockizer.RunicLeaves);
		world.setBlock(i + 4, j + 12, k + 4, Blockizer.RunicLeaves);
		world.setBlock(i + 4, j + 12, k + 5, Blockizer.RunicLeaves);
		world.setBlock(i + 4, j + 13, k + 2, Blockizer.RunicLeaves);
		world.setBlock(i + 4, j + 13, k + 3, Blockizer.RunicLeaves);
		world.setBlock(i + 4, j + 13, k + 4, Blockizer.RunicLeaves);
		world.setBlock(i + 5, j + 8, k + 3, Blockizer.WoodRunic);
		world.setBlock(i + 5, j + 10, k + 1, Blockizer.RunicLeaves);
		world.setBlock(i + 5, j + 10, k + 2, Blockizer.RunicLeaves);
		world.setBlock(i + 5, j + 10, k + 3, Blockizer.RunicLeaves);
		world.setBlock(i + 5, j + 10, k + 4, Blockizer.RunicLeaves);
		world.setBlock(i + 5, j + 10, k + 5, Blockizer.RunicLeaves);
		world.setBlock(i + 5, j + 11, k + 1, Blockizer.RunicLeaves);
		world.setBlock(i + 5, j + 11, k + 2, Blockizer.RunicLeaves);
		world.setBlock(i + 5, j + 11, k + 3, Blockizer.RunicLeaves);
		world.setBlock(i + 5, j + 11, k + 4, Blockizer.RunicLeaves);
		world.setBlock(i + 5, j + 11, k + 5, Blockizer.RunicLeaves);
		world.setBlock(i + 5, j + 12, k + 1, Blockizer.RunicLeaves);
		world.setBlock(i + 5, j + 12, k + 2, Blockizer.RunicLeaves);
		world.setBlock(i + 5, j + 12, k + 3, Blockizer.RunicLeaves);
		world.setBlock(i + 5, j + 12, k + 4, Blockizer.RunicLeaves);
		world.setBlock(i + 5, j + 12, k + 5, Blockizer.RunicLeaves);
		world.setBlock(i + 6, j + 8, k + 3, Blockizer.WoodRunic);
		world.setBlock(i + 6, j + 9, k + 3, Blockizer.WoodRunic);
		world.setBlock(i + 6, j + 10, k + 3, Blockizer.WoodRunic);
		return true;
	}
}
