package net.nevermine.rendering;

import cpw.mods.fml.client.registry.RenderingRegistry;
import net.minecraft.client.model.ModelCow;
import net.minecraft.client.model.ModelSpider;
import net.minecraft.client.renderer.entity.RenderTNTPrimed;
import net.nevermine.boss.bane.*;
import net.nevermine.boss.baroness.*;
import net.nevermine.boss.cavern.*;
import net.nevermine.boss.cavern.holder.EntityHolderConiferon;
import net.nevermine.boss.cavern.holder.EntityHolderGoldorth;
import net.nevermine.boss.cavern.holder.EntityHolderHoron;
import net.nevermine.boss.cavern.holder.EntityHolderPenumbra;
import net.nevermine.boss.clunkhead.EntityClunkhead;
import net.nevermine.boss.clunkhead.RenderClunkhead;
import net.nevermine.boss.clunkhead.modelClunkhead;
import net.nevermine.boss.corallus.*;
import net.nevermine.boss.cottoncandor.EntityCottonCandor;
import net.nevermine.boss.cottoncandor.RenderCottonCandor;
import net.nevermine.boss.cottoncandor.modelCottonCandor;
import net.nevermine.boss.craexxeus.*;
import net.nevermine.boss.creep.EntityCreep;
import net.nevermine.boss.creep.RenderCreep;
import net.nevermine.boss.creep.modelCreep;
import net.nevermine.boss.crystocore.EntityCrystocore;
import net.nevermine.boss.crystocore.RenderCrystocore;
import net.nevermine.boss.crystocore.modelCrystocore;
import net.nevermine.boss.dracyon.EntityDracyon;
import net.nevermine.boss.dracyon.RenderDracyon;
import net.nevermine.boss.dracyon.modelDracyon;
import net.nevermine.boss.elusive.*;
import net.nevermine.boss.fourguardians.*;
import net.nevermine.boss.graw.EntityGraw;
import net.nevermine.boss.graw.RenderGraw;
import net.nevermine.boss.graw.modelGraw;
import net.nevermine.boss.gyro.EntityGyro;
import net.nevermine.boss.gyro.RenderGyro;
import net.nevermine.boss.gyro.modelGyro;
import net.nevermine.boss.hiveking.*;
import net.nevermine.boss.immortal.*;
import net.nevermine.boss.kingbambambam.*;
import net.nevermine.boss.kingshroomus.EntityKingShroomus;
import net.nevermine.boss.kingshroomus.RenderKingShroomus;
import net.nevermine.boss.kingshroomus.modelKingShroomus;
import net.nevermine.boss.kror.EntityKror;
import net.nevermine.boss.kror.RenderKror;
import net.nevermine.boss.kror.modelKror;
import net.nevermine.boss.mechbot.EntityMechBot;
import net.nevermine.boss.mechbot.RenderMechBot;
import net.nevermine.boss.mechbot.modelMechBot;
import net.nevermine.boss.nethengeicwither.EntityNethengeicWither;
import net.nevermine.boss.nethengeicwither.RenderNethengeicWither;
import net.nevermine.boss.nethengeicwither.modelNethengeicWither;
import net.nevermine.boss.primordialfive.*;
import net.nevermine.boss.rockrider.EntityRockRider;
import net.nevermine.boss.rockrider.RenderRockRider;
import net.nevermine.boss.rockrider.modelRockRider;
import net.nevermine.boss.shadowlord.EntityShadowlord;
import net.nevermine.boss.shadowlord.RenderShadowlord;
import net.nevermine.boss.shadowlord.modelShadowlord;
import net.nevermine.boss.silverfoot.EntitySilverfoot;
import net.nevermine.boss.silverfoot.RenderSilverfoot;
import net.nevermine.boss.silverfoot.modelSilverfoot;
import net.nevermine.boss.skeletalarmy.*;
import net.nevermine.boss.smash.EntitySmash;
import net.nevermine.boss.smash.RenderSmash;
import net.nevermine.boss.smash.modelSmash;
import net.nevermine.boss.tyrosaur.EntityTyrosaur;
import net.nevermine.boss.tyrosaur.RenderTyrosaur;
import net.nevermine.boss.tyrosaur.modelTyrosaur;
import net.nevermine.boss.vinocorne.*;
import net.nevermine.boss.visualent.EntityVisualent;
import net.nevermine.boss.visualent.RenderVisualent;
import net.nevermine.boss.visualent.modelVisualent;
import net.nevermine.boss.voxxulon.EntityVoxxulon;
import net.nevermine.boss.voxxulon.RenderVoxxulon;
import net.nevermine.boss.voxxulon.modelVoxxulon;
import net.nevermine.minion.entity.*;
import net.nevermine.minion.model.*;
import net.nevermine.minion.render.*;
import net.nevermine.mob.entity.abyss.*;
import net.nevermine.mob.entity.barathos.*;
import net.nevermine.mob.entity.candyland.*;
import net.nevermine.mob.entity.celeve.*;
import net.nevermine.mob.entity.creeponia.*;
import net.nevermine.mob.entity.crystevia.*;
import net.nevermine.mob.entity.deeplands.*;
import net.nevermine.mob.entity.dustopia.*;
import net.nevermine.mob.entity.gardencia.*;
import net.nevermine.mob.entity.greckon.*;
import net.nevermine.mob.entity.haven.*;
import net.nevermine.mob.entity.immortallis.*;
import net.nevermine.mob.entity.iromine.*;
import net.nevermine.mob.entity.lborean.*;
import net.nevermine.mob.entity.lelyetia.*;
import net.nevermine.mob.entity.lunalus.*;
import net.nevermine.mob.entity.mysterium.*;
import net.nevermine.mob.entity.nether.*;
import net.nevermine.mob.entity.night.*;
import net.nevermine.mob.entity.night.ghostly.*;
import net.nevermine.mob.entity.overworld.*;
import net.nevermine.mob.entity.precasia.*;
import net.nevermine.mob.entity.runandor.*;
import net.nevermine.mob.entity.runandor.templar.*;
import net.nevermine.mob.entity.shyrelands.*;
import net.nevermine.mob.entity.underground.*;
import net.nevermine.mob.entity.voxponds.*;
import net.nevermine.mob.model.abyss.*;
import net.nevermine.mob.model.barathos.*;
import net.nevermine.mob.model.candyland.*;
import net.nevermine.mob.model.celeve.*;
import net.nevermine.mob.model.creeponia.modelCreepird;
import net.nevermine.mob.model.crystevia.*;
import net.nevermine.mob.model.deeplands.*;
import net.nevermine.mob.model.dustopia.*;
import net.nevermine.mob.model.gardencia.*;
import net.nevermine.mob.model.greckon.*;
import net.nevermine.mob.model.haven.*;
import net.nevermine.mob.model.immortallis.*;
import net.nevermine.mob.model.iromine.*;
import net.nevermine.mob.model.lborean.*;
import net.nevermine.mob.model.lelyetia.*;
import net.nevermine.mob.model.lunalus.*;
import net.nevermine.mob.model.mysterium.*;
import net.nevermine.mob.model.nether.*;
import net.nevermine.mob.model.overworld.ghostly.*;
import net.nevermine.mob.model.overworld.*;
import net.nevermine.mob.model.precasia.*;
import net.nevermine.mob.model.runandor.*;
import net.nevermine.mob.model.shyrelands.*;
import net.nevermine.mob.model.underground.*;
import net.nevermine.mob.model.voxponds.*;
import net.nevermine.mob.render.abyss.*;
import net.nevermine.mob.render.barathos.*;
import net.nevermine.mob.render.candyland.*;
import net.nevermine.mob.render.celeve.*;
import net.nevermine.mob.render.creeponia.*;
import net.nevermine.mob.render.crystevia.*;
import net.nevermine.mob.render.deeplands.*;
import net.nevermine.mob.render.dustopia.*;
import net.nevermine.mob.render.gardencia.*;
import net.nevermine.mob.render.greckon.*;
import net.nevermine.mob.render.haven.*;
import net.nevermine.mob.render.immortallis.*;
import net.nevermine.mob.render.iromine.*;
import net.nevermine.mob.render.lborean.*;
import net.nevermine.mob.render.lelyetia.*;
import net.nevermine.mob.render.lunalus.*;
import net.nevermine.mob.render.mysterium.*;
import net.nevermine.mob.render.nether.*;
import net.nevermine.mob.render.overworld.*;
import net.nevermine.mob.render.precasia.*;
import net.nevermine.mob.render.runandor.*;
import net.nevermine.mob.render.runandor.templar.*;
import net.nevermine.mob.render.shyrelands.*;
import net.nevermine.mob.render.underground.*;
import net.nevermine.mob.render.voxponds.*;
import net.nevermine.npc.auxil.EntityBloodlust;
import net.nevermine.npc.entity.*;
import net.nevermine.npc.entity.artistry.*;
import net.nevermine.npc.entity.lottoman.*;
import net.nevermine.npc.entity.primordial.*;
import net.nevermine.npc.entity.zal.*;
import net.nevermine.npc.model.*;
import net.nevermine.npc.pixon.*;
import net.nevermine.npc.render.*;
import net.nevermine.npc.render.artist.*;
import net.nevermine.npc.render.lottoman.*;
import net.nevermine.npc.totem.*;

public class MobRenders {
	public static void init() {
		RenderingRegistry.registerEntityRenderingHandler(EntityHunch.class, new RenderHunch(new modelHunch(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityEnt.class, new RenderEnt(new modelEnt(), 1.3f));
		RenderingRegistry.registerEntityRenderingHandler(EntityFacelessRunner.class, new RenderFacelessRunner(new modelFacelessRunner(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityShade.class, new RenderShade(new modelShade(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityShadow.class, new RenderShadow(new modelShadow(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRammerhead.class, new RenderRammerhead(new modelRammerhead(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityYeti.class, new RenderYeti(new modelYeti(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySasquatch.class, new RenderSasquatch(new modelYeti(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityChimera.class, new RenderChimera(new modelChimera(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGoblin.class, new RenderGoblin(new modelGoblin(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySmash.class, new RenderSmash(new modelSmash(), 0.8f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGhost.class, new RenderGhost(new modelGhost(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityShadowStalker.class, new RenderShadowStalker(new modelShadowStalker(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRockRider.class, new RenderRockRider(new modelRockRider(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityElusive.class, new RenderElusive(new modelElusive(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityElusiveClone.class, new RenderElusiveClone(new modelElusive(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySkeleman.class, new RenderSkeleman(new modelSkeleman(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySkelemanStrong.class, new RenderSkelemanStrong(new modelSkelemanStrong(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySkelemanElite.class, new RenderSkelemanElite(new modelSkelemanElite(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySkeleHopper.class, new RenderSkeleHopper(new modelSkeleHopper(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySkeleHopperStrong.class, new RenderSkeleHopperStrong(new modelSkeleHopperStrong(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySkeleHopperElite.class, new RenderSkeleHopperElite(new modelSkeleHopperElite(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySkelepig.class, new RenderSkelepig(new modelSkelepig(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySkelepigStrong.class, new RenderSkelepigStrong(new modelSkelepigStrong(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySkelepigElite.class, new RenderSkelepigElite(new modelSkelepigElite(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySkeleElder.class, new RenderSkeleElder(new modelSkeleElder(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySkeletron.class, new RenderSkeletron(new modelSkeletron(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityApparition.class, new RenderApparition(new modelApparition(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityDistorter.class, new RenderDistorter(new modelDistorter(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityFiend.class, new RenderFiend(new modelFiend(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySlimer.class, new RenderSlimer(new modelSlimer(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityOcculent.class, new RenderOcculent(new modelOcculent(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityFleshEater.class, new RenderFleshEater(new modelFleshEater(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityAutomaton.class, new RenderAutomaton(new modelAutomaton(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityVolar.class, new RenderVolar(new modelVolar(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityVoliant.class, new RenderVoliant(new modelVoliant(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHalycon.class, new RenderHalycon(new modelHalycon(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySeeker.class, new RenderSeeker(new modelSeeker(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRainicorn.class, new RenderRainicorn(new modelRainicorn(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySurveyor.class, new RenderSurveyor(new modelSurveyor(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityDyrehorn.class, new RenderDyrehorn(new modelDyrehorn(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityDiocus.class, new RenderDiocus(new modelDiocus(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIosaur.class, new RenderIosaur(new modelIosaur(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySpinoledon.class, new RenderSpinoledon(new modelSpinoledon(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityMegatherium.class, new RenderMegatherium(new modelMegatherium(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySabretooth.class, new RenderSabretooth(new modelSabretooth(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityTortione.class, new RenderTortione(new modelTortione(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityTerradon.class, new RenderTerradon(new modelTerradon(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGiantSlug.class, new RenderGiantSlug(new modelSlug(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCyclops.class, new RenderCyclops(new modelCyclops(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCharger.class, new RenderCharger(new modelCharger(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityChomper.class, new RenderChomper(new modelChomper(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityBushBaby.class, new RenderBushBaby(new modelBushBaby(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityStinger.class, new RenderStinger(new modelStinger(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHillCharger.class, new RenderHillCharger(new modelCharger(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityMuckopede.class, new RenderMuckopede(new modelMuckopede(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySandGolem.class, new RenderSandGolem(new modelSandGolem(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySphinx.class, new RenderSphinx(new modelSphinx(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityAmphibiyte.class, new RenderAmphibiyte(new modelAmphibiyte(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySeaTroll.class, new RenderSeaTroll(new modelSeaTroll(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySeaCharger.class, new RenderSeaCharger(new modelCharger(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityPolarUrsa.class, new RenderPolarUrsa(new modelUrsa(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityUrka.class, new RenderUrka(new modelUrka(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityBlackUrsa.class, new RenderUrsa(new modelUrsa(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityBombCarrier.class, new RenderBombCarrier(new modelBombCarrier(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityFakeTnt.class, new RenderTNTPrimed());
		RenderingRegistry.registerEntityRenderingHandler(EntityDarkBeast.class, new RenderDarkBeast(new modelDarkbeast(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityEverbeast.class, new RenderEverbeast(new modelEverbeast(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityNightWatcher.class, new RenderNightWatcher(new modelNightWatcher(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityScrubby.class, new RenderScrubby(new modelScrubby(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySkellox.class, new RenderSkellox(new modelSkellox(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityVoidwalker.class, new RenderVoidwalker(new modelVoidwalker(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityMotherVoidwalker.class, new RenderMotherVoidwalker(new modelMotherVoidwalker(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityTrickster.class, new RenderTrickster(new modelTrickster(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityTricksterClone.class, new RenderTrickster(new modelTrickster(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityNethengeicBeast.class, new RenderNethengeicBeast(new modelNethengeicBeast(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySkeletalCowman.class, new RenderSkeletalCowman());
		RenderingRegistry.registerEntityRenderingHandler(EntityWitherWizard.class, new RenderWitherWizard(new modelWitherWizard(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityInfernal.class, new RenderInfernal(new modelInfernal(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityKingBamBamBam.class, new RenderKingBamBamBam(new modelKingBamBamBam(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLittleBam.class, new RenderLittleBam(new modelLittleBam(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGuardianRed.class, new RenderGuardianRed(new modelGuardian(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGuardianYellow.class, new RenderGuardianYellow(new modelGuardian(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGuardianBlue.class, new RenderGuardianBlue(new modelGuardian(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGuardianGreen.class, new RenderGuardianGreen(new modelGuardian(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityNethengeicWither.class, new RenderNethengeicWither(new modelNethengeicWither(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityShadowlord.class, new RenderShadowlord(new modelShadowlord(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCorallus.class, new RenderCorallus(new modelCorallus(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCorallusShot.class, new RenderCorallusShot(new modelCorallusShot(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLivingFungi.class, new RenderLivingFungi(new modelLivingFungi(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHidingFungi.class, new RenderHidingFungi(new modelHidingFungi(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityKaiyu.class, new RenderKaiyu(new modelKaiyu(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityBloodsucker.class, new RenderBloodsucker(new modelBloodsucker(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityWebReaper.class, new RenderWebReaper(new modelWebReaper(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityClown.class, new RenderClown());
		RenderingRegistry.registerEntityRenderingHandler(EntityEeo.class, new RenderEeo(new modelEeo(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityEeoRunning.class, new RenderEeo(new modelEeo(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityFungik.class, new RenderFungik(new modelFungik(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityFungback.class, new RenderFungback(new modelFungback(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySpiritGuardian.class, new RenderSpiritGuardian(new modelSpiritGuardian(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySpiritProtector.class, new RenderSpiritProtector(new modelSpiritProtector(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityPhantom.class, new RenderPhantom());
		RenderingRegistry.registerEntityRenderingHandler(EntityBanshee.class, new RenderBanshee(new modelBanshee(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityNightmareSpider.class, new RenderNightmareSpider(new modelNightmareSpider(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRunicGolem.class, new RenderRunicGolem(new modelRunicGolem(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityUndeadTroll.class, new RenderUndeadTroll(new modelSeaTroll(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityPenguin.class, new RenderPenguin(new modelPenguin(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCompeer.class, new RenderCompeer(new modelCompeer(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCorby.class, new RenderCorby(new modelCorby(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLottoman.class, new RenderLottoman(new modelLottoman(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGorbCitizen.class, new RenderGorbCitizen(new modelGorb(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGorbEngineer.class, new RenderGorbEngineer(new modelGorb(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGorbArmsDealer.class, new RenderGorbArmsDealer(new modelGorb(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityTrollTrader.class, new RenderTrollTrader(new modelSeaTroll(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolAbominator.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolGigaCannon.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolAncientBow.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolSoulfireBow.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolBloodfury.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolWartGun.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolPenguinBlaster.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolPurplePunisher.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolSoundCannon.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityZalBanker.class, new RenderZalBanker(new modelZal(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityZalHerbalist.class, new RenderZalHerbalist(new modelZal(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityZalCitizen.class, new RenderZalCitizen(new modelZal(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityZalChild.class, new RenderZalChild(new modelZal(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityZalFoodMarket.class, new RenderZalFoodMarket(new modelZal(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityZalLunarade.class, new RenderZalLunarade(new modelZal(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityZalSpellbinder.class, new RenderZalSpellbinder(new modelZal(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLottomanLunalus.class, new RenderLottomanLunalus(new modelLottoman(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLottomanRunandor.class, new RenderLottomanRunandor(new modelLottoman(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityDestructor.class, new RenderDestructor(new modelDestructor(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityEnderCarrier.class, new RenderEnderCarrier(new modelEnderCarrier(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityTerrestrial.class, new RenderTerrestrial(new modelTerrestrial(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityDawnlight.class, new RenderDawnlight(new modelDawnlight(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityNightReaper.class, new RenderNightReaper(new modelNightReaper(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityDemonReaper.class, new RenderDemonReaper(new modelNightReaper(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityQuickpocket.class, new RenderQuickpocket(new modelQuickpocket(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityPolytom.class, new RenderPolytom(new modelPolytom(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityVoltron.class, new RenderVoltron(new modelVoltron(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityEnforcer.class, new RenderEnforcer(new modelEnforcer(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityMechyon.class, new RenderMechyon(new modelMechyon(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityMechachron.class, new RenderMechachron(new modelMechachron(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityMechamaton.class, new RenderMechamaton(new modelMechamaton(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityExplodot.class, new RenderExplodot(new modelExplodot(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityInmateX.class, new RenderInmateX(new modelInmateX(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityInmateY.class, new RenderInmateY(new modelInmateY(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityVisulon.class, new RenderVisulon(new modelVisulon(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityVisular.class, new RenderVisular(new modelVisular(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLunarcher.class, new RenderLunarcher());
		RenderingRegistry.registerEntityRenderingHandler(EntityGrillface.class, new RenderGrillface(new modelGrillface(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySugarface.class, new RenderSugarface(new modelSugarface(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHunter.class, new RenderHunter(new modelHunter(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityValkyrie.class, new RenderValkyrie(new modelValkyrie(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityShifter.class, new RenderShifter(new modelShifter(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySilencer.class, new RenderSilencer(new modelSilencer(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySkullCreature.class, new RenderSkullCreature(new modelSkullCreature(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRockCrawler.class, new RenderRockCrawler(new modelRockCrawler(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRockCritter.class, new RenderRockCritter(new modelRockCritter(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRockbiter.class, new RenderRockbiter(new modelRockbiter(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityDweller.class, new RenderDweller(new modelDweller(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityDwellerClone.class, new RenderDweller(new modelDweller(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityDoubler.class, new RenderDoubler(new modelDoubler(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityNipper.class, new RenderNipper(new modelNipper(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCaveCreep.class, new RenderCaveCreep(new modelCaveCreep(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityFlowerface.class, new RenderFlowerface(new modelFlowerface(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityPodPlant.class, new RenderPodPlant(new modelPodPlant(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityArchvine.class, new RenderArchvine(new modelArchvine(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCorny.class, new RenderCorny(new modelCorny(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCarrotop.class, new RenderCarrotop(new modelCarrotop(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityBroccohead.class, new RenderBroccohead(new modelBroccohead(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySunny.class, new RenderSunny(new modelSunny(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySquasher.class, new RenderSquasher(new modelSquasher(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityVineWizard.class, new RenderVineWizard(new modelVineWizard(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityAlarmo.class, new RenderAlarmo(new modelAlarmo(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGadgetoid.class, new RenderGadgetoid(new modelGadgetoid(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCentinel.class, new RenderCentinel(new modelCentinel(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGrocculate.class, new RenderGrocculate(new modelGrocculate(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityNightwing.class, new RenderNightwing(new modelNightwing(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityToxxulous.class, new RenderToxxulous(new modelToxxulous(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCoratee.class, new RenderCoratee(new modelCoratee(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityAngler.class, new RenderAngler(new modelAngler(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCoralon.class, new RenderCoralon(new modelCoralon(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityNeptuno.class, new RenderNeptuno(new modelNeptuno(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityMuncher.class, new RenderMuncher(new modelMuncher(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityAmphibior.class, new RenderAmphibior(new modelAmphibior(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityMermage.class, new RenderMermage(new modelMermage(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySeaViper.class, new RenderSeaViper(new modelSeaViper(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityBasilisk.class, new RenderBasilisk(new modelBasilisk(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLostSoul.class, new RenderLostSoul(new modelLostSoul(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityDusteiva.class, new RenderDusteiva(new modelDusteiva(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityMerkyre.class, new RenderMerkyre(new modelMerkyre(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityDevourer.class, new RenderDevourer(new modelDevourer(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityDuston.class, new RenderDuston(new modelDuston(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityDustStrider.class, new RenderDustStrider(new modelDustStrider(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityStalker.class, new RenderStalker(new modelStalker(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityStalkerPrime.class, new RenderStalkerPrime(new modelStalkerPrime(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLurker.class, new RenderLurker(new modelLurker(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityBouncer.class, new RenderBouncer(new modelBouncer(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityEyeCreature.class, new RenderEyeCreature(new modelEyeCreature(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityAriel.class, new RenderAriel(new modelAriel(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRunicGuardian.class, new RenderRunicGuardian(new modelRunicGuardian(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityPaladin.class, new RenderPaladin(new modelPaladin(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySpectralWizard.class, new RenderSpectralWizard(new modelSpectralWizard(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRunicorn.class, new RenderRunicorn(new modelRainicorn(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRunicornRider.class, new RenderRunicornRider(new modelRunicornRider(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityArkback.class, new RenderArkback(new modelArkback(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityEmperorBeast.class, new RenderEmperorBeast(new modelEmperorBeast(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRamradon.class, new RenderRamradon(new modelRamradon(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityNospike.class, new RenderNospike(new modelNospike(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityTharafly.class, new RenderTharafly(new modelTharafly(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityKeeler.class, new RenderKeeler(new modelKeeler(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityParasect.class, new RenderParasect(new modelParasect(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityEchodar.class, new RenderEchodar(new modelEchodar(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCryptid.class, new RenderCryptid(new modelCryptid(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySquiggler.class, new RenderSquiggler(new modelSquiggler(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityEilosapien.class, new RenderEilosapien(new modelEilosapien(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySpikeback.class, new RenderSpikeback(new modelSpikeback(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRammerhorn.class, new RenderRammerhorn(new modelRammerhorn(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityPlateosaur.class, new RenderPlateosaur(new modelPlateosaur(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHorntail.class, new RenderHorntail(new modelHorntail(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHellquin.class, new RenderHellquin(new modelPenguin(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityAlluricorn.class, new RenderAlluricorn(new modelRainicorn(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGnawer.class, new RenderGnawer(new modelGnawer(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityMechaCyclops.class, new RenderMechaCyclops(new modelMechaCyclops(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityMechaSkellox.class, new RenderMechaSkellox(new modelMechaSkellox(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHealingGolem.class, new RenderHealingGolem(new modelHealingGolem(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHiveSoldier.class, new RenderHiveSoldier(new modelHiveSoldier(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityPortalMaster.class, new RenderPortalMaster(new modelPortalMaster(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityProfessor.class, new RenderProfessor(new modelProfessor(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityStoreKeeper.class, new RenderStoreKeeper(new modelStoreKeeper(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityBane.class, new RenderBane(new modelBane(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityBaneBig.class, new RenderBaneBig(new modelBane(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityBaneClone.class, new RenderBaneClone(new modelBane(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityClunkhead.class, new RenderClunkhead(new modelClunkhead(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityDracyon.class, new RenderDracyon(new modelDracyon(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHiveKing.class, new RenderHiveKing(new modelHiveKing(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHiveWorker.class, new RenderHiveSoldier(new modelHiveSoldier(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityKingShroomus.class, new RenderKingShroomus(new modelKingShroomus(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityKror.class, new RenderKror(new modelKror(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHarkos.class, new RenderHarkos(new modelHarkos(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityKajaros.class, new RenderKajaros(new modelKajaros(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityMiskel.class, new RenderMiskel(new modelMiskel(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityOkazor.class, new RenderOkazor(new modelOkazor(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRaxxan.class, new RenderRaxxan(new modelRaxxan(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySilverfoot.class, new RenderSilverfoot(new modelSilverfoot(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityVisualent.class, new RenderVisualent(new modelVisualent(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityVoxxulon.class, new RenderVoxxulon(new modelVoxxulon(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityVinocorne.class, new RenderVinocorne(new modelVinocorne(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityBlueFlower.class, new RenderBlueFlower(new modelFlowerface(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGreenFlower.class, new RenderGreenFlower(new modelFlowerface(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityYellowFlower.class, new RenderYellowFlower(new modelFlowerface(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityOrangeFlower.class, new RenderOrangeFlower(new modelFlowerface(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityPurpleFlower.class, new RenderPurpleFlower(new modelFlowerface(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityPrimordialGuide.class, new RenderPrimordialGuide(new modelPrimordialNPC(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityPrimordialSpellbinder.class, new RenderPrimordialSpellbinder(new modelPrimordialNPC(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityPrimordialBanker.class, new RenderPrimordialBanker(new modelPrimordialNPC(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityPrimordialMerchant.class, new RenderPrimordialMerchant(new modelPrimordialNPC(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityPrimordialWizard.class, new RenderPrimordialWizard(new modelPrimordialNPC(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLottomanAbyss.class, new RenderLottomanAbyss(new modelLottoman(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLottomanHaven.class, new RenderLottomanHaven(new modelLottoman(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLottomanMysterium.class, new RenderLottomanMysterium(new modelLottoman(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLottomanPrecasia.class, new RenderLottomanPrecasia(new modelLottoman(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLottomanIromine.class, new RenderLottomanIromine(new modelLottoman(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLottomanDeeplands.class, new RenderLottomanDeeplands(new modelLottoman(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLottomanGreckon.class, new RenderLottomanGreckon(new modelLottoman(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLottomanGardencia.class, new RenderLottomanGardencia(new modelLottoman(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLottomanDustopia.class, new RenderLottomanDustopia(new modelLottoman(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLottomanBarathos.class, new RenderLottomanBarathos(new modelLottoman(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLottomanVoxPonds.class, new RenderLottomanVoxPonds(new modelLottoman(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLottomanLborean.class, new RenderLottomanBoreic(new modelLottoman(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLottomanNether.class, new RenderLottomanNether(new modelLottoman(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolAquaticStaff.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolBaronSSR.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolBaronStaff.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolBayonetteSR.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolDaybreaker.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolExplochronSword.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolFlamingFury.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolFlowercorne.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolFormationStaff.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolHauntersRifle.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolLunaBlaster.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolMechaBlaster.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolNoxiousGreatblade.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolPredatiousBow.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolPulsator.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolRosidianArchergun.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolTerminator.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolTidalGreatblade.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolViralArchergun.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolWizardStaff.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolViper1.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRosid.class, new RenderRosid(new modelRosid(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRunicLifeformRed.class, new RenderRunicLifeformRed(new modelRunicLifeform(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRunicLifeformYellow.class, new RenderRunicLifeformYellow(new modelRunicLifeform(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRunicLifeformBlue.class, new RenderRunicLifeformBlue(new modelRunicLifeform(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRunicLifeformGreen.class, new RenderRunicLifeformGreen(new modelRunicLifeform(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRuneTemplarRed.class, new RenderRuneTemplarRed(new modelRuneTemplar(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRuneTemplarGreen.class, new RenderRuneTemplarGreen(new modelRuneTemplar(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRuneTemplarYellow.class, new RenderRuneTemplarYellow(new modelRuneTemplar(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRuneTemplarBlue.class, new RenderRuneTemplarBlue(new modelRuneTemplar(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRuneTemplarRedDisabled.class, new RenderRuneTemplarRedDisabled(new modelRuneTemplar(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRuneTemplarBlueDisabled.class, new RenderRuneTemplarBlueDisabled(new modelRuneTemplar(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRuneTemplarYellowDisabled.class, new RenderRuneTemplarYellowDisabled(new modelRuneTemplar(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRuneTemplarGreenDisabled.class, new RenderRuneTemplarGreenDisabled(new modelRuneTemplar(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityExoid.class, new RenderExoid(new modelExoid(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityFacelessFloater.class, new RenderFacelessFloater(new modelFacelessFloater(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHydrolisk.class, new RenderHydrolisk(new modelHydrolisk(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHydroliskShield.class, new RenderHydroliskShielded(new modelHydrolisk(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHydrolon.class, new RenderHydrolon(new modelCoralon(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityBrute.class, new RenderBrute(new modelBrute(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityBoneCreature.class, new RenderBoneCreature(new modelBoneCreature(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityEmbrake.class, new RenderEmbrake(new modelEmbrake(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHellspot.class, new RenderHellspot(new modelHellspot(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGhostineAncient.class, new RenderGhostineAncient(new modelGhostineAncient(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityBugeye.class, new RenderBugeye(new modelBugeye(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityNightfly.class, new RenderNightfly(new modelNightfly(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHeadlessHunter.class, new RenderHeadlessHunter(new modelHeadlessHunter(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityKingCharger.class, new RenderKingCharger(new modelKingCharger(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityFungat.class, new RenderFungat(new modelFungat(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(BloomingPixon.class, new RenderShadow(new modelShadow(), 0.1f));
		RenderingRegistry.registerEntityRenderingHandler(GlaringPixon.class, new RenderShadow(new modelShadow(), 0.1f));
		RenderingRegistry.registerEntityRenderingHandler(GleamingPixon.class, new RenderShadow(new modelShadow(), 0.1f));
		RenderingRegistry.registerEntityRenderingHandler(GlowingPixon.class, new RenderShadow(new modelShadow(), 0.1f));
		RenderingRegistry.registerEntityRenderingHandler(GlisteningPixon.class, new RenderShadow(new modelShadow(), 0.1f));
		RenderingRegistry.registerEntityRenderingHandler(RadiantPixon.class, new RenderShadow(new modelShadow(), 0.1f));
		RenderingRegistry.registerEntityRenderingHandler(ShiningPixon.class, new RenderShadow(new modelShadow(), 0.1f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHolderConiferon.class, new RenderShadow(new modelShadow(), 0.0f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHolderPenumbra.class, new RenderShadow(new modelShadow(), 0.0f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHolderGoldorth.class, new RenderShadow(new modelShadow(), 0.0f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHolderHoron.class, new RenderShadow(new modelShadow(), 0.0f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHag.class, new RenderHag(new modelHag(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityPincher.class, new RenderPincher(new modelPincher(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySpinux.class, new RenderSpinux(new modelSpinux(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityDicer.class, new RenderDicer(new modelDicer(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLinger.class, new RenderLinger(new modelLinger(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityBloodmist.class, new RenderBloodmist(new modelBloodmist(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityAnemia.class, new RenderAnemia(new modelAnemia(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGraw.class, new RenderGraw(new modelGraw(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityPenumbra.class, new RenderPenumbra(new modelPenumbra(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHoron.class, new RenderHoron(new modelHoron(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityConiferon.class, new RenderConiferon(new modelConiferon(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGoldorth.class, new RenderGoldorth(new modelGoldorth(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityTrotter.class, new RenderTrotter(new modelTrotter(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityTracker.class, new RenderTracker(new modelTracker(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityFlye.class, new RenderFlye(new modelFlye(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLelyetianCaster.class, new RenderLelyetianCaster(new modelLelyetianCaster(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLelyetianWarrior.class, new RenderLelyetianWarrior(new modelLelyetianWarrior(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityParavite.class, new RenderParavite(new modelParavite(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRawbone.class, new RenderRawbone(new modelRawbone(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityExohead.class, new RenderExohead(new modelExohead(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityZhinx.class, new RenderZhinx(new modelZhinx(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGrobbler.class, new RenderGrobbler(new modelGrobbler(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityElkanyne.class, new RenderElkanyne(new modelElkanyne(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHunterMaster.class, new RenderHunterMaster());
		RenderingRegistry.registerEntityRenderingHandler(EntityAuguryMaster.class, new RenderAuguryMaster());
		RenderingRegistry.registerEntityRenderingHandler(EntityForagingMaster.class, new RenderForagingMaster());
		RenderingRegistry.registerEntityRenderingHandler(EntityCreationMaster.class, new RenderCreationMaster());
		RenderingRegistry.registerEntityRenderingHandler(EntityInfusionMaster.class, new RenderInfusionMaster());
		RenderingRegistry.registerEntityRenderingHandler(EntityRunationMaster.class, new RenderRunationMaster());
		RenderingRegistry.registerEntityRenderingHandler(EntityLelyetianBanker.class, new RenderLelyetianBanker(new modelLelyetianNPC(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLelyetianTrader.class, new RenderLelyetianTrader(new modelLelyetianNPC(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLottomanLelyetia.class, new RenderLottomanLelyetia(new modelLottoman(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolRoyalGreatblade.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolSwarmotron.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityBlissard.class, new RenderBlissard(new modelBlissard(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGoalby.class, new RenderGoalby(new modelGoalby(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityJawe.class, new RenderJawe(new modelJawe(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityDraggy.class, new RenderDraggy(new modelDraggy(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityWaggy.class, new RenderWaggy(new modelWaggy(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySpraggy.class, new RenderSpraggy(new modelSpraggy(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCraggy.class, new RenderCraggy(new modelCraggy(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityShaddy.class, new RenderShaddy(new modelShaddy(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHorndron.class, new RenderHorndron(new modelHorndron(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySkolle.class, new RenderSkolle(new modelSkolle(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGrunt.class, new RenderGrunt(new modelGrunt(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityMagicke.class, new RenderMagicke(new modelMagicke(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityWarclops.class, new RenderWarclops(new modelWarclops(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityAncientGolem.class, new RenderAncientGolem(new modelAncientGolem(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityFurlion.class, new RenderFurlion(new modelFurlion(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityWickett.class, new RenderWickett(new modelWickett(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityNatura.class, new RenderNatura(new modelNatura(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySticky.class, new RenderSticky(new modelSticky(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityStitches.class, new RenderStitches(new modelStitches(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityKranky.class, new RenderKranky(new modelKranky(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityJumbo.class, new RenderJumbo(new modelJumbo(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityKoko.class, new RenderKoko(new modelKoko(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityChocko.class, new RenderChocko(new modelChocko(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityTipsy.class, new RenderTipsy(new modelTipsy(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityBobo.class, new RenderBobo(new modelBobo(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySnappy.class, new RenderSnappy(new modelSnappy(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGyro.class, new RenderGyro(new modelGyro(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLottomanCeleve.class, new RenderLottomanCeleve(new modelLottoman(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityAnimaMaster.class, new RenderAnimaMaster());
		RenderingRegistry.registerEntityRenderingHandler(EntityVitalityMaster.class, new RenderVitalityMaster());
		RenderingRegistry.registerEntityRenderingHandler(EntityInnervationMaster.class, new RenderInnervationMaster());
		RenderingRegistry.registerEntityRenderingHandler(EntityToyMerchant.class, new RenderToyMerchant(new modelChocko(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolGoofyGreatblade.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolWhimsyWinder.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityVoidCharger.class, new RenderVoidCharger(new modelCharger(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySnowCharger.class, new RenderSnowCharger(new modelCharger(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySwampCharger.class, new RenderSwampCharger(new modelCharger(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityDesertCharger.class, new RenderDesertCharger(new modelCharger(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityFlamewalker.class, new RenderFlamewalker(new modelFlamewalker(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityPigotron.class, new RenderPigotron(new modelPigotron(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityFakePigman.class, new RenderFakePigman());
		RenderingRegistry.registerEntityRenderingHandler(EntityFishix.class, new RenderFishix(new modelFishix(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHellcat.class, new RenderHellcat(new modelHellcat(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityBoneback.class, new RenderBoneback(new modelBoneback(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySkipper.class, new RenderSkipper(new modelSkipper(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCrystocore.class, new RenderCrystocore(new modelCrystocore(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityConstructRange.class, new RenderConstructRange(new modelConstructRange(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityConstructStrength.class, new RenderConstructStrength(new modelConstructStrength(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityConstructResistance.class, new RenderConstructResistance(new modelConstructResistance(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityConstructSpeed.class, new RenderConstructSpeed(new modelConstructSpeed(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityConstructFlight.class, new RenderConstructFlight(new modelConstructFlight(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityConstructTerror.class, new RenderConstructTerror(new modelConstructTerror(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityConstructMind.class, new RenderConstructMind(new modelConstructMind(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolCrystaneer.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolCrystalMaul.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLottomanCrystevia.class, new RenderLottomanCrystevia(new modelLottomanClear(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCrystalTrader.class, new RenderCrystalTrader());
		RenderingRegistry.registerEntityRenderingHandler(EntityConstructServility.class, new RenderConstructServility(new modelConstructServility(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGoofer.class, new RenderGoofer(new modelGoofer(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityFungung.class, new RenderFungung(new modelFungung(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(AmbientPixon.class, new RenderShadow(new modelShadow(), 0.1f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGhostlyCharger.class, new RenderGhostlyCharger(new modelGhostlyCharger(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGhostlyCyclops.class, new RenderGhostlyCyclops(new modelGhostlyCyclops(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGhostlySasquatch.class, new RenderGhostlySasquatch(new modelGhostlySasquatch(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGhostlyGoblin.class, new RenderGhostlyGoblin(new modelGhostlyGoblin(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGhostlyBugeye.class, new RenderGhostlyBugeye(new modelGhostlyBugeye(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGhostlyNightReaper.class, new RenderGhostlyNightReaper(new modelGhostlyNightReaper(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityOrbiter.class, new RenderOrbiter(new modelOrbiter(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityAngelica.class, new RenderAngelica(new modelAngelica(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityMetalloid.class, new RenderMetalloid());
		RenderingRegistry.registerEntityRenderingHandler(EntityRealmShifter.class, new RenderRealmShifter());
		RenderingRegistry.registerEntityRenderingHandler(EntityNaturalist.class, new RenderNaturalist());
		RenderingRegistry.registerEntityRenderingHandler(EntityCorruptedTraveller.class, new RenderCorruptedTraveller(new modelBipedClear(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySoulAgent.class, new RenderSoulAgent());
		RenderingRegistry.registerEntityRenderingHandler(EntityAssassin.class, new RenderAssassin());
		RenderingRegistry.registerEntityRenderingHandler(EntityFungock.class, new RenderFungock(new modelFungock(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityOpteryx.class, new RenderOpteryx(new modelOpteryx(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCandyCorny.class, new RenderCandyCorny(new modelCandyCorny(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCaneBug.class, new RenderCaneBug(new modelCaneBug(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLollypopper.class, new RenderLollypopper(new modelLollypopper(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityAirhead.class, new RenderAirhead(new modelAirhead(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGingerbreadMan.class, new RenderGingerbreadMan(new modelGingerbreadMan(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGingerbird.class, new RenderGingerbird(new modelGingerbird(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCherryBlaster.class, new RenderCherryBlaster(new modelCherryBlaster(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCherryBarrager.class, new RenderCherryBarrager(new modelCherryBarrager(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityPeppermintSlug.class, new RenderPeppermintSlug(new modelGummySlug(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySpearmintSlug.class, new RenderSpearmintSlug(new modelGummySlug(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCottonCandor.class, new RenderCottonCandor(new modelCottonCandor(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolFroster.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolMintMagnum.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLottomanCandyland.class, new RenderLottomanCandyland(new modelLottoman(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityExpeditionMaster.class, new RenderExpeditionMaster());
		RenderingRegistry.registerEntityRenderingHandler(EntityArocknid.class, new RenderArocknid(new modelArocknid(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCaseConstruct.class, new RenderCaseConstruct(new modelCaseConstruct(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHost.class, new RenderHost(new modelHost(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityDeathHunter.class, new RenderDeathHunter(new modelDeathHunter(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityWingedCreeper.class, new RenderWingedCreeper());
		RenderingRegistry.registerEntityRenderingHandler(EntityBoneCreeper.class, new RenderBoneCreeper());
		RenderingRegistry.registerEntityRenderingHandler(EntityCaveCreepoid.class, new RenderCaveCreepoid());
		RenderingRegistry.registerEntityRenderingHandler(EntityCreeperlock.class, new RenderCreeperlock());
		RenderingRegistry.registerEntityRenderingHandler(EntityCreepCow.class, new RenderCreepCow(new ModelCow(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCreepird.class, new RenderCreepird(new modelCreepird(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCreepuple.class, new RenderCreepuple());
		RenderingRegistry.registerEntityRenderingHandler(EntityKingCreeper.class, new RenderKingCreeper());
		RenderingRegistry.registerEntityRenderingHandler(EntityMagicalCreeper.class, new RenderMagicalCreeper());
		RenderingRegistry.registerEntityRenderingHandler(EntityBloodlust.class, new RenderBloodlust(new modelBloodlust(), 0.1f));
		RenderingRegistry.registerEntityRenderingHandler(EntityFakeZorp.class, new RenderZorp(new modelZorp(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityZorp.class, new RenderZorp(new modelZorp(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityZarg.class, new RenderZarg(new modelZarg(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityBaumba.class, new RenderBaumba(new modelBaumba(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRefluct.class, new RenderRefluct(new modelRefluct(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityArkzyne.class, new RenderArkzyne(new modelArkzyne(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCrusilisk.class, new RenderCrusilisk(new modelCrusilisk(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityTorano.class, new RenderTorano(new modelTorano(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityPoseido.class, new RenderPoseido(new modelPoseido(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityFade.class, new RenderFade(new modelFade(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySceptron.class, new RenderSceptron(new modelSceptron(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCenturion.class, new RenderCenturion(new modelCenturion(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityMegaGuardian.class, new RenderMegaGuardian(new modelMegaGuardian(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityMushroomSpider.class, new RenderMushroomSpider(new modelMushroomSpider(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityReaver.class, new RenderReaver(new modelReaver(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityUrioh.class, new RenderUrioh(new modelUrioh(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGoldus.class, new RenderGoldus(new modelGoldCreature(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGoldum.class, new RenderGoldum(new modelGoldCreature(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySkelekyte.class, new RenderSkelekyte(new modelSkelekyte(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySkeledon.class, new RenderSkeledon(new modelSkeledon(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityShavo.class, new RenderShavo(new modelShavo(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityFenix.class, new RenderFenix(new modelFenix(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityGhastus.class, new RenderGhastus(new modelGhastus(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityUrv.class, new RenderUrv(new modelUrv(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityVisage.class, new RenderVisage(new modelVisage(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityDaysee.class, new RenderDaysee(new modelDaysee(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLottomanCreeponia.class, new RenderLottomanCreeponia(new modelLottoman(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCreepBanker.class, new RenderCreepBanker());
		RenderingRegistry.registerEntityRenderingHandler(EntityExplosivesExpert.class, new RenderExplosivesExpert());
		RenderingRegistry.registerEntityRenderingHandler(EntityMirage.class, new RenderMirage(new modelMirage(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityKlobber.class, new RenderKlobber(new modelKlobber(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityFlash.class, new RenderFlash(new modelFlash(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityProshield.class, new RenderProshield(new modelProshield(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityCreep.class, new RenderCreep(new modelCreep(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityTokenCollector.class, new RenderTokenCollector());
		RenderingRegistry.registerEntityRenderingHandler(EntityDungeonKeeper.class, new RenderDungeonKeeper());
		RenderingRegistry.registerEntityRenderingHandler(EntityOrbling.class, new RenderOrbling(new modelOrbling(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolBoomBoom.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolCreepoidGreatblade.class, new RenderLottoIdol(new modelLottoIdol(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityButcheryMaster.class, new RenderButcheryMaster());
		RenderingRegistry.registerEntityRenderingHandler(EntityHermetismMaster.class, new RenderHermetismMaster());
		RenderingRegistry.registerEntityRenderingHandler(EntityVulcanismMaster.class, new RenderVulcanismMaster());
		RenderingRegistry.registerEntityRenderingHandler(EntityLoggingMaster.class, new RenderLoggingMaster());
		RenderingRegistry.registerEntityRenderingHandler(EntityStoneGiant.class, new RenderStoneGiant(new modelGiant(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIceGiant.class, new RenderIceGiant(new modelGiant(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityLeafyGiant.class, new RenderLeafyGiant(new modelGiant(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityWoodGiant.class, new RenderWoodGiant(new modelGiant(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySandGiant.class, new RenderSandGiant(new modelGiant(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityReaperTwins.class, new RenderReaperTwins(new modelReaperTwins(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHeadlessDestroyer.class, new RenderHeadlessDestroyer(new modelHeadlessDestroyer(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityTriclops.class, new RenderTriclops(new modelTriclops(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityRoloscope.class, new RenderRoloscope(new modelRoloscope(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityWalker.class, new RenderWalker(new modelWalker(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityVertebron.class, new RenderVertebron(new modelVertebron(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityModulo.class, new RenderModulo(new modelModulo(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityIrkling.class, new RenderIrkling(new modelIrkling(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityFischer.class, new RenderFischer(new modelFischer(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntitySeaSkeleton.class, new RenderSeaSkeleton());
		RenderingRegistry.registerEntityRenderingHandler(EntitySeaSpider.class, new RenderSeaSpider(new ModelSpider(), 0.5f));
		RenderingRegistry.registerEntityRenderingHandler(EntityHaulingMaster.class, new RenderHaulingMaster());

		RenderingRegistry.registerEntityRenderingHandler(EntityCraexxeus.class, new RenderCraexxeus(new modelCraexxeus(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityXxeus.class, new RenderXxeus(new modelXxeus(), 0.5F));

		RenderingRegistry.registerEntityRenderingHandler(EntityArcbeast.class, new RenderArcbeast(new modelArcbeast(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityArcflower.class, new RenderArcflower(new modelArcflower(), 0.0F));
		RenderingRegistry.registerEntityRenderingHandler(EntityArcWizard.class, new RenderArcWizard(new modelArcWizard(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityArcworm.class, new RenderArcworm(new modelArcworm(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityAxiolight.class, new RenderAxiolight(new modelAxiolight(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityOmnilight.class, new RenderOmnilight(new modelOmnilight(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityShyreKnight.class, new RenderShyreKnight(new modelShyreKnight(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntitySoulscorne.class, new RenderSoulscorne(new modelSoulscorne(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntitySoulvyre.class, new RenderSoulvyre(new modelSoulvyre(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityStimulo.class, new RenderStimulo(new modelStimulo(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityStimulosus.class, new RenderStimulosus(new modelStimulosus(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntitySysker.class, new RenderSysker(new modelSysker(), 0.5F));

		RenderingRegistry.registerEntityRenderingHandler(EntityIdolSkyStaff.class, new RenderLottoIdol(new modelLottoIdol(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityIdolSoulBone.class, new RenderLottoIdol(new modelLottoIdol(), 0.5F));

		RenderingRegistry.registerEntityRenderingHandler(EntityShyreBanker.class, new RenderShyreBanker());
		RenderingRegistry.registerEntityRenderingHandler(EntityShyreArcher.class, new RenderShyreArcher());
		RenderingRegistry.registerEntityRenderingHandler(EntityLottomanShyrelands.class, new RenderLottomanShyrelands(new modelLottoman(), 0.5F));

		RenderingRegistry.registerEntityRenderingHandler(EntityShyreTroll.class, new RenderShyreTroll(new modelShyreTroll(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityLuxocron.class, new RenderLuxocron(new modelLuxocron(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityLightwalker.class, new RenderLightwalker(new modelLightwalker(), 0.5F));

		RenderingRegistry.registerEntityRenderingHandler(EntityTyrosaur.class, new RenderTyrosaur(new modelTyrosaur(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityMechBot.class, new RenderMechBot(new modelMechBot(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityBaroness.class, new RenderBaroness(new modelBaroness(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityBaronBomb.class, new RenderBaronBomb(new modelBaronBomb(), 0.5F));

	}
}
