package net.nevermine.assist;

import net.minecraft.util.ResourceLocation;

public class TileResourceLocation {
	public static final String modelPrefix = "textures/model/";
	public static final ResourceLocation SMASH_STATUE;
	public static final ResourceLocation Rockrider_Statue;
	public static final ResourceLocation KingBamBamBam_Statue;
	public static final ResourceLocation Skeletor_Statue;
	public static final ResourceLocation Skeleelder_Statue;
	public static final ResourceLocation Skelepig_Statue;
	public static final ResourceLocation Skeleman_Statue;
	public static final ResourceLocation SkeleHopper_Statue;
	public static final ResourceLocation Guardian_StatueBlue;
	public static final ResourceLocation Guardian_StatueGreen;
	public static final ResourceLocation Guardian_StatueRed;
	public static final ResourceLocation Guardian_StatueYellow;
	public static final ResourceLocation NethengeicWither_Statue;
	public static final ResourceLocation Elusive_Statue;
	public static final ResourceLocation Shadowlord_Statue;
	public static final ResourceLocation Corallus_Statue;
	public static final ResourceLocation Charging_Table;
	public static final ResourceLocation Iro_Pole;
	public static final ResourceLocation Miskel_Statue;
	public static final ResourceLocation Harkos_Statue;
	public static final ResourceLocation Kajaros_Statue;
	public static final ResourceLocation Okazor_Statue;
	public static final ResourceLocation Raxxan_Statue;
	public static final ResourceLocation Dracyon_Statue;
	public static final ResourceLocation Kror_Statue;
	public static final ResourceLocation Voxxulon_Statue;
	public static final ResourceLocation Bane_Statue;
	public static final ResourceLocation Silverfoot_Statue;
	public static final ResourceLocation Visualent_Statue;
	public static final ResourceLocation HiveKing_Statue;
	public static final ResourceLocation KingShroomus_Statue;
	public static final ResourceLocation Vinocorne_Statue;
	public static final ResourceLocation Clunkhead_Statue;
	public static final ResourceLocation Hydro_Table;
	public static final ResourceLocation SMASH_STATUEGold;
	public static final ResourceLocation Rockrider_StatueGold;
	public static final ResourceLocation KingBamBamBam_StatueGold;
	public static final ResourceLocation Skeletor_StatueGold;
	public static final ResourceLocation Skeleelder_StatueGold;
	public static final ResourceLocation Skelepig_StatueGold;
	public static final ResourceLocation Skeleman_StatueGold;
	public static final ResourceLocation SkeleHopper_StatueGold;
	public static final ResourceLocation Guardian_StatueGoldBlue;
	public static final ResourceLocation Guardian_StatueGoldGreen;
	public static final ResourceLocation Guardian_StatueGoldRed;
	public static final ResourceLocation Guardian_StatueGoldYellow;
	public static final ResourceLocation NethengeicWither_StatueGold;
	public static final ResourceLocation Elusive_StatueGold;
	public static final ResourceLocation Shadowlord_StatueGold;
	public static final ResourceLocation Corallus_StatueGold;
	public static final ResourceLocation Miskel_StatueGold;
	public static final ResourceLocation Harkos_StatueGold;
	public static final ResourceLocation Kajaros_StatueGold;
	public static final ResourceLocation Okazor_StatueGold;
	public static final ResourceLocation Raxxan_StatueGold;
	public static final ResourceLocation Dracyon_StatueGold;
	public static final ResourceLocation Kror_StatueGold;
	public static final ResourceLocation Voxxulon_StatueGold;
	public static final ResourceLocation Bane_StatueGold;
	public static final ResourceLocation Silverfoot_StatueGold;
	public static final ResourceLocation Visualent_StatueGold;
	public static final ResourceLocation HiveKing_StatueGold;
	public static final ResourceLocation KingShroomus_StatueGold;
	public static final ResourceLocation Vinocorne_StatueGold;
	public static final ResourceLocation Clunkhead_StatueGold;
	public static final ResourceLocation Teasink;
	public static final ResourceLocation TeasinkFull;
	public static final ResourceLocation Graw_StatueGold;
	public static final ResourceLocation Graw_Statue;
	public static final ResourceLocation Horon_StatueGold;
	public static final ResourceLocation Horon_Statue;
	public static final ResourceLocation Coniferon_StatueGold;
	public static final ResourceLocation Coniferon_Statue;
	public static final ResourceLocation Goldorth_StatueGold;
	public static final ResourceLocation Goldorth_Statue;
	public static final ResourceLocation Penumbra_StatueGold;
	public static final ResourceLocation Penumbra_Statue;
	public static final ResourceLocation Gyro_StatueGold;
	public static final ResourceLocation Gyro_Statue;
	public static final ResourceLocation[] Campfire;
	public static final ResourceLocation Crystocore_StatueGold;
	public static final ResourceLocation Crystocore_Statue;
	public static final ResourceLocation FiltrationSystemOff;
	public static final ResourceLocation FiltrationSystemOn;
	public static final ResourceLocation BlueShroom;
	public static final ResourceLocation GreenShroom;
	public static final ResourceLocation YellowShroom;
	public static final ResourceLocation OrangeShroom;
	public static final ResourceLocation PurpleShroom;
	public static final ResourceLocation ShroomStem;
	public static final ResourceLocation CottonCandor_StatueGold;
	public static final ResourceLocation CottonCandor_Statue;
	public static final ResourceLocation Creep_StatueGold;
	public static final ResourceLocation Creep_Statue;

	public static final ResourceLocation Craexxeus_Statue = addModel("craexxeusStatue");
	public static final ResourceLocation Craexxeus_StatueGold = addModel("craexxeusStatueGold");

	public static final ResourceLocation Xxeus_Statue = addModel("craexxeusStatue");
	public static final ResourceLocation Xxeus_StatueGold = addModel("craexxeusStatueGold");

	public static final ResourceLocation VoxLog1;
	public static final ResourceLocation VoxLog2;
	public static final ResourceLocation VoxShroom;

	private static ResourceLocation addModel(final String tex) {
		return new ResourceLocation("nevermine:textures/model/" + tex + ".png");
	}

	public static ResourceLocation[] addAnimatedModel(final String tex, final int frames) {
		final ResourceLocation[] ret = new ResourceLocation[frames];
		for (int i = 0; i < frames; ++i) {
			ret[i] = new ResourceLocation("nevermine:textures/model/" + tex + "_" + i + ".png");
		}
		return ret;
	}

	static {
		SMASH_STATUE = addModel("smashStatue");
		Rockrider_Statue = addModel("rockriderStatue");
		KingBamBamBam_Statue = addModel("kingbambambamStatue");
		Skeletor_Statue = addModel("skeletorStatue");
		Skeleelder_Statue = addModel("skeleelderStatue");
		Skelepig_Statue = addModel("skelepigStatue");
		Skeleman_Statue = addModel("skelemanStatue");
		SkeleHopper_Statue = addModel("skelehopperStatue");
		Guardian_StatueBlue = addModel("guardianStatue");
		Guardian_StatueGreen = addModel("guardianStatue");
		Guardian_StatueRed = addModel("guardianStatue");
		Guardian_StatueYellow = addModel("guardianStatue");
		NethengeicWither_Statue = addModel("nethengeicWitherStatue");
		Elusive_Statue = addModel("elusiveStatue");
		Shadowlord_Statue = addModel("shadowlordStatue");
		Corallus_Statue = addModel("corallusStatue");
		Charging_Table = addModel("chargingTable");
		Iro_Pole = addModel("iropole");
		Miskel_Statue = addModel("miskelStatue");
		Harkos_Statue = addModel("harkosStatue");
		Kajaros_Statue = addModel("kajarosStatue");
		Okazor_Statue = addModel("okazorStatue");
		Raxxan_Statue = addModel("raxxanStatue");
		Dracyon_Statue = addModel("dracyonStatue");
		Kror_Statue = addModel("krorStatue");
		Voxxulon_Statue = addModel("voxxulonStatue");
		Bane_Statue = addModel("baneStatue");
		Silverfoot_Statue = addModel("silverfootStatue");
		Visualent_Statue = addModel("visualentStatue");
		HiveKing_Statue = addModel("hivekingStatue");
		KingShroomus_Statue = addModel("kingshroomusStatue");
		Vinocorne_Statue = addModel("vinocorneStatue");
		Clunkhead_Statue = addModel("clunkheadStatue");
		Hydro_Table = addModel("hydroTable");
		SMASH_STATUEGold = addModel("smashStatueGold");
		Rockrider_StatueGold = addModel("rockriderStatueGold");
		KingBamBamBam_StatueGold = addModel("kingbambambamStatueGold");
		Skeletor_StatueGold = addModel("skeletorStatueGold");
		Skeleelder_StatueGold = addModel("skeleelderStatueGold");
		Skelepig_StatueGold = addModel("skelepigStatueGold");
		Skeleman_StatueGold = addModel("skelemanStatueGold");
		SkeleHopper_StatueGold = addModel("skelehopperStatueGold");
		Guardian_StatueGoldBlue = addModel("guardianStatueGold");
		Guardian_StatueGoldGreen = addModel("guardianStatueGold");
		Guardian_StatueGoldRed = addModel("guardianStatueGold");
		Guardian_StatueGoldYellow = addModel("guardianStatueGold");
		NethengeicWither_StatueGold = addModel("nethengeicWitherStatueGold");
		Elusive_StatueGold = addModel("elusiveStatueGold");
		Shadowlord_StatueGold = addModel("shadowlordStatueGold");
		Corallus_StatueGold = addModel("corallusStatueGold");
		Miskel_StatueGold = addModel("miskelStatueGold");
		Harkos_StatueGold = addModel("harkosStatueGold");
		Kajaros_StatueGold = addModel("kajarosStatueGold");
		Okazor_StatueGold = addModel("okazorStatueGold");
		Raxxan_StatueGold = addModel("raxxanStatueGold");
		Dracyon_StatueGold = addModel("dracyonStatueGold");
		Kror_StatueGold = addModel("krorStatueGold");
		Voxxulon_StatueGold = addModel("voxxulonStatueGold");
		Bane_StatueGold = addModel("baneStatueGold");
		Silverfoot_StatueGold = addModel("silverfootStatueGold");
		Visualent_StatueGold = addModel("visualentStatueGold");
		HiveKing_StatueGold = addModel("hivekingStatueGold");
		KingShroomus_StatueGold = addModel("kingshroomusStatueGold");
		Vinocorne_StatueGold = addModel("vinocorneStatueGold");
		Clunkhead_StatueGold = addModel("clunkheadStatueGold");
		Teasink = addModel("teaSink");
		TeasinkFull = addModel("teaSinkFull");
		Graw_StatueGold = addModel("grawStatueGolden");
		Graw_Statue = addModel("grawStatue");
		Horon_StatueGold = addModel("horonStatueGolden");
		Horon_Statue = addModel("horonStatue");
		Coniferon_StatueGold = addModel("coniferonStatueGolden");
		Coniferon_Statue = addModel("coniferonStatue");
		Goldorth_StatueGold = addModel("goldorthStatueGolden");
		Goldorth_Statue = addModel("goldorthStatue");
		Penumbra_StatueGold = addModel("penumbraStatueGolden");
		Penumbra_Statue = addModel("penumbraStatue");
		Gyro_StatueGold = addModel("gyroStatueGold");
		Gyro_Statue = addModel("gyroStatue");
		Campfire = addAnimatedModel("campfire", 12);
		Crystocore_StatueGold = addModel("crystocoreStatueGold");
		Crystocore_Statue = addModel("crystocoreStatue");
		FiltrationSystemOff = addModel("filtrationSystemOff");
		FiltrationSystemOn = addModel("filtrationSystemOn");
		BlueShroom = addModel("blueShroom");
		GreenShroom = addModel("greenShroom");
		YellowShroom = addModel("yellowShroom");
		OrangeShroom = addModel("orangeShroom");
		PurpleShroom = addModel("purpleShroom");
		ShroomStem = addModel("shroomStem");
		CottonCandor_StatueGold = addModel("cottoncandorStatueGold");
		CottonCandor_Statue = addModel("cottoncandorStatue");
		Creep_StatueGold = addModel("creepStatueGold");
		Creep_Statue = addModel("creepStatue");
		VoxLog1 = addModel("voxlog1");
		VoxLog2 = addModel("voxlog2");
		VoxShroom = addModel("voxShroom");
	}
}
