package net.nevermine.structures.precasia;

import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenerator;
import net.nevermine.izer.Blockizer;

import java.util.Random;

public class EucadonTree extends WorldGenerator {

	public EucadonTree() {
	}

	public boolean generate(World world, Random rand, int i, int j, int k) {

		world.setBlock(i + 0, j + 24, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 0, j + 25, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 1, j + 22, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 1, j + 23, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 1, j + 24, k + 2, Blockizer.LeavesEucadon);
		world.setBlock(i + 1, j + 24, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 1, j + 24, k + 4, Blockizer.LeavesEucadon);
		world.setBlock(i + 1, j + 25, k + 2, Blockizer.LeavesEucadon);
		world.setBlock(i + 1, j + 25, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 1, j + 25, k + 4, Blockizer.LeavesEucadon);
		world.setBlock(i + 1, j + 26, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 1, j + 27, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 2, j + 21, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 2, j + 22, k + 2, Blockizer.LeavesEucadon);
		world.setBlock(i + 2, j + 22, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 2, j + 22, k + 4, Blockizer.LeavesEucadon);
		world.setBlock(i + 2, j + 23, k + 2, Blockizer.LeavesEucadon);
		world.setBlock(i + 2, j + 23, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 2, j + 23, k + 4, Blockizer.LeavesEucadon);
		world.setBlock(i + 2, j + 24, k + 1, Blockizer.LeavesEucadon);
		world.setBlock(i + 2, j + 24, k + 2, Blockizer.LeavesEucadon);
		world.setBlock(i + 2, j + 24, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 2, j + 24, k + 4, Blockizer.LeavesEucadon);
		world.setBlock(i + 2, j + 24, k + 5, Blockizer.LeavesEucadon);
		world.setBlock(i + 2, j + 25, k + 1, Blockizer.LeavesEucadon);
		world.setBlock(i + 2, j + 25, k + 2, Blockizer.LeavesEucadon);
		world.setBlock(i + 2, j + 25, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 2, j + 25, k + 4, Blockizer.LeavesEucadon);
		world.setBlock(i + 2, j + 25, k + 5, Blockizer.LeavesEucadon);
		world.setBlock(i + 2, j + 26, k + 2, Blockizer.LeavesEucadon);
		world.setBlock(i + 2, j + 26, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 2, j + 26, k + 4, Blockizer.LeavesEucadon);
		world.setBlock(i + 2, j + 27, k + 2, Blockizer.LeavesEucadon);
		world.setBlock(i + 2, j + 27, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 2, j + 27, k + 4, Blockizer.LeavesEucadon);
		world.setBlock(i + 2, j + 28, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 0, k + 3, Blockizer.WoodEucadon);
		world.setBlock(i + 3, j + 1, k + 3, Blockizer.WoodEucadon);
		world.setBlock(i + 3, j + 2, k + 3, Blockizer.WoodEucadon);
		world.setBlock(i + 3, j + 3, k + 3, Blockizer.WoodEucadon);
		world.setBlock(i + 3, j + 4, k + 3, Blockizer.WoodEucadon);
		world.setBlock(i + 3, j + 5, k + 3, Blockizer.WoodEucadon);
		world.setBlock(i + 3, j + 6, k + 3, Blockizer.WoodEucadon);
		world.setBlock(i + 3, j + 7, k + 3, Blockizer.WoodEucadon);
		world.setBlock(i + 3, j + 8, k + 3, Blockizer.WoodEucadon);
		world.setBlock(i + 3, j + 9, k + 3, Blockizer.WoodEucadon);
		world.setBlock(i + 3, j + 10, k + 3, Blockizer.WoodEucadon);
		world.setBlock(i + 3, j + 11, k + 3, Blockizer.WoodEucadon);
		world.setBlock(i + 3, j + 12, k + 3, Blockizer.WoodEucadon);
		world.setBlock(i + 3, j + 13, k + 3, Blockizer.WoodEucadon);
		world.setBlock(i + 3, j + 14, k + 3, Blockizer.WoodEucadon);
		world.setBlock(i + 3, j + 15, k + 3, Blockizer.WoodEucadon);
		world.setBlock(i + 3, j + 16, k + 3, Blockizer.WoodEucadon);
		world.setBlock(i + 3, j + 17, k + 3, Blockizer.WoodEucadon);
		world.setBlock(i + 3, j + 18, k + 3, Blockizer.WoodEucadon);
		world.setBlock(i + 3, j + 19, k + 3, Blockizer.WoodEucadon);
		world.setBlock(i + 3, j + 20, k + 3, Blockizer.WoodEucadon);
		world.setBlock(i + 3, j + 21, k + 2, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 21, k + 3, Blockizer.WoodEucadon);
		world.setBlock(i + 3, j + 21, k + 4, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 22, k + 1, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 22, k + 2, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 22, k + 3, Blockizer.WoodEucadon);
		world.setBlock(i + 3, j + 22, k + 4, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 22, k + 5, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 23, k + 1, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 23, k + 2, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 23, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 23, k + 4, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 23, k + 5, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 24, k + 0, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 24, k + 1, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 24, k + 2, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 24, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 24, k + 4, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 24, k + 5, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 24, k + 6, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 25, k + 0, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 25, k + 1, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 25, k + 2, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 25, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 25, k + 4, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 25, k + 5, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 25, k + 6, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 26, k + 1, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 26, k + 2, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 26, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 26, k + 4, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 26, k + 5, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 27, k + 1, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 27, k + 2, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 27, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 27, k + 4, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 27, k + 5, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 28, k + 2, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 28, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 3, j + 28, k + 4, Blockizer.LeavesEucadon);
		world.setBlock(i + 4, j + 21, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 4, j + 22, k + 2, Blockizer.LeavesEucadon);
		world.setBlock(i + 4, j + 22, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 4, j + 22, k + 4, Blockizer.LeavesEucadon);
		world.setBlock(i + 4, j + 23, k + 2, Blockizer.LeavesEucadon);
		world.setBlock(i + 4, j + 23, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 4, j + 23, k + 4, Blockizer.LeavesEucadon);
		world.setBlock(i + 4, j + 24, k + 1, Blockizer.LeavesEucadon);
		world.setBlock(i + 4, j + 24, k + 2, Blockizer.LeavesEucadon);
		world.setBlock(i + 4, j + 24, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 4, j + 24, k + 4, Blockizer.LeavesEucadon);
		world.setBlock(i + 4, j + 24, k + 5, Blockizer.LeavesEucadon);
		world.setBlock(i + 4, j + 25, k + 1, Blockizer.LeavesEucadon);
		world.setBlock(i + 4, j + 25, k + 2, Blockizer.LeavesEucadon);
		world.setBlock(i + 4, j + 25, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 4, j + 25, k + 4, Blockizer.LeavesEucadon);
		world.setBlock(i + 4, j + 25, k + 5, Blockizer.LeavesEucadon);
		world.setBlock(i + 4, j + 26, k + 2, Blockizer.LeavesEucadon);
		world.setBlock(i + 4, j + 26, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 4, j + 26, k + 4, Blockizer.LeavesEucadon);
		world.setBlock(i + 4, j + 27, k + 2, Blockizer.LeavesEucadon);
		world.setBlock(i + 4, j + 27, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 4, j + 27, k + 4, Blockizer.LeavesEucadon);
		world.setBlock(i + 4, j + 28, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 5, j + 22, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 5, j + 23, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 5, j + 24, k + 2, Blockizer.LeavesEucadon);
		world.setBlock(i + 5, j + 24, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 5, j + 24, k + 4, Blockizer.LeavesEucadon);
		world.setBlock(i + 5, j + 25, k + 2, Blockizer.LeavesEucadon);
		world.setBlock(i + 5, j + 25, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 5, j + 25, k + 4, Blockizer.LeavesEucadon);
		world.setBlock(i + 5, j + 26, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 5, j + 27, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 6, j + 24, k + 3, Blockizer.LeavesEucadon);
		world.setBlock(i + 6, j + 25, k + 3, Blockizer.LeavesEucadon);

		return true;
	}
}