package net.tslat.aoa3.structure.gardencia;

import net.minecraft.block.state.IBlockState;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
import net.tslat.aoa3.common.registration.BlockRegister;
import net.tslat.aoa3.structure.AoAStructure;

import java.util.Random;

public class BlueStarflower2 extends AoAStructure { //StructureSize: 1x17x11
	private static final IBlockState bluePetals = BlockRegister.petalsBlue.getDefaultState();
	private static final IBlockState lightBluePetals = BlockRegister.petalsLightBlue.getDefaultState();
	private static final IBlockState stem = BlockRegister.plantStem.getDefaultState();
	private static final IBlockState flowerCore = BlockRegister.flowerCore.getDefaultState();

	public BlueStarflower2() {
		super("BlueStarflower2");
	}

	@Override
	protected void build(World world, Random rand, BlockPos basePos) {
		addBlock(world, basePos, 0, 0, 5, stem);
		addBlock(world, basePos, 0, 1, 5, stem);
		addBlock(world, basePos, 0, 2, 5, stem);
		addBlock(world, basePos, 0, 3, 0, bluePetals);
		addBlock(world, basePos, 0, 3, 1, bluePetals);
		addBlock(world, basePos, 0, 3, 2, bluePetals);
		addBlock(world, basePos, 0, 3, 3, bluePetals);
		addBlock(world, basePos, 0, 3, 5, stem);
		addBlock(world, basePos, 0, 3, 7, bluePetals);
		addBlock(world, basePos, 0, 3, 8, bluePetals);
		addBlock(world, basePos, 0, 3, 9, bluePetals);
		addBlock(world, basePos, 0, 3, 10, bluePetals);
		addBlock(world, basePos, 0, 4, 0, bluePetals);
		addBlock(world, basePos, 0, 4, 1, lightBluePetals);
		addBlock(world, basePos, 0, 4, 2, lightBluePetals);
		addBlock(world, basePos, 0, 4, 3, bluePetals);
		addBlock(world, basePos, 0, 4, 4, bluePetals);
		addBlock(world, basePos, 0, 4, 5, stem);
		addBlock(world, basePos, 0, 4, 6, bluePetals);
		addBlock(world, basePos, 0, 4, 7, bluePetals);
		addBlock(world, basePos, 0, 4, 8, lightBluePetals);
		addBlock(world, basePos, 0, 4, 9, lightBluePetals);
		addBlock(world, basePos, 0, 4, 10, bluePetals);
		addBlock(world, basePos, 0, 5, 0, bluePetals);
		addBlock(world, basePos, 0, 5, 1, lightBluePetals);
		addBlock(world, basePos, 0, 5, 2, lightBluePetals);
		addBlock(world, basePos, 0, 5, 3, lightBluePetals);
		addBlock(world, basePos, 0, 5, 4, bluePetals);
		addBlock(world, basePos, 0, 5, 5, stem);
		addBlock(world, basePos, 0, 5, 6, bluePetals);
		addBlock(world, basePos, 0, 5, 7, lightBluePetals);
		addBlock(world, basePos, 0, 5, 8, lightBluePetals);
		addBlock(world, basePos, 0, 5, 9, lightBluePetals);
		addBlock(world, basePos, 0, 5, 10, bluePetals);
		addBlock(world, basePos, 0, 6, 0, bluePetals);
		addBlock(world, basePos, 0, 6, 1, lightBluePetals);
		addBlock(world, basePos, 0, 6, 2, lightBluePetals);
		addBlock(world, basePos, 0, 6, 3, lightBluePetals);
		addBlock(world, basePos, 0, 6, 4, lightBluePetals);
		addBlock(world, basePos, 0, 6, 5, lightBluePetals);
		addBlock(world, basePos, 0, 6, 6, lightBluePetals);
		addBlock(world, basePos, 0, 6, 7, lightBluePetals);
		addBlock(world, basePos, 0, 6, 8, lightBluePetals);
		addBlock(world, basePos, 0, 6, 9, lightBluePetals);
		addBlock(world, basePos, 0, 6, 10, bluePetals);
		addBlock(world, basePos, 0, 7, 0, bluePetals);
		addBlock(world, basePos, 0, 7, 1, bluePetals);
		addBlock(world, basePos, 0, 7, 2, lightBluePetals);
		addBlock(world, basePos, 0, 7, 3, lightBluePetals);
		addBlock(world, basePos, 0, 7, 4, lightBluePetals);
		addBlock(world, basePos, 0, 7, 5, lightBluePetals);
		addBlock(world, basePos, 0, 7, 6, lightBluePetals);
		addBlock(world, basePos, 0, 7, 7, lightBluePetals);
		addBlock(world, basePos, 0, 7, 8, lightBluePetals);
		addBlock(world, basePos, 0, 7, 9, bluePetals);
		addBlock(world, basePos, 0, 7, 10, bluePetals);
		addBlock(world, basePos, 0, 8, 1, bluePetals);
		addBlock(world, basePos, 0, 8, 2, bluePetals);
		addBlock(world, basePos, 0, 8, 3, lightBluePetals);
		addBlock(world, basePos, 0, 8, 4, flowerCore);
		addBlock(world, basePos, 0, 8, 5, flowerCore);
		addBlock(world, basePos, 0, 8, 6, flowerCore);
		addBlock(world, basePos, 0, 8, 7, lightBluePetals);
		addBlock(world, basePos, 0, 8, 8, bluePetals);
		addBlock(world, basePos, 0, 8, 9, bluePetals);
		addBlock(world, basePos, 0, 9, 2, bluePetals);
		addBlock(world, basePos, 0, 9, 3, lightBluePetals);
		addBlock(world, basePos, 0, 9, 4, flowerCore);
		addBlock(world, basePos, 0, 9, 5, flowerCore);
		addBlock(world, basePos, 0, 9, 6, flowerCore);
		addBlock(world, basePos, 0, 9, 7, lightBluePetals);
		addBlock(world, basePos, 0, 9, 8, bluePetals);
		addBlock(world, basePos, 0, 10, 2, bluePetals);
		addBlock(world, basePos, 0, 10, 3, lightBluePetals);
		addBlock(world, basePos, 0, 10, 4, flowerCore);
		addBlock(world, basePos, 0, 10, 5, flowerCore);
		addBlock(world, basePos, 0, 10, 6, flowerCore);
		addBlock(world, basePos, 0, 10, 7, lightBluePetals);
		addBlock(world, basePos, 0, 10, 8, bluePetals);
		addBlock(world, basePos, 0, 10, 9, bluePetals);
		addBlock(world, basePos, 0, 11, 1, bluePetals);
		addBlock(world, basePos, 0, 11, 2, bluePetals);
		addBlock(world, basePos, 0, 11, 3, lightBluePetals);
		addBlock(world, basePos, 0, 11, 4, lightBluePetals);
		addBlock(world, basePos, 0, 11, 5, lightBluePetals);
		addBlock(world, basePos, 0, 11, 6, lightBluePetals);
		addBlock(world, basePos, 0, 11, 7, lightBluePetals);
		addBlock(world, basePos, 0, 11, 8, lightBluePetals);
		addBlock(world, basePos, 0, 11, 9, bluePetals);
		addBlock(world, basePos, 0, 11, 10, bluePetals);
		addBlock(world, basePos, 0, 12, 0, bluePetals);
		addBlock(world, basePos, 0, 12, 1, bluePetals);
		addBlock(world, basePos, 0, 12, 2, lightBluePetals);
		addBlock(world, basePos, 0, 12, 3, lightBluePetals);
		addBlock(world, basePos, 0, 12, 4, lightBluePetals);
		addBlock(world, basePos, 0, 12, 5, lightBluePetals);
		addBlock(world, basePos, 0, 12, 6, lightBluePetals);
		addBlock(world, basePos, 0, 12, 7, lightBluePetals);
		addBlock(world, basePos, 0, 12, 8, lightBluePetals);
		addBlock(world, basePos, 0, 12, 9, lightBluePetals);
		addBlock(world, basePos, 0, 12, 10, bluePetals);
		addBlock(world, basePos, 0, 13, 0, bluePetals);
		addBlock(world, basePos, 0, 13, 1, lightBluePetals);
		addBlock(world, basePos, 0, 13, 2, lightBluePetals);
		addBlock(world, basePos, 0, 13, 3, lightBluePetals);
		addBlock(world, basePos, 0, 13, 4, lightBluePetals);
		addBlock(world, basePos, 0, 13, 5, lightBluePetals);
		addBlock(world, basePos, 0, 13, 6, lightBluePetals);
		addBlock(world, basePos, 0, 13, 7, lightBluePetals);
		addBlock(world, basePos, 0, 13, 8, lightBluePetals);
		addBlock(world, basePos, 0, 13, 9, lightBluePetals);
		addBlock(world, basePos, 0, 13, 10, bluePetals);
		addBlock(world, basePos, 0, 14, 0, bluePetals);
		addBlock(world, basePos, 0, 14, 1, lightBluePetals);
		addBlock(world, basePos, 0, 14, 2, lightBluePetals);
		addBlock(world, basePos, 0, 14, 3, lightBluePetals);
		addBlock(world, basePos, 0, 14, 4, bluePetals);
		addBlock(world, basePos, 0, 14, 5, bluePetals);
		addBlock(world, basePos, 0, 14, 6, bluePetals);
		addBlock(world, basePos, 0, 14, 7, lightBluePetals);
		addBlock(world, basePos, 0, 14, 8, lightBluePetals);
		addBlock(world, basePos, 0, 14, 9, lightBluePetals);
		addBlock(world, basePos, 0, 14, 10, bluePetals);
		addBlock(world, basePos, 0, 15, 0, bluePetals);
		addBlock(world, basePos, 0, 15, 1, lightBluePetals);
		addBlock(world, basePos, 0, 15, 2, lightBluePetals);
		addBlock(world, basePos, 0, 15, 3, bluePetals);
		addBlock(world, basePos, 0, 15, 4, bluePetals);
		addBlock(world, basePos, 0, 15, 6, bluePetals);
		addBlock(world, basePos, 0, 15, 7, bluePetals);
		addBlock(world, basePos, 0, 15, 8, lightBluePetals);
		addBlock(world, basePos, 0, 15, 9, lightBluePetals);
		addBlock(world, basePos, 0, 15, 10, bluePetals);
		addBlock(world, basePos, 0, 16, 0, bluePetals);
		addBlock(world, basePos, 0, 16, 1, bluePetals);
		addBlock(world, basePos, 0, 16, 2, bluePetals);
		addBlock(world, basePos, 0, 16, 3, bluePetals);
		addBlock(world, basePos, 0, 16, 7, bluePetals);
		addBlock(world, basePos, 0, 16, 8, bluePetals);
		addBlock(world, basePos, 0, 16, 9, bluePetals);
		addBlock(world, basePos, 0, 16, 10, bluePetals);
	}
}
