package net.tslat.aoa3.structure.creeponia;

import net.minecraft.block.BlockVine;
import net.minecraft.block.state.IBlockState;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
import net.tslat.aoa3.common.registration.BlockRegister;
import net.tslat.aoa3.structure.AoAStructure;

import java.util.Random;

public class CreepTree6 extends AoAStructure { //StructureSize: 7x13x7
	private static final IBlockState creepLeaves = BlockRegister.leavesCreep.getDefaultState();
	private static final IBlockState creepLog = BlockRegister.logCreep.getDefaultState();
	private static final IBlockState creepVineEast = BlockRegister.plantCreepVines.getDefaultState().withProperty(BlockVine.EAST, true);
	private static final IBlockState creepVineNorth = BlockRegister.plantCreepVines.getDefaultState().withProperty(BlockVine.NORTH, true);
	private static final IBlockState creepVineSouth = BlockRegister.plantCreepVines.getDefaultState().withProperty(BlockVine.SOUTH, true);
	private static final IBlockState creepVineWest = BlockRegister.plantCreepVines.getDefaultState().withProperty(BlockVine.WEST, true);

	public CreepTree6() {
		super("CreepTree6");
	}

	@Override
	protected void build(World world, Random rand, BlockPos basePos) {
		addBlock(world, basePos, 3, 0, 3, creepLog);
		addBlock(world, basePos, 3, 1, 3, creepLog);
		addBlock(world, basePos, 3, 2, 3, creepLog);
		addBlock(world, basePos, 3, 3, 3, creepLog);
		addBlock(world, basePos, 1, 4, 1, creepLeaves);
		addBlock(world, basePos, 1, 4, 2, creepLeaves);
		addBlock(world, basePos, 1, 4, 3, creepLeaves);
		addBlock(world, basePos, 1, 4, 4, creepLeaves);
		addBlock(world, basePos, 1, 4, 5, creepLeaves);
		addBlock(world, basePos, 2, 4, 1, creepLeaves);
		addBlock(world, basePos, 2, 4, 2, creepLeaves);
		addBlock(world, basePos, 2, 4, 3, creepLeaves);
		addBlock(world, basePos, 2, 4, 4, creepLeaves);
		addBlock(world, basePos, 2, 4, 5, creepLeaves);
		addBlock(world, basePos, 3, 4, 1, creepLeaves);
		addBlock(world, basePos, 3, 4, 2, creepLeaves);
		addBlock(world, basePos, 3, 4, 3, creepLeaves);
		addBlock(world, basePos, 3, 4, 4, creepLeaves);
		addBlock(world, basePos, 3, 4, 5, creepLeaves);
		addBlock(world, basePos, 4, 4, 1, creepLeaves);
		addBlock(world, basePos, 4, 4, 2, creepLeaves);
		addBlock(world, basePos, 4, 4, 3, creepLeaves);
		addBlock(world, basePos, 4, 4, 4, creepLeaves);
		addBlock(world, basePos, 4, 4, 5, creepLeaves);
		addBlock(world, basePos, 5, 4, 1, creepLeaves);
		addBlock(world, basePos, 5, 4, 2, creepLeaves);
		addBlock(world, basePos, 5, 4, 3, creepLeaves);
		addBlock(world, basePos, 5, 4, 4, creepLeaves);
		addBlock(world, basePos, 5, 4, 5, creepLeaves);
		addBlock(world, basePos, 3, 5, 3, creepLog);
		addBlock(world, basePos, 3, 6, 3, creepLog);
		addBlock(world, basePos, 3, 7, 3, creepLog);
		addBlock(world, basePos, 1, 8, 1, creepLeaves);
		addBlock(world, basePos, 1, 8, 2, creepLeaves);
		addBlock(world, basePos, 1, 8, 3, creepLeaves);
		addBlock(world, basePos, 1, 8, 4, creepLeaves);
		addBlock(world, basePos, 1, 8, 5, creepLeaves);
		addBlock(world, basePos, 2, 8, 1, creepLeaves);
		addBlock(world, basePos, 2, 8, 2, creepLeaves);
		addBlock(world, basePos, 2, 8, 3, creepLeaves);
		addBlock(world, basePos, 2, 8, 4, creepLeaves);
		addBlock(world, basePos, 2, 8, 5, creepLeaves);
		addBlock(world, basePos, 3, 8, 1, creepLeaves);
		addBlock(world, basePos, 3, 8, 2, creepLeaves);
		addBlock(world, basePos, 3, 8, 3, creepLeaves);
		addBlock(world, basePos, 3, 8, 4, creepLeaves);
		addBlock(world, basePos, 3, 8, 5, creepLeaves);
		addBlock(world, basePos, 4, 8, 1, creepLeaves);
		addBlock(world, basePos, 4, 8, 2, creepLeaves);
		addBlock(world, basePos, 4, 8, 3, creepLeaves);
		addBlock(world, basePos, 4, 8, 4, creepLeaves);
		addBlock(world, basePos, 4, 8, 5, creepLeaves);
		addBlock(world, basePos, 5, 8, 1, creepLeaves);
		addBlock(world, basePos, 5, 8, 2, creepLeaves);
		addBlock(world, basePos, 5, 8, 3, creepLeaves);
		addBlock(world, basePos, 5, 8, 4, creepLeaves);
		addBlock(world, basePos, 5, 8, 5, creepLeaves);
		addBlock(world, basePos, 2, 9, 2, creepLeaves);
		addBlock(world, basePos, 2, 9, 3, creepLeaves);
		addBlock(world, basePos, 2, 9, 4, creepLeaves);
		addBlock(world, basePos, 3, 9, 2, creepLeaves);
		addBlock(world, basePos, 3, 9, 3, creepLog);
		addBlock(world, basePos, 3, 9, 4, creepLeaves);
		addBlock(world, basePos, 4, 9, 2, creepLeaves);
		addBlock(world, basePos, 4, 9, 3, creepLeaves);
		addBlock(world, basePos, 4, 9, 4, creepLeaves);
		addBlock(world, basePos, 3, 10, 3, creepLog);
		addBlock(world, basePos, 3, 11, 3, creepLog);
		addBlock(world, basePos, 2, 12, 2, creepLeaves);
		addBlock(world, basePos, 2, 12, 3, creepLeaves);
		addBlock(world, basePos, 2, 12, 4, creepLeaves);
		addBlock(world, basePos, 3, 12, 2, creepLeaves);
		addBlock(world, basePos, 3, 12, 3, creepLeaves);
		addBlock(world, basePos, 3, 12, 4, creepLeaves);
		addBlock(world, basePos, 4, 12, 2, creepLeaves);
		addBlock(world, basePos, 4, 12, 3, creepLeaves);
		addBlock(world, basePos, 4, 12, 4, creepLeaves);

		addBlock(world, basePos, 1, 1, 0, creepVineSouth);
		addBlock(world, basePos, 1, 1, 6, creepVineNorth);
		addBlock(world, basePos, 5, 1, 0, creepVineSouth);
		addBlock(world, basePos, 5, 1, 6, creepVineNorth);
		addBlock(world, basePos, 1, 2, 0, creepVineSouth);
		addBlock(world, basePos, 1, 2, 6, creepVineNorth);
		addBlock(world, basePos, 2, 2, 0, creepVineSouth);
		addBlock(world, basePos, 2, 2, 6, creepVineNorth);
		addBlock(world, basePos, 4, 2, 0, creepVineSouth);
		addBlock(world, basePos, 4, 2, 6, creepVineNorth);
		addBlock(world, basePos, 5, 2, 0, creepVineSouth);
		addBlock(world, basePos, 5, 2, 6, creepVineNorth);
		addBlock(world, basePos, 0, 3, 5, creepVineEast);
		addBlock(world, basePos, 1, 3, 0, creepVineSouth);
		addBlock(world, basePos, 1, 3, 6, creepVineNorth);
		addBlock(world, basePos, 2, 3, 0, creepVineSouth);
		addBlock(world, basePos, 2, 3, 6, creepVineNorth);
		addBlock(world, basePos, 3, 3, 0, creepVineSouth);
		addBlock(world, basePos, 3, 3, 6, creepVineNorth);
		addBlock(world, basePos, 4, 3, 0, creepVineSouth);
		addBlock(world, basePos, 4, 3, 6, creepVineNorth);
		addBlock(world, basePos, 5, 3, 0, creepVineSouth);
		addBlock(world, basePos, 5, 3, 6, creepVineNorth);
		addBlock(world, basePos, 6, 3, 5, creepVineWest);
		addBlock(world, basePos, 0, 4, 1, creepVineEast);
		addBlock(world, basePos, 0, 4, 2, creepVineEast);
		addBlock(world, basePos, 0, 4, 3, creepVineEast);
		addBlock(world, basePos, 0, 4, 4, creepVineEast);
		addBlock(world, basePos, 0, 4, 5, creepVineEast);
		addBlock(world, basePos, 1, 4, 0, creepVineSouth);
		addBlock(world, basePos, 1, 4, 6, creepVineNorth);
		addBlock(world, basePos, 2, 4, 0, creepVineSouth);
		addBlock(world, basePos, 2, 4, 6, creepVineNorth);
		addBlock(world, basePos, 3, 4, 0, creepVineSouth);
		addBlock(world, basePos, 3, 4, 6, creepVineNorth);
		addBlock(world, basePos, 4, 4, 0, creepVineSouth);
		addBlock(world, basePos, 4, 4, 6, creepVineNorth);
		addBlock(world, basePos, 5, 4, 0, creepVineSouth);
		addBlock(world, basePos, 5, 4, 6, creepVineNorth);
		addBlock(world, basePos, 6, 4, 1, creepVineWest);
		addBlock(world, basePos, 6, 4, 2, creepVineWest);
		addBlock(world, basePos, 6, 4, 3, creepVineWest);
		addBlock(world, basePos, 6, 4, 4, creepVineWest);
		addBlock(world, basePos, 6, 4, 5, creepVineWest);
		addBlock(world, basePos, 0, 6, 5, creepVineEast);
		addBlock(world, basePos, 1, 6, 0, creepVineSouth);
		addBlock(world, basePos, 1, 6, 6, creepVineNorth);
		addBlock(world, basePos, 2, 6, 0, creepVineSouth);
		addBlock(world, basePos, 2, 6, 6, creepVineNorth);
		addBlock(world, basePos, 3, 6, 0, creepVineSouth);
		addBlock(world, basePos, 3, 6, 6, creepVineNorth);
		addBlock(world, basePos, 4, 6, 0, creepVineSouth);
		addBlock(world, basePos, 4, 6, 6, creepVineNorth);
		addBlock(world, basePos, 5, 6, 0, creepVineSouth);
		addBlock(world, basePos, 5, 6, 6, creepVineNorth);
		addBlock(world, basePos, 6, 6, 5, creepVineWest);
		addBlock(world, basePos, 0, 7, 1, creepVineEast);
		addBlock(world, basePos, 0, 7, 5, creepVineEast);
		addBlock(world, basePos, 1, 7, 0, creepVineSouth);
		addBlock(world, basePos, 1, 7, 6, creepVineNorth);
		addBlock(world, basePos, 2, 7, 0, creepVineSouth);
		addBlock(world, basePos, 2, 7, 6, creepVineNorth);
		addBlock(world, basePos, 3, 7, 0, creepVineSouth);
		addBlock(world, basePos, 3, 7, 6, creepVineNorth);
		addBlock(world, basePos, 4, 7, 0, creepVineSouth);
		addBlock(world, basePos, 4, 7, 6, creepVineNorth);
		addBlock(world, basePos, 5, 7, 0, creepVineSouth);
		addBlock(world, basePos, 5, 7, 6, creepVineNorth);
		addBlock(world, basePos, 6, 7, 5, creepVineWest);
		addBlock(world, basePos, 0, 8, 1, creepVineEast);
		addBlock(world, basePos, 0, 8, 2, creepVineEast);
		addBlock(world, basePos, 0, 8, 3, creepVineEast);
		addBlock(world, basePos, 0, 8, 4, creepVineEast);
		addBlock(world, basePos, 0, 8, 5, creepVineEast);
		addBlock(world, basePos, 1, 8, 0, creepVineSouth);
		addBlock(world, basePos, 1, 8, 6, creepVineNorth);
		addBlock(world, basePos, 2, 8, 0, creepVineSouth);
		addBlock(world, basePos, 2, 8, 6, creepVineNorth);
		addBlock(world, basePos, 3, 8, 0, creepVineSouth);
		addBlock(world, basePos, 3, 8, 6, creepVineNorth);
		addBlock(world, basePos, 4, 8, 0, creepVineSouth);
		addBlock(world, basePos, 4, 8, 6, creepVineNorth);
		addBlock(world, basePos, 5, 8, 0, creepVineSouth);
		addBlock(world, basePos, 5, 8, 6, creepVineNorth);
		addBlock(world, basePos, 6, 8, 1, creepVineWest);
		addBlock(world, basePos, 6, 8, 2, creepVineWest);
		addBlock(world, basePos, 6, 8, 3, creepVineWest);
		addBlock(world, basePos, 6, 8, 4, creepVineWest);
		addBlock(world, basePos, 6, 8, 5, creepVineWest);
		addBlock(world, basePos, 1, 10, 4, creepVineEast);
		addBlock(world, basePos, 2, 10, 1, creepVineSouth);
		addBlock(world, basePos, 2, 10, 5, creepVineNorth);
		addBlock(world, basePos, 3, 10, 1, creepVineSouth);
		addBlock(world, basePos, 3, 10, 5, creepVineNorth);
		addBlock(world, basePos, 4, 10, 1, creepVineSouth);
		addBlock(world, basePos, 4, 10, 5, creepVineNorth);
		addBlock(world, basePos, 5, 10, 4, creepVineWest);
		addBlock(world, basePos, 1, 11, 4, creepVineEast);
		addBlock(world, basePos, 2, 11, 1, creepVineSouth);
		addBlock(world, basePos, 2, 11, 5, creepVineNorth);
		addBlock(world, basePos, 3, 11, 1, creepVineSouth);
		addBlock(world, basePos, 3, 11, 5, creepVineNorth);
		addBlock(world, basePos, 4, 11, 1, creepVineSouth);
		addBlock(world, basePos, 4, 11, 5, creepVineNorth);
		addBlock(world, basePos, 5, 11, 4, creepVineWest);
		addBlock(world, basePos, 1, 12, 2, creepVineEast);
		addBlock(world, basePos, 1, 12, 3, creepVineEast);
		addBlock(world, basePos, 1, 12, 4, creepVineEast);
		addBlock(world, basePos, 2, 12, 1, creepVineSouth);
		addBlock(world, basePos, 2, 12, 5, creepVineNorth);
		addBlock(world, basePos, 3, 12, 1, creepVineSouth);
		addBlock(world, basePos, 3, 12, 5, creepVineNorth);
		addBlock(world, basePos, 4, 12, 1, creepVineSouth);
		addBlock(world, basePos, 4, 12, 5, creepVineNorth);
		addBlock(world, basePos, 5, 12, 2, creepVineWest);
		addBlock(world, basePos, 5, 12, 3, creepVineWest);
		addBlock(world, basePos, 5, 12, 4, creepVineWest);
	}
}
