package net.tslat.aoa3.structure.deeplands;

import net.minecraft.block.state.IBlockState;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
import net.tslat.aoa3.common.registration.BlockRegister;
import net.tslat.aoa3.structure.AoAStructure;

import java.util.Random;

public class Deepshine5 extends AoAStructure { //StructureSize: 3x42x3
	private static final IBlockState stone = BlockRegister.stoneDeeplands.getDefaultState();
	private static final IBlockState deepshine = BlockRegister.deepshine.getDefaultState();

	public Deepshine5() {
		super("Deepshine5");
	}

	@Override
	protected void build(World world, Random rand, BlockPos basePos) {
		addBlock(world, basePos, 1, 0, 1, stone);
		addBlock(world, basePos, 1, 1, 1, stone);
		addBlock(world, basePos, 0, 2, 0, deepshine);
		addBlock(world, basePos, 0, 2, 1, deepshine);
		addBlock(world, basePos, 0, 2, 2, deepshine);
		addBlock(world, basePos, 1, 2, 0, deepshine);
		addBlock(world, basePos, 1, 2, 1, stone);
		addBlock(world, basePos, 1, 2, 2, deepshine);
		addBlock(world, basePos, 2, 2, 0, deepshine);
		addBlock(world, basePos, 2, 2, 1, deepshine);
		addBlock(world, basePos, 2, 2, 2, deepshine);
		addBlock(world, basePos, 1, 3, 1, stone);
		addBlock(world, basePos, 1, 4, 1, stone);
		addBlock(world, basePos, 0, 5, 0, deepshine);
		addBlock(world, basePos, 0, 5, 1, deepshine);
		addBlock(world, basePos, 0, 5, 2, deepshine);
		addBlock(world, basePos, 1, 5, 0, deepshine);
		addBlock(world, basePos, 1, 5, 1, stone);
		addBlock(world, basePos, 1, 5, 2, deepshine);
		addBlock(world, basePos, 2, 5, 0, deepshine);
		addBlock(world, basePos, 2, 5, 1, deepshine);
		addBlock(world, basePos, 2, 5, 2, deepshine);
		addBlock(world, basePos, 1, 6, 1, stone);
		addBlock(world, basePos, 1, 7, 1, stone);
		addBlock(world, basePos, 0, 8, 0, deepshine);
		addBlock(world, basePos, 0, 8, 1, deepshine);
		addBlock(world, basePos, 0, 8, 2, deepshine);
		addBlock(world, basePos, 1, 8, 0, deepshine);
		addBlock(world, basePos, 1, 8, 1, stone);
		addBlock(world, basePos, 1, 8, 2, deepshine);
		addBlock(world, basePos, 2, 8, 0, deepshine);
		addBlock(world, basePos, 2, 8, 1, deepshine);
		addBlock(world, basePos, 2, 8, 2, deepshine);
		addBlock(world, basePos, 1, 9, 1, stone);
		addBlock(world, basePos, 1, 10, 1, stone);
		addBlock(world, basePos, 0, 11, 0, deepshine);
		addBlock(world, basePos, 0, 11, 1, deepshine);
		addBlock(world, basePos, 0, 11, 2, deepshine);
		addBlock(world, basePos, 1, 11, 0, deepshine);
		addBlock(world, basePos, 1, 11, 1, stone);
		addBlock(world, basePos, 1, 11, 2, deepshine);
		addBlock(world, basePos, 2, 11, 0, deepshine);
		addBlock(world, basePos, 2, 11, 1, deepshine);
		addBlock(world, basePos, 2, 11, 2, deepshine);
		addBlock(world, basePos, 1, 12, 1, stone);
		addBlock(world, basePos, 1, 13, 1, stone);
		addBlock(world, basePos, 0, 14, 0, deepshine);
		addBlock(world, basePos, 0, 14, 1, deepshine);
		addBlock(world, basePos, 0, 14, 2, deepshine);
		addBlock(world, basePos, 1, 14, 0, deepshine);
		addBlock(world, basePos, 1, 14, 1, stone);
		addBlock(world, basePos, 1, 14, 2, deepshine);
		addBlock(world, basePos, 2, 14, 0, deepshine);
		addBlock(world, basePos, 2, 14, 1, deepshine);
		addBlock(world, basePos, 2, 14, 2, deepshine);
		addBlock(world, basePos, 1, 15, 1, stone);
		addBlock(world, basePos, 1, 16, 1, stone);
		addBlock(world, basePos, 0, 17, 0, deepshine);
		addBlock(world, basePos, 0, 17, 1, deepshine);
		addBlock(world, basePos, 0, 17, 2, deepshine);
		addBlock(world, basePos, 1, 17, 0, deepshine);
		addBlock(world, basePos, 1, 17, 1, stone);
		addBlock(world, basePos, 1, 17, 2, deepshine);
		addBlock(world, basePos, 2, 17, 0, deepshine);
		addBlock(world, basePos, 2, 17, 1, deepshine);
		addBlock(world, basePos, 2, 17, 2, deepshine);
		addBlock(world, basePos, 1, 18, 1, stone);
		addBlock(world, basePos, 1, 19, 1, stone);
		addBlock(world, basePos, 0, 20, 0, deepshine);
		addBlock(world, basePos, 0, 20, 1, deepshine);
		addBlock(world, basePos, 0, 20, 2, deepshine);
		addBlock(world, basePos, 1, 20, 0, deepshine);
		addBlock(world, basePos, 1, 20, 1, stone);
		addBlock(world, basePos, 1, 20, 2, deepshine);
		addBlock(world, basePos, 2, 20, 0, deepshine);
		addBlock(world, basePos, 2, 20, 1, deepshine);
		addBlock(world, basePos, 2, 20, 2, deepshine);
		addBlock(world, basePos, 1, 21, 1, stone);
		addBlock(world, basePos, 1, 22, 1, stone);
		addBlock(world, basePos, 0, 23, 0, deepshine);
		addBlock(world, basePos, 0, 23, 1, deepshine);
		addBlock(world, basePos, 0, 23, 2, deepshine);
		addBlock(world, basePos, 1, 23, 0, deepshine);
		addBlock(world, basePos, 1, 23, 1, stone);
		addBlock(world, basePos, 1, 23, 2, deepshine);
		addBlock(world, basePos, 2, 23, 0, deepshine);
		addBlock(world, basePos, 2, 23, 1, deepshine);
		addBlock(world, basePos, 2, 23, 2, deepshine);
		addBlock(world, basePos, 1, 24, 1, stone);
		addBlock(world, basePos, 1, 25, 1, stone);
		addBlock(world, basePos, 0, 26, 0, deepshine);
		addBlock(world, basePos, 0, 26, 1, deepshine);
		addBlock(world, basePos, 0, 26, 2, deepshine);
		addBlock(world, basePos, 1, 26, 0, deepshine);
		addBlock(world, basePos, 1, 26, 1, stone);
		addBlock(world, basePos, 1, 26, 2, deepshine);
		addBlock(world, basePos, 2, 26, 0, deepshine);
		addBlock(world, basePos, 2, 26, 1, deepshine);
		addBlock(world, basePos, 2, 26, 2, deepshine);
		addBlock(world, basePos, 1, 27, 1, stone);
		addBlock(world, basePos, 1, 28, 1, stone);
		addBlock(world, basePos, 0, 29, 0, deepshine);
		addBlock(world, basePos, 0, 29, 1, deepshine);
		addBlock(world, basePos, 0, 29, 2, deepshine);
		addBlock(world, basePos, 1, 29, 0, deepshine);
		addBlock(world, basePos, 1, 29, 1, stone);
		addBlock(world, basePos, 1, 29, 2, deepshine);
		addBlock(world, basePos, 2, 29, 0, deepshine);
		addBlock(world, basePos, 2, 29, 1, deepshine);
		addBlock(world, basePos, 2, 29, 2, deepshine);
		addBlock(world, basePos, 1, 30, 1, stone);
		addBlock(world, basePos, 1, 31, 1, stone);
		addBlock(world, basePos, 0, 32, 0, deepshine);
		addBlock(world, basePos, 0, 32, 1, deepshine);
		addBlock(world, basePos, 0, 32, 2, deepshine);
		addBlock(world, basePos, 1, 32, 0, deepshine);
		addBlock(world, basePos, 1, 32, 1, stone);
		addBlock(world, basePos, 1, 32, 2, deepshine);
		addBlock(world, basePos, 2, 32, 0, deepshine);
		addBlock(world, basePos, 2, 32, 1, deepshine);
		addBlock(world, basePos, 2, 32, 2, deepshine);
		addBlock(world, basePos, 1, 33, 1, stone);
		addBlock(world, basePos, 1, 34, 1, stone);
		addBlock(world, basePos, 0, 35, 0, deepshine);
		addBlock(world, basePos, 0, 35, 1, deepshine);
		addBlock(world, basePos, 0, 35, 2, deepshine);
		addBlock(world, basePos, 1, 35, 0, deepshine);
		addBlock(world, basePos, 1, 35, 1, stone);
		addBlock(world, basePos, 1, 35, 2, deepshine);
		addBlock(world, basePos, 2, 35, 0, deepshine);
		addBlock(world, basePos, 2, 35, 1, deepshine);
		addBlock(world, basePos, 2, 35, 2, deepshine);
		addBlock(world, basePos, 1, 36, 1, stone);
		addBlock(world, basePos, 1, 37, 1, stone);
		addBlock(world, basePos, 0, 38, 0, deepshine);
		addBlock(world, basePos, 0, 38, 1, deepshine);
		addBlock(world, basePos, 0, 38, 2, deepshine);
		addBlock(world, basePos, 1, 38, 0, deepshine);
		addBlock(world, basePos, 1, 38, 1, stone);
		addBlock(world, basePos, 1, 38, 2, deepshine);
		addBlock(world, basePos, 2, 38, 0, deepshine);
		addBlock(world, basePos, 2, 38, 1, deepshine);
		addBlock(world, basePos, 2, 38, 2, deepshine);
		addBlock(world, basePos, 1, 39, 1, stone);
		addBlock(world, basePos, 1, 40, 1, stone);
		addBlock(world, basePos, 0, 41, 0, deepshine);
		addBlock(world, basePos, 0, 41, 1, deepshine);
		addBlock(world, basePos, 0, 41, 2, deepshine);
		addBlock(world, basePos, 1, 41, 0, deepshine);
		addBlock(world, basePos, 1, 41, 1, stone);
		addBlock(world, basePos, 1, 41, 2, deepshine);
		addBlock(world, basePos, 2, 41, 0, deepshine);
		addBlock(world, basePos, 2, 41, 1, deepshine);
		addBlock(world, basePos, 2, 41, 2, deepshine);
	}
}
