package net.nevermine.structures.gardencia;

import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenerator;
import net.nevermine.izer.Blockizer;

import java.util.Random;

public class StarflowerRose2 extends WorldGenerator {
	public boolean generate(final World world, final Random rand, final int i, final int j, final int k) {
		if (world.getBlock(i + 0, j - 1, k + 5) != Blockizer.GrassGardencia && world.getBlock(i + 0, j - 1, k + 5) != Blockizer.DirtGardencia) {
			return false;
		}
		world.setBlock(i + 0, j + 0, k + 5, Blockizer.PlantStem);
		world.setBlock(i + 0, j + 1, k + 5, Blockizer.PlantStem);
		world.setBlock(i + 0, j + 2, k + 5, Blockizer.PlantStem);
		world.setBlock(i + 0, j + 3, k + 0, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 3, k + 1, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 3, k + 2, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 3, k + 3, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 3, k + 5, Blockizer.PlantStem);
		world.setBlock(i + 0, j + 3, k + 7, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 3, k + 8, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 3, k + 9, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 3, k + 10, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 4, k + 0, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 4, k + 1, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 4, k + 2, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 4, k + 3, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 4, k + 4, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 4, k + 5, Blockizer.PlantStem);
		world.setBlock(i + 0, j + 4, k + 6, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 4, k + 7, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 4, k + 8, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 4, k + 9, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 4, k + 10, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 5, k + 0, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 5, k + 1, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 5, k + 2, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 5, k + 3, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 5, k + 4, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 5, k + 5, Blockizer.PlantStem);
		world.setBlock(i + 0, j + 5, k + 6, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 5, k + 7, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 5, k + 8, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 5, k + 9, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 5, k + 10, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 6, k + 0, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 6, k + 1, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 6, k + 2, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 6, k + 3, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 6, k + 4, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 6, k + 5, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 6, k + 6, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 6, k + 7, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 6, k + 8, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 6, k + 9, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 6, k + 10, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 7, k + 0, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 7, k + 1, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 7, k + 2, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 7, k + 3, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 7, k + 4, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 7, k + 5, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 7, k + 6, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 7, k + 7, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 7, k + 8, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 7, k + 9, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 7, k + 10, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 8, k + 1, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 8, k + 2, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 8, k + 3, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 8, k + 4, Blockizer.FlowerCore);
		world.setBlock(i + 0, j + 8, k + 5, Blockizer.FlowerCore);
		world.setBlock(i + 0, j + 8, k + 6, Blockizer.FlowerCore);
		world.setBlock(i + 0, j + 8, k + 7, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 8, k + 8, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 8, k + 9, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 9, k + 2, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 9, k + 3, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 9, k + 4, Blockizer.FlowerCore);
		world.setBlock(i + 0, j + 9, k + 5, Blockizer.FlowerCore);
		world.setBlock(i + 0, j + 9, k + 6, Blockizer.FlowerCore);
		world.setBlock(i + 0, j + 9, k + 7, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 9, k + 8, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 10, k + 2, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 10, k + 3, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 10, k + 4, Blockizer.FlowerCore);
		world.setBlock(i + 0, j + 10, k + 5, Blockizer.FlowerCore);
		world.setBlock(i + 0, j + 10, k + 6, Blockizer.FlowerCore);
		world.setBlock(i + 0, j + 10, k + 7, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 10, k + 8, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 10, k + 9, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 11, k + 1, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 11, k + 2, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 11, k + 3, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 11, k + 4, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 11, k + 5, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 11, k + 6, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 11, k + 7, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 11, k + 8, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 11, k + 9, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 11, k + 10, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 12, k + 0, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 12, k + 1, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 12, k + 2, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 12, k + 3, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 12, k + 4, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 12, k + 5, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 12, k + 6, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 12, k + 7, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 12, k + 8, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 12, k + 9, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 12, k + 10, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 13, k + 0, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 13, k + 1, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 13, k + 2, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 13, k + 3, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 13, k + 4, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 13, k + 5, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 13, k + 6, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 13, k + 7, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 13, k + 8, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 13, k + 9, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 13, k + 10, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 14, k + 0, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 14, k + 1, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 14, k + 2, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 14, k + 3, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 14, k + 4, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 14, k + 5, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 14, k + 6, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 14, k + 7, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 14, k + 8, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 14, k + 9, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 14, k + 10, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 15, k + 0, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 15, k + 1, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 15, k + 2, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 15, k + 3, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 15, k + 4, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 15, k + 6, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 15, k + 7, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 15, k + 8, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 15, k + 9, Blockizer.PedalsLightRose);
		world.setBlock(i + 0, j + 15, k + 10, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 16, k + 0, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 16, k + 1, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 16, k + 2, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 16, k + 3, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 16, k + 7, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 16, k + 8, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 16, k + 9, Blockizer.PedalsRose);
		world.setBlock(i + 0, j + 16, k + 10, Blockizer.PedalsRose);
		return true;
	}
}
