package net.tslat.aoa3.worldgen.structures.haven;

import net.minecraft.block.BlockState;
import net.minecraft.block.Blocks;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.IWorld;
import net.tslat.aoa3.common.registration.AoABlocks;
import net.tslat.aoa3.worldgen.structures.AoAStructure;

import java.util.Random;

public class PurpleHavenTree extends AoAStructure { //StructureSize: 10x12x10
	private static final BlockState purpleLeaves = AoABlocks.PURPLE_HAVEN_LEAVES.get().getDefaultState();
	private static final BlockState log = Blocks.OAK_LOG.getDefaultState();

	public PurpleHavenTree() {
		super("PurpleHavenTree");
	}

	@Override
	protected void build(IWorld world, Random rand, BlockPos basePos) {
		addBlock(world, basePos, 4, 0, 4, log);
		addBlock(world, basePos, 4, 0, 5, log);
		addBlock(world, basePos, 5, 0, 4, log);
		addBlock(world, basePos, 5, 0, 5, log);
		addBlock(world, basePos, 4, 1, 4, log);
		addBlock(world, basePos, 4, 1, 5, log);
		addBlock(world, basePos, 5, 1, 4, log);
		addBlock(world, basePos, 5, 1, 5, log);
		addBlock(world, basePos, 4, 2, 4, log);
		addBlock(world, basePos, 4, 2, 5, log);
		addBlock(world, basePos, 5, 2, 4, log);
		addBlock(world, basePos, 5, 2, 5, log);
		addBlock(world, basePos, 4, 3, 4, log);
		addBlock(world, basePos, 4, 3, 5, log);
		addBlock(world, basePos, 5, 3, 4, log);
		addBlock(world, basePos, 5, 3, 5, log);
		addBlock(world, basePos, 4, 4, 4, log);
		addBlock(world, basePos, 4, 4, 5, log);
		addBlock(world, basePos, 5, 4, 4, log);
		addBlock(world, basePos, 5, 4, 5, log);
		addBlock(world, basePos, 4, 5, 4, log);
		addBlock(world, basePos, 4, 5, 5, log);
		addBlock(world, basePos, 5, 5, 4, log);
		addBlock(world, basePos, 5, 5, 5, log);
		addBlock(world, basePos, 4, 6, 4, log);
		addBlock(world, basePos, 4, 6, 5, log);
		addBlock(world, basePos, 5, 6, 4, log);
		addBlock(world, basePos, 5, 6, 5, log);
		addBlock(world, basePos, 4, 7, 4, log);
		addBlock(world, basePos, 4, 7, 5, log);
		addBlock(world, basePos, 5, 7, 4, log);
		addBlock(world, basePos, 5, 7, 5, log);
		addBlock(world, basePos, 0, 8, 2, purpleLeaves);
		addBlock(world, basePos, 0, 8, 3, purpleLeaves);
		addBlock(world, basePos, 0, 8, 4, purpleLeaves);
		addBlock(world, basePos, 0, 8, 5, purpleLeaves);
		addBlock(world, basePos, 0, 8, 6, purpleLeaves);
		addBlock(world, basePos, 0, 8, 7, purpleLeaves);
		addBlock(world, basePos, 1, 8, 2, purpleLeaves);
		addBlock(world, basePos, 1, 8, 7, purpleLeaves);
		addBlock(world, basePos, 2, 8, 0, purpleLeaves);
		addBlock(world, basePos, 2, 8, 1, purpleLeaves);
		addBlock(world, basePos, 2, 8, 2, purpleLeaves);
		addBlock(world, basePos, 2, 8, 7, purpleLeaves);
		addBlock(world, basePos, 2, 8, 8, purpleLeaves);
		addBlock(world, basePos, 2, 8, 9, purpleLeaves);
		addBlock(world, basePos, 3, 8, 0, purpleLeaves);
		addBlock(world, basePos, 3, 8, 4, log);
		addBlock(world, basePos, 3, 8, 5, log);
		addBlock(world, basePos, 3, 8, 9, purpleLeaves);
		addBlock(world, basePos, 4, 8, 0, purpleLeaves);
		addBlock(world, basePos, 4, 8, 3, log);
		addBlock(world, basePos, 4, 8, 4, log);
		addBlock(world, basePos, 4, 8, 5, log);
		addBlock(world, basePos, 4, 8, 6, log);
		addBlock(world, basePos, 4, 8, 9, purpleLeaves);
		addBlock(world, basePos, 5, 8, 0, purpleLeaves);
		addBlock(world, basePos, 5, 8, 3, log);
		addBlock(world, basePos, 5, 8, 4, log);
		addBlock(world, basePos, 5, 8, 5, log);
		addBlock(world, basePos, 5, 8, 6, log);
		addBlock(world, basePos, 5, 8, 9, purpleLeaves);
		addBlock(world, basePos, 6, 8, 0, purpleLeaves);
		addBlock(world, basePos, 6, 8, 4, log);
		addBlock(world, basePos, 6, 8, 5, log);
		addBlock(world, basePos, 6, 8, 9, purpleLeaves);
		addBlock(world, basePos, 7, 8, 0, purpleLeaves);
		addBlock(world, basePos, 7, 8, 1, purpleLeaves);
		addBlock(world, basePos, 7, 8, 2, purpleLeaves);
		addBlock(world, basePos, 7, 8, 7, purpleLeaves);
		addBlock(world, basePos, 7, 8, 8, purpleLeaves);
		addBlock(world, basePos, 7, 8, 9, purpleLeaves);
		addBlock(world, basePos, 8, 8, 2, purpleLeaves);
		addBlock(world, basePos, 8, 8, 7, purpleLeaves);
		addBlock(world, basePos, 9, 8, 2, purpleLeaves);
		addBlock(world, basePos, 9, 8, 3, purpleLeaves);
		addBlock(world, basePos, 9, 8, 4, purpleLeaves);
		addBlock(world, basePos, 9, 8, 5, purpleLeaves);
		addBlock(world, basePos, 9, 8, 6, purpleLeaves);
		addBlock(world, basePos, 9, 8, 7, purpleLeaves);
		addBlock(world, basePos, 1, 9, 3, purpleLeaves);
		addBlock(world, basePos, 1, 9, 4, purpleLeaves);
		addBlock(world, basePos, 1, 9, 5, purpleLeaves);
		addBlock(world, basePos, 1, 9, 6, purpleLeaves);
		addBlock(world, basePos, 2, 9, 3, purpleLeaves);
		addBlock(world, basePos, 2, 9, 4, log);
		addBlock(world, basePos, 2, 9, 5, log);
		addBlock(world, basePos, 2, 9, 6, purpleLeaves);
		addBlock(world, basePos, 3, 9, 1, purpleLeaves);
		addBlock(world, basePos, 3, 9, 2, purpleLeaves);
		addBlock(world, basePos, 3, 9, 3, purpleLeaves);
		addBlock(world, basePos, 3, 9, 4, log);
		addBlock(world, basePos, 3, 9, 5, log);
		addBlock(world, basePos, 3, 9, 6, purpleLeaves);
		addBlock(world, basePos, 3, 9, 7, purpleLeaves);
		addBlock(world, basePos, 3, 9, 8, purpleLeaves);
		addBlock(world, basePos, 4, 9, 1, purpleLeaves);
		addBlock(world, basePos, 4, 9, 2, log);
		addBlock(world, basePos, 4, 9, 3, log);
		addBlock(world, basePos, 4, 9, 4, purpleLeaves);
		addBlock(world, basePos, 4, 9, 5, purpleLeaves);
		addBlock(world, basePos, 4, 9, 6, log);
		addBlock(world, basePos, 4, 9, 7, log);
		addBlock(world, basePos, 4, 9, 8, purpleLeaves);
		addBlock(world, basePos, 5, 9, 1, purpleLeaves);
		addBlock(world, basePos, 5, 9, 2, log);
		addBlock(world, basePos, 5, 9, 3, log);
		addBlock(world, basePos, 5, 9, 4, purpleLeaves);
		addBlock(world, basePos, 5, 9, 5, purpleLeaves);
		addBlock(world, basePos, 5, 9, 6, log);
		addBlock(world, basePos, 5, 9, 7, log);
		addBlock(world, basePos, 5, 9, 8, purpleLeaves);
		addBlock(world, basePos, 6, 9, 1, purpleLeaves);
		addBlock(world, basePos, 6, 9, 2, purpleLeaves);
		addBlock(world, basePos, 6, 9, 3, purpleLeaves);
		addBlock(world, basePos, 6, 9, 4, log);
		addBlock(world, basePos, 6, 9, 5, log);
		addBlock(world, basePos, 6, 9, 6, purpleLeaves);
		addBlock(world, basePos, 6, 9, 7, purpleLeaves);
		addBlock(world, basePos, 6, 9, 8, purpleLeaves);
		addBlock(world, basePos, 7, 9, 3, purpleLeaves);
		addBlock(world, basePos, 7, 9, 4, log);
		addBlock(world, basePos, 7, 9, 5, log);
		addBlock(world, basePos, 7, 9, 6, purpleLeaves);
		addBlock(world, basePos, 8, 9, 3, purpleLeaves);
		addBlock(world, basePos, 8, 9, 4, purpleLeaves);
		addBlock(world, basePos, 8, 9, 5, purpleLeaves);
		addBlock(world, basePos, 8, 9, 6, purpleLeaves);
		addBlock(world, basePos, 2, 10, 4, purpleLeaves);
		addBlock(world, basePos, 2, 10, 5, purpleLeaves);
		addBlock(world, basePos, 3, 10, 4, purpleLeaves);
		addBlock(world, basePos, 3, 10, 5, purpleLeaves);
		addBlock(world, basePos, 4, 10, 2, purpleLeaves);
		addBlock(world, basePos, 4, 10, 3, purpleLeaves);
		addBlock(world, basePos, 4, 10, 4, purpleLeaves);
		addBlock(world, basePos, 4, 10, 5, purpleLeaves);
		addBlock(world, basePos, 4, 10, 6, purpleLeaves);
		addBlock(world, basePos, 4, 10, 7, purpleLeaves);
		addBlock(world, basePos, 5, 10, 2, purpleLeaves);
		addBlock(world, basePos, 5, 10, 3, purpleLeaves);
		addBlock(world, basePos, 5, 10, 4, purpleLeaves);
		addBlock(world, basePos, 5, 10, 5, purpleLeaves);
		addBlock(world, basePos, 5, 10, 6, purpleLeaves);
		addBlock(world, basePos, 5, 10, 7, purpleLeaves);
		addBlock(world, basePos, 6, 10, 4, purpleLeaves);
		addBlock(world, basePos, 6, 10, 5, purpleLeaves);
		addBlock(world, basePos, 7, 10, 4, purpleLeaves);
		addBlock(world, basePos, 7, 10, 5, purpleLeaves);
		addBlock(world, basePos, 4, 11, 4, purpleLeaves);
		addBlock(world, basePos, 4, 11, 5, purpleLeaves);
		addBlock(world, basePos, 5, 11, 4, purpleLeaves);
		addBlock(world, basePos, 5, 11, 5, purpleLeaves);
	}
}
