package net.tslat.aoa3.worldgen.structures.gardencia;

import net.minecraft.block.BlockState;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.IWorld;
import net.tslat.aoa3.common.registration.AoABlocks;
import net.tslat.aoa3.worldgen.structures.AoAStructure;

import java.util.Random;

public class RoseStarflower1 extends AoAStructure { //StructureSize: 11x17x1
	private static final BlockState rosePetals = AoABlocks.ROSE_PETALS.get().getDefaultState();
	private static final BlockState redPetals = AoABlocks.RED_PETALS.get().getDefaultState();
	private static final BlockState stem = AoABlocks.GIANT_PLANT_STEM.get().getDefaultState();
	private static final BlockState flowerCore = AoABlocks.FLOWER_CORE.get().getDefaultState();

	public RoseStarflower1() {
		super("RoseStarflower1");
	}

	@Override
	protected void build(IWorld world, Random rand, BlockPos basePos) {
		addBlock(world, basePos, 5, 0, 0, stem);
		addBlock(world, basePos, 5, 1, 0, stem);
		addBlock(world, basePos, 5, 2, 0, stem);
		addBlock(world, basePos, 0, 3, 0, rosePetals);
		addBlock(world, basePos, 1, 3, 0, rosePetals);
		addBlock(world, basePos, 2, 3, 0, rosePetals);
		addBlock(world, basePos, 3, 3, 0, rosePetals);
		addBlock(world, basePos, 5, 3, 0, stem);
		addBlock(world, basePos, 7, 3, 0, rosePetals);
		addBlock(world, basePos, 8, 3, 0, rosePetals);
		addBlock(world, basePos, 9, 3, 0, rosePetals);
		addBlock(world, basePos, 10, 3, 0, rosePetals);
		addBlock(world, basePos, 0, 4, 0, rosePetals);
		addBlock(world, basePos, 1, 4, 0, redPetals);
		addBlock(world, basePos, 2, 4, 0, redPetals);
		addBlock(world, basePos, 3, 4, 0, rosePetals);
		addBlock(world, basePos, 4, 4, 0, rosePetals);
		addBlock(world, basePos, 5, 4, 0, stem);
		addBlock(world, basePos, 6, 4, 0, rosePetals);
		addBlock(world, basePos, 7, 4, 0, rosePetals);
		addBlock(world, basePos, 8, 4, 0, redPetals);
		addBlock(world, basePos, 9, 4, 0, redPetals);
		addBlock(world, basePos, 10, 4, 0, rosePetals);
		addBlock(world, basePos, 0, 5, 0, rosePetals);
		addBlock(world, basePos, 1, 5, 0, redPetals);
		addBlock(world, basePos, 2, 5, 0, redPetals);
		addBlock(world, basePos, 3, 5, 0, redPetals);
		addBlock(world, basePos, 4, 5, 0, rosePetals);
		addBlock(world, basePos, 5, 5, 0, stem);
		addBlock(world, basePos, 6, 5, 0, rosePetals);
		addBlock(world, basePos, 7, 5, 0, redPetals);
		addBlock(world, basePos, 8, 5, 0, redPetals);
		addBlock(world, basePos, 9, 5, 0, redPetals);
		addBlock(world, basePos, 10, 5, 0, rosePetals);
		addBlock(world, basePos, 0, 6, 0, rosePetals);
		addBlock(world, basePos, 1, 6, 0, redPetals);
		addBlock(world, basePos, 2, 6, 0, redPetals);
		addBlock(world, basePos, 3, 6, 0, redPetals);
		addBlock(world, basePos, 4, 6, 0, redPetals);
		addBlock(world, basePos, 5, 6, 0, redPetals);
		addBlock(world, basePos, 6, 6, 0, redPetals);
		addBlock(world, basePos, 7, 6, 0, redPetals);
		addBlock(world, basePos, 8, 6, 0, redPetals);
		addBlock(world, basePos, 9, 6, 0, redPetals);
		addBlock(world, basePos, 10, 6, 0, rosePetals);
		addBlock(world, basePos, 0, 7, 0, rosePetals);
		addBlock(world, basePos, 1, 7, 0, rosePetals);
		addBlock(world, basePos, 2, 7, 0, redPetals);
		addBlock(world, basePos, 3, 7, 0, redPetals);
		addBlock(world, basePos, 4, 7, 0, redPetals);
		addBlock(world, basePos, 5, 7, 0, redPetals);
		addBlock(world, basePos, 6, 7, 0, redPetals);
		addBlock(world, basePos, 7, 7, 0, redPetals);
		addBlock(world, basePos, 8, 7, 0, redPetals);
		addBlock(world, basePos, 9, 7, 0, rosePetals);
		addBlock(world, basePos, 10, 7, 0, rosePetals);
		addBlock(world, basePos, 1, 8, 0, rosePetals);
		addBlock(world, basePos, 2, 8, 0, rosePetals);
		addBlock(world, basePos, 3, 8, 0, redPetals);
		addBlock(world, basePos, 4, 8, 0, flowerCore);
		addBlock(world, basePos, 5, 8, 0, flowerCore);
		addBlock(world, basePos, 6, 8, 0, flowerCore);
		addBlock(world, basePos, 7, 8, 0, redPetals);
		addBlock(world, basePos, 8, 8, 0, rosePetals);
		addBlock(world, basePos, 9, 8, 0, rosePetals);
		addBlock(world, basePos, 2, 9, 0, rosePetals);
		addBlock(world, basePos, 3, 9, 0, redPetals);
		addBlock(world, basePos, 4, 9, 0, flowerCore);
		addBlock(world, basePos, 5, 9, 0, flowerCore);
		addBlock(world, basePos, 6, 9, 0, flowerCore);
		addBlock(world, basePos, 7, 9, 0, redPetals);
		addBlock(world, basePos, 8, 9, 0, rosePetals);
		addBlock(world, basePos, 1, 10, 0, rosePetals);
		addBlock(world, basePos, 2, 10, 0, rosePetals);
		addBlock(world, basePos, 3, 10, 0, redPetals);
		addBlock(world, basePos, 4, 10, 0, flowerCore);
		addBlock(world, basePos, 5, 10, 0, flowerCore);
		addBlock(world, basePos, 6, 10, 0, flowerCore);
		addBlock(world, basePos, 7, 10, 0, redPetals);
		addBlock(world, basePos, 8, 10, 0, rosePetals);
		addBlock(world, basePos, 0, 11, 0, rosePetals);
		addBlock(world, basePos, 1, 11, 0, rosePetals);
		addBlock(world, basePos, 2, 11, 0, redPetals);
		addBlock(world, basePos, 3, 11, 0, redPetals);
		addBlock(world, basePos, 4, 11, 0, redPetals);
		addBlock(world, basePos, 5, 11, 0, redPetals);
		addBlock(world, basePos, 6, 11, 0, redPetals);
		addBlock(world, basePos, 7, 11, 0, redPetals);
		addBlock(world, basePos, 8, 11, 0, rosePetals);
		addBlock(world, basePos, 9, 11, 0, rosePetals);
		addBlock(world, basePos, 0, 12, 0, rosePetals);
		addBlock(world, basePos, 1, 12, 0, redPetals);
		addBlock(world, basePos, 2, 12, 0, redPetals);
		addBlock(world, basePos, 3, 12, 0, redPetals);
		addBlock(world, basePos, 4, 12, 0, redPetals);
		addBlock(world, basePos, 5, 12, 0, redPetals);
		addBlock(world, basePos, 6, 12, 0, redPetals);
		addBlock(world, basePos, 7, 12, 0, redPetals);
		addBlock(world, basePos, 8, 12, 0, redPetals);
		addBlock(world, basePos, 9, 12, 0, rosePetals);
		addBlock(world, basePos, 10, 12, 0, rosePetals);
		addBlock(world, basePos, 0, 13, 0, rosePetals);
		addBlock(world, basePos, 1, 13, 0, redPetals);
		addBlock(world, basePos, 2, 13, 0, redPetals);
		addBlock(world, basePos, 3, 13, 0, redPetals);
		addBlock(world, basePos, 4, 13, 0, redPetals);
		addBlock(world, basePos, 5, 13, 0, redPetals);
		addBlock(world, basePos, 6, 13, 0, redPetals);
		addBlock(world, basePos, 7, 13, 0, redPetals);
		addBlock(world, basePos, 8, 13, 0, redPetals);
		addBlock(world, basePos, 9, 13, 0, redPetals);
		addBlock(world, basePos, 10, 13, 0, rosePetals);
		addBlock(world, basePos, 0, 14, 0, rosePetals);
		addBlock(world, basePos, 1, 14, 0, redPetals);
		addBlock(world, basePos, 2, 14, 0, redPetals);
		addBlock(world, basePos, 3, 14, 0, redPetals);
		addBlock(world, basePos, 4, 14, 0, rosePetals);
		addBlock(world, basePos, 5, 14, 0, rosePetals);
		addBlock(world, basePos, 6, 14, 0, rosePetals);
		addBlock(world, basePos, 7, 14, 0, redPetals);
		addBlock(world, basePos, 8, 14, 0, redPetals);
		addBlock(world, basePos, 9, 14, 0, redPetals);
		addBlock(world, basePos, 10, 14, 0, rosePetals);
		addBlock(world, basePos, 0, 15, 0, rosePetals);
		addBlock(world, basePos, 1, 15, 0, redPetals);
		addBlock(world, basePos, 2, 15, 0, redPetals);
		addBlock(world, basePos, 3, 15, 0, rosePetals);
		addBlock(world, basePos, 4, 15, 0, rosePetals);
		addBlock(world, basePos, 6, 15, 0, rosePetals);
		addBlock(world, basePos, 7, 15, 0, rosePetals);
		addBlock(world, basePos, 8, 15, 0, redPetals);
		addBlock(world, basePos, 9, 15, 0, redPetals);
		addBlock(world, basePos, 10, 15, 0, rosePetals);
		addBlock(world, basePos, 0, 16, 0, rosePetals);
		addBlock(world, basePos, 1, 16, 0, rosePetals);
		addBlock(world, basePos, 2, 16, 0, rosePetals);
		addBlock(world, basePos, 3, 16, 0, rosePetals);
		addBlock(world, basePos, 7, 16, 0, rosePetals);
		addBlock(world, basePos, 8, 16, 0, rosePetals);
		addBlock(world, basePos, 9, 16, 0, rosePetals);
		addBlock(world, basePos, 10, 16, 0, rosePetals);
	}
}
