package net.tslat.aoa3.structure.iromine;

import net.minecraft.block.state.IBlockState;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
import net.tslat.aoa3.common.registration.BlockRegister;
import net.tslat.aoa3.structure.AoAStructure;

import java.util.Random;

public class ChargingPads extends AoAStructure { //StructureSize: 17x10x17
	private static final IBlockState mechbotAltar = BlockRegister.MECHBOT_ALTAR.getDefaultState();
	private static final IBlockState stripedBrick = BlockRegister.IRO_STRIPED_BRICKS.getDefaultState();
	private static final IBlockState dottedBrick = BlockRegister.IRO_DOTTED_BRICKS.getDefaultState();
	private static final IBlockState iropole = BlockRegister.IROPOLE.getDefaultState();

	public ChargingPads() {
		super("ChargingPads");
	}

	@Override
	protected boolean replacesBlocks() {
		return true;
	}

	@Override
	protected void build(World world, Random rand, BlockPos basePos) {
		addBlock(world, basePos, 5, 0, 8, stripedBrick);
		addBlock(world, basePos, 6, 0, 8, stripedBrick);
		addBlock(world, basePos, 7, 0, 7, stripedBrick);
		addBlock(world, basePos, 7, 0, 8, stripedBrick);
		addBlock(world, basePos, 7, 0, 9, stripedBrick);
		addBlock(world, basePos, 8, 0, 5, stripedBrick);
		addBlock(world, basePos, 8, 0, 6, stripedBrick);
		addBlock(world, basePos, 8, 0, 7, stripedBrick);
		addBlock(world, basePos, 8, 0, 8, stripedBrick);
		addBlock(world, basePos, 8, 0, 9, stripedBrick);
		addBlock(world, basePos, 8, 0, 10, stripedBrick);
		addBlock(world, basePos, 8, 0, 11, stripedBrick);
		addBlock(world, basePos, 9, 0, 7, stripedBrick);
		addBlock(world, basePos, 9, 0, 8, stripedBrick);
		addBlock(world, basePos, 9, 0, 9, stripedBrick);
		addBlock(world, basePos, 10, 0, 8, stripedBrick);
		addBlock(world, basePos, 11, 0, 8, stripedBrick);
		addBlock(world, basePos, 2, 1, 8, stripedBrick);
		addBlock(world, basePos, 3, 1, 8, stripedBrick);
		addBlock(world, basePos, 4, 1, 8, stripedBrick);
		addBlock(world, basePos, 5, 1, 8, stripedBrick);
		addBlock(world, basePos, 7, 1, 7, iropole);
		addBlock(world, basePos, 7, 1, 9, iropole);
		addBlock(world, basePos, 8, 1, 2, stripedBrick);
		addBlock(world, basePos, 8, 1, 3, stripedBrick);
		addBlock(world, basePos, 8, 1, 4, stripedBrick);
		addBlock(world, basePos, 8, 1, 5, stripedBrick);
		addBlock(world, basePos, 8, 1, 11, stripedBrick);
		addBlock(world, basePos, 8, 1, 12, stripedBrick);
		addBlock(world, basePos, 8, 1, 13, stripedBrick);
		addBlock(world, basePos, 8, 1, 14, stripedBrick);
		addBlock(world, basePos, 9, 1, 7, iropole);
		addBlock(world, basePos, 9, 1, 9, iropole);
		addBlock(world, basePos, 11, 1, 8, stripedBrick);
		addBlock(world, basePos, 12, 1, 8, stripedBrick);
		addBlock(world, basePos, 13, 1, 8, stripedBrick);
		addBlock(world, basePos, 14, 1, 8, stripedBrick);
		addBlock(world, basePos, 2, 2, 8, stripedBrick);
		addBlock(world, basePos, 7, 2, 7, iropole);
		addBlock(world, basePos, 7, 2, 9, iropole);
		addBlock(world, basePos, 8, 2, 2, stripedBrick);
		addBlock(world, basePos, 8, 2, 14, stripedBrick);
		addBlock(world, basePos, 9, 2, 7, iropole);
		addBlock(world, basePos, 9, 2, 9, iropole);
		addBlock(world, basePos, 14, 2, 8, stripedBrick);
		addBlock(world, basePos, 0, 3, 6, stripedBrick);
		addBlock(world, basePos, 0, 3, 7, stripedBrick);
		addBlock(world, basePos, 0, 3, 8, stripedBrick);
		addBlock(world, basePos, 0, 3, 9, stripedBrick);
		addBlock(world, basePos, 0, 3, 10, stripedBrick);
		addBlock(world, basePos, 1, 3, 6, stripedBrick);
		addBlock(world, basePos, 1, 3, 7, dottedBrick);
		addBlock(world, basePos, 1, 3, 8, dottedBrick);
		addBlock(world, basePos, 1, 3, 9, dottedBrick);
		addBlock(world, basePos, 1, 3, 10, stripedBrick);
		addBlock(world, basePos, 2, 3, 6, stripedBrick);
		addBlock(world, basePos, 2, 3, 7, dottedBrick);
		addBlock(world, basePos, 2, 3, 8, dottedBrick);
		addBlock(world, basePos, 2, 3, 9, dottedBrick);
		addBlock(world, basePos, 2, 3, 10, stripedBrick);
		addBlock(world, basePos, 3, 3, 6, stripedBrick);
		addBlock(world, basePos, 3, 3, 7, dottedBrick);
		addBlock(world, basePos, 3, 3, 8, dottedBrick);
		addBlock(world, basePos, 3, 3, 9, dottedBrick);
		addBlock(world, basePos, 3, 3, 10, stripedBrick);
		addBlock(world, basePos, 4, 3, 6, stripedBrick);
		addBlock(world, basePos, 4, 3, 7, stripedBrick);
		addBlock(world, basePos, 4, 3, 8, stripedBrick);
		addBlock(world, basePos, 4, 3, 9, stripedBrick);
		addBlock(world, basePos, 4, 3, 10, stripedBrick);
		addBlock(world, basePos, 5, 3, 8, stripedBrick);
		addBlock(world, basePos, 6, 3, 0, stripedBrick);
		addBlock(world, basePos, 6, 3, 1, stripedBrick);
		addBlock(world, basePos, 6, 3, 2, stripedBrick);
		addBlock(world, basePos, 6, 3, 3, stripedBrick);
		addBlock(world, basePos, 6, 3, 4, stripedBrick);
		addBlock(world, basePos, 6, 3, 12, stripedBrick);
		addBlock(world, basePos, 6, 3, 13, stripedBrick);
		addBlock(world, basePos, 6, 3, 14, stripedBrick);
		addBlock(world, basePos, 6, 3, 15, stripedBrick);
		addBlock(world, basePos, 6, 3, 16, stripedBrick);
		addBlock(world, basePos, 7, 3, 0, stripedBrick);
		addBlock(world, basePos, 7, 3, 1, dottedBrick);
		addBlock(world, basePos, 7, 3, 2, dottedBrick);
		addBlock(world, basePos, 7, 3, 3, dottedBrick);
		addBlock(world, basePos, 7, 3, 4, stripedBrick);
		addBlock(world, basePos, 7, 3, 7, iropole);
		addBlock(world, basePos, 7, 3, 9, iropole);
		addBlock(world, basePos, 7, 3, 12, stripedBrick);
		addBlock(world, basePos, 7, 3, 13, dottedBrick);
		addBlock(world, basePos, 7, 3, 14, dottedBrick);
		addBlock(world, basePos, 7, 3, 15, dottedBrick);
		addBlock(world, basePos, 7, 3, 16, stripedBrick);
		addBlock(world, basePos, 8, 3, 0, stripedBrick);
		addBlock(world, basePos, 8, 3, 1, dottedBrick);
		addBlock(world, basePos, 8, 3, 2, dottedBrick);
		addBlock(world, basePos, 8, 3, 3, dottedBrick);
		addBlock(world, basePos, 8, 3, 4, stripedBrick);
		addBlock(world, basePos, 8, 3, 5, stripedBrick);
		addBlock(world, basePos, 8, 3, 11, stripedBrick);
		addBlock(world, basePos, 8, 3, 12, stripedBrick);
		addBlock(world, basePos, 8, 3, 13, dottedBrick);
		addBlock(world, basePos, 8, 3, 14, dottedBrick);
		addBlock(world, basePos, 8, 3, 15, dottedBrick);
		addBlock(world, basePos, 8, 3, 16, stripedBrick);
		addBlock(world, basePos, 9, 3, 0, stripedBrick);
		addBlock(world, basePos, 9, 3, 1, dottedBrick);
		addBlock(world, basePos, 9, 3, 2, dottedBrick);
		addBlock(world, basePos, 9, 3, 3, dottedBrick);
		addBlock(world, basePos, 9, 3, 4, stripedBrick);
		addBlock(world, basePos, 9, 3, 7, iropole);
		addBlock(world, basePos, 9, 3, 9, iropole);
		addBlock(world, basePos, 9, 3, 12, stripedBrick);
		addBlock(world, basePos, 9, 3, 13, dottedBrick);
		addBlock(world, basePos, 9, 3, 14, dottedBrick);
		addBlock(world, basePos, 9, 3, 15, dottedBrick);
		addBlock(world, basePos, 9, 3, 16, stripedBrick);
		addBlock(world, basePos, 10, 3, 0, stripedBrick);
		addBlock(world, basePos, 10, 3, 1, stripedBrick);
		addBlock(world, basePos, 10, 3, 2, stripedBrick);
		addBlock(world, basePos, 10, 3, 3, stripedBrick);
		addBlock(world, basePos, 10, 3, 4, stripedBrick);
		addBlock(world, basePos, 10, 3, 12, stripedBrick);
		addBlock(world, basePos, 10, 3, 13, stripedBrick);
		addBlock(world, basePos, 10, 3, 14, stripedBrick);
		addBlock(world, basePos, 10, 3, 15, stripedBrick);
		addBlock(world, basePos, 10, 3, 16, stripedBrick);
		addBlock(world, basePos, 11, 3, 8, stripedBrick);
		addBlock(world, basePos, 12, 3, 6, stripedBrick);
		addBlock(world, basePos, 12, 3, 7, stripedBrick);
		addBlock(world, basePos, 12, 3, 8, stripedBrick);
		addBlock(world, basePos, 12, 3, 9, stripedBrick);
		addBlock(world, basePos, 12, 3, 10, stripedBrick);
		addBlock(world, basePos, 13, 3, 6, stripedBrick);
		addBlock(world, basePos, 13, 3, 7, dottedBrick);
		addBlock(world, basePos, 13, 3, 8, dottedBrick);
		addBlock(world, basePos, 13, 3, 9, dottedBrick);
		addBlock(world, basePos, 13, 3, 10, stripedBrick);
		addBlock(world, basePos, 14, 3, 6, stripedBrick);
		addBlock(world, basePos, 14, 3, 7, dottedBrick);
		addBlock(world, basePos, 14, 3, 8, dottedBrick);
		addBlock(world, basePos, 14, 3, 9, dottedBrick);
		addBlock(world, basePos, 14, 3, 10, stripedBrick);
		addBlock(world, basePos, 15, 3, 6, stripedBrick);
		addBlock(world, basePos, 15, 3, 7, dottedBrick);
		addBlock(world, basePos, 15, 3, 8, dottedBrick);
		addBlock(world, basePos, 15, 3, 9, dottedBrick);
		addBlock(world, basePos, 15, 3, 10, stripedBrick);
		addBlock(world, basePos, 16, 3, 6, stripedBrick);
		addBlock(world, basePos, 16, 3, 7, stripedBrick);
		addBlock(world, basePos, 16, 3, 8, stripedBrick);
		addBlock(world, basePos, 16, 3, 9, stripedBrick);
		addBlock(world, basePos, 16, 3, 10, stripedBrick);
		addBlock(world, basePos, 2, 4, 8, mechbotAltar);
		addBlock(world, basePos, 5, 4, 8, stripedBrick);
		addBlock(world, basePos, 7, 4, 7, iropole);
		addBlock(world, basePos, 7, 4, 9, iropole);
		addBlock(world, basePos, 8, 4, 2, mechbotAltar);
		addBlock(world, basePos, 8, 4, 5, stripedBrick);
		addBlock(world, basePos, 8, 4, 11, stripedBrick);
		addBlock(world, basePos, 8, 4, 14, mechbotAltar);
		addBlock(world, basePos, 9, 4, 7, iropole);
		addBlock(world, basePos, 9, 4, 9, iropole);
		addBlock(world, basePos, 11, 4, 8, stripedBrick);
		addBlock(world, basePos, 14, 4, 8, mechbotAltar);
		addBlock(world, basePos, 5, 5, 8, stripedBrick);
		addBlock(world, basePos, 6, 5, 8, stripedBrick);
		addBlock(world, basePos, 7, 5, 7, stripedBrick);
		addBlock(world, basePos, 7, 5, 8, stripedBrick);
		addBlock(world, basePos, 7, 5, 9, stripedBrick);
		addBlock(world, basePos, 8, 5, 5, stripedBrick);
		addBlock(world, basePos, 8, 5, 6, stripedBrick);
		addBlock(world, basePos, 8, 5, 7, stripedBrick);
		addBlock(world, basePos, 8, 5, 9, stripedBrick);
		addBlock(world, basePos, 8, 5, 10, stripedBrick);
		addBlock(world, basePos, 8, 5, 11, stripedBrick);
		addBlock(world, basePos, 9, 5, 7, stripedBrick);
		addBlock(world, basePos, 9, 5, 8, stripedBrick);
		addBlock(world, basePos, 9, 5, 9, stripedBrick);
		addBlock(world, basePos, 10, 5, 8, stripedBrick);
		addBlock(world, basePos, 11, 5, 8, stripedBrick);
		addBlock(world, basePos, 7, 6, 7, iropole);
		addBlock(world, basePos, 7, 6, 9, iropole);
		addBlock(world, basePos, 9, 6, 7, iropole);
		addBlock(world, basePos, 9, 6, 9, iropole);
		addBlock(world, basePos, 7, 7, 7, iropole);
		addBlock(world, basePos, 7, 7, 9, iropole);
		addBlock(world, basePos, 9, 7, 7, iropole);
		addBlock(world, basePos, 9, 7, 9, iropole);
		addBlock(world, basePos, 7, 8, 7, iropole);
		addBlock(world, basePos, 7, 8, 9, iropole);
		addBlock(world, basePos, 9, 8, 7, iropole);
		addBlock(world, basePos, 9, 8, 9, iropole);
		addBlock(world, basePos, 7, 9, 7, stripedBrick);
		addBlock(world, basePos, 7, 9, 8, stripedBrick);
		addBlock(world, basePos, 7, 9, 9, stripedBrick);
		addBlock(world, basePos, 8, 9, 7, stripedBrick);
		addBlock(world, basePos, 8, 9, 8, stripedBrick);
		addBlock(world, basePos, 8, 9, 9, stripedBrick);
		addBlock(world, basePos, 9, 9, 7, stripedBrick);
		addBlock(world, basePos, 9, 9, 8, stripedBrick);
		addBlock(world, basePos, 9, 9, 9, stripedBrick);
	}
}
