package net.tslat.aoa3.structure.greckon;

import net.minecraft.block.state.IBlockState;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
import net.tslat.aoa3.common.registration.BlockRegister;
import net.tslat.aoa3.structure.AoAStructure;

import java.util.Random;

public class FacelessTree extends AoAStructure { //StructureSize: 9x13x9
	private static final IBlockState hauntedLeaves = BlockRegister.leavesHaunted.getDefaultState();
	private static final IBlockState hauntedLog = BlockRegister.logHaunted.getDefaultState();
	private static final IBlockState facelessFloaterSpawner = BlockRegister.spawnerFacelessFloater.getDefaultState();

	public FacelessTree() {
		super("FacelessTree");
	}

	@Override
	protected boolean replacesBlocks() {
		return true;
	}

	@Override
	protected void build(World world, Random rand, BlockPos basePos) {
		addBlock(world, basePos, 3, 0, 3, hauntedLog);
		addBlock(world, basePos, 3, 0, 4, hauntedLog);
		addBlock(world, basePos, 3, 0, 5, hauntedLog);
		addBlock(world, basePos, 4, 0, 3, hauntedLog);
		addBlock(world, basePos, 4, 0, 4, hauntedLog);
		addBlock(world, basePos, 4, 0, 5, hauntedLog);
		addBlock(world, basePos, 5, 0, 3, hauntedLog);
		addBlock(world, basePos, 5, 0, 4, hauntedLog);
		addBlock(world, basePos, 5, 0, 5, hauntedLog);
		addBlock(world, basePos, 3, 1, 3, hauntedLog);
		addBlock(world, basePos, 3, 1, 4, facelessFloaterSpawner);
		addBlock(world, basePos, 3, 1, 5, hauntedLog);
		addBlock(world, basePos, 4, 1, 3, facelessFloaterSpawner);
		addBlock(world, basePos, 4, 1, 4, hauntedLog);
		addBlock(world, basePos, 4, 1, 5, facelessFloaterSpawner);
		addBlock(world, basePos, 5, 1, 3, hauntedLog);
		addBlock(world, basePos, 5, 1, 4, facelessFloaterSpawner);
		addBlock(world, basePos, 5, 1, 5, hauntedLog);
		addBlock(world, basePos, 3, 2, 3, hauntedLog);
		addBlock(world, basePos, 3, 2, 4, hauntedLog);
		addBlock(world, basePos, 3, 2, 5, hauntedLog);
		addBlock(world, basePos, 4, 2, 3, hauntedLog);
		addBlock(world, basePos, 4, 2, 4, hauntedLog);
		addBlock(world, basePos, 4, 2, 5, hauntedLog);
		addBlock(world, basePos, 5, 2, 3, hauntedLog);
		addBlock(world, basePos, 5, 2, 4, hauntedLog);
		addBlock(world, basePos, 5, 2, 5, hauntedLog);
		addBlock(world, basePos, 3, 3, 3, hauntedLog);
		addBlock(world, basePos, 3, 3, 4, hauntedLog);
		addBlock(world, basePos, 3, 3, 5, hauntedLog);
		addBlock(world, basePos, 4, 3, 3, hauntedLog);
		addBlock(world, basePos, 4, 3, 4, hauntedLog);
		addBlock(world, basePos, 4, 3, 5, hauntedLog);
		addBlock(world, basePos, 5, 3, 3, hauntedLog);
		addBlock(world, basePos, 5, 3, 4, hauntedLog);
		addBlock(world, basePos, 5, 3, 5, hauntedLog);
		addBlock(world, basePos, 2, 4, 3, hauntedLeaves);
		addBlock(world, basePos, 2, 4, 4, hauntedLeaves);
		addBlock(world, basePos, 2, 4, 5, hauntedLeaves);
		addBlock(world, basePos, 3, 4, 2, hauntedLeaves);
		addBlock(world, basePos, 3, 4, 3, hauntedLog);
		addBlock(world, basePos, 3, 4, 4, hauntedLog);
		addBlock(world, basePos, 3, 4, 5, hauntedLog);
		addBlock(world, basePos, 3, 4, 6, hauntedLeaves);
		addBlock(world, basePos, 4, 4, 2, hauntedLeaves);
		addBlock(world, basePos, 4, 4, 3, hauntedLog);
		addBlock(world, basePos, 4, 4, 4, hauntedLog);
		addBlock(world, basePos, 4, 4, 5, hauntedLog);
		addBlock(world, basePos, 4, 4, 6, hauntedLeaves);
		addBlock(world, basePos, 5, 4, 3, hauntedLog);
		addBlock(world, basePos, 5, 4, 4, hauntedLog);
		addBlock(world, basePos, 5, 4, 5, hauntedLog);
		addBlock(world, basePos, 5, 4, 6, hauntedLeaves);
		addBlock(world, basePos, 6, 4, 2, hauntedLeaves);
		addBlock(world, basePos, 6, 4, 3, hauntedLeaves);
		addBlock(world, basePos, 6, 4, 4, hauntedLeaves);
		addBlock(world, basePos, 6, 4, 5, hauntedLeaves);
		addBlock(world, basePos, 3, 5, 3, hauntedLog);
		addBlock(world, basePos, 3, 5, 4, hauntedLog);
		addBlock(world, basePos, 3, 5, 5, hauntedLog);
		addBlock(world, basePos, 4, 5, 3, hauntedLog);
		addBlock(world, basePos, 4, 5, 4, hauntedLog);
		addBlock(world, basePos, 4, 5, 5, hauntedLog);
		addBlock(world, basePos, 5, 5, 3, hauntedLog);
		addBlock(world, basePos, 5, 5, 4, hauntedLog);
		addBlock(world, basePos, 5, 5, 5, hauntedLog);
		addBlock(world, basePos, 3, 6, 3, hauntedLog);
		addBlock(world, basePos, 3, 6, 4, hauntedLog);
		addBlock(world, basePos, 3, 6, 5, hauntedLog);
		addBlock(world, basePos, 4, 6, 3, hauntedLog);
		addBlock(world, basePos, 4, 6, 4, hauntedLog);
		addBlock(world, basePos, 4, 6, 5, hauntedLog);
		addBlock(world, basePos, 5, 6, 3, hauntedLog);
		addBlock(world, basePos, 5, 6, 4, hauntedLog);
		addBlock(world, basePos, 5, 6, 5, hauntedLog);
		addBlock(world, basePos, 2, 7, 3, hauntedLeaves);
		addBlock(world, basePos, 2, 7, 4, hauntedLeaves);
		addBlock(world, basePos, 2, 7, 5, hauntedLeaves);
		addBlock(world, basePos, 3, 7, 2, hauntedLeaves);
		addBlock(world, basePos, 3, 7, 3, hauntedLog);
		addBlock(world, basePos, 3, 7, 4, hauntedLog);
		addBlock(world, basePos, 3, 7, 5, hauntedLog);
		addBlock(world, basePos, 3, 7, 6, hauntedLeaves);
		addBlock(world, basePos, 4, 7, 2, hauntedLeaves);
		addBlock(world, basePos, 4, 7, 3, hauntedLog);
		addBlock(world, basePos, 4, 7, 4, hauntedLog);
		addBlock(world, basePos, 4, 7, 5, hauntedLog);
		addBlock(world, basePos, 4, 7, 6, hauntedLeaves);
		addBlock(world, basePos, 5, 7, 2, hauntedLeaves);
		addBlock(world, basePos, 5, 7, 3, hauntedLog);
		addBlock(world, basePos, 5, 7, 4, hauntedLog);
		addBlock(world, basePos, 5, 7, 5, hauntedLog);
		addBlock(world, basePos, 5, 7, 6, hauntedLeaves);
		addBlock(world, basePos, 6, 7, 3, hauntedLeaves);
		addBlock(world, basePos, 6, 7, 4, hauntedLeaves);
		addBlock(world, basePos, 6, 7, 5, hauntedLeaves);
		addBlock(world, basePos, 0, 8, 2, hauntedLeaves);
		addBlock(world, basePos, 0, 8, 3, hauntedLeaves);
		addBlock(world, basePos, 0, 8, 4, hauntedLeaves);
		addBlock(world, basePos, 0, 8, 5, hauntedLeaves);
		addBlock(world, basePos, 0, 8, 6, hauntedLeaves);
		addBlock(world, basePos, 1, 8, 1, hauntedLeaves);
		addBlock(world, basePos, 1, 8, 2, hauntedLeaves);
		addBlock(world, basePos, 1, 8, 3, hauntedLeaves);
		addBlock(world, basePos, 1, 8, 4, hauntedLeaves);
		addBlock(world, basePos, 1, 8, 5, hauntedLeaves);
		addBlock(world, basePos, 1, 8, 6, hauntedLeaves);
		addBlock(world, basePos, 1, 8, 7, hauntedLeaves);
		addBlock(world, basePos, 2, 8, 0, hauntedLeaves);
		addBlock(world, basePos, 2, 8, 1, hauntedLeaves);
		addBlock(world, basePos, 2, 8, 2, hauntedLeaves);
		addBlock(world, basePos, 2, 8, 3, hauntedLeaves);
		addBlock(world, basePos, 2, 8, 4, hauntedLeaves);
		addBlock(world, basePos, 2, 8, 5, hauntedLeaves);
		addBlock(world, basePos, 2, 8, 6, hauntedLeaves);
		addBlock(world, basePos, 2, 8, 7, hauntedLeaves);
		addBlock(world, basePos, 2, 8, 8, hauntedLeaves);
		addBlock(world, basePos, 3, 8, 0, hauntedLeaves);
		addBlock(world, basePos, 3, 8, 1, hauntedLeaves);
		addBlock(world, basePos, 3, 8, 2, hauntedLeaves);
		addBlock(world, basePos, 3, 8, 3, hauntedLeaves);
		addBlock(world, basePos, 3, 8, 4, hauntedLeaves);
		addBlock(world, basePos, 3, 8, 5, hauntedLeaves);
		addBlock(world, basePos, 3, 8, 6, hauntedLeaves);
		addBlock(world, basePos, 3, 8, 7, hauntedLeaves);
		addBlock(world, basePos, 3, 8, 8, hauntedLeaves);
		addBlock(world, basePos, 4, 8, 0, hauntedLeaves);
		addBlock(world, basePos, 4, 8, 1, hauntedLeaves);
		addBlock(world, basePos, 4, 8, 2, hauntedLeaves);
		addBlock(world, basePos, 4, 8, 3, hauntedLeaves);
		addBlock(world, basePos, 4, 8, 4, hauntedLeaves);
		addBlock(world, basePos, 4, 8, 5, hauntedLeaves);
		addBlock(world, basePos, 4, 8, 6, hauntedLeaves);
		addBlock(world, basePos, 4, 8, 7, hauntedLeaves);
		addBlock(world, basePos, 4, 8, 8, hauntedLeaves);
		addBlock(world, basePos, 5, 8, 0, hauntedLeaves);
		addBlock(world, basePos, 5, 8, 1, hauntedLeaves);
		addBlock(world, basePos, 5, 8, 2, hauntedLeaves);
		addBlock(world, basePos, 5, 8, 3, hauntedLeaves);
		addBlock(world, basePos, 5, 8, 4, hauntedLeaves);
		addBlock(world, basePos, 5, 8, 5, hauntedLeaves);
		addBlock(world, basePos, 5, 8, 6, hauntedLeaves);
		addBlock(world, basePos, 5, 8, 7, hauntedLeaves);
		addBlock(world, basePos, 5, 8, 8, hauntedLeaves);
		addBlock(world, basePos, 6, 8, 0, hauntedLeaves);
		addBlock(world, basePos, 6, 8, 1, hauntedLeaves);
		addBlock(world, basePos, 6, 8, 2, hauntedLeaves);
		addBlock(world, basePos, 6, 8, 3, hauntedLeaves);
		addBlock(world, basePos, 6, 8, 4, hauntedLeaves);
		addBlock(world, basePos, 6, 8, 5, hauntedLeaves);
		addBlock(world, basePos, 6, 8, 6, hauntedLeaves);
		addBlock(world, basePos, 6, 8, 7, hauntedLeaves);
		addBlock(world, basePos, 6, 8, 8, hauntedLeaves);
		addBlock(world, basePos, 7, 8, 1, hauntedLeaves);
		addBlock(world, basePos, 7, 8, 2, hauntedLeaves);
		addBlock(world, basePos, 7, 8, 3, hauntedLeaves);
		addBlock(world, basePos, 7, 8, 4, hauntedLeaves);
		addBlock(world, basePos, 7, 8, 5, hauntedLeaves);
		addBlock(world, basePos, 7, 8, 6, hauntedLeaves);
		addBlock(world, basePos, 7, 8, 7, hauntedLeaves);
		addBlock(world, basePos, 8, 8, 2, hauntedLeaves);
		addBlock(world, basePos, 8, 8, 3, hauntedLeaves);
		addBlock(world, basePos, 8, 8, 4, hauntedLeaves);
		addBlock(world, basePos, 8, 8, 5, hauntedLeaves);
		addBlock(world, basePos, 8, 8, 6, hauntedLeaves);
		addBlock(world, basePos, 1, 9, 3, hauntedLeaves);
		addBlock(world, basePos, 1, 9, 4, hauntedLeaves);
		addBlock(world, basePos, 1, 9, 5, hauntedLeaves);
		addBlock(world, basePos, 2, 9, 2, hauntedLeaves);
		addBlock(world, basePos, 2, 9, 3, hauntedLeaves);
		addBlock(world, basePos, 2, 9, 4, hauntedLeaves);
		addBlock(world, basePos, 2, 9, 5, hauntedLeaves);
		addBlock(world, basePos, 2, 9, 6, hauntedLeaves);
		addBlock(world, basePos, 3, 9, 1, hauntedLeaves);
		addBlock(world, basePos, 3, 9, 2, hauntedLeaves);
		addBlock(world, basePos, 3, 9, 3, hauntedLeaves);
		addBlock(world, basePos, 3, 9, 4, hauntedLeaves);
		addBlock(world, basePos, 3, 9, 5, hauntedLeaves);
		addBlock(world, basePos, 3, 9, 6, hauntedLeaves);
		addBlock(world, basePos, 3, 9, 7, hauntedLeaves);
		addBlock(world, basePos, 4, 9, 1, hauntedLeaves);
		addBlock(world, basePos, 4, 9, 2, hauntedLeaves);
		addBlock(world, basePos, 4, 9, 3, hauntedLeaves);
		addBlock(world, basePos, 4, 9, 4, hauntedLeaves);
		addBlock(world, basePos, 4, 9, 5, hauntedLeaves);
		addBlock(world, basePos, 4, 9, 6, hauntedLeaves);
		addBlock(world, basePos, 4, 9, 7, hauntedLeaves);
		addBlock(world, basePos, 5, 9, 1, hauntedLeaves);
		addBlock(world, basePos, 5, 9, 2, hauntedLeaves);
		addBlock(world, basePos, 5, 9, 3, hauntedLeaves);
		addBlock(world, basePos, 5, 9, 4, hauntedLeaves);
		addBlock(world, basePos, 5, 9, 5, hauntedLeaves);
		addBlock(world, basePos, 5, 9, 6, hauntedLeaves);
		addBlock(world, basePos, 5, 9, 7, hauntedLeaves);
		addBlock(world, basePos, 6, 9, 2, hauntedLeaves);
		addBlock(world, basePos, 6, 9, 3, hauntedLeaves);
		addBlock(world, basePos, 6, 9, 4, hauntedLeaves);
		addBlock(world, basePos, 6, 9, 5, hauntedLeaves);
		addBlock(world, basePos, 6, 9, 6, hauntedLeaves);
		addBlock(world, basePos, 7, 9, 3, hauntedLeaves);
		addBlock(world, basePos, 7, 9, 4, hauntedLeaves);
		addBlock(world, basePos, 7, 9, 5, hauntedLeaves);
		addBlock(world, basePos, 2, 10, 3, hauntedLeaves);
		addBlock(world, basePos, 2, 10, 4, hauntedLeaves);
		addBlock(world, basePos, 2, 10, 5, hauntedLeaves);
		addBlock(world, basePos, 3, 10, 2, hauntedLeaves);
		addBlock(world, basePos, 3, 10, 3, hauntedLeaves);
		addBlock(world, basePos, 3, 10, 4, hauntedLeaves);
		addBlock(world, basePos, 3, 10, 5, hauntedLeaves);
		addBlock(world, basePos, 3, 10, 6, hauntedLeaves);
		addBlock(world, basePos, 4, 10, 2, hauntedLeaves);
		addBlock(world, basePos, 4, 10, 3, hauntedLeaves);
		addBlock(world, basePos, 4, 10, 4, hauntedLeaves);
		addBlock(world, basePos, 4, 10, 5, hauntedLeaves);
		addBlock(world, basePos, 4, 10, 6, hauntedLeaves);
		addBlock(world, basePos, 5, 10, 2, hauntedLeaves);
		addBlock(world, basePos, 5, 10, 3, hauntedLeaves);
		addBlock(world, basePos, 5, 10, 4, hauntedLeaves);
		addBlock(world, basePos, 5, 10, 5, hauntedLeaves);
		addBlock(world, basePos, 5, 10, 6, hauntedLeaves);
		addBlock(world, basePos, 6, 10, 3, hauntedLeaves);
		addBlock(world, basePos, 6, 10, 4, hauntedLeaves);
		addBlock(world, basePos, 6, 10, 5, hauntedLeaves);
		addBlock(world, basePos, 3, 11, 3, hauntedLeaves);
		addBlock(world, basePos, 3, 11, 4, hauntedLeaves);
		addBlock(world, basePos, 3, 11, 5, hauntedLeaves);
		addBlock(world, basePos, 4, 11, 3, hauntedLeaves);
		addBlock(world, basePos, 4, 11, 4, hauntedLeaves);
		addBlock(world, basePos, 4, 11, 5, hauntedLeaves);
		addBlock(world, basePos, 5, 11, 3, hauntedLeaves);
		addBlock(world, basePos, 5, 11, 4, hauntedLeaves);
		addBlock(world, basePos, 5, 11, 5, hauntedLeaves);
		addBlock(world, basePos, 4, 12, 4, hauntedLeaves);
	}
}
