package net.tslat.aoa3.worldgen.structures.lunalus;

import net.minecraft.block.BlockState;
import net.minecraft.block.Blocks;
import net.minecraft.block.FlowingFluidBlock;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.IWorld;
import net.tslat.aoa3.block.functional.light.LampBlock;
import net.tslat.aoa3.common.registration.AoABlocks;
import net.tslat.aoa3.common.registration.AoAEntities;
import net.tslat.aoa3.entity.npc.ambient.ZalCitizenEntity;
import net.tslat.aoa3.worldgen.structures.AoAStructure;

import java.util.Random;

public class LunarFountain extends AoAStructure { //StructureSize: 19x13x19
	private static final BlockState lunarLamp = AoABlocks.LUNAR_LAMP.get().getDefaultState().with(LampBlock.TOGGLEABLE, false);
	private static final BlockState lunarBricks = AoABlocks.LUNAR_BRICKS.get().getDefaultState();
	private static final BlockState stainedGlass = Blocks.WHITE_STAINED_GLASS.getDefaultState();
	private static final BlockState water = Blocks.WATER.getDefaultState().with(FlowingFluidBlock.LEVEL, 15);

	public LunarFountain() {
		super("LunarFountain");
	}

	@Override
	protected boolean replacesBlocks() {
		return true;
	}

	@Override
	protected void build(IWorld world, Random rand, BlockPos basePos) {
		addBlock(world, basePos, 3, 0, 5, lunarBricks);
		addBlock(world, basePos, 3, 0, 6, lunarBricks);
		addBlock(world, basePos, 3, 0, 7, lunarBricks);
		addBlock(world, basePos, 3, 0, 8, lunarBricks);
		addBlock(world, basePos, 3, 0, 9, lunarBricks);
		addBlock(world, basePos, 3, 0, 10, lunarBricks);
		addBlock(world, basePos, 3, 0, 11, lunarBricks);
		addBlock(world, basePos, 3, 0, 12, lunarBricks);
		addBlock(world, basePos, 3, 0, 13, lunarBricks);
		addBlock(world, basePos, 4, 0, 4, lunarBricks);
		addBlock(world, basePos, 4, 0, 5, lunarBricks);
		addBlock(world, basePos, 4, 0, 6, stainedGlass);
		addBlock(world, basePos, 4, 0, 7, stainedGlass);
		addBlock(world, basePos, 4, 0, 8, stainedGlass);
		addBlock(world, basePos, 4, 0, 9, stainedGlass);
		addBlock(world, basePos, 4, 0, 10, stainedGlass);
		addBlock(world, basePos, 4, 0, 11, stainedGlass);
		addBlock(world, basePos, 4, 0, 12, stainedGlass);
		addBlock(world, basePos, 4, 0, 13, lunarBricks);
		addBlock(world, basePos, 4, 0, 14, lunarBricks);
		addBlock(world, basePos, 5, 0, 3, lunarBricks);
		addBlock(world, basePos, 5, 0, 4, lunarBricks);
		addBlock(world, basePos, 5, 0, 5, stainedGlass);
		addBlock(world, basePos, 5, 0, 6, stainedGlass);
		addBlock(world, basePos, 5, 0, 7, lunarBricks);
		addBlock(world, basePos, 5, 0, 8, lunarBricks);
		addBlock(world, basePos, 5, 0, 9, lunarBricks);
		addBlock(world, basePos, 5, 0, 10, lunarBricks);
		addBlock(world, basePos, 5, 0, 11, lunarBricks);
		addBlock(world, basePos, 5, 0, 12, stainedGlass);
		addBlock(world, basePos, 5, 0, 13, stainedGlass);
		addBlock(world, basePos, 5, 0, 14, lunarBricks);
		addBlock(world, basePos, 5, 0, 15, lunarBricks);
		addBlock(world, basePos, 6, 0, 3, lunarBricks);
		addBlock(world, basePos, 6, 0, 4, stainedGlass);
		addBlock(world, basePos, 6, 0, 5, stainedGlass);
		addBlock(world, basePos, 6, 0, 6, lunarBricks);
		addBlock(world, basePos, 6, 0, 7, lunarBricks);
		addBlock(world, basePos, 6, 0, 8, stainedGlass);
		addBlock(world, basePos, 6, 0, 9, stainedGlass);
		addBlock(world, basePos, 6, 0, 10, stainedGlass);
		addBlock(world, basePos, 6, 0, 11, lunarBricks);
		addBlock(world, basePos, 6, 0, 12, lunarBricks);
		addBlock(world, basePos, 6, 0, 13, stainedGlass);
		addBlock(world, basePos, 6, 0, 14, stainedGlass);
		addBlock(world, basePos, 6, 0, 15, lunarBricks);
		addBlock(world, basePos, 7, 0, 3, lunarBricks);
		addBlock(world, basePos, 7, 0, 4, stainedGlass);
		addBlock(world, basePos, 7, 0, 5, lunarBricks);
		addBlock(world, basePos, 7, 0, 6, lunarBricks);
		addBlock(world, basePos, 7, 0, 7, stainedGlass);
		addBlock(world, basePos, 7, 0, 8, stainedGlass);
		addBlock(world, basePos, 7, 0, 9, lunarBricks);
		addBlock(world, basePos, 7, 0, 10, stainedGlass);
		addBlock(world, basePos, 7, 0, 11, stainedGlass);
		addBlock(world, basePos, 7, 0, 12, lunarBricks);
		addBlock(world, basePos, 7, 0, 13, lunarBricks);
		addBlock(world, basePos, 7, 0, 14, stainedGlass);
		addBlock(world, basePos, 7, 0, 15, lunarBricks);
		addBlock(world, basePos, 8, 0, 3, lunarBricks);
		addBlock(world, basePos, 8, 0, 4, stainedGlass);
		addBlock(world, basePos, 8, 0, 5, lunarBricks);
		addBlock(world, basePos, 8, 0, 6, stainedGlass);
		addBlock(world, basePos, 8, 0, 7, stainedGlass);
		addBlock(world, basePos, 8, 0, 8, lunarBricks);
		addBlock(world, basePos, 8, 0, 9, lunarBricks);
		addBlock(world, basePos, 8, 0, 10, lunarBricks);
		addBlock(world, basePos, 8, 0, 11, stainedGlass);
		addBlock(world, basePos, 8, 0, 12, stainedGlass);
		addBlock(world, basePos, 8, 0, 13, lunarBricks);
		addBlock(world, basePos, 8, 0, 14, stainedGlass);
		addBlock(world, basePos, 8, 0, 15, lunarBricks);
		addBlock(world, basePos, 9, 0, 3, lunarBricks);
		addBlock(world, basePos, 9, 0, 4, stainedGlass);
		addBlock(world, basePos, 9, 0, 5, lunarBricks);
		addBlock(world, basePos, 9, 0, 6, stainedGlass);
		addBlock(world, basePos, 9, 0, 7, lunarBricks);
		addBlock(world, basePos, 9, 0, 8, lunarBricks);
		addBlock(world, basePos, 9, 0, 9, lunarBricks);
		addBlock(world, basePos, 9, 0, 10, lunarBricks);
		addBlock(world, basePos, 9, 0, 11, lunarBricks);
		addBlock(world, basePos, 9, 0, 12, stainedGlass);
		addBlock(world, basePos, 9, 0, 13, lunarBricks);
		addBlock(world, basePos, 9, 0, 14, stainedGlass);
		addBlock(world, basePos, 9, 0, 15, lunarBricks);
		addBlock(world, basePos, 10, 0, 3, lunarBricks);
		addBlock(world, basePos, 10, 0, 4, stainedGlass);
		addBlock(world, basePos, 10, 0, 5, lunarBricks);
		addBlock(world, basePos, 10, 0, 6, stainedGlass);
		addBlock(world, basePos, 10, 0, 7, stainedGlass);
		addBlock(world, basePos, 10, 0, 8, lunarBricks);
		addBlock(world, basePos, 10, 0, 9, lunarBricks);
		addBlock(world, basePos, 10, 0, 10, lunarBricks);
		addBlock(world, basePos, 10, 0, 11, stainedGlass);
		addBlock(world, basePos, 10, 0, 12, stainedGlass);
		addBlock(world, basePos, 10, 0, 13, lunarBricks);
		addBlock(world, basePos, 10, 0, 14, stainedGlass);
		addBlock(world, basePos, 10, 0, 15, lunarBricks);
		addBlock(world, basePos, 11, 0, 3, lunarBricks);
		addBlock(world, basePos, 11, 0, 4, stainedGlass);
		addBlock(world, basePos, 11, 0, 5, lunarBricks);
		addBlock(world, basePos, 11, 0, 6, lunarBricks);
		addBlock(world, basePos, 11, 0, 7, stainedGlass);
		addBlock(world, basePos, 11, 0, 8, stainedGlass);
		addBlock(world, basePos, 11, 0, 9, lunarBricks);
		addBlock(world, basePos, 11, 0, 10, stainedGlass);
		addBlock(world, basePos, 11, 0, 11, stainedGlass);
		addBlock(world, basePos, 11, 0, 12, lunarBricks);
		addBlock(world, basePos, 11, 0, 13, lunarBricks);
		addBlock(world, basePos, 11, 0, 14, stainedGlass);
		addBlock(world, basePos, 11, 0, 15, lunarBricks);
		addBlock(world, basePos, 12, 0, 3, lunarBricks);
		addBlock(world, basePos, 12, 0, 4, stainedGlass);
		addBlock(world, basePos, 12, 0, 5, stainedGlass);
		addBlock(world, basePos, 12, 0, 6, lunarBricks);
		addBlock(world, basePos, 12, 0, 7, lunarBricks);
		addBlock(world, basePos, 12, 0, 8, stainedGlass);
		addBlock(world, basePos, 12, 0, 9, stainedGlass);
		addBlock(world, basePos, 12, 0, 10, stainedGlass);
		addBlock(world, basePos, 12, 0, 11, lunarBricks);
		addBlock(world, basePos, 12, 0, 12, lunarBricks);
		addBlock(world, basePos, 12, 0, 13, stainedGlass);
		addBlock(world, basePos, 12, 0, 14, stainedGlass);
		addBlock(world, basePos, 12, 0, 15, lunarBricks);
		addBlock(world, basePos, 13, 0, 3, lunarBricks);
		addBlock(world, basePos, 13, 0, 4, lunarBricks);
		addBlock(world, basePos, 13, 0, 5, stainedGlass);
		addBlock(world, basePos, 13, 0, 6, stainedGlass);
		addBlock(world, basePos, 13, 0, 7, lunarBricks);
		addBlock(world, basePos, 13, 0, 8, lunarBricks);
		addBlock(world, basePos, 13, 0, 9, lunarBricks);
		addBlock(world, basePos, 13, 0, 10, lunarBricks);
		addBlock(world, basePos, 13, 0, 11, lunarBricks);
		addBlock(world, basePos, 13, 0, 12, stainedGlass);
		addBlock(world, basePos, 13, 0, 13, stainedGlass);
		addBlock(world, basePos, 13, 0, 14, lunarBricks);
		addBlock(world, basePos, 13, 0, 15, lunarBricks);
		addBlock(world, basePos, 14, 0, 4, lunarBricks);
		addBlock(world, basePos, 14, 0, 5, lunarBricks);
		addBlock(world, basePos, 14, 0, 6, stainedGlass);
		addBlock(world, basePos, 14, 0, 7, stainedGlass);
		addBlock(world, basePos, 14, 0, 8, stainedGlass);
		addBlock(world, basePos, 14, 0, 9, stainedGlass);
		addBlock(world, basePos, 14, 0, 10, stainedGlass);
		addBlock(world, basePos, 14, 0, 11, stainedGlass);
		addBlock(world, basePos, 14, 0, 12, stainedGlass);
		addBlock(world, basePos, 14, 0, 13, lunarBricks);
		addBlock(world, basePos, 14, 0, 14, lunarBricks);
		addBlock(world, basePos, 15, 0, 5, lunarBricks);
		addBlock(world, basePos, 15, 0, 6, lunarBricks);
		addBlock(world, basePos, 15, 0, 7, lunarBricks);
		addBlock(world, basePos, 15, 0, 8, lunarBricks);
		addBlock(world, basePos, 15, 0, 9, lunarBricks);
		addBlock(world, basePos, 15, 0, 10, lunarBricks);
		addBlock(world, basePos, 15, 0, 11, lunarBricks);
		addBlock(world, basePos, 15, 0, 12, lunarBricks);
		addBlock(world, basePos, 15, 0, 13, lunarBricks);
		addBlock(world, basePos, 2, 1, 4, lunarBricks);
		addBlock(world, basePos, 2, 1, 5, lunarBricks);
		addBlock(world, basePos, 2, 1, 6, lunarBricks);
		addBlock(world, basePos, 2, 1, 7, lunarBricks);
		addBlock(world, basePos, 2, 1, 8, lunarBricks);
		addBlock(world, basePos, 2, 1, 9, lunarBricks);
		addBlock(world, basePos, 2, 1, 10, lunarBricks);
		addBlock(world, basePos, 2, 1, 11, lunarBricks);
		addBlock(world, basePos, 2, 1, 12, lunarBricks);
		addBlock(world, basePos, 2, 1, 13, lunarBricks);
		addBlock(world, basePos, 2, 1, 14, lunarBricks);
		addBlock(world, basePos, 3, 1, 3, lunarBricks);
		addBlock(world, basePos, 3, 1, 4, lunarBricks);
		addBlock(world, basePos, 3, 1, 14, lunarBricks);
		addBlock(world, basePos, 3, 1, 15, lunarBricks);
		addBlock(world, basePos, 4, 1, 2, lunarBricks);
		addBlock(world, basePos, 4, 1, 3, lunarBricks);
		addBlock(world, basePos, 4, 1, 15, lunarBricks);
		addBlock(world, basePos, 4, 1, 16, lunarBricks);
		addBlock(world, basePos, 5, 1, 2, lunarBricks);
		addBlock(world, basePos, 5, 1, 16, lunarBricks);
		addBlock(world, basePos, 6, 1, 2, lunarBricks);
		addBlock(world, basePos, 6, 1, 16, lunarBricks);
		addBlock(world, basePos, 7, 1, 2, lunarBricks);
		addBlock(world, basePos, 7, 1, 9, lunarBricks);
		addBlock(world, basePos, 7, 1, 16, lunarBricks);
		addBlock(world, basePos, 8, 1, 2, lunarBricks);
		addBlock(world, basePos, 8, 1, 8, lunarBricks);
		addBlock(world, basePos, 8, 1, 9, lunarBricks);
		addBlock(world, basePos, 8, 1, 10, lunarBricks);
		addBlock(world, basePos, 8, 1, 16, lunarBricks);
		addBlock(world, basePos, 9, 1, 2, lunarBricks);
		addBlock(world, basePos, 9, 1, 7, lunarBricks);
		addBlock(world, basePos, 9, 1, 8, lunarBricks);
		addBlock(world, basePos, 9, 1, 9, lunarBricks);
		addBlock(world, basePos, 9, 1, 10, lunarBricks);
		addBlock(world, basePos, 9, 1, 11, lunarBricks);
		addBlock(world, basePos, 9, 1, 16, lunarBricks);
		addBlock(world, basePos, 10, 1, 2, lunarBricks);
		addBlock(world, basePos, 10, 1, 8, lunarBricks);
		addBlock(world, basePos, 10, 1, 9, lunarBricks);
		addBlock(world, basePos, 10, 1, 10, lunarBricks);
		addBlock(world, basePos, 10, 1, 16, lunarBricks);
		addBlock(world, basePos, 11, 1, 2, lunarBricks);
		addBlock(world, basePos, 11, 1, 9, lunarBricks);
		addBlock(world, basePos, 11, 1, 16, lunarBricks);
		addBlock(world, basePos, 12, 1, 2, lunarBricks);
		addBlock(world, basePos, 12, 1, 16, lunarBricks);
		addBlock(world, basePos, 13, 1, 2, lunarBricks);
		addBlock(world, basePos, 13, 1, 16, lunarBricks);
		addBlock(world, basePos, 14, 1, 2, lunarBricks);
		addBlock(world, basePos, 14, 1, 3, lunarBricks);
		addBlock(world, basePos, 14, 1, 15, lunarBricks);
		addBlock(world, basePos, 14, 1, 16, lunarBricks);
		addBlock(world, basePos, 15, 1, 3, lunarBricks);
		addBlock(world, basePos, 15, 1, 4, lunarBricks);
		addBlock(world, basePos, 15, 1, 14, lunarBricks);
		addBlock(world, basePos, 15, 1, 15, lunarBricks);
		addBlock(world, basePos, 16, 1, 4, lunarBricks);
		addBlock(world, basePos, 16, 1, 5, lunarBricks);
		addBlock(world, basePos, 16, 1, 6, lunarBricks);
		addBlock(world, basePos, 16, 1, 7, lunarBricks);
		addBlock(world, basePos, 16, 1, 8, lunarBricks);
		addBlock(world, basePos, 16, 1, 9, lunarBricks);
		addBlock(world, basePos, 16, 1, 10, lunarBricks);
		addBlock(world, basePos, 16, 1, 11, lunarBricks);
		addBlock(world, basePos, 16, 1, 12, lunarBricks);
		addBlock(world, basePos, 16, 1, 13, lunarBricks);
		addBlock(world, basePos, 16, 1, 14, lunarBricks);
		addBlock(world, basePos, 0, 2, 3, lunarBricks);
		addBlock(world, basePos, 0, 2, 4, lunarBricks);
		addBlock(world, basePos, 0, 2, 5, lunarBricks);
		addBlock(world, basePos, 0, 2, 6, lunarBricks);
		addBlock(world, basePos, 0, 2, 7, lunarBricks);
		addBlock(world, basePos, 0, 2, 8, lunarBricks);
		addBlock(world, basePos, 0, 2, 9, lunarBricks);
		addBlock(world, basePos, 0, 2, 10, lunarBricks);
		addBlock(world, basePos, 0, 2, 11, lunarBricks);
		addBlock(world, basePos, 0, 2, 12, lunarBricks);
		addBlock(world, basePos, 0, 2, 13, lunarBricks);
		addBlock(world, basePos, 0, 2, 14, lunarBricks);
		addBlock(world, basePos, 0, 2, 15, lunarBricks);
		addBlock(world, basePos, 1, 2, 2, lunarBricks);
		addBlock(world, basePos, 1, 2, 3, lunarBricks);
		addBlock(world, basePos, 1, 2, 4, lunarBricks);
		addBlock(world, basePos, 1, 2, 5, lunarBricks);
		addBlock(world, basePos, 1, 2, 6, lunarBricks);
		addBlock(world, basePos, 1, 2, 7, lunarBricks);
		addBlock(world, basePos, 1, 2, 8, lunarBricks);
		addBlock(world, basePos, 1, 2, 9, lunarBricks);
		addBlock(world, basePos, 1, 2, 10, lunarBricks);
		addBlock(world, basePos, 1, 2, 11, lunarBricks);
		addBlock(world, basePos, 1, 2, 12, lunarBricks);
		addBlock(world, basePos, 1, 2, 13, lunarBricks);
		addBlock(world, basePos, 1, 2, 14, lunarBricks);
		addBlock(world, basePos, 1, 2, 15, lunarBricks);
		addBlock(world, basePos, 1, 2, 16, lunarBricks);
		addBlock(world, basePos, 2, 2, 1, lunarBricks);
		addBlock(world, basePos, 2, 2, 2, lunarBricks);
		addBlock(world, basePos, 2, 2, 3, lunarBricks);
		addBlock(world, basePos, 2, 2, 15, lunarBricks);
		addBlock(world, basePos, 2, 2, 16, lunarBricks);
		addBlock(world, basePos, 2, 2, 17, lunarBricks);
		addBlock(world, basePos, 3, 2, 0, lunarBricks);
		addBlock(world, basePos, 3, 2, 1, lunarBricks);
		addBlock(world, basePos, 3, 2, 2, lunarBricks);
		addBlock(world, basePos, 3, 2, 16, lunarBricks);
		addBlock(world, basePos, 3, 2, 17, lunarBricks);
		addBlock(world, basePos, 3, 2, 18, lunarBricks);
		addBlock(world, basePos, 4, 2, 0, lunarBricks);
		addBlock(world, basePos, 4, 2, 1, lunarBricks);
		addBlock(world, basePos, 4, 2, 17, lunarBricks);
		addBlock(world, basePos, 4, 2, 18, lunarBricks);
		addBlock(world, basePos, 5, 2, 0, lunarBricks);
		addBlock(world, basePos, 5, 2, 1, lunarBricks);
		addBlock(world, basePos, 5, 2, 17, lunarBricks);
		addBlock(world, basePos, 5, 2, 18, lunarBricks);
		addBlock(world, basePos, 6, 2, 0, lunarBricks);
		addBlock(world, basePos, 6, 2, 1, lunarBricks);
		addBlock(world, basePos, 6, 2, 17, lunarBricks);
		addBlock(world, basePos, 6, 2, 18, lunarBricks);
		addBlock(world, basePos, 7, 2, 0, lunarBricks);
		addBlock(world, basePos, 7, 2, 1, lunarBricks);
		addBlock(world, basePos, 7, 2, 17, lunarBricks);
		addBlock(world, basePos, 7, 2, 18, lunarBricks);
		addBlock(world, basePos, 8, 2, 0, lunarBricks);
		addBlock(world, basePos, 8, 2, 1, lunarBricks);
		addBlock(world, basePos, 8, 2, 9, lunarBricks);
		addBlock(world, basePos, 8, 2, 17, lunarBricks);
		addBlock(world, basePos, 8, 2, 18, lunarBricks);
		addBlock(world, basePos, 9, 2, 0, lunarBricks);
		addBlock(world, basePos, 9, 2, 1, lunarBricks);
		addBlock(world, basePos, 9, 2, 8, lunarBricks);
		addBlock(world, basePos, 9, 2, 9, lunarBricks);
		addBlock(world, basePos, 9, 2, 10, lunarBricks);
		addBlock(world, basePos, 9, 2, 17, lunarBricks);
		addBlock(world, basePos, 9, 2, 18, lunarBricks);
		addBlock(world, basePos, 10, 2, 0, lunarBricks);
		addBlock(world, basePos, 10, 2, 1, lunarBricks);
		addBlock(world, basePos, 10, 2, 9, lunarBricks);
		addBlock(world, basePos, 10, 2, 17, lunarBricks);
		addBlock(world, basePos, 10, 2, 18, lunarBricks);
		addBlock(world, basePos, 11, 2, 0, lunarBricks);
		addBlock(world, basePos, 11, 2, 1, lunarBricks);
		addBlock(world, basePos, 11, 2, 17, lunarBricks);
		addBlock(world, basePos, 11, 2, 18, lunarBricks);
		addBlock(world, basePos, 12, 2, 0, lunarBricks);
		addBlock(world, basePos, 12, 2, 1, lunarBricks);
		addBlock(world, basePos, 12, 2, 17, lunarBricks);
		addBlock(world, basePos, 12, 2, 18, lunarBricks);
		addBlock(world, basePos, 13, 2, 0, lunarBricks);
		addBlock(world, basePos, 13, 2, 1, lunarBricks);
		addBlock(world, basePos, 13, 2, 17, lunarBricks);
		addBlock(world, basePos, 13, 2, 18, lunarBricks);
		addBlock(world, basePos, 14, 2, 0, lunarBricks);
		addBlock(world, basePos, 14, 2, 1, lunarBricks);
		addBlock(world, basePos, 14, 2, 17, lunarBricks);
		addBlock(world, basePos, 14, 2, 18, lunarBricks);
		addBlock(world, basePos, 15, 2, 0, lunarBricks);
		addBlock(world, basePos, 15, 2, 1, lunarBricks);
		addBlock(world, basePos, 15, 2, 2, lunarBricks);
		addBlock(world, basePos, 15, 2, 16, lunarBricks);
		addBlock(world, basePos, 15, 2, 17, lunarBricks);
		addBlock(world, basePos, 15, 2, 18, lunarBricks);
		addBlock(world, basePos, 16, 2, 1, lunarBricks);
		addBlock(world, basePos, 16, 2, 2, lunarBricks);
		addBlock(world, basePos, 16, 2, 3, lunarBricks);
		addBlock(world, basePos, 16, 2, 15, lunarBricks);
		addBlock(world, basePos, 16, 2, 16, lunarBricks);
		addBlock(world, basePos, 16, 2, 17, lunarBricks);
		addBlock(world, basePos, 17, 2, 2, lunarBricks);
		addBlock(world, basePos, 17, 2, 3, lunarBricks);
		addBlock(world, basePos, 17, 2, 4, lunarBricks);
		addBlock(world, basePos, 17, 2, 5, lunarBricks);
		addBlock(world, basePos, 17, 2, 6, lunarBricks);
		addBlock(world, basePos, 17, 2, 7, lunarBricks);
		addBlock(world, basePos, 17, 2, 8, lunarBricks);
		addBlock(world, basePos, 17, 2, 9, lunarBricks);
		addBlock(world, basePos, 17, 2, 10, lunarBricks);
		addBlock(world, basePos, 17, 2, 11, lunarBricks);
		addBlock(world, basePos, 17, 2, 12, lunarBricks);
		addBlock(world, basePos, 17, 2, 13, lunarBricks);
		addBlock(world, basePos, 17, 2, 14, lunarBricks);
		addBlock(world, basePos, 17, 2, 15, lunarBricks);
		addBlock(world, basePos, 17, 2, 16, lunarBricks);
		addBlock(world, basePos, 18, 2, 3, lunarBricks);
		addBlock(world, basePos, 18, 2, 4, lunarBricks);
		addBlock(world, basePos, 18, 2, 5, lunarBricks);
		addBlock(world, basePos, 18, 2, 6, lunarBricks);
		addBlock(world, basePos, 18, 2, 7, lunarBricks);
		addBlock(world, basePos, 18, 2, 8, lunarBricks);
		addBlock(world, basePos, 18, 2, 9, lunarBricks);
		addBlock(world, basePos, 18, 2, 10, lunarBricks);
		addBlock(world, basePos, 18, 2, 11, lunarBricks);
		addBlock(world, basePos, 18, 2, 12, lunarBricks);
		addBlock(world, basePos, 18, 2, 13, lunarBricks);
		addBlock(world, basePos, 18, 2, 14, lunarBricks);
		addBlock(world, basePos, 18, 2, 15, lunarBricks);
		addBlock(world, basePos, 9, 3, 9, lunarBricks);
		addBlock(world, basePos, 9, 4, 9, lunarBricks);
		addBlock(world, basePos, 9, 5, 9, lunarBricks);
		addBlock(world, basePos, 9, 6, 9, lunarBricks);
		addBlock(world, basePos, 9, 7, 9, lunarBricks);
		addBlock(world, basePos, 9, 8, 9, lunarBricks);
		addBlock(world, basePos, 8, 9, 9, water);
		addBlock(world, basePos, 9, 9, 8, water);
		addBlock(world, basePos, 9, 9, 9, lunarBricks);
		addBlock(world, basePos, 9, 9, 10, water);
		addBlock(world, basePos, 10, 9, 9, water);
		addBlock(world, basePos, 9, 10, 9, lunarBricks);
		addBlock(world, basePos, 7, 11, 9, lunarBricks);
		addBlock(world, basePos, 8, 11, 9, lunarBricks);
		addBlock(world, basePos, 9, 11, 7, lunarBricks);
		addBlock(world, basePos, 9, 11, 8, lunarBricks);
		addBlock(world, basePos, 9, 11, 9, lunarBricks);
		addBlock(world, basePos, 9, 11, 10, lunarBricks);
		addBlock(world, basePos, 9, 11, 11, lunarBricks);
		addBlock(world, basePos, 10, 11, 9, lunarBricks);
		addBlock(world, basePos, 11, 11, 9, lunarBricks);
		addBlock(world, basePos, 5, 12, 9, lunarLamp);
		addBlock(world, basePos, 6, 12, 9, lunarBricks);
		addBlock(world, basePos, 7, 12, 9, lunarBricks);
		addBlock(world, basePos, 9, 12, 5, lunarLamp);
		addBlock(world, basePos, 9, 12, 6, lunarBricks);
		addBlock(world, basePos, 9, 12, 7, lunarBricks);
		addBlock(world, basePos, 9, 12, 11, lunarBricks);
		addBlock(world, basePos, 9, 12, 12, lunarBricks);
		addBlock(world, basePos, 9, 12, 13, lunarLamp);
		addBlock(world, basePos, 11, 12, 9, lunarBricks);
		addBlock(world, basePos, 12, 12, 9, lunarBricks);
		addBlock(world, basePos, 13, 12, 9, lunarLamp);
	}

	@Override
	protected void spawnEntities(IWorld world, Random rand, BlockPos basePos) {
		ZalCitizenEntity zalCitizen = new ZalCitizenEntity(AoAEntities.NPCs.ZAL_CITIZEN.get(), world.getWorld());
		ZalCitizenEntity zalCitizen2 = new ZalCitizenEntity(AoAEntities.NPCs.ZAL_CITIZEN.get(), world.getWorld());
		ZalCitizenEntity zalCitizen3 = new ZalCitizenEntity(AoAEntities.NPCs.ZAL_CITIZEN.get(), world.getWorld());
		ZalCitizenEntity zalCitizen4 = new ZalCitizenEntity(AoAEntities.NPCs.ZAL_CITIZEN.get(), world.getWorld());

		zalCitizen.setLocationAndAngles(basePos.getX() + 9, basePos.getY() + 3, basePos.getZ() + 1, rand.nextFloat() * 360, 0);
		zalCitizen2.setLocationAndAngles(basePos.getX() + 9, basePos.getY() + 3, basePos.getZ() + 18, rand.nextFloat() * 360, 0);
		zalCitizen3.setLocationAndAngles(basePos.getX() + 1, basePos.getY() + 3, basePos.getZ() + 9, rand.nextFloat() * 360, 0);
		zalCitizen4.setLocationAndAngles(basePos.getX() + 18, basePos.getY() + 3, basePos.getZ() + 9, rand.nextFloat() * 360, 0);
		world.addEntity(zalCitizen);
		world.addEntity(zalCitizen2);
		world.addEntity(zalCitizen3);
		world.addEntity(zalCitizen4);
	}
}
