package net.tslat.aoa3.worldgen.structures.lunalus;

import net.minecraft.block.BlockState;
import net.minecraft.block.Blocks;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.IWorld;
import net.tslat.aoa3.block.functional.light.LampBlock;
import net.tslat.aoa3.common.registration.AoABlocks;
import net.tslat.aoa3.common.registration.AoAEntities;
import net.tslat.aoa3.entity.npc.ambient.ZalCitizenEntity;
import net.tslat.aoa3.entity.npc.lottoman.LunarLottomanEntity;
import net.tslat.aoa3.worldgen.structures.AoAStructure;

import java.util.Random;

public class LunarLottoPlatform extends AoAStructure { //StructureSize: 11x11x11
	private static final BlockState lunarLamp = AoABlocks.LUNAR_LAMP.get().getDefaultState().with(LampBlock.TOGGLEABLE, false);
	private static final BlockState lunarBricks = AoABlocks.LUNAR_BRICKS.get().getDefaultState();
	private static final BlockState whitewashBricks = AoABlocks.WHITEWASH_BRICKS.get().getDefaultState();
	private static final BlockState stainedGlass = Blocks.WHITE_STAINED_GLASS.getDefaultState();
	private static final BlockState lunarPillar = AoABlocks.LUNAR_PILLAR.get().getDefaultState();

	public LunarLottoPlatform() {
		super("LunarLottoPlatform");
	}

	@Override
	protected boolean replacesBlocks() {
		return true;
	}

	@Override
	protected void build(IWorld world, Random rand, BlockPos basePos) {
		addBlock(world, basePos, 0, 0, 0, lunarPillar);
		addBlock(world, basePos, 0, 0, 10, lunarPillar);
		addBlock(world, basePos, 10, 0, 0, lunarPillar);
		addBlock(world, basePos, 10, 0, 10, lunarPillar);
		addBlock(world, basePos, 0, 1, 0, lunarPillar);
		addBlock(world, basePos, 0, 1, 10, lunarPillar);
		addBlock(world, basePos, 10, 1, 0, lunarPillar);
		addBlock(world, basePos, 10, 1, 10, lunarPillar);
		addBlock(world, basePos, 0, 2, 0, lunarPillar);
		addBlock(world, basePos, 0, 2, 10, lunarPillar);
		addBlock(world, basePos, 10, 2, 0, lunarPillar);
		addBlock(world, basePos, 10, 2, 10, lunarPillar);
		addBlock(world, basePos, 0, 3, 0, lunarPillar);
		addBlock(world, basePos, 0, 3, 1, lunarBricks);
		addBlock(world, basePos, 0, 3, 9, lunarBricks);
		addBlock(world, basePos, 0, 3, 10, lunarPillar);
		addBlock(world, basePos, 1, 3, 0, lunarBricks);
		addBlock(world, basePos, 1, 3, 1, whitewashBricks);
		addBlock(world, basePos, 1, 3, 2, whitewashBricks);
		addBlock(world, basePos, 1, 3, 3, whitewashBricks);
		addBlock(world, basePos, 1, 3, 4, whitewashBricks);
		addBlock(world, basePos, 1, 3, 5, whitewashBricks);
		addBlock(world, basePos, 1, 3, 6, whitewashBricks);
		addBlock(world, basePos, 1, 3, 7, whitewashBricks);
		addBlock(world, basePos, 1, 3, 8, whitewashBricks);
		addBlock(world, basePos, 1, 3, 9, whitewashBricks);
		addBlock(world, basePos, 1, 3, 10, lunarBricks);
		addBlock(world, basePos, 2, 3, 1, whitewashBricks);
		addBlock(world, basePos, 2, 3, 2, lunarBricks);
		addBlock(world, basePos, 2, 3, 3, lunarBricks);
		addBlock(world, basePos, 2, 3, 4, lunarBricks);
		addBlock(world, basePos, 2, 3, 5, lunarBricks);
		addBlock(world, basePos, 2, 3, 6, lunarBricks);
		addBlock(world, basePos, 2, 3, 7, lunarBricks);
		addBlock(world, basePos, 2, 3, 8, lunarBricks);
		addBlock(world, basePos, 2, 3, 9, whitewashBricks);
		addBlock(world, basePos, 3, 3, 1, whitewashBricks);
		addBlock(world, basePos, 3, 3, 2, lunarBricks);
		addBlock(world, basePos, 3, 3, 3, lunarBricks);
		addBlock(world, basePos, 3, 3, 4, lunarBricks);
		addBlock(world, basePos, 3, 3, 5, lunarBricks);
		addBlock(world, basePos, 3, 3, 6, lunarBricks);
		addBlock(world, basePos, 3, 3, 7, lunarBricks);
		addBlock(world, basePos, 3, 3, 8, lunarBricks);
		addBlock(world, basePos, 3, 3, 9, whitewashBricks);
		addBlock(world, basePos, 4, 3, 1, whitewashBricks);
		addBlock(world, basePos, 4, 3, 2, lunarBricks);
		addBlock(world, basePos, 4, 3, 3, lunarBricks);
		addBlock(world, basePos, 4, 3, 4, stainedGlass);
		addBlock(world, basePos, 4, 3, 5, stainedGlass);
		addBlock(world, basePos, 4, 3, 6, stainedGlass);
		addBlock(world, basePos, 4, 3, 7, lunarBricks);
		addBlock(world, basePos, 4, 3, 8, lunarBricks);
		addBlock(world, basePos, 4, 3, 9, whitewashBricks);
		addBlock(world, basePos, 5, 3, 1, whitewashBricks);
		addBlock(world, basePos, 5, 3, 2, lunarBricks);
		addBlock(world, basePos, 5, 3, 3, lunarBricks);
		addBlock(world, basePos, 5, 3, 4, stainedGlass);
		addBlock(world, basePos, 5, 3, 5, stainedGlass);
		addBlock(world, basePos, 5, 3, 6, stainedGlass);
		addBlock(world, basePos, 5, 3, 7, lunarBricks);
		addBlock(world, basePos, 5, 3, 8, lunarBricks);
		addBlock(world, basePos, 5, 3, 9, whitewashBricks);
		addBlock(world, basePos, 6, 3, 1, whitewashBricks);
		addBlock(world, basePos, 6, 3, 2, lunarBricks);
		addBlock(world, basePos, 6, 3, 3, lunarBricks);
		addBlock(world, basePos, 6, 3, 4, stainedGlass);
		addBlock(world, basePos, 6, 3, 5, stainedGlass);
		addBlock(world, basePos, 6, 3, 6, stainedGlass);
		addBlock(world, basePos, 6, 3, 7, lunarBricks);
		addBlock(world, basePos, 6, 3, 8, lunarBricks);
		addBlock(world, basePos, 6, 3, 9, whitewashBricks);
		addBlock(world, basePos, 7, 3, 1, whitewashBricks);
		addBlock(world, basePos, 7, 3, 2, lunarBricks);
		addBlock(world, basePos, 7, 3, 3, lunarBricks);
		addBlock(world, basePos, 7, 3, 4, lunarBricks);
		addBlock(world, basePos, 7, 3, 5, lunarBricks);
		addBlock(world, basePos, 7, 3, 6, lunarBricks);
		addBlock(world, basePos, 7, 3, 7, lunarBricks);
		addBlock(world, basePos, 7, 3, 8, lunarBricks);
		addBlock(world, basePos, 7, 3, 9, whitewashBricks);
		addBlock(world, basePos, 8, 3, 1, whitewashBricks);
		addBlock(world, basePos, 8, 3, 2, lunarBricks);
		addBlock(world, basePos, 8, 3, 3, lunarBricks);
		addBlock(world, basePos, 8, 3, 4, lunarBricks);
		addBlock(world, basePos, 8, 3, 5, lunarBricks);
		addBlock(world, basePos, 8, 3, 6, lunarBricks);
		addBlock(world, basePos, 8, 3, 7, lunarBricks);
		addBlock(world, basePos, 8, 3, 8, lunarBricks);
		addBlock(world, basePos, 8, 3, 9, whitewashBricks);
		addBlock(world, basePos, 9, 3, 0, lunarBricks);
		addBlock(world, basePos, 9, 3, 1, whitewashBricks);
		addBlock(world, basePos, 9, 3, 2, whitewashBricks);
		addBlock(world, basePos, 9, 3, 3, whitewashBricks);
		addBlock(world, basePos, 9, 3, 4, whitewashBricks);
		addBlock(world, basePos, 9, 3, 5, whitewashBricks);
		addBlock(world, basePos, 9, 3, 6, whitewashBricks);
		addBlock(world, basePos, 9, 3, 7, whitewashBricks);
		addBlock(world, basePos, 9, 3, 8, whitewashBricks);
		addBlock(world, basePos, 9, 3, 9, whitewashBricks);
		addBlock(world, basePos, 9, 3, 10, lunarBricks);
		addBlock(world, basePos, 10, 3, 0, lunarPillar);
		addBlock(world, basePos, 10, 3, 1, lunarBricks);
		addBlock(world, basePos, 10, 3, 9, lunarBricks);
		addBlock(world, basePos, 10, 3, 10, lunarPillar);
		addBlock(world, basePos, 0, 4, 0, lunarPillar);
		addBlock(world, basePos, 0, 4, 1, lunarBricks);
		addBlock(world, basePos, 0, 4, 9, lunarBricks);
		addBlock(world, basePos, 0, 4, 10, lunarPillar);
		addBlock(world, basePos, 1, 4, 0, lunarBricks);
		addBlock(world, basePos, 1, 4, 10, lunarBricks);
		addBlock(world, basePos, 9, 4, 0, lunarBricks);
		addBlock(world, basePos, 9, 4, 10, lunarBricks);
		addBlock(world, basePos, 10, 4, 0, lunarPillar);
		addBlock(world, basePos, 10, 4, 1, lunarBricks);
		addBlock(world, basePos, 10, 4, 9, lunarBricks);
		addBlock(world, basePos, 10, 4, 10, lunarPillar);
		addBlock(world, basePos, 0, 5, 0, lunarPillar);
		addBlock(world, basePos, 0, 5, 1, lunarBricks);
		addBlock(world, basePos, 0, 5, 9, lunarBricks);
		addBlock(world, basePos, 0, 5, 10, lunarPillar);
		addBlock(world, basePos, 1, 5, 0, lunarBricks);
		addBlock(world, basePos, 1, 5, 10, lunarBricks);
		addBlock(world, basePos, 9, 5, 0, lunarBricks);
		addBlock(world, basePos, 9, 5, 10, lunarBricks);
		addBlock(world, basePos, 10, 5, 0, lunarPillar);
		addBlock(world, basePos, 10, 5, 1, lunarBricks);
		addBlock(world, basePos, 10, 5, 9, lunarBricks);
		addBlock(world, basePos, 10, 5, 10, lunarPillar);
		addBlock(world, basePos, 0, 6, 0, lunarPillar);
		addBlock(world, basePos, 0, 6, 1, lunarBricks);
		addBlock(world, basePos, 0, 6, 9, lunarBricks);
		addBlock(world, basePos, 0, 6, 10, lunarPillar);
		addBlock(world, basePos, 1, 6, 0, lunarBricks);
		addBlock(world, basePos, 1, 6, 1, lunarLamp);
		addBlock(world, basePos, 1, 6, 9, lunarLamp);
		addBlock(world, basePos, 1, 6, 10, lunarBricks);
		addBlock(world, basePos, 9, 6, 0, lunarBricks);
		addBlock(world, basePos, 9, 6, 1, lunarLamp);
		addBlock(world, basePos, 9, 6, 9, lunarLamp);
		addBlock(world, basePos, 9, 6, 10, lunarBricks);
		addBlock(world, basePos, 10, 6, 0, lunarPillar);
		addBlock(world, basePos, 10, 6, 1, lunarBricks);
		addBlock(world, basePos, 10, 6, 9, lunarBricks);
		addBlock(world, basePos, 10, 6, 10, lunarPillar);
		addBlock(world, basePos, 0, 7, 0, lunarPillar);
		addBlock(world, basePos, 0, 7, 1, lunarBricks);
		addBlock(world, basePos, 0, 7, 9, lunarBricks);
		addBlock(world, basePos, 0, 7, 10, lunarPillar);
		addBlock(world, basePos, 1, 7, 0, lunarBricks);
		addBlock(world, basePos, 1, 7, 1, whitewashBricks);
		addBlock(world, basePos, 1, 7, 2, whitewashBricks);
		addBlock(world, basePos, 1, 7, 3, whitewashBricks);
		addBlock(world, basePos, 1, 7, 4, whitewashBricks);
		addBlock(world, basePos, 1, 7, 5, whitewashBricks);
		addBlock(world, basePos, 1, 7, 6, whitewashBricks);
		addBlock(world, basePos, 1, 7, 7, whitewashBricks);
		addBlock(world, basePos, 1, 7, 8, whitewashBricks);
		addBlock(world, basePos, 1, 7, 9, whitewashBricks);
		addBlock(world, basePos, 1, 7, 10, lunarBricks);
		addBlock(world, basePos, 2, 7, 1, whitewashBricks);
		addBlock(world, basePos, 2, 7, 2, lunarBricks);
		addBlock(world, basePos, 2, 7, 3, lunarBricks);
		addBlock(world, basePos, 2, 7, 4, lunarBricks);
		addBlock(world, basePos, 2, 7, 5, lunarBricks);
		addBlock(world, basePos, 2, 7, 6, lunarBricks);
		addBlock(world, basePos, 2, 7, 7, lunarBricks);
		addBlock(world, basePos, 2, 7, 8, lunarBricks);
		addBlock(world, basePos, 2, 7, 9, whitewashBricks);
		addBlock(world, basePos, 3, 7, 1, whitewashBricks);
		addBlock(world, basePos, 3, 7, 2, lunarBricks);
		addBlock(world, basePos, 3, 7, 3, lunarBricks);
		addBlock(world, basePos, 3, 7, 4, lunarBricks);
		addBlock(world, basePos, 3, 7, 5, lunarBricks);
		addBlock(world, basePos, 3, 7, 6, lunarBricks);
		addBlock(world, basePos, 3, 7, 7, lunarBricks);
		addBlock(world, basePos, 3, 7, 8, lunarBricks);
		addBlock(world, basePos, 3, 7, 9, whitewashBricks);
		addBlock(world, basePos, 4, 7, 1, whitewashBricks);
		addBlock(world, basePos, 4, 7, 2, lunarBricks);
		addBlock(world, basePos, 4, 7, 3, lunarBricks);
		addBlock(world, basePos, 4, 7, 4, stainedGlass);
		addBlock(world, basePos, 4, 7, 5, stainedGlass);
		addBlock(world, basePos, 4, 7, 6, stainedGlass);
		addBlock(world, basePos, 4, 7, 7, lunarBricks);
		addBlock(world, basePos, 4, 7, 8, lunarBricks);
		addBlock(world, basePos, 4, 7, 9, whitewashBricks);
		addBlock(world, basePos, 5, 7, 1, whitewashBricks);
		addBlock(world, basePos, 5, 7, 2, lunarBricks);
		addBlock(world, basePos, 5, 7, 3, lunarBricks);
		addBlock(world, basePos, 5, 7, 4, stainedGlass);
		addBlock(world, basePos, 5, 7, 5, stainedGlass);
		addBlock(world, basePos, 5, 7, 6, stainedGlass);
		addBlock(world, basePos, 5, 7, 7, lunarBricks);
		addBlock(world, basePos, 5, 7, 8, lunarBricks);
		addBlock(world, basePos, 5, 7, 9, whitewashBricks);
		addBlock(world, basePos, 6, 7, 1, whitewashBricks);
		addBlock(world, basePos, 6, 7, 2, lunarBricks);
		addBlock(world, basePos, 6, 7, 3, lunarBricks);
		addBlock(world, basePos, 6, 7, 4, stainedGlass);
		addBlock(world, basePos, 6, 7, 5, stainedGlass);
		addBlock(world, basePos, 6, 7, 6, stainedGlass);
		addBlock(world, basePos, 6, 7, 7, lunarBricks);
		addBlock(world, basePos, 6, 7, 8, lunarBricks);
		addBlock(world, basePos, 6, 7, 9, whitewashBricks);
		addBlock(world, basePos, 7, 7, 1, whitewashBricks);
		addBlock(world, basePos, 7, 7, 2, lunarBricks);
		addBlock(world, basePos, 7, 7, 3, lunarBricks);
		addBlock(world, basePos, 7, 7, 4, lunarBricks);
		addBlock(world, basePos, 7, 7, 5, lunarBricks);
		addBlock(world, basePos, 7, 7, 6, lunarBricks);
		addBlock(world, basePos, 7, 7, 7, lunarBricks);
		addBlock(world, basePos, 7, 7, 8, lunarBricks);
		addBlock(world, basePos, 7, 7, 9, whitewashBricks);
		addBlock(world, basePos, 8, 7, 1, whitewashBricks);
		addBlock(world, basePos, 8, 7, 2, lunarBricks);
		addBlock(world, basePos, 8, 7, 3, lunarBricks);
		addBlock(world, basePos, 8, 7, 4, lunarBricks);
		addBlock(world, basePos, 8, 7, 5, lunarBricks);
		addBlock(world, basePos, 8, 7, 6, lunarBricks);
		addBlock(world, basePos, 8, 7, 7, lunarBricks);
		addBlock(world, basePos, 8, 7, 8, lunarBricks);
		addBlock(world, basePos, 8, 7, 9, whitewashBricks);
		addBlock(world, basePos, 9, 7, 0, lunarBricks);
		addBlock(world, basePos, 9, 7, 1, whitewashBricks);
		addBlock(world, basePos, 9, 7, 2, whitewashBricks);
		addBlock(world, basePos, 9, 7, 3, whitewashBricks);
		addBlock(world, basePos, 9, 7, 4, whitewashBricks);
		addBlock(world, basePos, 9, 7, 5, whitewashBricks);
		addBlock(world, basePos, 9, 7, 6, whitewashBricks);
		addBlock(world, basePos, 9, 7, 7, whitewashBricks);
		addBlock(world, basePos, 9, 7, 8, whitewashBricks);
		addBlock(world, basePos, 9, 7, 9, whitewashBricks);
		addBlock(world, basePos, 9, 7, 10, lunarBricks);
		addBlock(world, basePos, 10, 7, 0, lunarPillar);
		addBlock(world, basePos, 10, 7, 1, lunarBricks);
		addBlock(world, basePos, 10, 7, 9, lunarBricks);
		addBlock(world, basePos, 10, 7, 10, lunarPillar);
		addBlock(world, basePos, 0, 8, 0, lunarPillar);
		addBlock(world, basePos, 0, 8, 10, lunarPillar);
		addBlock(world, basePos, 10, 8, 0, lunarPillar);
		addBlock(world, basePos, 10, 8, 10, lunarPillar);
		addBlock(world, basePos, 0, 9, 0, lunarPillar);
		addBlock(world, basePos, 0, 9, 10, lunarPillar);
		addBlock(world, basePos, 10, 9, 0, lunarPillar);
		addBlock(world, basePos, 10, 9, 10, lunarPillar);
		addBlock(world, basePos, 0, 10, 0, lunarPillar);
		addBlock(world, basePos, 0, 10, 10, lunarPillar);
		addBlock(world, basePos, 10, 10, 0, lunarPillar);
		addBlock(world, basePos, 10, 10, 10, lunarPillar);
	}

	@Override
	protected void spawnEntities(IWorld world, Random rand, BlockPos basePos) {
		LunarLottomanEntity lottoman = new LunarLottomanEntity(AoAEntities.NPCs.LUNAR_LOTTOMAN.get(), world.getWorld());
		ZalCitizenEntity zalCitizen = new ZalCitizenEntity(AoAEntities.NPCs.ZAL_CITIZEN.get(), world.getWorld());
		ZalCitizenEntity zalCitizen2 = new ZalCitizenEntity(AoAEntities.NPCs.ZAL_CITIZEN.get(), world.getWorld());

		lottoman.setLocationAndAngles(basePos.getX() + 6, basePos.getY() + 4, basePos.getZ() + 6, rand.nextFloat() * 360, 0);
		zalCitizen.setLocationAndAngles(basePos.getX() + 4, basePos.getY() + 4, basePos.getZ() + 4, rand.nextFloat() * 360, 0);
		zalCitizen2.setLocationAndAngles(basePos.getX() + 8, basePos.getY() + 4, basePos.getZ() + 8, rand.nextFloat() * 360, 0);
		world.addEntity(lottoman);
		world.addEntity(zalCitizen);
		world.addEntity(zalCitizen2);
	}
}
