package net.nevermine.structures.lunalus;

import net.minecraft.init.Blocks;
import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenerator;
import net.nevermine.izer.Blockizer;
import net.nevermine.npc.entity.lottoman.EntityLottomanLunalus;
import net.nevermine.npc.entity.zal.EntityZalCitizen;

import java.util.Random;

public class LunarLottoPlatform extends WorldGenerator {
	public boolean generate(final World world, final Random rand, final int i, final int j, final int k) {
		world.setBlock(i + 0, j + 0, k + 0, Blockizer.LunarPillar);
		world.setBlock(i + 0, j + 0, k + 10, Blockizer.LunarPillar);
		world.setBlock(i + 0, j + 1, k + 0, Blockizer.LunarPillar);
		world.setBlock(i + 0, j + 1, k + 10, Blockizer.LunarPillar);
		world.setBlock(i + 0, j + 2, k + 0, Blockizer.LunarPillar);
		world.setBlock(i + 0, j + 2, k + 10, Blockizer.LunarPillar);
		world.setBlock(i + 0, j + 3, k + 0, Blockizer.LunarPillar);
		world.setBlock(i + 0, j + 3, k + 1, Blockizer.LunarBricks);
		world.setBlock(i + 0, j + 3, k + 9, Blockizer.LunarBricks);
		world.setBlock(i + 0, j + 3, k + 10, Blockizer.LunarPillar);
		world.setBlock(i + 0, j + 4, k + 0, Blockizer.LunarPillar);
		world.setBlock(i + 0, j + 4, k + 1, Blockizer.LunarBricks);
		world.setBlock(i + 0, j + 4, k + 9, Blockizer.LunarBricks);
		world.setBlock(i + 0, j + 4, k + 10, Blockizer.LunarPillar);
		world.setBlock(i + 0, j + 5, k + 0, Blockizer.LunarPillar);
		world.setBlock(i + 0, j + 5, k + 1, Blockizer.LunarBricks);
		world.setBlock(i + 0, j + 5, k + 9, Blockizer.LunarBricks);
		world.setBlock(i + 0, j + 5, k + 10, Blockizer.LunarPillar);
		world.setBlock(i + 0, j + 6, k + 0, Blockizer.LunarPillar);
		world.setBlock(i + 0, j + 6, k + 1, Blockizer.LunarBricks);
		world.setBlock(i + 0, j + 6, k + 9, Blockizer.LunarBricks);
		world.setBlock(i + 0, j + 6, k + 10, Blockizer.LunarPillar);
		world.setBlock(i + 0, j + 7, k + 0, Blockizer.LunarPillar);
		world.setBlock(i + 0, j + 7, k + 1, Blockizer.LunarBricks);
		world.setBlock(i + 0, j + 7, k + 9, Blockizer.LunarBricks);
		world.setBlock(i + 0, j + 7, k + 10, Blockizer.LunarPillar);
		world.setBlock(i + 0, j + 8, k + 0, Blockizer.LunarPillar);
		world.setBlock(i + 0, j + 8, k + 10, Blockizer.LunarPillar);
		world.setBlock(i + 0, j + 9, k + 0, Blockizer.LunarPillar);
		world.setBlock(i + 0, j + 9, k + 10, Blockizer.LunarPillar);
		world.setBlock(i + 0, j + 10, k + 0, Blockizer.LunarPillar);
		world.setBlock(i + 0, j + 10, k + 10, Blockizer.LunarPillar);
		world.setBlock(i + 1, j + 3, k + 0, Blockizer.LunarBricks);
		world.setBlock(i + 1, j + 3, k + 1, Blockizer.WhiteWashBricks);
		world.setBlock(i + 1, j + 3, k + 2, Blockizer.WhiteWashBricks);
		world.setBlock(i + 1, j + 3, k + 3, Blockizer.WhiteWashBricks);
		world.setBlock(i + 1, j + 3, k + 4, Blockizer.WhiteWashBricks);
		world.setBlock(i + 1, j + 3, k + 5, Blockizer.WhiteWashBricks);
		world.setBlock(i + 1, j + 3, k + 6, Blockizer.WhiteWashBricks);
		world.setBlock(i + 1, j + 3, k + 7, Blockizer.WhiteWashBricks);
		world.setBlock(i + 1, j + 3, k + 8, Blockizer.WhiteWashBricks);
		world.setBlock(i + 1, j + 3, k + 9, Blockizer.WhiteWashBricks);
		world.setBlock(i + 1, j + 3, k + 10, Blockizer.LunarBricks);
		world.setBlock(i + 1, j + 4, k + 0, Blockizer.LunarBricks);
		world.setBlock(i + 1, j + 4, k + 10, Blockizer.LunarBricks);
		world.setBlock(i + 1, j + 5, k + 0, Blockizer.LunarBricks);
		world.setBlock(i + 1, j + 5, k + 10, Blockizer.LunarBricks);
		world.setBlock(i + 1, j + 6, k + 0, Blockizer.LunarBricks);
		world.setBlock(i + 1, j + 6, k + 1, Blockizer.LampLunar);
		world.setBlock(i + 1, j + 6, k + 9, Blockizer.LampLunar);
		world.setBlock(i + 1, j + 6, k + 10, Blockizer.LunarBricks);
		world.setBlock(i + 1, j + 7, k + 0, Blockizer.LunarBricks);
		world.setBlock(i + 1, j + 7, k + 1, Blockizer.WhiteWashBricks);
		world.setBlock(i + 1, j + 7, k + 2, Blockizer.WhiteWashBricks);
		world.setBlock(i + 1, j + 7, k + 3, Blockizer.WhiteWashBricks);
		world.setBlock(i + 1, j + 7, k + 4, Blockizer.WhiteWashBricks);
		world.setBlock(i + 1, j + 7, k + 5, Blockizer.WhiteWashBricks);
		world.setBlock(i + 1, j + 7, k + 6, Blockizer.WhiteWashBricks);
		world.setBlock(i + 1, j + 7, k + 7, Blockizer.WhiteWashBricks);
		world.setBlock(i + 1, j + 7, k + 8, Blockizer.WhiteWashBricks);
		world.setBlock(i + 1, j + 7, k + 9, Blockizer.WhiteWashBricks);
		world.setBlock(i + 1, j + 7, k + 10, Blockizer.LunarBricks);
		world.setBlock(i + 2, j + 3, k + 1, Blockizer.WhiteWashBricks);
		world.setBlock(i + 2, j + 3, k + 2, Blockizer.LunarBricks);
		world.setBlock(i + 2, j + 3, k + 3, Blockizer.LunarBricks);
		world.setBlock(i + 2, j + 3, k + 4, Blockizer.LunarBricks);
		world.setBlock(i + 2, j + 3, k + 5, Blockizer.LunarBricks);
		world.setBlock(i + 2, j + 3, k + 6, Blockizer.LunarBricks);
		world.setBlock(i + 2, j + 3, k + 7, Blockizer.LunarBricks);
		world.setBlock(i + 2, j + 3, k + 8, Blockizer.LunarBricks);
		world.setBlock(i + 2, j + 3, k + 9, Blockizer.WhiteWashBricks);
		world.setBlock(i + 2, j + 7, k + 1, Blockizer.WhiteWashBricks);
		world.setBlock(i + 2, j + 7, k + 2, Blockizer.LunarBricks);
		world.setBlock(i + 2, j + 7, k + 3, Blockizer.LunarBricks);
		world.setBlock(i + 2, j + 7, k + 4, Blockizer.LunarBricks);
		world.setBlock(i + 2, j + 7, k + 5, Blockizer.LunarBricks);
		world.setBlock(i + 2, j + 7, k + 6, Blockizer.LunarBricks);
		world.setBlock(i + 2, j + 7, k + 7, Blockizer.LunarBricks);
		world.setBlock(i + 2, j + 7, k + 8, Blockizer.LunarBricks);
		world.setBlock(i + 2, j + 7, k + 9, Blockizer.WhiteWashBricks);
		world.setBlock(i + 3, j + 3, k + 1, Blockizer.WhiteWashBricks);
		world.setBlock(i + 3, j + 3, k + 2, Blockizer.LunarBricks);
		world.setBlock(i + 3, j + 3, k + 3, Blockizer.LunarBricks);
		world.setBlock(i + 3, j + 3, k + 4, Blockizer.LunarBricks);
		world.setBlock(i + 3, j + 3, k + 5, Blockizer.LunarBricks);
		world.setBlock(i + 3, j + 3, k + 6, Blockizer.LunarBricks);
		world.setBlock(i + 3, j + 3, k + 7, Blockizer.LunarBricks);
		world.setBlock(i + 3, j + 3, k + 8, Blockizer.LunarBricks);
		world.setBlock(i + 3, j + 3, k + 9, Blockizer.WhiteWashBricks);
		if (!world.isRemote) {
			final EntityZalCitizen var2 = new EntityZalCitizen(world);
			var2.setLocationAndAngles((double)(i + 3), (double)(j + 5), (double)(k + 7), rand.nextFloat() * 360.0f, 0.0f);
			world.spawnEntityInWorld(var2);
		}
		world.setBlock(i + 3, j + 7, k + 1, Blockizer.WhiteWashBricks);
		world.setBlock(i + 3, j + 7, k + 2, Blockizer.LunarBricks);
		world.setBlock(i + 3, j + 7, k + 3, Blockizer.LunarBricks);
		world.setBlock(i + 3, j + 7, k + 4, Blockizer.LunarBricks);
		world.setBlock(i + 3, j + 7, k + 5, Blockizer.LunarBricks);
		world.setBlock(i + 3, j + 7, k + 6, Blockizer.LunarBricks);
		world.setBlock(i + 3, j + 7, k + 7, Blockizer.LunarBricks);
		world.setBlock(i + 3, j + 7, k + 8, Blockizer.LunarBricks);
		world.setBlock(i + 3, j + 7, k + 9, Blockizer.WhiteWashBricks);
		world.setBlock(i + 4, j + 3, k + 1, Blockizer.WhiteWashBricks);
		world.setBlock(i + 4, j + 3, k + 2, Blockizer.LunarBricks);
		world.setBlock(i + 4, j + 3, k + 3, Blockizer.LunarBricks);
		world.setBlock(i + 4, j + 3, k + 4, Blocks.stained_glass);
		world.setBlock(i + 4, j + 3, k + 5, Blocks.stained_glass);
		world.setBlock(i + 4, j + 3, k + 6, Blocks.stained_glass);
		world.setBlock(i + 4, j + 3, k + 7, Blockizer.LunarBricks);
		world.setBlock(i + 4, j + 3, k + 8, Blockizer.LunarBricks);
		world.setBlock(i + 4, j + 3, k + 9, Blockizer.WhiteWashBricks);
		world.setBlock(i + 4, j + 7, k + 1, Blockizer.WhiteWashBricks);
		world.setBlock(i + 4, j + 7, k + 2, Blockizer.LunarBricks);
		world.setBlock(i + 4, j + 7, k + 3, Blockizer.LunarBricks);
		world.setBlock(i + 4, j + 7, k + 4, Blocks.stained_glass);
		world.setBlock(i + 4, j + 7, k + 5, Blocks.stained_glass);
		world.setBlock(i + 4, j + 7, k + 6, Blocks.stained_glass);
		world.setBlock(i + 4, j + 7, k + 7, Blockizer.LunarBricks);
		world.setBlock(i + 4, j + 7, k + 8, Blockizer.LunarBricks);
		world.setBlock(i + 4, j + 7, k + 9, Blockizer.WhiteWashBricks);
		world.setBlock(i + 5, j + 3, k + 1, Blockizer.WhiteWashBricks);
		world.setBlock(i + 5, j + 3, k + 2, Blockizer.LunarBricks);
		world.setBlock(i + 5, j + 3, k + 3, Blockizer.LunarBricks);
		world.setBlock(i + 5, j + 3, k + 4, Blocks.stained_glass);
		world.setBlock(i + 5, j + 3, k + 5, Blocks.stained_glass);
		world.setBlock(i + 5, j + 3, k + 6, Blocks.stained_glass);
		world.setBlock(i + 5, j + 3, k + 7, Blockizer.LunarBricks);
		world.setBlock(i + 5, j + 3, k + 8, Blockizer.LunarBricks);
		world.setBlock(i + 5, j + 3, k + 9, Blockizer.WhiteWashBricks);
		if (!world.isRemote) {
			final EntityLottomanLunalus var3 = new EntityLottomanLunalus(world);
			var3.setLocationAndAngles((double)(i + 5), (double)(j + 5), (double)(k + 5), rand.nextFloat() * 360.0f, 0.0f);
			world.spawnEntityInWorld(var3);
		}
		world.setBlock(i + 5, j + 7, k + 1, Blockizer.WhiteWashBricks);
		world.setBlock(i + 5, j + 7, k + 2, Blockizer.LunarBricks);
		world.setBlock(i + 5, j + 7, k + 3, Blockizer.LunarBricks);
		world.setBlock(i + 5, j + 7, k + 4, Blocks.stained_glass);
		world.setBlock(i + 5, j + 7, k + 5, Blocks.stained_glass);
		world.setBlock(i + 5, j + 7, k + 6, Blocks.stained_glass);
		world.setBlock(i + 5, j + 7, k + 7, Blockizer.LunarBricks);
		world.setBlock(i + 5, j + 7, k + 8, Blockizer.LunarBricks);
		world.setBlock(i + 5, j + 7, k + 9, Blockizer.WhiteWashBricks);
		world.setBlock(i + 6, j + 3, k + 1, Blockizer.WhiteWashBricks);
		world.setBlock(i + 6, j + 3, k + 2, Blockizer.LunarBricks);
		world.setBlock(i + 6, j + 3, k + 3, Blockizer.LunarBricks);
		world.setBlock(i + 6, j + 3, k + 4, Blocks.stained_glass);
		world.setBlock(i + 6, j + 3, k + 5, Blocks.stained_glass);
		world.setBlock(i + 6, j + 3, k + 6, Blocks.stained_glass);
		world.setBlock(i + 6, j + 3, k + 7, Blockizer.LunarBricks);
		world.setBlock(i + 6, j + 3, k + 8, Blockizer.LunarBricks);
		world.setBlock(i + 6, j + 3, k + 9, Blockizer.WhiteWashBricks);
		if (!world.isRemote) {
			final EntityZalCitizen var2 = new EntityZalCitizen(world);
			var2.setLocationAndAngles((double)(i + 6), (double)(j + 5), (double)(k + 3), rand.nextFloat() * 360.0f, 0.0f);
			world.spawnEntityInWorld(var2);
		}
		world.setBlock(i + 6, j + 7, k + 1, Blockizer.WhiteWashBricks);
		world.setBlock(i + 6, j + 7, k + 2, Blockizer.LunarBricks);
		world.setBlock(i + 6, j + 7, k + 3, Blockizer.LunarBricks);
		world.setBlock(i + 6, j + 7, k + 4, Blocks.stained_glass);
		world.setBlock(i + 6, j + 7, k + 5, Blocks.stained_glass);
		world.setBlock(i + 6, j + 7, k + 6, Blocks.stained_glass);
		world.setBlock(i + 6, j + 7, k + 7, Blockizer.LunarBricks);
		world.setBlock(i + 6, j + 7, k + 8, Blockizer.LunarBricks);
		world.setBlock(i + 6, j + 7, k + 9, Blockizer.WhiteWashBricks);
		world.setBlock(i + 7, j + 3, k + 1, Blockizer.WhiteWashBricks);
		world.setBlock(i + 7, j + 3, k + 2, Blockizer.LunarBricks);
		world.setBlock(i + 7, j + 3, k + 3, Blockizer.LunarBricks);
		world.setBlock(i + 7, j + 3, k + 4, Blockizer.LunarBricks);
		world.setBlock(i + 7, j + 3, k + 5, Blockizer.LunarBricks);
		world.setBlock(i + 7, j + 3, k + 6, Blockizer.LunarBricks);
		world.setBlock(i + 7, j + 3, k + 7, Blockizer.LunarBricks);
		world.setBlock(i + 7, j + 3, k + 8, Blockizer.LunarBricks);
		world.setBlock(i + 7, j + 3, k + 9, Blockizer.WhiteWashBricks);
		world.setBlock(i + 7, j + 7, k + 1, Blockizer.WhiteWashBricks);
		world.setBlock(i + 7, j + 7, k + 2, Blockizer.LunarBricks);
		world.setBlock(i + 7, j + 7, k + 3, Blockizer.LunarBricks);
		world.setBlock(i + 7, j + 7, k + 4, Blockizer.LunarBricks);
		world.setBlock(i + 7, j + 7, k + 5, Blockizer.LunarBricks);
		world.setBlock(i + 7, j + 7, k + 6, Blockizer.LunarBricks);
		world.setBlock(i + 7, j + 7, k + 7, Blockizer.LunarBricks);
		world.setBlock(i + 7, j + 7, k + 8, Blockizer.LunarBricks);
		world.setBlock(i + 7, j + 7, k + 9, Blockizer.WhiteWashBricks);
		world.setBlock(i + 8, j + 3, k + 1, Blockizer.WhiteWashBricks);
		world.setBlock(i + 8, j + 3, k + 2, Blockizer.LunarBricks);
		world.setBlock(i + 8, j + 3, k + 3, Blockizer.LunarBricks);
		world.setBlock(i + 8, j + 3, k + 4, Blockizer.LunarBricks);
		world.setBlock(i + 8, j + 3, k + 5, Blockizer.LunarBricks);
		world.setBlock(i + 8, j + 3, k + 6, Blockizer.LunarBricks);
		world.setBlock(i + 8, j + 3, k + 7, Blockizer.LunarBricks);
		world.setBlock(i + 8, j + 3, k + 8, Blockizer.LunarBricks);
		world.setBlock(i + 8, j + 3, k + 9, Blockizer.WhiteWashBricks);
		world.setBlock(i + 8, j + 7, k + 1, Blockizer.WhiteWashBricks);
		world.setBlock(i + 8, j + 7, k + 2, Blockizer.LunarBricks);
		world.setBlock(i + 8, j + 7, k + 3, Blockizer.LunarBricks);
		world.setBlock(i + 8, j + 7, k + 4, Blockizer.LunarBricks);
		world.setBlock(i + 8, j + 7, k + 5, Blockizer.LunarBricks);
		world.setBlock(i + 8, j + 7, k + 6, Blockizer.LunarBricks);
		world.setBlock(i + 8, j + 7, k + 7, Blockizer.LunarBricks);
		world.setBlock(i + 8, j + 7, k + 8, Blockizer.LunarBricks);
		world.setBlock(i + 8, j + 7, k + 9, Blockizer.WhiteWashBricks);
		world.setBlock(i + 9, j + 3, k + 0, Blockizer.LunarBricks);
		world.setBlock(i + 9, j + 3, k + 1, Blockizer.WhiteWashBricks);
		world.setBlock(i + 9, j + 3, k + 2, Blockizer.WhiteWashBricks);
		world.setBlock(i + 9, j + 3, k + 3, Blockizer.WhiteWashBricks);
		world.setBlock(i + 9, j + 3, k + 4, Blockizer.WhiteWashBricks);
		world.setBlock(i + 9, j + 3, k + 5, Blockizer.WhiteWashBricks);
		world.setBlock(i + 9, j + 3, k + 6, Blockizer.WhiteWashBricks);
		world.setBlock(i + 9, j + 3, k + 7, Blockizer.WhiteWashBricks);
		world.setBlock(i + 9, j + 3, k + 8, Blockizer.WhiteWashBricks);
		world.setBlock(i + 9, j + 3, k + 9, Blockizer.WhiteWashBricks);
		world.setBlock(i + 9, j + 3, k + 10, Blockizer.LunarBricks);
		world.setBlock(i + 9, j + 4, k + 0, Blockizer.LunarBricks);
		world.setBlock(i + 9, j + 4, k + 10, Blockizer.LunarBricks);
		world.setBlock(i + 9, j + 5, k + 0, Blockizer.LunarBricks);
		world.setBlock(i + 9, j + 5, k + 10, Blockizer.LunarBricks);
		world.setBlock(i + 9, j + 6, k + 0, Blockizer.LunarBricks);
		world.setBlock(i + 9, j + 6, k + 1, Blockizer.LampLunar);
		world.setBlock(i + 9, j + 6, k + 9, Blockizer.LampLunar);
		world.setBlock(i + 9, j + 6, k + 10, Blockizer.LunarBricks);
		world.setBlock(i + 9, j + 7, k + 0, Blockizer.LunarBricks);
		world.setBlock(i + 9, j + 7, k + 1, Blockizer.WhiteWashBricks);
		world.setBlock(i + 9, j + 7, k + 2, Blockizer.WhiteWashBricks);
		world.setBlock(i + 9, j + 7, k + 3, Blockizer.WhiteWashBricks);
		world.setBlock(i + 9, j + 7, k + 4, Blockizer.WhiteWashBricks);
		world.setBlock(i + 9, j + 7, k + 5, Blockizer.WhiteWashBricks);
		world.setBlock(i + 9, j + 7, k + 6, Blockizer.WhiteWashBricks);
		world.setBlock(i + 9, j + 7, k + 7, Blockizer.WhiteWashBricks);
		world.setBlock(i + 9, j + 7, k + 8, Blockizer.WhiteWashBricks);
		world.setBlock(i + 9, j + 7, k + 9, Blockizer.WhiteWashBricks);
		world.setBlock(i + 9, j + 7, k + 10, Blockizer.LunarBricks);
		world.setBlock(i + 10, j + 0, k + 0, Blockizer.LunarPillar);
		world.setBlock(i + 10, j + 0, k + 10, Blockizer.LunarPillar);
		world.setBlock(i + 10, j + 1, k + 0, Blockizer.LunarPillar);
		world.setBlock(i + 10, j + 1, k + 10, Blockizer.LunarPillar);
		world.setBlock(i + 10, j + 2, k + 0, Blockizer.LunarPillar);
		world.setBlock(i + 10, j + 2, k + 10, Blockizer.LunarPillar);
		world.setBlock(i + 10, j + 3, k + 0, Blockizer.LunarPillar);
		world.setBlock(i + 10, j + 3, k + 1, Blockizer.LunarBricks);
		world.setBlock(i + 10, j + 3, k + 9, Blockizer.LunarBricks);
		world.setBlock(i + 10, j + 3, k + 10, Blockizer.LunarPillar);
		world.setBlock(i + 10, j + 4, k + 0, Blockizer.LunarPillar);
		world.setBlock(i + 10, j + 4, k + 1, Blockizer.LunarBricks);
		world.setBlock(i + 10, j + 4, k + 9, Blockizer.LunarBricks);
		world.setBlock(i + 10, j + 4, k + 10, Blockizer.LunarPillar);
		world.setBlock(i + 10, j + 5, k + 0, Blockizer.LunarPillar);
		world.setBlock(i + 10, j + 5, k + 1, Blockizer.LunarBricks);
		world.setBlock(i + 10, j + 5, k + 9, Blockizer.LunarBricks);
		world.setBlock(i + 10, j + 5, k + 10, Blockizer.LunarPillar);
		world.setBlock(i + 10, j + 6, k + 0, Blockizer.LunarPillar);
		world.setBlock(i + 10, j + 6, k + 1, Blockizer.LunarBricks);
		world.setBlock(i + 10, j + 6, k + 9, Blockizer.LunarBricks);
		world.setBlock(i + 10, j + 6, k + 10, Blockizer.LunarPillar);
		world.setBlock(i + 10, j + 7, k + 0, Blockizer.LunarPillar);
		world.setBlock(i + 10, j + 7, k + 1, Blockizer.LunarBricks);
		world.setBlock(i + 10, j + 7, k + 9, Blockizer.LunarBricks);
		world.setBlock(i + 10, j + 7, k + 10, Blockizer.LunarPillar);
		world.setBlock(i + 10, j + 8, k + 0, Blockizer.LunarPillar);
		world.setBlock(i + 10, j + 8, k + 10, Blockizer.LunarPillar);
		world.setBlock(i + 10, j + 9, k + 0, Blockizer.LunarPillar);
		world.setBlock(i + 10, j + 9, k + 10, Blockizer.LunarPillar);
		world.setBlock(i + 10, j + 10, k + 0, Blockizer.LunarPillar);
		world.setBlock(i + 10, j + 10, k + 10, Blockizer.LunarPillar);
		return true;
	}
}
