package net.nevermine.structures.lunalus;

import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenerator;
import net.nevermine.izer.Blockizer;

import java.util.Random;

public class LunarAtom extends WorldGenerator {
	public boolean generate(final World world, final Random rand, final int i, final int j, final int k) {
		world.setBlock(i + 0, j + 5, k + 5, Blockizer.LampLunar);
		world.setBlock(i + 5, j + 5, k + 10, Blockizer.LampLunar);
		world.setBlock(i + 1, j + 0, k + 1, Blockizer.LampLunar);
		world.setBlock(i + 1, j + 0, k + 9, Blockizer.LampLunar);
		world.setBlock(i + 1, j + 1, k + 1, Blockizer.LunarBricks);
		world.setBlock(i + 1, j + 1, k + 9, Blockizer.LunarBricks);
		world.setBlock(i + 1, j + 5, k + 5, Blockizer.LunarBricks);
		world.setBlock(i + 1, j + 9, k + 1, Blockizer.LunarBricks);
		world.setBlock(i + 1, j + 9, k + 9, Blockizer.LunarBricks);
		world.setBlock(i + 1, j + 10, k + 1, Blockizer.LampLunar);
		world.setBlock(i + 1, j + 10, k + 9, Blockizer.LampLunar);
		world.setBlock(i + 2, j + 1, k + 2, Blockizer.LunarBricks);
		world.setBlock(i + 2, j + 1, k + 8, Blockizer.LunarBricks);
		world.setBlock(i + 2, j + 2, k + 2, Blockizer.LunarBricks);
		world.setBlock(i + 2, j + 2, k + 8, Blockizer.LunarBricks);
		world.setBlock(i + 2, j + 5, k + 5, Blockizer.LunarBricks);
		world.setBlock(i + 2, j + 8, k + 2, Blockizer.LunarBricks);
		world.setBlock(i + 2, j + 8, k + 8, Blockizer.LunarBricks);
		world.setBlock(i + 2, j + 9, k + 2, Blockizer.LunarBricks);
		world.setBlock(i + 2, j + 9, k + 8, Blockizer.LunarBricks);
		world.setBlock(i + 3, j + 2, k + 3, Blockizer.LunarBricks);
		world.setBlock(i + 3, j + 2, k + 7, Blockizer.LunarBricks);
		world.setBlock(i + 3, j + 3, k + 3, Blockizer.LunarBricks);
		world.setBlock(i + 3, j + 3, k + 7, Blockizer.LunarBricks);
		world.setBlock(i + 3, j + 5, k + 5, Blockizer.LunarBricks);
		world.setBlock(i + 3, j + 7, k + 3, Blockizer.LunarBricks);
		world.setBlock(i + 3, j + 7, k + 7, Blockizer.LunarBricks);
		world.setBlock(i + 3, j + 8, k + 3, Blockizer.LunarBricks);
		world.setBlock(i + 3, j + 8, k + 7, Blockizer.LunarBricks);
		world.setBlock(i + 4, j + 3, k + 4, Blockizer.LunarBricks);
		world.setBlock(i + 4, j + 3, k + 6, Blockizer.LunarBricks);
		world.setBlock(i + 4, j + 4, k + 4, Blockizer.LunarBricks);
		world.setBlock(i + 4, j + 4, k + 6, Blockizer.LunarBricks);
		world.setBlock(i + 4, j + 5, k + 5, Blockizer.LunarBricks);
		world.setBlock(i + 4, j + 6, k + 4, Blockizer.LunarBricks);
		world.setBlock(i + 4, j + 6, k + 6, Blockizer.LunarBricks);
		world.setBlock(i + 4, j + 7, k + 4, Blockizer.LunarBricks);
		world.setBlock(i + 4, j + 7, k + 6, Blockizer.LunarBricks);
		world.setBlock(i + 5, j + 0, k + 5, Blockizer.LampLunar);
		world.setBlock(i + 5, j + 1, k + 5, Blockizer.LunarBricks);
		world.setBlock(i + 5, j + 2, k + 5, Blockizer.LunarBricks);
		world.setBlock(i + 5, j + 3, k + 5, Blockizer.LunarBricks);
		world.setBlock(i + 5, j + 4, k + 5, Blockizer.LunarBricks);
		world.setBlock(i + 5, j + 5, k + 0, Blockizer.LampLunar);
		world.setBlock(i + 5, j + 5, k + 1, Blockizer.LunarBricks);
		world.setBlock(i + 5, j + 5, k + 2, Blockizer.LunarBricks);
		world.setBlock(i + 5, j + 5, k + 3, Blockizer.LunarBricks);
		world.setBlock(i + 5, j + 5, k + 4, Blockizer.LunarBricks);
		world.setBlock(i + 5, j + 5, k + 5, Blockizer.LunarBricks);
		world.setBlock(i + 5, j + 5, k + 6, Blockizer.LunarBricks);
		world.setBlock(i + 5, j + 5, k + 7, Blockizer.LunarBricks);
		world.setBlock(i + 5, j + 5, k + 8, Blockizer.LunarBricks);
		world.setBlock(i + 5, j + 5, k + 9, Blockizer.LunarBricks);
		world.setBlock(i + 5, j + 6, k + 5, Blockizer.LunarBricks);
		world.setBlock(i + 5, j + 7, k + 5, Blockizer.LunarBricks);
		world.setBlock(i + 5, j + 8, k + 5, Blockizer.LunarBricks);
		world.setBlock(i + 5, j + 9, k + 5, Blockizer.LunarBricks);
		world.setBlock(i + 5, j + 10, k + 5, Blockizer.LampLunar);
		world.setBlock(i + 6, j + 3, k + 4, Blockizer.LunarBricks);
		world.setBlock(i + 6, j + 3, k + 6, Blockizer.LunarBricks);
		world.setBlock(i + 6, j + 4, k + 4, Blockizer.LunarBricks);
		world.setBlock(i + 6, j + 4, k + 6, Blockizer.LunarBricks);
		world.setBlock(i + 6, j + 5, k + 5, Blockizer.LunarBricks);
		world.setBlock(i + 6, j + 6, k + 4, Blockizer.LunarBricks);
		world.setBlock(i + 6, j + 6, k + 6, Blockizer.LunarBricks);
		world.setBlock(i + 6, j + 7, k + 4, Blockizer.LunarBricks);
		world.setBlock(i + 6, j + 7, k + 6, Blockizer.LunarBricks);
		world.setBlock(i + 7, j + 2, k + 3, Blockizer.LunarBricks);
		world.setBlock(i + 7, j + 2, k + 7, Blockizer.LunarBricks);
		world.setBlock(i + 7, j + 3, k + 3, Blockizer.LunarBricks);
		world.setBlock(i + 7, j + 3, k + 7, Blockizer.LunarBricks);
		world.setBlock(i + 7, j + 5, k + 5, Blockizer.LunarBricks);
		world.setBlock(i + 7, j + 7, k + 3, Blockizer.LunarBricks);
		world.setBlock(i + 7, j + 7, k + 7, Blockizer.LunarBricks);
		world.setBlock(i + 7, j + 8, k + 3, Blockizer.LunarBricks);
		world.setBlock(i + 7, j + 8, k + 7, Blockizer.LunarBricks);
		world.setBlock(i + 8, j + 1, k + 2, Blockizer.LunarBricks);
		world.setBlock(i + 8, j + 1, k + 8, Blockizer.LunarBricks);
		world.setBlock(i + 8, j + 2, k + 2, Blockizer.LunarBricks);
		world.setBlock(i + 8, j + 2, k + 8, Blockizer.LunarBricks);
		world.setBlock(i + 8, j + 5, k + 5, Blockizer.LunarBricks);
		world.setBlock(i + 8, j + 8, k + 2, Blockizer.LunarBricks);
		world.setBlock(i + 8, j + 8, k + 8, Blockizer.LunarBricks);
		world.setBlock(i + 8, j + 9, k + 2, Blockizer.LunarBricks);
		world.setBlock(i + 8, j + 9, k + 8, Blockizer.LunarBricks);
		world.setBlock(i + 9, j + 0, k + 1, Blockizer.LampLunar);
		world.setBlock(i + 9, j + 0, k + 9, Blockizer.LampLunar);
		world.setBlock(i + 9, j + 1, k + 1, Blockizer.LunarBricks);
		world.setBlock(i + 9, j + 1, k + 9, Blockizer.LunarBricks);
		world.setBlock(i + 9, j + 5, k + 5, Blockizer.LunarBricks);
		world.setBlock(i + 9, j + 9, k + 1, Blockizer.LunarBricks);
		world.setBlock(i + 9, j + 9, k + 9, Blockizer.LunarBricks);
		world.setBlock(i + 9, j + 10, k + 1, Blockizer.LampLunar);
		world.setBlock(i + 9, j + 10, k + 9, Blockizer.LampLunar);
		world.setBlock(i + 10, j + 5, k + 5, Blockizer.LampLunar);
		return true;
	}
}
