package net.nevermine.izer;

import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraftforge.oredict.OreDictionary;
import net.nevermine.block.decoration.*;
import net.nevermine.block.functional.*;
import net.nevermine.block.generation.*;
import net.nevermine.block.generation.grass.*;
import net.nevermine.block.generation.plant.*;
import net.nevermine.block.generation.structure.*;
import net.nevermine.block.generation.wood.*;
import net.nevermine.dimension.abyss.BlockAbyssPortal;
import net.nevermine.dimension.ancientcavern.BlockAncientCavernPortal;
import net.nevermine.dimension.barathos.BlockBarathosPortal;
import net.nevermine.dimension.candyland.BlockCandylandPortal;
import net.nevermine.dimension.celeve.BlockCelevePortal;
import net.nevermine.dimension.creeponia.BlockCreeponiaPortal;
import net.nevermine.dimension.crystevia.BlockCrysteviaPortal;
import net.nevermine.dimension.deeplands.BlockDeeplandsPortal;
import net.nevermine.dimension.dustopia.BlockDustopiaPortal;
import net.nevermine.dimension.gardencia.BlockGardenciaPortal;
import net.nevermine.dimension.greckon.BlockGreckonPortal;
import net.nevermine.dimension.haven.BlockHavenPortal;
import net.nevermine.dimension.immortallis.BlockImmortallisPortal;
import net.nevermine.dimension.iromine.BlockIrominePortal;
import net.nevermine.dimension.labricon.BlockLabriconPortal;
import net.nevermine.dimension.lborean.BlockBoreanPortal;
import net.nevermine.dimension.lelyetia.BlockLelyetiaPortal;
import net.nevermine.dimension.lunalus.BlockLunalusPortal;
import net.nevermine.dimension.mysterium.BlockMysteriumPortal;
import net.nevermine.dimension.precasia.BlockPrecasiaPortal;
import net.nevermine.dimension.runandor.BlockRunandorPortal;
import net.nevermine.dimension.shyrelands.BlockShyrelandsPortal;
import net.nevermine.dimension.voxponds.BlockVoxpondsPortal;

public class Blockizer {
	private final static String oreDictWood = "logWood";
	private final static String oreDictPlanks = "plankWood";
	private final static String oreDictStairsWood = "stairWood";
	private final static String oreDictLeaves = "treeLeaves";
	private final static String oreDictGlass = "blockGlass";
	private final static String oreDictCobble = "cobblestone";
	private final static String oreDictStone = "stone";
	private final static String oreDictSand = "sand";

	public static Block DkStone = new LightBlocks().setName("darkstone");
	public static Block AbyssGrass = new AbyssGrass(Material.ground).setBlockName("AbyssGrass");
	public static Block AbyssStone = new BlockForagingStone(Material.rock).setName("stoneAbyss");
	public static Block oreBloodstone = new OreBlock().setName("oreBloodstone");
	public static Block LeavesShadow = new Leaves().setName("leavesShadow");
	public static Block LeavesBlood = new Leaves().setName("leavesBlood");
	public static Block WoodShadow = new WoodShadow(Material.wood).setBlockName("WoodShadow");
	public static Block WoodBlood = new WoodBlood(Material.wood).setBlockName("WoodBlood");
	public static Block abyssPortal = new BlockAbyssPortal();
	public static Block havenPortal = new BlockHavenPortal();
	public static Block precasiaPortal = new BlockPrecasiaPortal();
	public static Block mysteriumPortal = new BlockMysteriumPortal();
	public static Block blockAcid = new BlockAcid().setBlockName("acidBlock").setBlockTextureName("nevermine:slugAcid");
	public static Block Crate = new BasicDecoration(Material.wood).setName("crate");
	public static Block Crystallanium = new Crystallanium(Material.glass).setBlockName("Crystallanium").setBlockTextureName("nevermine:crystallanium");
	public static Block Emberium = new Emberium(Material.rock).setBlockName("Emberium").setBlockTextureName("nevermine:emberium");
	public static Block DirtHaven = new GeneratedBlock(Material.ground).setName("dirtHaven").setStepSound(new Block.SoundType("gravel", 1.0f, 1.0f));
	public static Block GrassHaven = new GrassHaven(Material.ground).setBlockName("GrassHaven");
	public static Block GrassPrecasia = new GrassPrecasia(Material.rock).setBlockName("GrassPrecasia");
	public static Block GuardianAltar = new GuardianAltar(Material.rock).setBlockName("GuardianAltar");
	public static Block HavenLeavesBlue = new Leaves().setName("leavesHavenBlue");
	public static Block HavenLeavesYellow = new Leaves().setName("leavesHavenYellow");
	public static Block HavenLeavesPink = new Leaves().setName("leavesHavenPink");
	public static Block HavenLeavesRed = new Leaves().setName("leavesHavenRed");
	public static Block HavenLeavesPurple = new Leaves().setName("leavesHavenPurple");
	public static Block HavenLeavesTurq = new Leaves().setName("leavesHavenTurq");
	public static Block LeavesLucalus = new Leaves().setName("leavesLucalus");
	public static Block LeavesCycade = new Leaves().setName("leavesCycade");
	public static Block LeavesStranglewood = new Leaves().setName("leavesStranglewood");
	public static Block oreAmethyst = new OreBlock().setName("oreAmethyst");
	public static Block oreChestboneFragment = new OreBlock().setName("oreChestFragments");
	public static Block oreCrystallite = new OreBlock().setName("oreCrystallite");
	public static Block oreEmberstone = new OreBlock().setName("oreEmberstone");
	public static Block oreFootFragment = new OreBlock().setName("oreFootFragments");
	public static Block oreJade = new OreBlock().setName("oreJade");
	public static Block oreLegFragment = new OreBlock().setName("oreLegFragments");
	public static Block oreLimonite = new OreBlock().setName("oreLimonite");
	public static Block oreRosite = new OreBlock().setName("oreRosite");
	public static Block oreSapphire = new OreBlock().setName("oreSapphire");
	public static Block oreSkullFragment = new OreBlock().setName("oreSkullFragments");
	public static Block planksBloodwood = new BasicDecoration(Material.wood).setName("planksBloodwood");
	public static Block planksCycade = new BasicDecoration(Material.wood).setName("planksCycade");
	public static Block planksLucalus = new BasicDecoration(Material.wood).setName("planksLucalus");
	public static Block planksShadow = new BasicDecoration(Material.wood).setName("planksShadow");
	public static Block planksStranglewood = new BasicDecoration(Material.wood).setName("planksStranglewood");
	public static Block RockriderShrine = new RockriderShrine(Material.rock).setBlockName("RockriderShrine");
	public static Block ShadowAltar = new ShadowAltar(Material.rock).setBlockName("ShadowAltar");
	public static Block SpawnerAmphibiyte = new BlockSpawner("nevermine.Amphibiyte").setName("spawnerAmphibiyte");
	public static Block SpawnerNethengeic = new BlockSpawner("nevermine.NethengeicBeast").setName("spawnerNethengeic");
	public static Block SpawnerFleshEater = new BlockSpawner("nevermine.FleshEater").setName("spawnerFlesh");
	public static Block SpawnerHavenSeeker = new BlockSpawner("nevermine.Seeker").setName("spawnerHaven");
	public static Block SpawnerHavenSurveyor = new BlockSpawner("nevermine.Surveyor").setName("spawnerHaven2");
	public static Block SpawnerHavenVolar = new BlockSpawner("nevermine.Volar").setName("spawnerHaven3");
	public static Block SpawnerPrecasianIosaur = new BlockSpawner("nevermine.Iosaur").setName("spawnerPrecasian");
	public static Block SpawnerPrecasianSpinoledon = new BlockSpawner("nevermine.Spinoledon").setName("spawnerPrecasian2");
	public static Block SpawnerPrecasianDiocus = new BlockSpawner("nevermine.Diocus").setName("spawnerPrecasian3");
	public static Block SpawnerHauntedBanshee = new BlockSpawner("nevermine.Banshee").setName("spawnerHaunted1");
	public static Block SpawnerHauntedPhantom = new BlockSpawner("nevermine.Phantom").setName("spawnerHaunted2");
	public static Block SpawnerHauntedNightmareSpider = new BlockSpawner("nevermine.NightmareSpider").setName("spawnerHaunted3");
	public static Block SpawnerHauntedUndeadTroll = new BlockSpawner("nevermine.UndeadTroll").setName("spawnerHaunted4");
	public static Block SpawnerRunic = new BlockSpawner("nevermine.RunicGolem").setName("spawnerRunic");
	public static Block SpawnerKaiyu = new BlockSpawner("nevermine.Kaiyu").setName("spawnerKaiyu");
	public static Block StonePrecasianHigh = new BlockForagingStone(Material.rock).setName("stonePrecasiaHigh").setBlockTextureName("nevermine:stonePrecasiaHigh");
	public static Block StonePrecasianLow = new BlockForagingStone(Material.rock).setName("stonePrecasiaLow").setBlockTextureName("nevermine:stonePrecasiaLow");
	public static Block StoneHaven = new BlockForagingStone(Material.rock).setName("stoneHaven");
	public static Block TwinkleStone = new LightBlocks().setName("twinklestone");
	public static Block WhiteWashTable = new WhitewashingTable(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("WhiteWashTable");
	public static Block WoodLucalus = new WoodLucalus(Material.wood).setBlockName("WoodLucalus");
	public static Block WoodCycade = new WoodCycade(Material.wood).setBlockName("WoodCycade");
	public static Block WoodStranglewood = new WoodStranglewood(Material.wood).setBlockName("WoodStranglewood");
	public static Block SkeletalBlock = new BasicDecoration(Material.rock).setName("skeletalBlock");
	public static Block Shadonantium = new Shadonantium(Material.rock).setBlockName("Shadonantium").setBlockTextureName("nevermine:shadonantium");
	public static Block Skeletanium = new Skeletanium(Material.rock).setBlockName("Skeletanium").setBlockTextureName("nevermine:skeletanium");
	public static Block ColorBricks0 = new ColouredBricks().setName("brick_0");
	public static Block ColorBricks1 = new ColouredBricks().setName("brick_1");
	public static Block ColorBricks2 = new ColouredBricks().setName("brick_2");
	public static Block ColorBricks3 = new ColouredBricks().setName("brick_3");
	public static Block ColorBricks4 = new ColouredBricks().setName("brick_4");
	public static Block ColorBricks5 = new ColouredBricks().setName("brick_5");
	public static Block ColorBricks6 = new ColouredBricks().setName("brick_6");
	public static Block ColorBricks7 = new ColouredBricks().setName("brick_7");
	public static Block ColorBricks8 = new ColouredBricks().setName("brick_8");
	public static Block ColorBricks9 = new ColouredBricks().setName("brick_9");
	public static Block ColorBricks10 = new ColouredBricks().setName("brick_10");
	public static Block ColorBricks11 = new ColouredBricks().setName("brick_11");
	public static Block ColorBricks12 = new ColouredBricks().setName("brick_12");
	public static Block ColorBricks13 = new ColouredBricks().setName("brick_13");
	public static Block ColorBricks14 = new ColouredBricks().setName("brick_14");
	public static Block ColorBricks15 = new ColouredBricks().setName("brick_15");
	public static Block WhiteWashBricks = new WashBricks().setName("bricksWhitewash");
	public static Block DarkWashBricks = new WashBricks().setName("bricksDarkwash");
	public static Block SkeletalBricks = new WashBricks().setName("bricksSkeletal");
	public static Block CrystalliteBricks = new WashBricks().setName("bricksCrystallite");
	public static Block CoralBricks = new WashBricks().setName("bricksCoral");
	public static Block BloodstoneBricks = new WashBricks().setName("bricksBloodstone");
	public static Block HauntedBricks = new WashBricks().setName("bricksHaunted");
	public static Block IvoryBlock = new IvoryBlocks().setName("ivory");
	public static Block IvoryBlockAmethyst = new IvoryBlocks().setName("ivoryAmethyst");
	public static Block IvoryBlockRosite = new IvoryBlocks().setName("ivoryRosite");
	public static Block IvoryBlockLimonite = new IvoryBlocks().setName("ivoryLimonite");
	public static Block IvoryBlockJade = new IvoryBlocks().setName("ivoryJade");
	public static Block IvoryBlockSapphire = new IvoryBlocks().setName("ivorySapphire");
	public static Block LampAmethyst = new LampBlock().setName("lampAmethyst");
	public static Block LampRosite = new LampBlock().setName("lampRosite");
	public static Block LampLimonite = new LampBlock().setName("lampLimonite");
	public static Block LampJade = new LampBlock().setName("lampJade");
	public static Block LampSapphire = new LampBlock().setName("lampSapphire");
	public static Block LampEmberstone = new LampBlock().setName("lampEmberstone");
	public static Block LampBloodstone = new LampBlock().setName("lampBloodstone");
	public static Block LampCrystallite = new LampBlock().setName("lampCrystallite");
	public static Block LampSkeletal = new LampBlock().setName("lampSkeletal");
	public static Block FireLamp = new LampBlock().setName("animated/FireLamp");
	public static Block RedstoneNeon = new LampBlock().setName("animated/RedstoneNeon");
	public static Block RedstoneNeonCircling = new LampBlock().setName("animated/RedstoneNeonCircling");
	public static Block LapisNeon = new LampBlock().setName("animated/LapisNeon");
	public static Block LapisNeonCircling = new LampBlock().setName("animated/LapisNeonCircling");
	public static Block LapisNeonTriangles = new LampBlock().setName("animated/LapisNeonTriangles");
	public static Block RedstoneNeonTriangles = new LampBlock().setName("animated/RedstoneNeonTriangles");
	public static Block BloodstoneBarBlock = new GeneratedBlock(Material.iron).setName("bloodstoneBarBlock");
	public static Block BloodstoneBarBricks = new GeneratedBlock(Material.iron).setName("bloodstoneBarBricks");
	public static Block BloodSpikes = new BloodSpikes(Material.gourd).setBlockName("BloodSpikes").setBlockTextureName("nevermine:bloodSpikes");
	public static Block BloodStrands = new BloodStrands(Material.gourd).setBlockName("BloodStrands").setBlockTextureName("nevermine:bloodStrands");
	public static Block EyeBlock = new EyeBlock(Material.gourd).setBlockName("EyeBlock");
	public static Block LeavesVein = new Leaves().setName("leavesVein");
	public static Block LeavesShadowblood = new Leaves().setName("leavesShadowblood");
	public static Block WoodEyeball = new WoodEyeball(Material.wood).setBlockName("woodEyeball").setBlockTextureName("nevermine:woodEyeball");
	public static Block TentacleBlock = new TentacleBlocks(Material.gourd, "TentacleBlock").setBlockName("tentacleBlock");
	public static Block IllusionAltar = new IllusionAltar(Material.rock).setBlockName("IllusionAltar");
	public static Block TentacleEyeOrange = new TentacleBlocks(Material.gourd, "TentacleEyeOrange").setBlockName("tentacleEyeOrange");
	public static Block TentacleEyeRed = new TentacleBlocks(Material.gourd, "TentacleEyeRed").setBlockName("tentacleEyeRed");
	public static Block ToxicBlock = new ToxicBlock(Material.sponge).setBlockName("ToxicBlock").setBlockTextureName("nevermine:toxicBlock");
	public static Block MushroomOutsidePurple = new GeneratedBlock(Material.gourd).setName("mushroomOutsidePurple");
	public static Block MushroomInsidePurple = new GeneratedBlock(Material.gourd).setName("mushroomInsidePurple");
	public static Block MushroomOutsideOrange = new GeneratedBlock(Material.gourd).setName("mushroomOutsideOrange");
	public static Block MushroomInsideOrange = new GeneratedBlock(Material.gourd).setName("mushroomInsideOrange");
	public static Block MushroomOutsideGreen = new GeneratedBlock(Material.gourd).setName("mushroomOutsideGreen");
	public static Block MushroomInsideGreen = new GeneratedBlock(Material.gourd).setName("mushroomInsideGreen");
	public static Block MushroomOutsideYellow = new GeneratedBlock(Material.gourd).setName("mushroomOutsideYellow");
	public static Block MushroomInsideYellow = new GeneratedBlock(Material.gourd).setName("mushroomInsideYellow");
	public static Block MushroomOutsideBlue = new GeneratedBlock(Material.gourd).setName("mushroomOutsideBlue");
	public static Block MushroomInsideBlue = new GeneratedBlock(Material.gourd).setName("mushroomInsideBlue");
	public static Block MushroomStemBlue = new BlockMushroomStem(Material.gourd, "Blue").setBlockName("MushroomStemBlue");
	public static Block MushroomStemOrange = new BlockMushroomStem(Material.gourd, "Orange").setBlockName("MushroomStemOrange");
	public static Block MushroomStemGreen = new BlockMushroomStem(Material.gourd, "Green").setBlockName("MushroomStemGreen");
	public static Block MushroomStemYellow = new BlockMushroomStem(Material.gourd, "Yellow").setBlockName("MushroomStemYellow");
	public static Block MushroomStemPurple = new BlockMushroomStem(Material.gourd, "Purple").setBlockName("MushroomStemPurple");
	public static Block oreMystite = new OreBlock().setName("oreMystite");
	public static Block MysteriumBricksBlack = new BasicDecoration(Material.rock).setName("mysteriumBricksBlack");
	public static Block MysteriumBricksGreen = new BasicDecoration(Material.rock).setName("mysteriumBricksGreen");
	public static Block StoneMysterium = new BlockForagingStone(Material.rock).setName("stoneMysterium");
	public static Block DirtMysterium = new GeneratedBlock(Material.ground).setName("dirtMysterium").setStepSound(new Block.SoundType("gravel", 1.0f, 1.0f));
	public static Block LampMystic = new LampBlock().setName("lampMystic");
	public static Block GrassMysterium = new GrassMysterium(Material.ground).setBlockName("GrassMysterium");
	public static Block MysticFerns = new BlockGenMysteriumPlant(Material.grass).setName("mysticFerns");
	public static Block MysticBush = new BlockGenMysteriumPlant(Material.grass).setName("mysticBush");
	public static Block KaiyuTempleFace = new TempleBlock(Material.rock).setName("kaiyuTempleFace");
	public static Block KaiyuTemplePattern1 = new TempleBlock(Material.rock).setName("kaiyuTemplePattern1");
	public static Block KaiyuTemplePattern2 = new TempleBlock(Material.rock).setName("kaiyuTemplePattern2");
	public static Block KaiyuTemplePattern3 = new TempleBlock(Material.rock).setName("kaiyuTemplePattern3");
	public static Block KaiyuTemplePattern4 = new TempleBlock(Material.rock).setName("kaiyuTemplePattern4");
	public static Block KaiyuTemplePattern5 = new TempleBlock(Material.rock).setName("kaiyuTemplePattern5");
	public static Block KaiyuTemplePlain = new TempleBlock(Material.rock).setName("kaiyuTemplePlain");
	public static Block TempleTrapFire = new TempleTrapFire(Material.rock).setBlockTextureName("nevermine:kaiyuTemplePattern3").setBlockName("TempleTrapFire");
	public static Block TempleTrapPoison = new TempleTrapPoison(Material.rock).setBlockTextureName("nevermine:kaiyuTemplePattern4").setBlockName("TempleTrapPoison");
	public static Block TempleTrapWither = new TempleTrapWither(Material.rock).setBlockTextureName("nevermine:kaiyuTemplePattern1").setBlockName("TempleTrapWither");
	public static Block TempleTrapDamage = new TempleTrapDamage(Material.rock).setBlockTextureName("nevermine:kaiyuTemplePattern2").setBlockName("TempleTrapDamage");
	public static Block RunicBlock = new RunicBlock(Material.rock).setBlockTextureName("nevermine:runicBlock").setCreativeTab(Itemizer.TablesTab).setBlockName("RunicBlock");
	public static Block ArmyBlock = new ArmyBlock(Material.rock).setBlockName("ArmyBlock").setCreativeTab(Itemizer.TablesTab).setBlockTextureName("nevermine:armyBlock");
	public static Block IroStone = new BlockForagingStone(Material.rock).setName("stoneIromine");
	public static Block IrobrickStriped = new GeneratedBlock(Material.rock).setName("iroBrick_striped");
	public static Block IrobrickDotted = new GeneratedBlock(Material.rock).setName("iroBrick_dotted");
	public static Block LeavesIrogold = new Leaves().setName("leavesIrogold");
	public static Block LeavesIrodust = new Leaves().setName("leavesIrodust");
	public static Block IroLamp = new LampBlock().setName("iroLamp");
	public static Block IroGrass = new BlockGenIroPlant(Material.grass).setName("iroGrass");
	public static Block OreLyon = new OreBlock().setName("oreLyon");
	public static Block WoodIromine = new WoodIro(Material.wood).setBlockName("WoodIromine");
	public static Block GrassIromine = new GrassIromine(Material.grass).setBlockName("GrassIromine");
	public static Block irominePortal = new BlockIrominePortal();
	public static Block DirtLunalyte = new GeneratedBlock(Material.ground).setName("dirtLunalyte").setStepSound(new Block.SoundType("gravel", 1.0f, 1.0f));
	public static Block DirtLunasole = new GeneratedBlock(Material.ground).setName("dirtLunasole").setStepSound(new Block.SoundType("gravel", 1.0f, 1.0f));
	public static Block GrassLunalyte = new GrassLunalyte(Material.grass).setBlockName("GrassLunalyte");
	public static Block GrassLunasole = new GrassLunasole(Material.grass).setBlockName("GrassLunasole");
	public static Block LeavesLunicia = new Leaves().setName("leavesLunicia");
	public static Block LeavesLunosso = new Leaves().setName("leavesLunosso");
	public static Block WoodLunide = new WoodLunide(Material.wood).setBlockName("WoodLunide");
	public static Block Lunalip = new BlockGenLunarPlant(Material.grass).setName("lunaLip");
	public static Block Luntar = new BlockGenLunarPlant(Material.grass).setName("luntar");
	public static Block lunalusPortal = new BlockLunalusPortal();
	public static Block DeepCrystal = new LampBlock().setName("deepCrystal");
	public static Block DeepRock = new BlockForagingStone(Material.rock).setName("deeplandsRock");
	public static Block Deepcase = new DeepCase(Material.rock).setBlockName("DeepCase").setBlockTextureName("nevermine:oreDeepcase");
	public static Block DirtGardencia = new GeneratedBlock(Material.ground).setName("dirtGardencia").setStepSound(new Block.SoundType("gravel", 1.0f, 1.0f));
	public static Block StoneGardencia = new GeneratedBlock(Material.rock).setName("stoneGardencia");
	public static Block PedalsRose = new GeneratedBlock(Material.gourd).setName("pedalsRose");
	public static Block PedalsLightRose = new GeneratedBlock(Material.gourd).setName("pedalsLightRose");
	public static Block PedalsBlue = new GeneratedBlock(Material.gourd).setName("pedalsBlue");
	public static Block PedalsLightBlue = new GeneratedBlock(Material.gourd).setName("pedalsLightBlue");
	public static Block PedalsPurple = new GeneratedBlock(Material.gourd).setName("pedalsPurple");
	public static Block PedalsLightPurple = new GeneratedBlock(Material.gourd).setName("pedalsLightPurple");
	public static Block PedalsYellow = new GeneratedBlock(Material.gourd).setName("pedalsYellow");
	public static Block FlowerCore = new GeneratedBlock(Material.gourd).setName("flowerCore");
	public static Block PlantStem = new GeneratedBlock(Material.gourd).setName("plantStem");
	public static Block Lylips = new BlockGenericPlant(Material.vine).setName("lylips");
	public static Block Daileers = new BlockGenericPlant(Material.vine).setName("daileers");
	public static Block GardenGrass = new BlockGenericPlant(Material.vine).setTallPlant().setName("gardenGrass");
	public static Block GrassGardencia = new GrassGardencia(Material.grass).setBlockName("GrassGardencia");
	public static Block gardenciaPortal = new BlockGardenciaPortal();
	public static Block DirtGreckon = new GeneratedBlock(Material.ground).setName("dirtGreckon").setStepSound(new Block.SoundType("gravel", 1.0f, 1.0f));
	public static Block StoneGreckon = new BlockForagingStone(Material.rock).setName("stoneGreckon");
	public static Block OreGhastly = new OreBlock().setName("oreGhastly");
	public static Block OreGhoulish = new OreBlock().setName("oreGhoulish");
	public static Block LeavesHaunted = new Leaves().setName("leavesHaunted");
	public static Block HauntedFlower = new BlockGenericPlant(Material.vine).setName("hauntedFlower");
	public static Block WoodHaunted = new WoodHaunted(Material.wood).setBlockName("woodHaunted");
	public static Block GrassGreckon = new GrassGreckon(Material.grass).setBlockName("GrassGreckon");
	public static Block HauntedWoodFlashingFace = new HauntedWoodSpecials(Material.wood, "HauntedWoodFlashingFace").setBlockName("HauntedWoodFlashingFace");
	public static Block HauntedWoodPurpling = new HauntedWoodSpecials(Material.wood, "HauntedWoodPurpling").setBlockName("HauntedWoodPurpling");
	public static Block HauntedWoodRedEyes = new HauntedWoodSpecials(Material.wood, "HauntedWoodRedEyes").setBlockName("HauntedWoodRedEyes");
	public static Block HauntedWoodLargeEye = new HauntedWoodSpecials(Material.wood, "HauntedWoodLargeEye").setBlockName("HauntedWoodLargeEye");
	public static Block HauntedLeavesGhouls = new HauntedEyeLeaves(Material.wood, "HauntedLeavesGhouls").setBlockName("HauntedLeavesGhouls");
	public static Block greckonPortal = new BlockGreckonPortal();
	public static Block DirtDustopia = new GeneratedBlock(Material.ground).setName("dirtDustopia").setStepSound(new Block.SoundType("gravel", 1.0f, 1.0f));
	public static Block StoneDustopia = new BlockForagingStone(Material.rock).setName("stoneDustopia");
	public static Block DawnBush = new BlockGenericPlant(Material.vine).setName("dawnBush");
	public static Block DawnFlower = new BlockGenericPlant(Material.vine).setName("dawnFlower");
	public static Block LeavesDawn = new Leaves().setName("leavesDawn");
	public static Block WoodDawn = new WoodDawn(Material.wood).setBlockName("woodDawn");
	public static Block GrassDustopia = new GrassDustopia(Material.grass).setBlockName("GrassDustopia");
	public static Block DawnGrassTop = new BlockGenericPlant(Material.vine).setName("dawngrassTop");
	public static Block DawnwoodBars = new BlockGenericPlant(Material.wood).setTallPlant().setName("barsDawnwood");
	public static Block DawnwoodPlanks = new GeneratedBlock(Material.wood).setName("planksDawnwood");
	public static Block dustopiaPortal = new BlockDustopiaPortal();
	public static Block LunarCreationTable = new LunarCreationTable(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("LunarCreationTable");
	public static Block LunarPad = new LunarPad(Material.rock).setBlockName("LunarPad");
	public static Block LunarPillar = new LunarPillar(Material.rock).setBlockName("LunarPillar");
	public static Block LunarBricks = new WashBricks().setName("bricksLunar");
	public static Block planksLunide = new BasicDecoration(Material.wood).setName("planksLunide");
	public static Block LunarCarpet = new Carpet(Material.cloth).setName("carpetLunar");
	public static Block LampLunar = new LampBlock().setName("lampLunar");
	public static Block StoneBorean = new GeneratedBlock(Material.rock).setName("stoneBorean");
	public static Block StoneToxic = new BlockForagingStone(Material.rock).setName("stoneToxic");
	public static Block DirtBorean = new GeneratedBlock(Material.ground).setName("dirtBorean").setStepSound(new Block.SoundType("gravel", 1.0f, 1.0f));
	public static Block DirtToxic = new GeneratedBlock(Material.ground).setName("dirtToxic").setStepSound(new Block.SoundType("gravel", 1.0f, 1.0f));
	public static Block CoralPink = new GeneratedBlock(Material.rock).setName("coralPink");
	public static Block CoralGreen = new GeneratedBlock(Material.rock).setName("coralGreen");
	public static Block CoralYellow = new GeneratedBlock(Material.rock).setName("coralYellow");
	public static Block CoralOrange = new GeneratedBlock(Material.rock).setName("coralOrange");
	public static Block CoralWhite = new GeneratedBlock(Material.rock).setName("coralWhite");
	public static Block DegradedSteel = new GeneratedBlock(Material.iron).setName("degradedSteel");
	public static Block SteelLight = new SteelLight(Material.iron, "degradedLight").setCreativeTab(Itemizer.LightingTab).setBlockName("degradedLight");
	public static Block WoodToxic = new WoodToxic(Material.wood).setBlockName("woodToxic");
	public static Block GrassBorean = new GrassBorean(Material.grass).setBlockName("GrassBorean");
	public static Block GrassToxic = new GrassToxic(Material.grass).setBlockName("GrassToxic");
	public static Block ToxicWaste = new ToxicWaste(Material.sponge).setBlockName("ToxicWaste").setBlockTextureName("nevermine:toxicWaste");
	public static Block boreanPortal = new BlockBoreanPortal();
	public static Block BurealStocks = new BlockGenericPlant(Material.vine).setName("burealStocks");
	public static Block voxpondsPortal = new BlockVoxpondsPortal();
	public static Block LampDustopian = new LampBlock().setName("dustopianLampOn");
	public static Block DustopianLampOff = new BaseLampOff(Material.rock).setBlockName("DustopianLampOff").setBlockTextureName("nevermine:dustopianLampOff");
	public static Block PrimordialShrine = new PrimordialShrine(Material.rock).setBlockName("PrimordialShrine");
	public static Block DecayedBrick = new GeneratedBlock(Material.rock).setName("decayedBrick");
	public static Block RunicBrick = new BlockForagingStone(Material.rock).setName("runicBrick");
	public static Block DecayedGlass = new BlockClear().setName("decayedGlass");
	public static Block RunicLeaves = new BlockClear().setName("runicLeaves");
	public static Block WoodRunic = new WoodRunic(Material.wood).setBlockName("woodRunic");
	public static Block GrassRunic = new GrassRunic(Material.grass).setBlockName("GrassRunic");
	public static Block overgrowthPortal = new BlockRunandorPortal();
	public static Block RunicBush = new BlockGenericPlant(Material.vine).setName("runicBush");
	public static Block RuneBulbs = new BlockGenericPlant(Material.vine).setName("runeBulbs");
	public static Block Magias = new BlockGenericPlant(Material.vine).setName("magias");
	public static Block RunicGlass = new BlockClear().setName("runicGlass");
	public static Block RunicConstructBricks = new GeneratedBlock(Material.rock).setName("runicConstructBricks");
	public static Block RunicNeon = new GeneratedBlock(Material.rock).setName("animated/RunicNeon");
	public static Block BaronCarpet = new Carpet(Material.cloth).setName("carpetBaron");
	public static Block BaronBricks = new GeneratedBlock(Material.rock).setName("baronBricks");
	public static Block BaronCube = new GeneratedBlock(Material.rock).setName("baronCube");
	public static Block BaronGround = new GeneratedBlock(Material.rock).setName("baronGround");
	public static Block BaronStone = new BlockForagingStone(Material.rock).setName("baronStone");
	public static Block BaronGlass = new BlockClear().setName("baronGlass");
	public static Block barathosPortal = new BlockBarathosPortal();
	public static Block OreVarsium = new OreBlock().setName("oreVarsium");
	public static Block OreElecanium = new OreBlock().setName("oreElecanium");
	public static Block OreBaronyte = new OreBlock().setName("oreBaronyte");
	public static Block DarkBricks = new GeneratedBlock(Material.rock).setName("darkBricks");
	public static Block GreckonBricks = new GeneratedBlock(Material.rock).setName("greckonBricks");
	public static Block DarkBrickFace = new GeneratedBlock(Material.rock).setName("animated/DarkBrickFace");
	public static Block LunarGlass = new BlockUnbreakableClear().setName("lunarGlass");
	public static Block LunarEnrichmentTable = new LunarEnrichmentTable(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("LunarEnrichmentTable");
	public static Block deeplandsPortal = new BlockDeeplandsPortal();
	public static Block BlackMushroom = new GeneratedBlock(Material.gourd).setName("mushroomBlack");
	public static Block BlackMushroomStem = new GeneratedBlock(Material.gourd).setName("mushroomStemBlack");
	public static Block DeepGrass = new BlockGenericPlant(Material.vine).setName("deepGrass");
	public static Block DeepBlooms = new BlockGenericPlant(Material.vine).setName("deepBlooms");
	public static Block DeeplandsExplosionTrap = new BlockDeeplandsTrap(Material.rock).setName("DeeplandsExplosionTrap").setBlockTextureName("nevermine:deeplandsRock");
	public static Block DeeplandsLavaTrap = new BlockDeeplandsTrap(Material.rock).setName("DeeplandsLavaTrap").setBlockTextureName("nevermine:deeplandsRock");
	public static Block HavenGrass = new BlockGenericPlant(Material.vine).setName("havenGrass");
	public static Block IroGlass = new BlockClear().setName("iroGlass");
	public static Block IroCarpet = new Carpet(Material.cloth).setName("carpetIro");
	public static Block CogBlock = new GeneratedBlock(Material.rock).setName("cogBlock");
	public static Block BarathosHellstone = new BlockForagingStone(Material.rock).setName("barathosHellstone");
	public static Block OreBlazium = new OreBlock().setName("oreBlazium");
	public static Block ToxicStem = new GeneratedBlock(Material.gourd).setName("toxicStem");
	public static Block LampVox = new LampBlock().setName("voxLamp");
	public static Block DeadGrass = new BlockGenericPlant(Material.vine).setName("deadGrass");
	public static Block TangleThorns = new BlockGenericPlant(Material.vine).setName("tangleThorn");
	public static Block LuconGrass = new BlockGenericPlant(Material.vine).setName("luconGrass");
	public static Block RunePostLife = new BlockUnbreakable(Material.rock).setName("runePostLife");
	public static Block RunePostWater = new BlockUnbreakable(Material.rock).setName("runePostWater");
	public static Block RunePostFire = new BlockUnbreakable(Material.rock).setName("runePostFire");
	public static Block RunePostEnergy = new BlockUnbreakable(Material.rock).setName("runePostEnergy");
	public static Block RunePostPoison = new BlockUnbreakable(Material.rock).setName("runePostPoison");
	public static Block RunePostWither = new BlockUnbreakable(Material.rock).setName("runePostWither");
	public static Block RunePostLunar = new BlockUnbreakable(Material.rock).setName("runePostLunar");
	public static Block RunePostKinetic = new BlockUnbreakable(Material.rock).setName("runePostKinetic");
	public static Block RunePostStorm = new BlockUnbreakable(Material.rock).setName("runePostStorm");
	public static Block RunePostWind = new BlockUnbreakable(Material.rock).setName("runePostWind");
	public static Block RunePostStrike = new BlockUnbreakable(Material.rock).setName("runePostStrike");
	public static Block RunePostPower = new BlockUnbreakable(Material.rock).setName("runePostPower");
	public static Block RunePostDistortion = new BlockUnbreakable(Material.rock).setName("runePostDistortion");
	public static Block RuneShrine = new RuneShrine(Material.rock).setBlockName("runeShrine").setCreativeTab(Itemizer.TablesTab).setBlockTextureName("nevermine:runeShrine");
	public static Block IroBrickUnbreakable = new BlockUnbreakable(Material.rock).setName("iroBrick_unbreakable");
	public static Block UnbreakableStem = new BlockUnbreakable(Material.rock).setName("unbreakableStem");
	public static Block PedalsBlack = new BlockUnbreakable(Material.rock).setName("pedalsBlack");
	public static Block RosidianBricks = new WashBricks().setName("bricksRosidian");
	public static Block GardencianBricks = new WashBricks().setName("bricksGardencian");
	public static Block HiveWall = new GeneratedBlock(Material.rock).setName("hiveWall");
	public static Block BaronCastleWall = new GeneratedBlock(Material.rock).setName("baronCastleWall");
	public static Block GardencianCarpet = new Carpet(Material.cloth).setName("carpetGardencian");
	public static Block BoreanCarpet = new Carpet(Material.cloth).setName("carpetBorean");
	public static Block AquaticGlass = new BlockClear().setName("aquaticGlass");
	public static Block GardencianGlass = new BlockClear().setName("gardencianGlass");
	public static Block VoxGlass = new BlockClear().setName("voxGlass");
	public static Block HavenGlass = new BlockClear().setName("havenGlass");
	public static Block AbyssalGlass = new BlockClear().setName("abyssalGlass");
	public static Block DecloggingTable = new DecloggingTable(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("DecloggingTable");
	public static Block LampAquatic = new LampBlock().setName("lampAquatic");
	public static Block AquaticLampOff = new BaseLampOff(Material.rock).setBlockName("AquaticLampOff").setBlockTextureName("nevermine:lampAquaticOff");
	public static Block CoralCage = new BlockGenericPlant(Material.iron).setTallPlant().setName("coralCage");
	public static Block KrorAltar = new KrorAltar(Material.rock).setBlockName("KrorAltar").setCreativeTab(Itemizer.TablesTab).setBlockTextureName("nevermine:krorAltar");
	public static Block VisualentAltar = new VisualentAltar(Material.rock).setBlockName("VisualentAltar").setCreativeTab(Itemizer.TablesTab).setBlockTextureName("nevermine:visualentAltar");
	public static Block DracyonAltar = new DracyonAltar(Material.rock).setBlockName("DracyonAltar").setCreativeTab(Itemizer.TablesTab).setBlockTextureName("nevermine:dracyonAltar");
	public static Block VinocorneShrine = new VinocorneShrine(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("VinocorneShrine");
	public static Block VoxxulonAltar = new VoxxulonAltar(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("VoxxulonAltar");
	public static Block EnigmaTable = new EnigmaTable(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("EnigmaTable");
	public static Block MineralizationStation = new MineralizationStation(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("MineralizationStation");
	public static Block RuneRandomizer = new RuneRandomizer(Material.rock).setBlockName("RuneRandomizer").setCreativeTab(Itemizer.TablesTab).setBlockTextureName("nevermine:runeRandomizer");
	public static Block RecreationStation = new RecreationStation(Material.rock).setBlockName("RecreationStation").setCreativeTab(Itemizer.TablesTab).setBlockTextureName("nevermine:recreationStation");
	public static Block HiveSpawner = new HiveSpawner(Material.rock).setBlockName("HiveSpawner").setCreativeTab(Itemizer.TablesTab).setBlockTextureName("nevermine:hiveSpawner");
	public static Block HiveLight = new LampBlock().setName("hiveLight").setCreativeTab(Itemizer.LightingTab);
	public static Block IroConfusionTrap = new BlockIroTrap(Material.rock).setBlockTextureName("nevermine:iroBrick_dotted").setBlockName("BlockIroTrap");
	public static Block OrbSunfire = new GeneratedBlock(Material.rock).setName("orbSunfire");
	public static Block OrbMoonlight = new GeneratedBlock(Material.rock).setName("orbMoonlight");
	public static Block OrbDusk = new GeneratedBlock(Material.rock).setName("orbDusk");
	public static Block OrbDarklight = new GeneratedBlock(Material.rock).setName("orbDarklight");
	public static Block OrbLunar = new GeneratedBlock(Material.rock).setName("orbLunar");
	public static Block ClunkheadAltar = new ClunkheadAltar(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("ClunkheadAltar");
	public static Block SilverfootAltar = new SilverfootAltar(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("SilverfootAltar");
	public static Block SpawnerMermage = new BlockSpawner("nevermine.Mermage").setName("spawnerMermage");
	public static Block SpawnerAmphibior = new BlockSpawner("nevermine.Amphibior").setName("spawnerAmphibior");
	public static Block SpawnerDawnlight = new BlockSpawner("nevermine.Dawnlight").setName("spawnerDawnlight");
	public static Block SpawnerEnforcer = new BlockSpawner("nevermine.Enforcer").setName("spawnerEnforcer");
	public static Block SpawnerMechyon = new BlockSpawner("nevermine.Mechyon").setName("spawnerMechyon");
	public static Block SpawnerInmateX = new BlockSpawner("nevermine.InmateX").setName("spawnerInmateX");
	public static Block SpawnerInmateY = new BlockSpawner("nevermine.InmateY").setName("spawnerInmateY");
	public static Block SpawnerPodPlant = new BlockSpawner("nevermine.PodPlant").setName("spawnerPodPlant");
	public static Block SpawnerRunicGuardian = new BlockSpawner("nevermine.RunicGuardian").setName("spawnerRunicGuardian");
	public static Block SpawnerMerkyre = new BlockSpawner("nevermine.Merkyre").setName("spawnerMerkyre");
	public static Block SpawnerSpectralWizard = new BlockSpawner("nevermine.SpectralWizard").setName("spawnerSpectralWizard");
	public static Block SpawnerVineWizard = new BlockSpawner("nevermine.VineWizard").setName("spawnerVineWizard");
	public static Block SpawnerTharafly = new BlockSpawner("nevermine.Tharafly").setName("spawnerTharafly");
	public static Block VoxCrate = new VoxCrate(Material.rock).setBlockName("VoxCrate").setBlockTextureName("nevermine:voxCrate");
	public static Block VoxCrateStore = new VoxCrateStore(Material.rock).setBlockName("VoxCrateStore").setBlockTextureName("nevermine:voxCrate");
	public static Block PedalCraftingStation = new PedalCraftingStation(Material.rock).setBlockName("PedalCraftingStation").setBlockTextureName("nevermine:pedalCraftingStation");
	public static Block HauntingTable = new HauntingTable(Material.rock).setBlockName("HauntingTable").setBlockTextureName("nevermine:hauntingTable");
	public static Block IroCrate = new IroCrate(Material.rock).setBlockName("IroCrate").setBlockTextureName("nevermine:iroCrate");
	public static Block DeeplandsNipperTrap = new BlockDeeplandsTrap(Material.rock).setName("DeeplandsNipperTrap").setBlockTextureName("nevermine:deeplandsRock");
	public static Block oreRunium = new OreBlock().setName("oreRunium");
	public static Block oreRuniumCharged = new OreBlock().setName("oreChargedRunium");
	public static Block RunicBrickU = new BlockUnbreakable(Material.rock).setName("runicBrickU");
	public static Block RunicGlassU = new BlockUnbreakableClear().setName("runicGlassU");
	public static Block LabBrick = new BlockUnbreakable(Material.rock).setName("labBrick");
	public static Block LabWalls = new BlockUnbreakable(Material.rock).setName("labWalls");
	public static Block LabBrickGreen = new BlockUnbreakable(Material.rock).setName("labBrickGreen");
	public static Block LabGlassBasic = new BlockUnbreakableClear().setName("labGlassBasic");
	public static Block LabGlassSquares = new BlockUnbreakableClear().setName("labGlassSquares");
	public static Block LabLampDonut = new UnbreakableLamp(Material.rock).setName("labLampDonut");
	public static Block LeavesEternal = new Leaves().setName("leavesEternal");
	public static Block LabPost = new LabPost(Material.rock).setBlockName("labPost");
	public static Block WoodEternal = new WoodEternal(Material.wood).setBlockName("woodEternal");
	public static Block SpawnerFacelessFloater = new BlockSpawner("nevermine.FacelessFloater").setName("spawnerFacelessFloater");
	public static Block ExoidStation = new ExoidStation(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("ExoidStation").setBlockTextureName("nevermine:exoidStation");
	public static Block planksIrowood = new BasicDecoration(Material.wood).setName("planksIrowood");
	public static Block planksHauntedwood = new BasicDecoration(Material.wood).setName("planksHauntedwood");
	public static Block planksRunic = new BasicDecoration(Material.wood).setName("planksRunic");
	public static Block planksToxicwood = new BasicDecoration(Material.wood).setName("planksToxicwood");
	public static Block LeveledBrick = new BlockUnbreakable(Material.rock).setName("leveledBrick");
	public static Block LeveledBrickBrown = new BlockUnbreakable(Material.rock).setName("leveledBrickBrown");
	public static Block LeveledWalls = new BlockUnbreakable(Material.rock).setName("leveledWalls");
	public static Block DarkinBrick = new BlockUnbreakable(Material.rock).setName("darkinBrick");
	public static Block DarkinBrickRed = new BlockUnbreakable(Material.rock).setName("darkinBrickRed");
	public static Block DarkinWalls = new BlockUnbreakable(Material.rock).setName("darkinWalls");
	public static Block Irotops = new BlockGenIroPlant(Material.grass).setName("irotops");
	public static Block Lurchians = new BlockGenIroPlant(Material.grass).setName("lurchians");
	public static Block SpawnerNightwing = new BlockSpawner("nevermine.Nightwing").setName("spawnerNightwing");
	public static Block labriconPortal = new BlockLabriconPortal();
	public static Block LeavesChurry = new Leaves().setName("leavesChurry");
	public static Block LeavesAchony = new Leaves().setName("leavesAchony");
	public static Block LelyetianCore = new Leaves().setName("lelyetianCore");
	public static Block StoneLelyetia = new GeneratedBlock(Material.rock).setName("stoneLelyetia");
	public static Block LelyetianGrassDown = new BlockGenericPlant(Material.vine).setDown().setName("lelyetianGrassDown");
	public static Block LelyetianGrassUp = new BlockGenericPlant(Material.vine).setName("lelyetianGrassUp");
	public static Block WoodAchony = new WoodAchony(Material.wood).setBlockName("woodAchony");
	public static Block WoodChurry = new WoodChurry(Material.wood).setBlockName("woodChurry");
	public static Block GrassLelyetiaUp = new GrassLelyetiaUp(Material.grass).setBlockName("GrassLelyetiaUp");
	public static Block GrassLelyetiaDown = new GrassLelyetiaDown(Material.grass).setBlockName("GrassLelyetiaDown");
	public static Block lelyetiaPortal = new BlockLelyetiaPortal();
	public static Block AncientRock = new GeneratedBlock(Material.rock).setName("ancientRock");
	public static Block CarvedRune1 = new CarvedRunicBlockBase(Material.iron, "carvedRune1").setCreativeTab(Itemizer.GenerationTab).setBlockName("carvedRune1");
	public static Block CarvedRune2 = new CarvedRunicBlockBase(Material.iron, "carvedRune2").setCreativeTab(Itemizer.GenerationTab).setBlockName("carvedRune2");
	public static Block CarvedRune3 = new CarvedRunicBlockBase(Material.iron, "carvedRune3").setCreativeTab(Itemizer.GenerationTab).setBlockName("carvedRune3");
	public static Block CarvedRune6 = new CarvedRunicBlockBase(Material.iron, "carvedRune6").setCreativeTab(Itemizer.GenerationTab).setBlockName("carvedRune6");
	public static Block CarvedRune4 = new CarvedRunicBlock(Material.iron, "carvedRune4").setCreativeTab(Itemizer.GenerationTab).setBlockName("carvedRune4");
	public static Block AncientTileRed = new BlockUnbreakable(Material.rock).setName("ancientTileRed");
	public static Block AncientTileBright = new BlockUnbreakable(Material.rock).setName("ancientTileBright");
	public static Block AncientTileBlack = new BlockUnbreakable(Material.rock).setName("ancientTileBlack");
	public static Block AncientTileCore = new BlockUnbreakable(Material.rock).setName("ancientTileCore");
	public static Block AncientTileShrine = new BlockUnbreakable(Material.rock).setName("ancientTileShrine");
	public static Block AncientGlass = new BlockUnbreakableClear().setName("ancientGlass");
	public static Block AncientLamp = new UnbreakableLamp(Material.rock).setName("lampAncient");
	public static Block AncientVines = new BlockGenericPlant(Material.vine).setTallPlant().setStonePlant().setDown().setName("ancientVines");
	public static Block AncientVineCap = new BlockGenericPlant(Material.vine).setTallPlant().setChildPlant(AncientVines).setStonePlant().setDown().setName("ancientVineCap");
	public static Block ancientcavernPortal = new BlockAncientCavernPortal();
	public static Block blockOrangeAcid = new BlockOrangeAcid().setBlockName("blockOrangeAcid").setBlockTextureName("nevermine:skyAcid");
	public static Block SpawnerExohead = new BlockSpawner("nevermine.Exohead").setName("spawnerExohead");
	public static Block SpawnerRawbone = new BlockSpawner("nevermine.Rawbone").setName("spawnerRawbone");
	public static Block SpawnerParavite = new BlockSpawner("nevermine.Paravite").setName("spawnerParavite");
	public static Block SpawnerZhinx = new BlockSpawner("nevermine.Zhinx").setName("spawnerZhinx");
	public static Block SpawnerBloodsucker = new BlockSpawner("nevermine.Bloodsucker").setName("spawnerBloodsucker");
	public static Block SpawnerAutomaton = new BlockSpawner("nevermine.Automaton").setName("spawnerAutomaton");
	public static Block SpawnerCaveBug = new BlockSpawner("nevermine.RockCritter").setName("spawnerCaveBug");
	public static Block SpawnerFlowerface = new BlockSpawner("nevermine.FlowerFace").setName("spawnerFlowerface");
	public static Block BricksLelyetia = new GeneratedBlock(Material.rock).setName("bricksLelyetian");
	public static Block BoneyBlock = new BlockClear().setName("boneyBlock");
	public static Block ZhinxGlass = new BlockClear().setName("zhinxGlass");
	public static Block LelyetianGlass = new BlockClear().setName("lelyetianGlass");
	public static Block SelyanShrine = new CavernShrine(Material.rock).setBlockName("SelyanShrine").setBlockTextureName("nevermine:selyanShrine");
	public static Block LuxonShrine = new CavernShrine(Material.rock).setBlockName("LuxonShrine").setBlockTextureName("nevermine:luxonShrine");
	public static Block ErebonShrine = new CavernShrine(Material.rock).setBlockName("ErebonShrine").setBlockTextureName("nevermine:erebonShrine");
	public static Block PlutonShrine = new CavernShrine(Material.rock).setBlockName("PlutonShrine").setBlockTextureName("nevermine:plutonShrine");
	public static Block ParaviteHive = new GeneratedBlock(Material.gourd).setName("paraviteHive");
	public static Block CreationForge = new CreationForge(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("CreationForge");
	public static Block InfusionTable = new InfusionTable(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("InfusionTable");
	public static Block AscensionShrine = new AscensionShrine(Material.rock).setBlockName("AscensionShrine").setBlockTextureName("nevermine:ascensionShrine");
	public static Block GrawAltar = new GrawAltar(Material.rock).setBlockName("GrawAltar").setBlockTextureName("nevermine:grawAltar");
	public static Block SpikeyPillar = new SpikeyPillar(Material.rock).setBlockName("SpikeyPillar");
	public static Block LelyetianStem = new BlockGenericPlant(Material.vine).setTallPlant().isBidirectional().setName("lelyetianStem");
	public static Block LelyetianStemCapUp = new BlockGenericPlant(Material.vine).setTallPlant().setChildPlant(LelyetianStem).setName("lelyetianStemCapUp");
	public static Block LelyetianStemCapDown = new BlockGenericPlant(Material.vine).setTallPlant().setChildPlant(LelyetianStem).setDown().setName("lelyetianStemCapDown");
	public static Block LelyetianWiggler = new BlockGenericPlant(Material.vine).setTallPlant().isBidirectional().setName("lelyetianWiggler");
	public static Block LelyetianWigglerTop = new BlockGenericPlant(Material.vine).setTallPlant().setChildPlant(LelyetianWiggler).setName("lelyetianWigglerTop");
	public static Block LelyetianWigglerBottom = new BlockGenericPlant(Material.vine).setTallPlant().setChildPlant(LelyetianWiggler).setDown().setName("lelyetianWigglerBottom");
	public static Block Tubeicles = new BlockGenericPlant(Material.vine).setName("tubeicles");
	public static Block EyeShrubStem = new BlockGenericPlant(Material.vine).setTallPlant().setName("eyeShrubStem");
	public static Block BloodPineStem = new BlockGenericPlant(Material.vine).setTallPlant().setName("bloodPineStem");
	public static Block BloodPine = new BlockGenericPlant(Material.vine).setTallPlant().setChildPlant(BloodPineStem).setName("bloodPine");
	public static Block EyeShrub = new BlockGenericPlant(Material.vine).setTallPlant().setChildPlant(EyeShrubStem).setName("eyeShrub");
	public static Block SpawnerJawe = new BlockSpawner("nevermine.Jawe").setName("spawnerJawe");
	public static Block HeatLamp_0 = new HeatLamp().setName("heatLamp_0");
	public static Block HeatLamp_1 = new HeatLamp().setName("heatLamp_1");
	public static Block HeatLamp_2 = new HeatLamp().setName("heatLamp_2");
	public static Block HeatLamp_3 = new HeatLamp().setName("heatLamp_3");
	public static Block HeatLamp_4 = new HeatLamp().setName("heatLamp_4");
	public static Block HeatLamp_5 = new HeatLamp().setName("heatLamp_5");
	public static Block HeatLamp_6 = new HeatLamp().setName("heatLamp_6");
	public static Block HeatLamp_7 = new HeatLamp().setName("heatLamp_7");
	public static Block HeatLamp_8 = new HeatLamp().setName("heatLamp_8");
	public static Block HeatLamp_9 = new HeatLamp().setName("heatLamp_9");
	public static Block HeatLamp_10 = new HeatLamp().setName("heatLamp_10");
	public static Block HeatLamp_11 = new HeatLamp().setName("heatLamp_11");
	public static Block HeatLamp_12 = new HeatLamp().setName("heatLamp_12");
	public static Block HeatLamp_13 = new HeatLamp().setName("heatLamp_13");
	public static Block HeatLamp_14 = new HeatLamp().setName("heatLamp_14");
	public static Block HeatLamp_15 = new HeatLamp().setName("heatLamp_15");
	public static Block DirtCeleve = new GeneratedBlock(Material.ground).setName("dirtCeleve");
	public static Block GrassCeleve = new GrassCeleve(Material.grass).setBlockName("GrassCeleve");
	public static Block celevePortal = new BlockCelevePortal();
	public static Block CelevusRed = new Leaves().setName("celevusRed");
	public static Block CelevusGreen = new Leaves().setName("celevusGreen");
	public static Block CelevusBlue = new Leaves().setName("celevusBlue");
	public static Block CelevusYellow = new Leaves().setName("celevusYellow");
	public static Block CelevusPurple = new Leaves().setName("celevusPurple");
	public static Block CelevusWhite = new Leaves().setName("celevusWhite");
	public static Block CeleveStem = new CeleveStem(Material.gourd).setBlockName("CeleveStem");
	public static Block CeleviansBlue = new BlockGenericPlant(Material.vine).setName("celeviansBlue");
	public static Block CeleviansRed = new BlockGenericPlant(Material.vine).setName("celeviansRed");
	public static Block CeleviansPurple = new BlockGenericPlant(Material.vine).setName("celeviansPurple");
	public static Block CeleviansWhite = new BlockGenericPlant(Material.vine).setName("celeviansWhite");
	public static Block CelebulbsStem = new BlockGenericPlant(Material.vine).setTallPlant().setName("celebulbsStem");
	public static Block CelebulbsTopGreen = new BlockGenericPlant(Material.vine).setTallPlant().setChildPlant(CelebulbsStem).setName("celebulbsTopGreen");
	public static Block CelebulbsTopYellow = new BlockGenericPlant(Material.vine).setTallPlant().setChildPlant(CelebulbsStem).setName("celebulbsTopYellow");
	public static Block CrystalBlue = new BlockCrystal(Material.glass).setName("crystalBlue");
	public static Block CrystalGreen = new BlockCrystal(Material.glass).setName("crystalGreen");
	public static Block CrystalYellow = new BlockCrystal(Material.glass).setName("crystalYellow");
	public static Block CrystalWhite = new BlockCrystal(Material.glass).setName("crystalWhite");
	public static Block CrystalRed = new BlockCrystal(Material.glass).setName("crystalRed");
	public static Block CrystalPurple = new BlockCrystal(Material.glass).setName("crystalPurple");
	public static Block CrysteviaRock = new BlockForagingStone(Material.rock).setName("crysteviaRock");
	public static Block crysteviaPortal = new BlockCrysteviaPortal();
	public static Block oreCrystalPurple = new OreBlock().setName("oreCrystalPurple");
	public static Block oreCrystalBlue = new OreBlock().setName("oreCrystalBlue");
	public static Block oreCrystalGreen = new OreBlock().setName("oreCrystalGreen");
	public static Block oreCrystalYellow = new OreBlock().setName("oreCrystalYellow");
	public static Block oreCrystalRed = new OreBlock().setName("oreCrystalRed");
	public static Block oreCrystalWhite = new OreBlock().setName("oreCrystalWhite");
	public static Block CrystalBlockRed = new BlockClear().setName("crystalBlockRed");
	public static Block CrystalBlockGreen = new BlockClear().setName("crystalBlockGreen");
	public static Block CrystalBlockYellow = new BlockClear().setName("crystalBlockYellow");
	public static Block CrystalBlockBlue = new BlockClear().setName("crystalBlockBlue");
	public static Block CrystalBlockWhite = new BlockClear().setName("crystalBlockWhite");
	public static Block CrystalBlockPurple = new BlockClear().setName("crystalBlockPurple");
	public static Block RunePostCompass = new BlockUnbreakable(Material.rock).setName("runePostCompass");
	public static Block ToyBox = new ToyBox(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("ToyBox");
	public static Block planksChurry = new BasicDecoration(Material.wood).setName("planksChurry");
	public static Block planksAchony = new BasicDecoration(Material.wood).setName("planksAchony");
	public static Block planksBlueshroom = new BasicDecoration(Material.gourd).setName("planksBlueshroom");
	public static Block planksGreenshroom = new BasicDecoration(Material.gourd).setName("planksGreenshroom");
	public static Block planksYellowshroom = new BasicDecoration(Material.gourd).setName("planksYellowshroom");
	public static Block planksOrangeshroom = new BasicDecoration(Material.gourd).setName("planksOrangeshroom");
	public static Block planksPurpleshroom = new BasicDecoration(Material.gourd).setName("planksPurpleshroom");
	public static Block stairsPurpleshroom = new BasicStaircase(Blockizer.planksPurpleshroom).setName("stairsPurpleshroom");
	public static Block stairsGreenshroom = new BasicStaircase(Blockizer.planksGreenshroom).setName("stairsGreenshroom");
	public static Block stairsYellowshroom = new BasicStaircase(Blockizer.planksYellowshroom).setName("stairsYellowshroom");
	public static Block stairsOrangeshroom = new BasicStaircase(Blockizer.planksOrangeshroom).setName("stairsOrangeshroom");
	public static Block stairsBlueshroom = new BasicStaircase(Blockizer.planksBlueshroom).setName("stairsBlueshroom");
	public static Block stairsChurry = new BasicStaircase(Blockizer.planksChurry).setName("stairsChurry");
	public static Block stairsAchony = new BasicStaircase(Blockizer.planksAchony).setName("stairsAchony");
	public static Block stairsToxicwood = new BasicStaircase(Blockizer.planksToxicwood).setName("stairsToxicwood");
	public static Block stairsDawnwood = new BasicStaircase(Blockizer.DawnwoodPlanks).setName("stairsDawnwood");
	public static Block stairsLunide = new BasicStaircase(Blockizer.planksLunide).setName("stairsLunide");
	public static Block stairsIrowood = new BasicStaircase(Blockizer.planksIrowood).setName("stairsIrowood");
	public static Block stairsStranglewood = new BasicStaircase(Blockizer.planksStranglewood).setName("stairsStranglewood");
	public static Block stairsShadow = new BasicStaircase(Blockizer.planksShadow).setName("stairsShadow");
	public static Block stairsLucalus = new BasicStaircase(Blockizer.planksLucalus).setName("stairsLucalus");
	public static Block stairsCycade = new BasicStaircase(Blockizer.planksCycade).setName("stairsCycade");
	public static Block stairsBloodwood = new BasicStaircase(Blockizer.planksBloodwood).setName("stairsBloodwood");
	public static Block stairsRunic = new BasicStaircase(Blockizer.planksRunic).setName("stairsRunic");
	public static Block stairsHauntedwood = new BasicStaircase(Blockizer.planksHauntedwood).setName("stairsHauntedwood");
	public static Block planksEucadon = new BasicDecoration(Material.wood).setName("planksEucadon");
	public static Block planksMelumia = new BasicDecoration(Material.wood).setName("planksMelumia");
	public static Block planksDomiguous = new BasicDecoration(Material.wood).setName("planksDomiguous");
	public static Block planksOpollo = new BasicDecoration(Material.wood).setName("planksOpollo");
	public static Block stairsOpollo = new BasicStaircase(Blockizer.planksOpollo).setName("stairsOpollo");
	public static Block stairsDomiguous = new BasicStaircase(Blockizer.planksDomiguous).setName("stairsDomiguous");
	public static Block stairsMelumia = new BasicStaircase(Blockizer.planksMelumia).setName("stairsMelumia");
	public static Block stairsEucadon = new BasicStaircase(Blockizer.planksEucadon).setName("stairsEucadon");
	public static Block ColorStairs0 = new BasicStaircase(Blockizer.ColorBricks0).setName("sbrick_0");
	public static Block ColorStairs1 = new BasicStaircase(Blockizer.ColorBricks1).setName("sbrick_1");
	public static Block ColorStairs2 = new BasicStaircase(Blockizer.ColorBricks2).setName("sbrick_2");
	public static Block ColorStairs3 = new BasicStaircase(Blockizer.ColorBricks3).setName("sbrick_3");
	public static Block ColorStairs4 = new BasicStaircase(Blockizer.ColorBricks4).setName("sbrick_4");
	public static Block ColorStairs5 = new BasicStaircase(Blockizer.ColorBricks5).setName("sbrick_5");
	public static Block ColorStairs6 = new BasicStaircase(Blockizer.ColorBricks6).setName("sbrick_6");
	public static Block ColorStairs7 = new BasicStaircase(Blockizer.ColorBricks7).setName("sbrick_7");
	public static Block ColorStairs8 = new BasicStaircase(Blockizer.ColorBricks8).setName("sbrick_8");
	public static Block ColorStairs9 = new BasicStaircase(Blockizer.ColorBricks9).setName("sbrick_9");
	public static Block ColorStairs10 = new BasicStaircase(Blockizer.ColorBricks10).setName("sbrick_10");
	public static Block ColorStairs11 = new BasicStaircase(Blockizer.ColorBricks11).setName("sbrick_11");
	public static Block ColorStairs12 = new BasicStaircase(Blockizer.ColorBricks12).setName("sbrick_12");
	public static Block ColorStairs13 = new BasicStaircase(Blockizer.ColorBricks13).setName("sbrick_13");
	public static Block ColorStairs14 = new BasicStaircase(Blockizer.ColorBricks14).setName("sbrick_14");
	public static Block ColorStairs15 = new BasicStaircase(Blockizer.ColorBricks15).setName("sbrick_15");
	public static Block IvoryStairs = new BasicStaircase(Blockizer.IvoryBlock).setName("ivoryStairs");
	public static Block IvoryStairsAmethyst = new BasicStaircase(Blockizer.IvoryBlockAmethyst).setName("ivoryAmethystStairs");
	public static Block IvoryStairsRosite = new BasicStaircase(Blockizer.IvoryBlockRosite).setName("ivoryRositeStairs");
	public static Block IvoryStairsLimonite = new BasicStaircase(Blockizer.IvoryBlockLimonite).setName("ivoryLimoniteStairs");
	public static Block IvoryStairsJade = new BasicStaircase(Blockizer.IvoryBlockJade).setName("ivoryJadeStairs");
	public static Block IvoryStairsSapphire = new BasicStaircase(Blockizer.IvoryBlockSapphire).setName("ivorySapphireStairs");
	public static Block CrystevianBricks = new WashBricks().setName("bricksCrystevian");
	public static Block CrystalCreatorWhite = new CrystalCreatorWhite(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("CrystalCreatorWhite").setBlockTextureName("nevermine:crystalCreatorWhite");
	public static Block CrystalCreatorRed = new CrystalCreatorRed(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("CrystalCreatorRed").setBlockTextureName("nevermine:crystalCreatorRed");
	public static Block CrystalCreatorYellow = new CrystalCreatorYellow(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("CrystalCreatorYellow").setBlockTextureName("nevermine:crystalCreatorYellow");
	public static Block CrystalCreatorBlue = new CrystalCreatorBlue(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("CrystalCreatorBlue").setBlockTextureName("nevermine:crystalCreatorBlue");
	public static Block CrystalCreatorGreen = new CrystalCreatorGreen(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("CrystalCreatorGreen").setBlockTextureName("nevermine:crystalCreatorGreen");
	public static Block CrystalCreatorPurple = new CrystalCreatorPurple(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("CrystalCreatorPurple").setBlockTextureName("nevermine:crystalCreatorPurple");
	public static Block PowerStation = new PowerStation(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("PowerStation").setBlockTextureName("nevermine:powerStation");
	public static Block CrystalExtensionShrine = new CrystalExtensionShrine(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("CrystalExtensionShrine").setBlockTextureName("nevermine:crystalExtensionShrine");
	public static Block DirtCandyland = new GeneratedBlock(Material.ground).setName("dirtCandyland");
	public static Block GrassCandyland = new GrassCandyland(Material.grass).setBlockName("GrassCandyland");
	public static Block candylandPortal = new BlockCandylandPortal();
	public static Block CandyCane = new BlockCrystal(Material.glass).setName("candyCane");
	public static Block SpearmentRed = new BlockCrystal(Material.glass).setName("spearmentRed");
	public static Block SpearmentGreen = new BlockCrystal(Material.glass).setName("spearmentGreen");
	public static Block LollypopYellow = new BlockCrystal(Material.glass).setName("lollypopYellow");
	public static Block LollypopBlue = new BlockCrystal(Material.glass).setName("lollypopBlue");
	public static Block LollypopRed = new BlockCrystal(Material.glass).setName("lollypopRed");
	public static Block PlasticTube = new BlockCrystal(Material.glass).setName("plasticStick");
	public static Block CandyTube = new BlockCrystal(Material.glass).setName("candyTube");
	public static Block ChocolateBlock = new GeneratedBlock(Material.rock).setName("chocolateBlock");
	public static Block ChocolateBlockDark = new GeneratedBlock(Material.rock).setName("chocolateBlockDark");
	public static Block ChocolateBlockWhite = new GeneratedBlock(Material.rock).setName("chocolateBlockWhite");
	public static Block CandylandRedCandy = new GeneratedBlock(Material.rock).setName("candylandRedCandy");
	public static Block CandylandGreenCandy = new GeneratedBlock(Material.rock).setName("candylandGreenCandy");
	public static Block CandylandWhiteCandy = new GeneratedBlock(Material.rock).setName("candylandWhiteCandy");
	public static Block PlasticPole = new GeneratedBlock(Material.rock).setName("plasticPole");
	public static Block CandylandCottonPink = new GeneratedBlock(Material.cloth).setName("candylandCotton");
	public static Block CandylandCottonBlue = new GeneratedBlock(Material.cloth).setName("candylandCottonBlue");
	public static Block CandyGrass = new BlockGenericPlant(Material.vine).setName("candyGrass");
	public static Block CandyGrassBlue = new BlockGenericPlant(Material.vine).setName("candyGrassBlue");
	public static Block DivineStation = new DivineStation(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("DivineStation").setBlockTextureName("nevermine:divineStation");
	public static Block IvoryBlockP1 = new IvoryBlocks().setName("ivoryP1");
	public static Block IvoryBlockAmethystP1 = new IvoryBlocks().setName("ivoryAmethystP1");
	public static Block IvoryBlockRositeP1 = new IvoryBlocks().setName("ivoryRositeP1");
	public static Block IvoryBlockLimoniteP1 = new IvoryBlocks().setName("ivoryLimoniteP1");
	public static Block IvoryBlockJadeP1 = new IvoryBlocks().setName("ivoryJadeP1");
	public static Block IvoryBlockSapphireP1 = new IvoryBlocks().setName("ivorySapphireP1");
	public static Block IvoryBlockP2 = new IvoryBlocks().setName("ivoryP2");
	public static Block IvoryBlockAmethystP2 = new IvoryBlocks().setName("ivoryAmethystP2");
	public static Block IvoryBlockRositeP2 = new IvoryBlocks().setName("ivoryRositeP2");
	public static Block IvoryBlockLimoniteP2 = new IvoryBlocks().setName("ivoryLimoniteP2");
	public static Block IvoryBlockJadeP2 = new IvoryBlocks().setName("ivoryJadeP2");
	public static Block IvoryBlockSapphireP2 = new IvoryBlocks().setName("ivorySapphireP2");
	public static Block IvoryBlockP3 = new IvoryBlocks().setName("ivoryP3");
	public static Block IvoryBlockAmethystP3 = new IvoryBlocks().setName("ivoryAmethystP3");
	public static Block IvoryBlockRositeP3 = new IvoryBlocks().setName("ivoryRositeP3");
	public static Block IvoryBlockLimoniteP3 = new IvoryBlocks().setName("ivoryLimoniteP3");
	public static Block IvoryBlockJadeP3 = new IvoryBlocks().setName("ivoryJadeP3");
	public static Block IvoryBlockSapphireP3 = new IvoryBlocks().setName("ivorySapphireP3");
	public static Block LampIvory = new LampBlock().setName("lampIvory");
	public static Block LampIvoryAmethyst = new LampBlock().setName("lampIvoryAmethyst");
	public static Block LampIvoryJade = new LampBlock().setName("lampIvoryJade");
	public static Block LampIvorySapphire = new LampBlock().setName("lampIvorySapphire");
	public static Block LampIvoryRosite = new LampBlock().setName("lampIvoryRosite");
	public static Block LampIvoryLimonite = new LampBlock().setName("lampIvoryLimonite");
	public static Block MendingTable = new MendingTable(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("MendingTable");
	public static Block RainbowGrass = new BlockGenericPlant(Material.vine).setName("rainbowGrass");
	public static Block RainbowGrass2 = new BlockGenericPlant(Material.vine).setName("rainbowGrass2");
	public static Block RainbowGrass3 = new BlockGenericPlant(Material.vine).setName("rainbowGrass3");
	public static Block Gingerbread = new GeneratedBlock(Material.rock).setName("gingerbread");
	public static Block SpawnerCaneBug = new BlockSpawner("nevermine.CaneBug").setName("spawnerCaneBug");
	public static Block SpawnerGingerbird = new BlockSpawner("nevermine.Gingerbird").setName("spawnerGingerbird");
	public static Block SpawnerGingerbreadMan = new BlockSpawner("nevermine.GingerbreadMan").setName("spawnerGingerbreadMan");
	public static Block SpawnerFungock = new BlockSpawner("nevermine.Fungock").setName("spawnerFungock");
	public static Block SpawnerOpteryx = new BlockSpawner("nevermine.Opteryx").setName("spawnerOpteryx");
	public static Block CandyBlock = new CandyBlock(Material.rock).setBlockName("CandyBlock").setCreativeTab(Itemizer.TablesTab).setBlockTextureName("nevermine:candyBlock");
	public static Block SpawnerArocknid = new BlockSpawner("nevermine.Arocknid").setName("spawnerArocknid");
	public static Block ArchaicDirt = new BlockUnbreakable(Material.ground).setName("archaicDirt");
	public static Block ArchaicTiles = new BlockUnbreakable(Material.rock).setName("archaicTiles");
	public static Block ArchaicSquares = new BlockUnbreakable(Material.rock).setName("archaicSquares");
	public static Block ArchaicRectangles = new BlockUnbreakable(Material.rock).setName("archaicRectangles");
	public static Block ArchaicStreamHorizontal = new BlockUnbreakable(Material.rock).setName("animated/archaicStreamHorizontal");
	public static Block ArchaicStreamVertical = new BlockUnbreakable(Material.rock).setName("animated/archaicStreamVertical");
	public static Block ArchaicLamp = new UnbreakableLamp(Material.glass).setName("archaicLamp");
	public static Block CreepGrass = new BlockGenericPlant(Material.vine).setName("creepGrass");
	public static Block CreepFlowers = new BlockGenericPlant(Material.vine).setName("creepFlowers");
	public static Block CreepVines = new BlockGenericVines(Material.grass).setName("creepVines");
	public static Block CreepDirt = new GeneratedBlock(Material.ground).setName("dirtCreeponia");
	public static Block LeavesCreep = new Leaves().setName("leavesCreep");
	public static Block GrassCreeponia = new GrassCreeponia(Material.grass).setBlockName("GrassCreeponia");
	public static Block WoodCreep = new WoodCreep(Material.wood).setBlockName("woodCreep");
	public static Block creeponiaPortal = new BlockCreeponiaPortal();
	public static Block CreepStone = new BlockForagingStone(Material.rock).setName("stoneCreep");
	public static Block UnstableStone = new BlockForagingStone(Material.rock).setName("stoneUnstable");
	public static Block PrimedStone = new BlockForagingStone(Material.rock).setName("stonePrimed");
	public static Block EnhancerDamage = new GeneratedBlock(Material.rock).setName("enhancerDamage");
	public static Block EnhancerDurability = new GeneratedBlock(Material.rock).setName("enhancerDurability");
	public static Block EnhancerSpeed = new GeneratedBlock(Material.rock).setName("enhancerSpeed");
	public static Block EnhancerWeight = new GeneratedBlock(Material.rock).setName("enhancerWeight");
	public static Block EnhancerMagical = new GeneratedBlock(Material.rock).setName("enhancerMagical");
	public static Block EnhancerResistance = new GeneratedBlock(Material.rock).setName("enhancerResistance");
	public static Block CarvedRune5 = new CarvedRunicBlockBase(Material.iron, "carvedRune5").setCreativeTab(Itemizer.GenerationTab).setBlockName("carvedRune5");
	public static Block CarvedRune7 = new CarvedRunicBlockBase(Material.iron, "carvedRune7").setCreativeTab(Itemizer.GenerationTab).setBlockName("carvedRune7");
	public static Block CreepCrystal = new LampBlock().setName("creepCrystal");
	public static Block oreJewelyte = new OreBlock().setName("oreJewelyte");
	public static Block oreGemenyte = new OreBlock().setName("oreGemenyte");
	public static Block oreOrnamyte = new OreBlock().setName("oreOrnamyte");
	public static Block ArchaicGlass = new BlockUnbreakableClear().setName("archaicGlass");
	public static Block SpawnerGoldus = new BlockSpawner("nevermine.Goldus").setName("spawnerGoldus");
	public static Block SpawnerGoldem = new BlockSpawner("nevermine.Goldum").setName("spawnerGoldum");
	public static Block SpawnerVisage = new BlockSpawner("nevermine.Visage").setName("spawnerVisage");
	public static Block SpawnerGhastus = new BlockSpawner("nevermine.Ghastus").setName("spawnerGhastus");
	public static Block SpawnerUrioh = new BlockSpawner("nevermine.Urioh").setName("spawnerUrioh");
	public static Block SpawnerUrv = new BlockSpawner("nevermine.Urv").setName("spawnerUrv");
	public static Block SpawnerShavo = new BlockSpawner("nevermine.Shavo").setName("spawnerShavo");
	public static Block SpawnerFenix = new BlockSpawner("nevermine.Fenix").setName("spawnerFenix");
	public static Block SpawnerReaver = new BlockSpawner("nevermine.Reaver").setName("spawnerReaver");
	public static Block SpawnerSkeledon = new BlockSpawner("nevermine.Skeledon").setName("spawnerSkeledon");
	public static Block SpawnerSkelekyte = new BlockSpawner("nevermine.Skelekyte").setName("spawnerSkelekyte");
	public static Block GoldAccumulator = new GoldAccumulator(Material.rock).setName("goldAccumulator_top");
	public static Block PureGoldAccumulator = new PureGoldAccumulator(Material.rock).setName("goldAccumulator_side");
	public static Block iProgressor1 = new IProgressor(Material.rock).setName("progressorImmortallis1").setBlockTextureName("nevermine:progressorImmortallis");
	public static Block iProgressor2 = new IProgressor(Material.rock).setName("progressorImmortallis2").setBlockTextureName("nevermine:progressorImmortallis");
	public static Block iProgressor3 = new IProgressor(Material.rock).setName("progressorImmortallis3").setBlockTextureName("nevermine:progressorImmortallis");
	public static Block iProgressor4 = new IProgressor(Material.rock).setName("progressorImmortallis4").setBlockTextureName("nevermine:progressorImmortallis");
	public static Block iProgressor5 = new IProgressor(Material.rock).setName("progressorImmortallis5").setBlockTextureName("nevermine:progressorImmortallis");
	public static Block iProgressor6 = new IProgressor(Material.rock).setName("progressorImmortallis6").setBlockTextureName("nevermine:progressorImmortallis");
	public static Block iProgressor7 = new IProgressor(Material.rock).setName("progressorImmortallis7").setBlockTextureName("nevermine:progressorImmortallis");
	public static Block iProgressor8 = new IProgressor(Material.rock).setName("progressorImmortallis8").setBlockTextureName("nevermine:progressorImmortallis");
	public static Block iProgressor9 = new IProgressor(Material.rock).setName("progressorImmortallis9").setBlockTextureName("nevermine:progressorImmortallis");
	public static Block immortallisPortal = new BlockImmortallisPortal();
	public static Block ArchaicLadder = new BlockUnbreakableLadder(Material.iron).setName("archaicLadder");
	public static Block SpawnerZarg = new BlockSpawner("nevermine.Zarg").setName("spawnerZarg");
	public static Block SpawnerZorp = new BlockSpawner("nevermine.Zorp").setName("spawnerZorp");
	public static Block SpawnerBaumba = new BlockSpawner("nevermine.Baumba").setName("spawnerBaumba");
	public static Block SpawnerRefluct = new BlockSpawner("nevermine.Refluct").setName("spawnerRefluct");
	public static Block SpawnerMushroomSpider = new BlockSpawner("nevermine.MushroomSpider").setName("spawnerMushroomSpider");
	public static Block SpawnerDaysee = new BlockSpawner("nevermine.Daysee").setName("spawnerDaysee");
	public static Block SpawnerArkzyne = new BlockSpawner("nevermine.Arkzyne").setName("spawnerArkzyne");
	public static Block SpawnerCrusilisk = new BlockSpawner("nevermine.Crusilisk").setName("spawnerCrusilisk");
	public static Block SpawnerMegaGuardian = new BlockSpawner("nevermine.MegaGuardian").setName("spawnerMegaGuardian");
	public static Block SpawnerTorano = new BlockSpawner("nevermine.Torano").setName("spawnerTorano");
	public static Block SpawnerPoseido = new BlockSpawner("nevermine.Poseido").setName("spawnerPoseido");
	public static Block SpawnerFade = new BlockSpawner("nevermine.Fade").setName("spawnerFade");
	public static Block SpawnerSceptron = new BlockSpawner("nevermine.Sceptron").setName("spawnerSceptron");
	public static Block SpawnerCenturion = new BlockSpawner("nevermine.Centurion").setName("spawnerCenturion");
	public static Block CreeponianBricks = new WashBricks().setName("bricksCreeponian");
	public static Block CreepAltar = new CreepAltar(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("CreepAltar").setBlockTextureName("nevermine:creepAltar");
	public static Block TwinkleFence = new BlockLightFence("twinklestone").setName("twinkleFence");
	public static Block ExtractionDevice = new BlockExtractionDevice(false);
	public static Block ExtractionDeviceOn = new BlockExtractionDevice(true);
	public static Block planksCreep = new BasicDecoration(Material.wood).setName("planksCreep");
	public static Block stairsCreep = new BasicStaircase(Blockizer.planksCreep).setName("stairsCreep");
	public static Block planksCelevus = new BasicDecoration(Material.wood).setName("planksCelevus");
	public static Block stairsCelevus = new BasicStaircase(Blockizer.planksCelevus).setName("stairsCelevus");
	public static Block HavendalesBlue = new BlockGenericPlant(Material.vine).setName("havendalesBlue");
	public static Block HavendalesBlueStem = new BlockGenericPlant(Material.vine).setName("havendalesBlueStem");
	public static Block HavendalesYellow = new BlockGenericPlant(Material.vine).setName("havendalesYellow");
	public static Block HavendalesYellowStem = new BlockGenericPlant(Material.vine).setName("havendalesYellowStem");
	public static Block HavendalesPink = new BlockGenericPlant(Material.vine).setName("havendalesPink");
	public static Block HavendalesPinkStem = new BlockGenericPlant(Material.vine).setName("havendalesPinkStem");
	public static Block DayloomsBlue = new BlockGenericPlant(Material.vine).setName("dayloomsBlue");
	public static Block DayloomsPink = new BlockGenericPlant(Material.vine).setName("dayloomsPink");
	public static Block DayloomsYellow = new BlockGenericPlant(Material.vine).setName("dayloomsYellow");
	public static Block VoxFungi = new BlockGenericPlant(Material.vine).setName("voxFungi");
	public static Block VoxFungiStem = new BlockGenericPlant(Material.vine).setName("voxFungiStem");
	public static Block TentacleBlockGreen = new TentacleBlocks(Material.gourd, "TentacleBlockGreen").setBlockName("tentacleBlockGreen");
	public static Block TentacleDotsLeft = new TentacleBlocks(Material.gourd, "tentacleDotsLeft").setBlockName("tentacleDotsLeft");
	public static Block TentacleDotsRight = new TentacleBlocks(Material.gourd, "tentacleDotsRight").setBlockName("tentacleDotsRight");
	public static Block MiniTentacles = new BlockGenericPlant(Material.vine).setName("miniTentacles");
	public static Block MiniTentaclesTop = new BlockGenericPlant(Material.vine).setName("miniTentaclesTop");
	public static Block Ocealites = new BlockGenericPlant(Material.vine).setName("ocealites");
	public static Block WaterWeedsGreen = new BlockGenericPlant(Material.vine).setTallPlant().setName("waterweedsGreen");
	public static Block WaterWeedsYellow = new BlockGenericPlant(Material.vine).setTallPlant().setName("waterweedsYellow");
	public static Block WaterWeedsWhite = new BlockGenericPlant(Material.vine).setTallPlant().setName("waterweedsWhite");

	public static Block CraexxeusAltar = new CraexxeusAltar(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("CraexxeusAltar").setBlockTextureName("nevermine:craexxeusAltar");
	public static Block MechBotAltar = new MechBotAltar(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("MechBotAltar").setBlockTextureName("nevermine:mechBotAltar");
	public static Block BaronessAltar = new BaronessAltar(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("BaronessAltar").setBlockTextureName("nevermine:baronessAltar");
	public static Block TyrosaurAltar = new TyrosaurAltar(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("TyrosaurAltar").setBlockTextureName("nevermine:tyrosaurAltar");

	public static Block SpawnerSoulscorne = new BlockSpawner("nevermine.Soulscorne").setName("spawnerSoulscorne");
	public static Block SpawnerArcWizard = new BlockSpawner("nevermine.ArcWizard").setName("spawnerArcWizard");

	public static Block AncientAltar = new AncientAltar(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("AncientAltar").setBlockTextureName("nevermine:ancientAltar");
	public static Block StrangeBlock = new StrangeBlock(Material.rock).setCreativeTab(Itemizer.TablesTab).setBlockName("StrangeBlock").setBlockTextureName("nevermine:strangeBlock");

	public static Block SpawnerLuxocron = new BlockSpawner("nevermine.Luxocron").setName("spawnerLuxocron");
	public static Block SpawnerShyreTroll = new BlockSpawner("nevermine.ShyreTroll").setName("spawnerShyreTroll");
	public static Block SpawnerLightwalker = new BlockSpawner("nevermine.Lightwalker").setName("spawnerLightwalker");

	public static Block planksShyre = new BasicDecoration(Material.wood).setName("planksShyre");
	public static Block stairsShyrewood = new BasicStaircase(planksShyre).setName("stairsShyrewood");

	public static Block ShyreFlowers1 = new BlockGenericPlant(Material.grass).setName("shyreFlower1");
	public static Block ShyreFlowers2 = new BlockGenericPlant(Material.grass).setName("shyreFlower2");
	public static Block ShyreFlowers3 = new BlockGenericPlant(Material.grass).setName("shyreFlower3");
	public static Block ShyreFlowers4 = new BlockGenericPlant(Material.grass).setName("shyreFlower4");

	public static Block ShyreGlass = new BlockClear().setName("shyreGlass");
	public static Block ShyreWall = new GeneratedBlock(Material.rock).setName("shyreWall");
	public static Block ShyreWallWhite = new GeneratedBlock(Material.rock).setName("shyreWallWhite");
	public static Block ShyreRock = new BlockForagingStone(Material.rock).setName("stoneShyrelands");

	public static Block ShyreGems = new OreBlock().setName("shyreGems");
	public static Block ShyreStones = new OreBlock().setName("shyreStones");

	public static Block ShyreGrass = new GrassShyrelands(Material.grass).setBlockName("grassShyrelands");
	public static Block ShyreWood = new WoodShyre(Material.wood).setBlockName("woodShyre");

	public static Block ShyreLeaves = new ClearLeaves().setName("leavesShyre");
	public static Block ShyreLeavesB = new ClearLeaves().setName("leavesShyreBright");
	public static Block ShyreCloud = new BlockClearPass(Material.glass).setName("shyreCloud");

	public static BlockShyrelandsPortal shyrelandsPortal = new BlockShyrelandsPortal();

	public static Block ShyreStock = new BlockGenericPlant(Material.grass).setTallPlant().isBidirectional().setName("shyreStock");
	public static Block ShyreCapUp = new BlockGenericPlant(Material.grass).setTallPlant().setChildPlant(Blockizer.ShyreStock).setName("shyreCapUp");
	public static Block ShyreCapDown = new BlockGenericPlant(Material.grass).setTallPlant().setChildPlant(Blockizer.ShyreStock).setDown().setName("shyreCapDown");

	public static Block AncientCactus = new CustomCactus().setHardness(0.4F).setStepSound(new Block.SoundType("cloth", 1.0F, 1.0F)).setBlockName("cactus").setBlockTextureName("ancientCactus");
	public static Block PrecasianSand = new GeneratedBlock(Material.sand).setName("sandPrecasia");

	public static Block LeavesEucadon = new Leaves().setName("leavesEucadon");
	public static Block LeavesDomiguous = new Leaves().setName("leavesDomiguous");
	public static Block LeavesMelumia = new Leaves().setName("leavesMelumia");

	public static Block WoodEucadon = new WoodEucadon(Material.wood).setBlockName("WoodEucadon");
	public static Block WoodDomiguous = new WoodDomiguous(Material.wood).setBlockName("WoodDomiguous");
	public static Block WoodMelumia = new WoodMelumia(Material.wood).setBlockName("WoodMelumia");

	public static Block Mellians = new BlockGenericPlant(Material.grass).setName("mellians");
	public static Block Pertonias = new BlockGenericPlant(Material.grass).setName("pertonias");

	public static Block BulbStock = new BlockGenericPlant(Material.grass).setTallPlant().setName("bulbStock");
	public static Block BulbStockTop = new BlockGenericPlant(Material.grass).setTallPlant().setChildPlant(BulbStock).setName("bulbStockTop");
	public static Block Shadicles = new BlockGenericPlant(Material.grass).setTallPlant().setName("shadicles");
	public static Block ShadiclesTop = new BlockGenericPlant(Material.grass).setTallPlant().setChildPlant(Blockizer.Shadicles).setName("shadiclesTop");
	public static Block ShadowShrub = new BlockGenericPlant(Material.grass).setName("shadowShrub");

	public static Block SilverGrass = new BlockGenericPlant(Material.grass).setName("silverGrass");
	public static Block GrassSilvro = new GrassSilvro(Material.grass).setBlockName("grassSilvro");
	public static Block WoodOpollo = new WoodOpollo(Material.wood).setBlockName("WoodOpollo");


	public static Block SilvroBox = new BasicDecoration(Material.wood).setName("silvroBox");
	public static Block IroBox = new BasicDecoration(Material.wood).setName("iroBox");

	public static Block LeavesSilvro = new Leaves().setName("leavesSilvro");
	public static Block LeavesOpollo = new Leaves().setName("leavesOpollo");

	public static Block GrassMarshmallow = new GrassMarshmallow(Material.grass).setBlockName("GrassMarshmallow");
	public static Block GrassChocolate = new GrassChocolate(Material.grass).setBlockName("GrassChocolate");

	public static Block Licorice = new GeneratedBlock(Material.rock).setName("licorice");
	public static Block Marshmallow = new GeneratedBlock(Material.cloth).setName("marshmallow");

	public static Block ChocolateGrass = new BlockGenericPlant(Material.grass).setName("chocolateGrass");

	public static Block RockCandyBlue = new BlockClear().setName("rockCandyBlue");
	public static Block RockCandyPink = new BlockClear().setName("rockCandyPink");
	public static Block RockCandyGreen = new BlockClear().setName("rockCandyGreen");
	public static Block RockCandyPurple = new BlockClear().setName("rockCandyPurple");

	public static Block GrassCrystal = new GrassCrystal(Material.grass).setBlockName("GrassCrystal");

	public static Block CrystalCandyBlue = new BlockCrystal(Material.glass).setName("crystalCandyBlue");
	public static Block CrystalCandyPink = new BlockCrystal(Material.glass).setName("crystalCandyPink");
	public static Block CrystalCandyGreen = new BlockCrystal(Material.glass).setName("crystalCandyGreen");
	public static Block CrystalCandyPurple = new BlockCrystal(Material.glass).setName("crystalCandyPurple");
	public static Block RockCandyGrass = new BlockCrystal(Material.glass).setName("rockCandyGrass");

	public static Block ChocolateStocks = new BlockGenericPlant(Material.grass).setName("chocolateStocks");
	public static Block MarshTube = new BlockGenericPlant(Material.grass).setName("marshTube");
	public static Block MallowPile = new BlockGenericPlant(Material.grass).setName("mallowPile");
	public static Block CandyGrassWhite = new BlockGenericPlant(Material.grass).setName("candyGrassWhite");

	public static Block AquaFungi = new BlockGenericPlant(Material.grass).setName("aquaFungi");
	public static Block OrangeFungi = new BlockGenericPlant(Material.grass).setName("orangeFungi");

	public static Block OcealitesRed = new BlockGenericPlant(Material.grass).setName("ocealitesRed");
	public static Block WaterweedsRed = new BlockGenericPlant(Material.grass).setTallPlant().setName("waterweedsRed");

	public static Block HardCoral = new GeneratedBlock(Material.rock).setName("hardCoral");

	public static Block FlakeVine = new BlockGenericPlant(Material.grass).setTallPlant().setStonePlant().setName("flakeVine");
	public static Block FlakeVineTop = new BlockGenericPlant(Material.grass).setTallPlant().setChildPlant(FlakeVine).setName("flakeVineTop");

	public static Block Deepshine = new GeneratedBlock(Material.rock).setName("deepshine");

	public static Block DeepVines = new BlockGenericPlant(Material.grass).setTallPlant().setName("deepVines");
	public static Block DeepBulbs = new BlockGenericPlant(Material.grass).setTallPlant().setChildPlant(DeepVines).setName("deepBulbs");

	public static Block DawnStocks = new BlockGenericPlant(Material.grass).setTallPlant().setName("dawnStocks");
	public static Block DawnStocksTop = new BlockGenericPlant(Material.grass).setTallPlant().setChildPlant(DawnStocks).setName("dawnStocksTop");
	public static Block DawnBulb = new BlockGenericPlant(Material.grass).setTallPlant().setChildPlant(DawnStocks).setName("dawnBulb");

	public static Block MushroomOutsidePeach = new GeneratedBlock(Material.gourd).setName("mushroomOutsidePeach");
	public static Block MushroomInsidePeach = new GeneratedBlock(Material.gourd).setName("mushroomInsidePeach");
	public static Block MushroomOutsideAqua = new GeneratedBlock(Material.gourd).setName("mushroomOutsideAqua");
	public static Block MushroomInsideAqua = new GeneratedBlock(Material.gourd).setName("mushroomInsideAqua");
	public static Block PedalsOrange = new GeneratedBlock(Material.gourd).setName("pedalsOrange");

	public static Block SkullBlock = new SkullBlock(Material.gourd, "skullBlock").setBlockName("skullBlock");
	public static Block SkullBlockDark = new SkullBlock(Material.gourd, "skullBlockDark").setBlockName("skullBlockDark");
	public static Block HauntedOrb = new SkullBlock(Material.gourd, "hauntedOrb").setBlockName("hauntedOrb");

	public static Block CoralBlue = new GeneratedBlock(Material.rock).setName("coralBlue");
	public static Block LeavesBubble = new BlockClearPass(Material.leaves).setName("leavesBubble");

	public static void oreDictInit() {
		OreDictionary.registerOre(oreDictWood, WoodShadow);
		OreDictionary.registerOre(oreDictWood, WoodBlood);
		OreDictionary.registerOre(oreDictWood, WoodLucalus);
		OreDictionary.registerOre(oreDictWood, WoodCycade);
		OreDictionary.registerOre(oreDictWood, WoodStranglewood);
		OreDictionary.registerOre(oreDictWood, WoodEyeball);
		OreDictionary.registerOre(oreDictWood, WoodIromine);
		OreDictionary.registerOre(oreDictWood, WoodLunide);
		OreDictionary.registerOre(oreDictWood, WoodHaunted);
		OreDictionary.registerOre(oreDictWood, WoodDawn);
		OreDictionary.registerOre(oreDictWood, WoodToxic);
		OreDictionary.registerOre(oreDictWood, WoodRunic);
		OreDictionary.registerOre(oreDictWood, WoodEternal);
		OreDictionary.registerOre(oreDictWood, WoodAchony);
		OreDictionary.registerOre(oreDictWood, WoodChurry);
		OreDictionary.registerOre(oreDictWood, WoodCreep);
		OreDictionary.registerOre(oreDictWood, ShyreWood);
		OreDictionary.registerOre(oreDictWood, WoodEucadon);
		OreDictionary.registerOre(oreDictWood, WoodDomiguous);
		OreDictionary.registerOre(oreDictWood, WoodMelumia);
		OreDictionary.registerOre(oreDictWood, WoodOpollo);

		OreDictionary.registerOre(oreDictPlanks, planksBloodwood);
		OreDictionary.registerOre(oreDictPlanks, planksCycade);
		OreDictionary.registerOre(oreDictPlanks, planksLucalus);
		OreDictionary.registerOre(oreDictPlanks, planksShadow);
		OreDictionary.registerOre(oreDictPlanks, planksLunide);
		OreDictionary.registerOre(oreDictPlanks, planksStranglewood);
		OreDictionary.registerOre(oreDictPlanks, DawnwoodPlanks);
		OreDictionary.registerOre(oreDictPlanks, planksIrowood);
		OreDictionary.registerOre(oreDictPlanks, planksHauntedwood);
		OreDictionary.registerOre(oreDictPlanks, planksRunic);
		OreDictionary.registerOre(oreDictPlanks, planksToxicwood);
		OreDictionary.registerOre(oreDictPlanks, planksChurry);
		OreDictionary.registerOre(oreDictPlanks, planksAchony);
		OreDictionary.registerOre(oreDictPlanks, planksBlueshroom);
		OreDictionary.registerOre(oreDictPlanks, planksGreenshroom);
		OreDictionary.registerOre(oreDictPlanks, planksYellowshroom);
		OreDictionary.registerOre(oreDictPlanks, planksOrangeshroom);
		OreDictionary.registerOre(oreDictPlanks, planksPurpleshroom);
		OreDictionary.registerOre(oreDictPlanks, planksCreep);
		OreDictionary.registerOre(oreDictPlanks, planksCelevus);
		OreDictionary.registerOre(oreDictPlanks, planksShyre);
		OreDictionary.registerOre(oreDictPlanks, planksDomiguous);
		OreDictionary.registerOre(oreDictPlanks, planksOpollo);
		OreDictionary.registerOre(oreDictPlanks, planksMelumia);
		OreDictionary.registerOre(oreDictPlanks, planksEucadon);

		OreDictionary.registerOre(oreDictStairsWood, stairsPurpleshroom);
		OreDictionary.registerOre(oreDictStairsWood, stairsCelevus);
		OreDictionary.registerOre(oreDictStairsWood, stairsCreep);
		OreDictionary.registerOre(oreDictStairsWood, stairsGreenshroom);
		OreDictionary.registerOre(oreDictStairsWood, stairsYellowshroom);
		OreDictionary.registerOre(oreDictStairsWood, stairsOrangeshroom);
		OreDictionary.registerOre(oreDictStairsWood, stairsBlueshroom);
		OreDictionary.registerOre(oreDictStairsWood, stairsChurry);
		OreDictionary.registerOre(oreDictStairsWood, stairsAchony);
		OreDictionary.registerOre(oreDictStairsWood, stairsToxicwood);
		OreDictionary.registerOre(oreDictStairsWood, stairsDawnwood);
		OreDictionary.registerOre(oreDictStairsWood, stairsLunide);
		OreDictionary.registerOre(oreDictStairsWood, stairsIrowood);
		OreDictionary.registerOre(oreDictStairsWood, stairsStranglewood);
		OreDictionary.registerOre(oreDictStairsWood, stairsShadow);
		OreDictionary.registerOre(oreDictStairsWood, stairsLucalus);
		OreDictionary.registerOre(oreDictStairsWood, stairsCycade);
		OreDictionary.registerOre(oreDictStairsWood, stairsBloodwood);
		OreDictionary.registerOre(oreDictStairsWood, stairsRunic);
		OreDictionary.registerOre(oreDictStairsWood, stairsHauntedwood);
		OreDictionary.registerOre(oreDictStairsWood, stairsShyrewood);
		OreDictionary.registerOre(oreDictStairsWood, stairsOpollo);
		OreDictionary.registerOre(oreDictStairsWood, stairsDomiguous);
		OreDictionary.registerOre(oreDictStairsWood, stairsMelumia);
		OreDictionary.registerOre(oreDictStairsWood, stairsEucadon);

		OreDictionary.registerOre(oreDictCobble, DkStone);
		OreDictionary.registerOre(oreDictCobble, AbyssStone);
		OreDictionary.registerOre(oreDictCobble, StoneHaven);
		OreDictionary.registerOre(oreDictCobble, StoneMysterium);
		OreDictionary.registerOre(oreDictCobble, StonePrecasianHigh);
		OreDictionary.registerOre(oreDictCobble, StoneGardencia);
		OreDictionary.registerOre(oreDictCobble, StoneGreckon);
		OreDictionary.registerOre(oreDictCobble, StoneDustopia);
		OreDictionary.registerOre(oreDictCobble, StoneBorean);
		OreDictionary.registerOre(oreDictCobble, StoneToxic);
		OreDictionary.registerOre(oreDictCobble, StonePrecasianLow);
		OreDictionary.registerOre(oreDictCobble, BarathosHellstone);
		OreDictionary.registerOre(oreDictCobble, StoneLelyetia);
		OreDictionary.registerOre(oreDictCobble, IroStone);
		OreDictionary.registerOre(oreDictCobble, DeepRock);
		OreDictionary.registerOre(oreDictCobble, BaronStone);
		OreDictionary.registerOre(oreDictCobble, CreepStone);
		OreDictionary.registerOre(oreDictCobble, UnstableStone);
		OreDictionary.registerOre(oreDictCobble, PrimedStone);
		OreDictionary.registerOre(oreDictCobble, ShyreRock);

		OreDictionary.registerOre(oreDictSand, PrecasianSand);

		OreDictionary.registerOre(oreDictGlass, RunicGlass);
		OreDictionary.registerOre(oreDictGlass, BaronGlass);
		OreDictionary.registerOre(oreDictGlass, LunarGlass);
		OreDictionary.registerOre(oreDictGlass, IroGlass);
		OreDictionary.registerOre(oreDictGlass, AquaticGlass);
		OreDictionary.registerOre(oreDictGlass, GardencianGlass);
		OreDictionary.registerOre(oreDictGlass, VoxGlass);
		OreDictionary.registerOre(oreDictGlass, HavenGlass);
		OreDictionary.registerOre(oreDictGlass, AbyssalGlass);
		OreDictionary.registerOre(oreDictGlass, ZhinxGlass);
		OreDictionary.registerOre(oreDictGlass, LelyetianGlass);
		OreDictionary.registerOre(oreDictGlass, ArchaicGlass);
		OreDictionary.registerOre(oreDictGlass, ShyreGlass);

		OreDictionary.registerOre("oreBloodstone", oreBloodstone);
		OreDictionary.registerOre("oreAmethyst", oreAmethyst);
		OreDictionary.registerOre("oreBone", oreChestboneFragment);
		OreDictionary.registerOre("oreBone", oreLegFragment);
		OreDictionary.registerOre("oreBone", oreFootFragment);
		OreDictionary.registerOre("oreBone", oreSkullFragment);
		OreDictionary.registerOre("oreCrystallite", oreCrystallite);
		OreDictionary.registerOre("oreEmberstone", oreEmberstone);
		OreDictionary.registerOre("oreJade", oreJade);
		OreDictionary.registerOre("oreLimonite", oreLimonite);
		OreDictionary.registerOre("oreRosite", oreRosite);
		OreDictionary.registerOre("oreSapphire", oreSapphire);
		OreDictionary.registerOre("oreMystite", oreMystite);
		OreDictionary.registerOre("oreLyon", OreLyon);
		OreDictionary.registerOre("oreGhastly", OreGhastly);
		OreDictionary.registerOre("oreGhoulish", OreGhoulish);
		OreDictionary.registerOre("oreVarsium", OreVarsium);
		OreDictionary.registerOre("oreElecanium", OreElecanium);
		OreDictionary.registerOre("oreBaronyte", OreBaronyte);
		OreDictionary.registerOre("oreBlazium", OreBlazium);
		OreDictionary.registerOre("oreRunium", oreRunium);
		OreDictionary.registerOre("oreRunium", oreRuniumCharged);
		OreDictionary.registerOre("oreJewelyte", oreJewelyte);
		OreDictionary.registerOre("oreGemenyte", oreGemenyte);
		OreDictionary.registerOre("oreOrnamyte", oreOrnamyte);
		OreDictionary.registerOre("oreShryeGems", ShyreGems);
		OreDictionary.registerOre("oreShyreStones", ShyreStones);

		OreDictionary.registerOre(oreDictLeaves, LeavesShadow);
		OreDictionary.registerOre(oreDictLeaves, LeavesBlood);
		OreDictionary.registerOre(oreDictLeaves, HavenLeavesBlue);
		OreDictionary.registerOre(oreDictLeaves, HavenLeavesYellow);
		OreDictionary.registerOre(oreDictLeaves, HavenLeavesPink);
		OreDictionary.registerOre(oreDictLeaves, HavenLeavesRed);
		OreDictionary.registerOre(oreDictLeaves, HavenLeavesPurple);
		OreDictionary.registerOre(oreDictLeaves, HavenLeavesTurq);
		OreDictionary.registerOre(oreDictLeaves, LeavesLucalus);
		OreDictionary.registerOre(oreDictLeaves, LeavesCycade);
		OreDictionary.registerOre(oreDictLeaves, LeavesStranglewood);
		OreDictionary.registerOre(oreDictLeaves, LeavesVein);
		OreDictionary.registerOre(oreDictLeaves, LeavesShadowblood);
		OreDictionary.registerOre(oreDictLeaves, LeavesIrogold);
		OreDictionary.registerOre(oreDictLeaves, LeavesIrodust);
		OreDictionary.registerOre(oreDictLeaves, LeavesLunicia);
		OreDictionary.registerOre(oreDictLeaves, LeavesLunosso);
		OreDictionary.registerOre(oreDictLeaves, LeavesHaunted);
		OreDictionary.registerOre(oreDictLeaves, LeavesDawn);
		OreDictionary.registerOre(oreDictLeaves, LeavesEternal);
		OreDictionary.registerOre(oreDictLeaves, LeavesChurry);
		OreDictionary.registerOre(oreDictLeaves, LeavesAchony);
		OreDictionary.registerOre(oreDictLeaves, CelevusRed);
		OreDictionary.registerOre(oreDictLeaves, CelevusGreen);
		OreDictionary.registerOre(oreDictLeaves, CelevusBlue);
		OreDictionary.registerOre(oreDictLeaves, CelevusYellow);
		OreDictionary.registerOre(oreDictLeaves, CelevusPurple);
		OreDictionary.registerOre(oreDictLeaves, CelevusWhite);
		OreDictionary.registerOre(oreDictLeaves, LeavesCreep);
		OreDictionary.registerOre(oreDictLeaves, ShyreLeaves);
		OreDictionary.registerOre(oreDictLeaves, ShyreLeavesB);
		OreDictionary.registerOre(oreDictLeaves, LeavesEucadon);
		OreDictionary.registerOre(oreDictLeaves, LeavesDomiguous);
		OreDictionary.registerOre(oreDictLeaves, LeavesMelumia);
		OreDictionary.registerOre(oreDictLeaves, LeavesSilvro);
		OreDictionary.registerOre(oreDictLeaves, LeavesOpollo);
		OreDictionary.registerOre(oreDictLeaves, LeavesBubble);

		OreDictionary.registerOre("blockShadonantium", Shadonantium);
		OreDictionary.registerOre("blockCrystallanium", Crystallanium);
		OreDictionary.registerOre("blockEmberium", Emberium);
		OreDictionary.registerOre("blockSkeletanium", Skeletanium);
	}
}
