package net.tslat.aoa3.structure.runandor;

import net.minecraft.block.state.IBlockState;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
import net.tslat.aoa3.common.registration.BlockRegister;
import net.tslat.aoa3.structure.AoAStructure;

import java.util.Random;

public class RunicTree5 extends AoAStructure { //StructureSize: 7x14x7
	private static final IBlockState runicLeaves = BlockRegister.RUNIC_LEAVES.getDefaultState();
	private static final IBlockState runicLog = BlockRegister.RUNIC_LOG.getDefaultState();

	public RunicTree5() {
		super("RunicTree5");
	}

	@Override
	protected void build(World world, Random rand, BlockPos basePos) {
		addBlock(world, basePos, 3, 0, 3, runicLog);
		addBlock(world, basePos, 3, 1, 3, runicLog);
		addBlock(world, basePos, 3, 2, 3, runicLog);
		addBlock(world, basePos, 3, 3, 3, runicLog);
		addBlock(world, basePos, 3, 4, 3, runicLog);
		addBlock(world, basePos, 3, 5, 3, runicLog);
		addBlock(world, basePos, 3, 6, 3, runicLog);
		addBlock(world, basePos, 3, 7, 3, runicLog);
		addBlock(world, basePos, 0, 8, 3, runicLog);
		addBlock(world, basePos, 1, 8, 3, runicLog);
		addBlock(world, basePos, 2, 8, 3, runicLog);
		addBlock(world, basePos, 3, 8, 0, runicLog);
		addBlock(world, basePos, 3, 8, 1, runicLog);
		addBlock(world, basePos, 3, 8, 2, runicLog);
		addBlock(world, basePos, 3, 8, 3, runicLog);
		addBlock(world, basePos, 3, 8, 4, runicLog);
		addBlock(world, basePos, 3, 8, 5, runicLog);
		addBlock(world, basePos, 3, 8, 6, runicLog);
		addBlock(world, basePos, 4, 8, 3, runicLog);
		addBlock(world, basePos, 5, 8, 3, runicLog);
		addBlock(world, basePos, 6, 8, 3, runicLog);
		addBlock(world, basePos, 0, 9, 3, runicLog);
		addBlock(world, basePos, 2, 9, 2, runicLeaves);
		addBlock(world, basePos, 2, 9, 3, runicLeaves);
		addBlock(world, basePos, 2, 9, 4, runicLeaves);
		addBlock(world, basePos, 3, 9, 0, runicLog);
		addBlock(world, basePos, 3, 9, 2, runicLeaves);
		addBlock(world, basePos, 3, 9, 3, runicLeaves);
		addBlock(world, basePos, 3, 9, 4, runicLeaves);
		addBlock(world, basePos, 3, 9, 6, runicLog);
		addBlock(world, basePos, 4, 9, 2, runicLeaves);
		addBlock(world, basePos, 4, 9, 3, runicLeaves);
		addBlock(world, basePos, 4, 9, 4, runicLeaves);
		addBlock(world, basePos, 6, 9, 3, runicLog);
		addBlock(world, basePos, 0, 10, 3, runicLog);
		addBlock(world, basePos, 1, 10, 1, runicLeaves);
		addBlock(world, basePos, 1, 10, 2, runicLeaves);
		addBlock(world, basePos, 1, 10, 3, runicLeaves);
		addBlock(world, basePos, 1, 10, 4, runicLeaves);
		addBlock(world, basePos, 1, 10, 5, runicLeaves);
		addBlock(world, basePos, 2, 10, 1, runicLeaves);
		addBlock(world, basePos, 2, 10, 2, runicLeaves);
		addBlock(world, basePos, 2, 10, 3, runicLeaves);
		addBlock(world, basePos, 2, 10, 4, runicLeaves);
		addBlock(world, basePos, 2, 10, 5, runicLeaves);
		addBlock(world, basePos, 3, 10, 0, runicLog);
		addBlock(world, basePos, 3, 10, 1, runicLeaves);
		addBlock(world, basePos, 3, 10, 2, runicLeaves);
		addBlock(world, basePos, 3, 10, 3, runicLeaves);
		addBlock(world, basePos, 3, 10, 4, runicLeaves);
		addBlock(world, basePos, 3, 10, 5, runicLeaves);
		addBlock(world, basePos, 3, 10, 6, runicLog);
		addBlock(world, basePos, 4, 10, 1, runicLeaves);
		addBlock(world, basePos, 4, 10, 2, runicLeaves);
		addBlock(world, basePos, 4, 10, 3, runicLeaves);
		addBlock(world, basePos, 4, 10, 4, runicLeaves);
		addBlock(world, basePos, 4, 10, 5, runicLeaves);
		addBlock(world, basePos, 5, 10, 1, runicLeaves);
		addBlock(world, basePos, 5, 10, 2, runicLeaves);
		addBlock(world, basePos, 5, 10, 3, runicLeaves);
		addBlock(world, basePos, 5, 10, 4, runicLeaves);
		addBlock(world, basePos, 5, 10, 5, runicLeaves);
		addBlock(world, basePos, 6, 10, 3, runicLog);
		addBlock(world, basePos, 1, 11, 1, runicLeaves);
		addBlock(world, basePos, 1, 11, 2, runicLeaves);
		addBlock(world, basePos, 1, 11, 3, runicLeaves);
		addBlock(world, basePos, 1, 11, 4, runicLeaves);
		addBlock(world, basePos, 1, 11, 5, runicLeaves);
		addBlock(world, basePos, 2, 11, 1, runicLeaves);
		addBlock(world, basePos, 2, 11, 2, runicLeaves);
		addBlock(world, basePos, 2, 11, 3, runicLeaves);
		addBlock(world, basePos, 2, 11, 4, runicLeaves);
		addBlock(world, basePos, 2, 11, 5, runicLeaves);
		addBlock(world, basePos, 3, 11, 1, runicLeaves);
		addBlock(world, basePos, 3, 11, 2, runicLeaves);
		addBlock(world, basePos, 3, 11, 3, runicLeaves);
		addBlock(world, basePos, 3, 11, 4, runicLeaves);
		addBlock(world, basePos, 3, 11, 5, runicLeaves);
		addBlock(world, basePos, 4, 11, 1, runicLeaves);
		addBlock(world, basePos, 4, 11, 2, runicLeaves);
		addBlock(world, basePos, 4, 11, 3, runicLeaves);
		addBlock(world, basePos, 4, 11, 4, runicLeaves);
		addBlock(world, basePos, 4, 11, 5, runicLeaves);
		addBlock(world, basePos, 5, 11, 1, runicLeaves);
		addBlock(world, basePos, 5, 11, 2, runicLeaves);
		addBlock(world, basePos, 5, 11, 3, runicLeaves);
		addBlock(world, basePos, 5, 11, 4, runicLeaves);
		addBlock(world, basePos, 5, 11, 5, runicLeaves);
		addBlock(world, basePos, 1, 12, 1, runicLeaves);
		addBlock(world, basePos, 1, 12, 2, runicLeaves);
		addBlock(world, basePos, 1, 12, 3, runicLeaves);
		addBlock(world, basePos, 1, 12, 4, runicLeaves);
		addBlock(world, basePos, 1, 12, 5, runicLeaves);
		addBlock(world, basePos, 2, 12, 1, runicLeaves);
		addBlock(world, basePos, 2, 12, 2, runicLeaves);
		addBlock(world, basePos, 2, 12, 3, runicLeaves);
		addBlock(world, basePos, 2, 12, 4, runicLeaves);
		addBlock(world, basePos, 2, 12, 5, runicLeaves);
		addBlock(world, basePos, 3, 12, 1, runicLeaves);
		addBlock(world, basePos, 3, 12, 2, runicLeaves);
		addBlock(world, basePos, 3, 12, 3, runicLeaves);
		addBlock(world, basePos, 3, 12, 4, runicLeaves);
		addBlock(world, basePos, 3, 12, 5, runicLeaves);
		addBlock(world, basePos, 4, 12, 1, runicLeaves);
		addBlock(world, basePos, 4, 12, 2, runicLeaves);
		addBlock(world, basePos, 4, 12, 3, runicLeaves);
		addBlock(world, basePos, 4, 12, 4, runicLeaves);
		addBlock(world, basePos, 4, 12, 5, runicLeaves);
		addBlock(world, basePos, 5, 12, 1, runicLeaves);
		addBlock(world, basePos, 5, 12, 2, runicLeaves);
		addBlock(world, basePos, 5, 12, 3, runicLeaves);
		addBlock(world, basePos, 5, 12, 4, runicLeaves);
		addBlock(world, basePos, 5, 12, 5, runicLeaves);
		addBlock(world, basePos, 2, 13, 2, runicLeaves);
		addBlock(world, basePos, 2, 13, 3, runicLeaves);
		addBlock(world, basePos, 2, 13, 4, runicLeaves);
		addBlock(world, basePos, 3, 13, 2, runicLeaves);
		addBlock(world, basePos, 3, 13, 3, runicLeaves);
		addBlock(world, basePos, 3, 13, 4, runicLeaves);
		addBlock(world, basePos, 4, 13, 2, runicLeaves);
		addBlock(world, basePos, 4, 13, 3, runicLeaves);
		addBlock(world, basePos, 4, 13, 4, runicLeaves);
	}
}
