package net.tslat.aoa3.common.registration.item;

import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.Item;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.tslat.aoa3.common.registration.AoACreativeModeTabs;
import net.tslat.aoa3.content.item.weapon.blaster.*;
import net.tslat.aoa3.content.item.weapon.bow.*;
import net.tslat.aoa3.content.item.weapon.cannon.*;
import net.tslat.aoa3.content.item.weapon.crossbow.*;
import net.tslat.aoa3.content.item.weapon.greatblade.*;
import net.tslat.aoa3.content.item.weapon.gun.*;
import net.tslat.aoa3.content.item.weapon.maul.*;
import net.tslat.aoa3.content.item.weapon.shotgun.*;
import net.tslat.aoa3.content.item.weapon.sniper.Terminator;
import net.tslat.aoa3.content.item.weapon.sniper.*;
import net.tslat.aoa3.content.item.weapon.staff.*;
import net.tslat.aoa3.content.item.weapon.sword.*;
import net.tslat.aoa3.content.item.weapon.thrown.*;
import net.tslat.aoa3.content.item.weapon.vulcane.*;
import net.tslat.aoa3.library.constant.AttackSpeed;
import org.jetbrains.annotations.Nullable;

import java.util.function.Supplier;

public final class AoAWeapons {
	public static void init() {}

	public static final DeferredHolder<Item, Item> BARON_SWORD = registerWeapon("baron_sword", BaronSword::new, AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> BLOODFURY = registerWeapon("bloodfury", () -> new BaseSword(AoATiers.BLOODFURY, 0, AttackSpeed.forAttacksPerSecond(1.8f)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> BLOODSTONE_SWORD = registerWeapon("bloodstone_sword", () -> new BaseSword(AoATiers.BLOODSTONE), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> CANDLEFIRE_SWORD = registerWeapon("candlefire_sword", CandlefireSword::new, AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> CARAMEL_CARVER = registerWeapon("caramel_carver", CaramelCarver::new, AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> CORALSTORM_SWORD = registerWeapon("coralstorm_sword", CoralstormSword::new, AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> CREEPIFIED_SWORD = registerWeapon("creepified_sword", CreepifiedSword::new, AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> CRYSTALLITE_SWORD = registerWeapon("crystallite_sword", () -> new BaseSword(AoATiers.CRYSTALLITE, 0, AttackSpeed.forAttacksPerSecond(1.7f)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> EMBERSTONE_SWORD = registerWeapon("emberstone_sword", EmberstoneSword::new, AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> EXPLOCHRON_SWORD = registerWeapon("explochron_sword", ExplochronSword::new, AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> FIREBORNE_SWORD = registerWeapon("fireborne_sword", FireborneSword::new, AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> GUARDIANS_SWORD = registerWeapon("guardians_sword", GuardiansSword::new, AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> HARVESTER_SWORD = registerWeapon("harvester_sword", HarvesterSword::new, AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> HOLY_SWORD = registerWeapon("holy_sword", HolySword::new, AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> ILLUSION_SWORD = registerWeapon("illusion_sword", IllusionSword::new, AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> JADE_SWORD = registerWeapon("jade_sword", () -> new BaseSword(AoATiers.JADE), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> LEGBONE_SWORD = registerWeapon("legbone_sword", LegboneSword::new, AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> LIGHTS_WAY = registerWeapon("lights_way", () -> new BaseSword(AoATiers.LIGHTS_WAY, 0, AttackSpeed.DOUBLE), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> LIMONITE_SWORD = registerWeapon("limonite_sword", () -> new BaseSword(AoATiers.LIMONITE), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> NETHENGEIC_SWORD = registerWeapon("nethengeic_sword", NethengeicSword::new, AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> PRIMAL_SWORD = registerWeapon("primal_sword", PrimalSword::new, AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> ROCKBASHER_SWORD = registerWeapon("rockbasher_sword", RockbasherSword::new, AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> ROCK_PICK_SWORD = registerWeapon("rock_pick_sword", RockPickSword::new, AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> ROSIDIAN_SWORD = registerWeapon("rosidian_sword", RosidianSword::new, AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> RUNIC_SWORD = registerWeapon("runic_sword", RunicSword::new, AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> SHADOW_SWORD = registerWeapon("shadow_sword", () -> new BaseSword(AoATiers.SHADOW), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> SHROOMUS_SWORD = registerWeapon("shroomus_sword", ShroomusSword::new, AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> SKELETAL_SWORD = registerWeapon("skeletal_sword", () -> new BaseSword(AoATiers.SKELETAL, 1, AttackSpeed.forAttacksPerSecond(2)), AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> SUPREMACY_SWORD = registerWeapon("supremacy_sword", SupremacySword::new, AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> SWEET_SWORD = registerWeapon("sweet_sword", SweetSword::new, AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> TROLL_BASHER_AXE = registerWeapon("troll_basher_axe", TrollBasherAxe::new, AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> ULTRAFLAME = registerWeapon("ultraflame", Ultraflame::new, AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> VOID_SWORD = registerWeapon("void_sword", VoidSword::new, AoACreativeModeTabs.SWORDS.getKey());
	public static final DeferredHolder<Item, Item> FAUNAMANCERS_BLADE = registerWeapon("faunamancers_blade", FaunamancersBlade::new, AoACreativeModeTabs.SWORDS.getKey());

	public static final DeferredHolder<Item, Item> BARON_GREATBLADE = registerWeapon("baron_greatblade", BaronGreatblade::new, AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> BLOODLURKER = registerWeapon("bloodlurker", () -> new BaseGreatblade(AoATiers.BLOODLURKER_GREATBLADE), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> CANDY_BLADE = registerWeapon("candy_blade", CandyBlade::new, AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> CORAL_GREATBLADE = registerWeapon("coral_greatblade", () -> new BaseGreatblade(AoATiers.CORAL_GREATBLADE), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> COTTON_CRUSHER = registerWeapon("cotton_crusher", CottonCrusher::new, AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> CREEPOID_GREATBLADE = registerWeapon("creepoid_greatblade", CreepoidGreatblade::new, AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> CRYSTAL_GREATBLADE = registerWeapon("crystal_greatblade", CrystalGreatblade::new, AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> EREBON_SCYTHE = registerWeapon("erebon_scythe", ErebonScythe::new, AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> GODS_GREATBLADE = registerWeapon("gods_greatblade", () -> new BaseGreatblade(AoATiers.GODS_GREATBLADE), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> GOOFY_GREATBLADE = registerWeapon("goofy_greatblade", GoofyGreatblade::new, AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> HAUNTED_GREATBLADE = registerWeapon("haunted_greatblade", HauntedGreatblade::new, AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> KNIGHTS_GUARD = registerWeapon("knights_guard", KnightsGuard::new, AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> LELYETIAN_GREATBLADE = registerWeapon("lelyetian_greatblade", LelyetianGreatblade::new, AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> LUNAR_GREATBLADE = registerWeapon("lunar_greatblade", LunarGreatblade::new, AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> LUXON_SCYTHE = registerWeapon("luxon_scythe", LuxonScythe::new, AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> LYONIC_GREATBLADE = registerWeapon("lyonic_greatblade", () -> new BaseGreatblade(AoATiers.LYONIC_GREATBLADE, AttackSpeed.forAttacksPerSecond(0.9f)), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> MILLENNIUM_GREATBLADE = registerWeapon("millennium_greatblade", MillenniumGreatblade::new, AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> NOXIOUS_GREATBLADE = registerWeapon("noxious_greatblade", NoxiousGreatblade::new, AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> PLUTON_SCYTHE = registerWeapon("pluton_scythe", PlutonScythe::new, AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> PRIMORDIAL_GREATBLADE = registerWeapon("primordial_greatblade", PrimordialGreatblade::new, AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> ROSIDIAN_GREATBLADE = registerWeapon("rosidian_greatblade", RosidianGreatblade::new, AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> ROYAL_GREATBLADE = registerWeapon("royal_greatblade", () -> new BaseGreatblade(AoATiers.ROYAL_GREATBLADE), AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> RUNIC_GREATBLADE = registerWeapon("runic_greatblade", RunicGreatblade::new, AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> SELYAN_SCYTHE = registerWeapon("selyan_scythe", SelyanScythe::new, AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> SHROOMIC_GREATBLADE = registerWeapon("shroomic_greatblade", ShroomicGreatblade::new, AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> SHYRE_SWORD = registerWeapon("shyre_sword", ShyreSword::new, AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> SUBTERRANEAN_GREATBLADE = registerWeapon("subterranean_greatblade", SubterraneanGreatblade::new, AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> TIDAL_GREATBLADE = registerWeapon("tidal_greatblade", TidalGreatblade::new, AoACreativeModeTabs.GREATBLADES.getKey());
	public static final DeferredHolder<Item, Item> UNDERWORLD_GREATBLADE = registerWeapon("underworld_greatblade", UnderworldGreatblade::new, AoACreativeModeTabs.GREATBLADES.getKey());

	public static final DeferredHolder<Item, Item> CORALSTONE_MAUL = registerWeapon("coralstone_maul", () -> new BaseMaul(26.5f, AttackSpeed.THIRD, 8.5d, 1600), AoACreativeModeTabs.MAULS.getKey());
	public static final DeferredHolder<Item, Item> CRYSTAL_MAUL = registerWeapon("crystal_maul", CrystalMaul::new, AoACreativeModeTabs.MAULS.getKey());
	public static final DeferredHolder<Item, Item> ELECTRON_MAUL = registerWeapon("electron_maul", ElectronMaul::new, AoACreativeModeTabs.MAULS.getKey());
	public static final DeferredHolder<Item, Item> HORIZON_MAUL = registerWeapon("horizon_maul", HorizonMaul::new, AoACreativeModeTabs.MAULS.getKey());
	public static final DeferredHolder<Item, Item> VULCAMMER_MAUL = registerWeapon("vulcammer_maul", VulcammerMaul::new, AoACreativeModeTabs.MAULS.getKey());

	public static final DeferredHolder<Item, Item> ABOMINATOR = registerWeapon("abominator", () -> new Abominator(2.625f,4720, 3, 0.8f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> APOCO_ASSAULT_RIFLE = registerWeapon("apoco_assault_rifle", () -> new ApocoAssaultRifle(5.625f, 5920, 6, 0.6f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> APOCO_RIFLE = registerWeapon("apoco_rifle", () -> new ApocoRifle(2.5f, 5960, 6, 1), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> AQUA_MAGNUM = registerWeapon("aqua_magnum", () -> new AquaMagnum(2.0625f, 6080, 2, 0.95f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> ARTIFACT = registerWeapon("artifact", () -> new Artifact(10f, 6000, 5, 0.65f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> BARONATOR = registerWeapon("baronator", () -> new Baronator(3f, 2480, 5, 0.95f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> BAYONETTE_RIFLE = registerWeapon("bayonette_rifle", () -> new BayonetteRifle(3.4375f, 2520, 5, 0.85f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> BIG_TOP = registerWeapon("big_top", () -> new BigTop(3.125f, 3680, 4, 0.9f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> BLOOD_IRON = registerWeapon("blood_iron", () -> new BloodIron(6.125f, 3480, 8, 0.55f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> CHAIN_WRECKER = registerWeapon("chain_wrecker", () -> new ChainWrecker(1.5f, 3840, 2, 1.2f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> CHILLI_CHUGGER = registerWeapon("chilli_chugger", () -> new ChilliChugger(3f, 3560, 4, 0.5f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> CLOWNERSHOT = registerWeapon("clownershot", () -> new Clownershot(2f, 5880, 4, 1.3f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> CONSTRUCT = registerWeapon("construct", () -> new Construct(2.375f, 3640, 3, 0.9f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> CORAL_CLOGGER = registerWeapon("coral_clogger", () -> new CoralClogger(9.075f, 2000, 10, 0.45f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> CORE_RIFLE = registerWeapon("core_rifle", () -> new CoreRifle(1.875f, 2520, 3, 1f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> CRYSTAL_CARVER = registerWeapon("crystal_carver", () -> new CrystalCarver(3f, 3480, 4, 0.85f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> CYCLONE = registerWeapon("cyclone", () -> new Cyclone(2.375f, 4400, 3, 1f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> DARKENER = registerWeapon("darkener", () -> new Darkener(2.875f, 6040, 3, 0.9f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> DART_GUN = registerWeapon("dart_gun", () -> new DartGun(4.675f, 4520, 5, 0.2f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> DESTRUCTION_RIFLE = registerWeapon("destruction_rifle", () -> new DestructionRifle(3.125f, 2440, 5, 1f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> DISCHARGE_RIFLE = registerWeapon("discharge_rifle", () -> new DischargeRifle(1.25f, 2280, 6, 3f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> DRACO = registerWeapon("draco", () -> new Draco(3.75f, 5560, 4, 0.75f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> DRAGILATOR = registerWeapon("dragilator", () -> new Dragilator(1.625f, 4480, 2, 1.1f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> DUSTOMETER = registerWeapon("dustometer", () -> new Dustometer(5.25f, 4720, 6, 0.65f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> ECHO_GULL = registerWeapon("echo_gull", () -> new EchoGull(4.375f, 2320, 7, 0.85f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> ELECTINATOR = registerWeapon("electinator", () -> new Electinator(1.625f, 4480, 2, 1.1f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> FLAME_WRECKER = registerWeapon("flame_wrecker", () -> new FlameWrecker(1.875f, 6120, 2, 1.15f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> FLAMING_FURY = registerWeapon("flaming_fury", () -> new FlamingFury(5.125f, 3440, 7, 0.6f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> FLORO_RIFLE = registerWeapon("floro_rifle", () -> new FloroRifle(3.75f, 6000, 4, 0.75f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> FLOWERS_FURY = registerWeapon("flowers_fury", () -> new FlowersFury(3.25f, 4400,4, 0.9f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> FROSTICATOR = registerWeapon("frosticator", () -> new Frosticator(1.625f, 4480, 2, 1.1f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> GARDENER = registerWeapon("gardener", () -> new Gardener(1.75f, 2520, 3, 1f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> GAUGE_RIFLE = registerWeapon("gauge_rifle", () -> new GaugeRifle(5.625f, 2360, 9, 0.85f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> GERMINATOR = registerWeapon("germinator", () -> new Germinator(1.625f, 4480, 2, 1.1f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> GOLDEN_FURY = registerWeapon("golden_fury", () -> new GoldenFury(6.5f, 6080, 7, 0.45f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> HAPPY_HAUNTER = registerWeapon("happy_haunter", () -> new HappyHaunter(2.875f, 6040, 3, 0.85f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> HAUNTER_RIFLE = registerWeapon("haunter_rifle", () -> new HaunterRifle(2.75f, 5680, 3, 0.9f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> HEAT_WAVE = registerWeapon("heat_wave", () -> new HeatWave(6.05f, 5880, 6, 0.8f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> HIVER = registerWeapon("hiver", () -> new Hiver(2.875f, 5960, 3, 1f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> HOT_SHOT = registerWeapon("hot_shot", () -> new HotShot(3.9875f, 2320, 6, 1f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> HUNTERS_RIFLE = registerWeapon("hunters_rifle", () -> new HuntersRifle(5.9125f, 3600, 7, 0.9f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> IOMINATOR = registerWeapon("iominator", () -> new Iominator(2.875f, 6000, 3, 0.95f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> ION_REVOLVER = registerWeapon("ion_revolver", () -> new IonRevolver(2.6125f, 3720, 3, 1.65f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> IRO_RIFLE = registerWeapon("iro_rifle", () -> new IroRifle(3.125f, 3640, 4, 0.95f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> KRILINATOR = registerWeapon("krilinator", () -> new Krilinator(3.75f, 3600, 5, 1.1f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> LIGHT_IRON = registerWeapon("light_iron", () -> new LightIron(7.625f, 5880, 8, 0.6f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> LUNAR_ASSAULT_RIFLE = registerWeapon("lunar_assault_rifle", () -> new LunarAssaultRifle(2.875f, 5720, 3, 0.85f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> MECHANICAL_ASSAULT_RIFLE = registerWeapon("mechanical_assault_rifle", () -> new MechanicalAssaultRifle(4.625f, 3760, 6, 0.85f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> MEGAGUN = registerWeapon("megagun", () -> new Megagun(1f, 6120, 1, 1.1f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> MIASMA = registerWeapon("miasma", () -> new Miasma(2.25f, 3760, 3, 1), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> MINIGUN = registerWeapon("minigun", () -> new Minigun(0.625f, 2680, 1, 1.5f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> MINT_MAGNUM = registerWeapon("mint_magnum", () -> new MintMagnum(1.65f, 3600, 2, 1.25f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> MK = registerWeapon("mk", () -> new MK(3.625f, 4960, 4, 0.75f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> MK_FUNG = registerWeapon("mk_fung", () -> new MKFung(3.75f, 5960, 4, 0.75f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> NETHENETTE_RIFLE = registerWeapon("nethenette_rifle", () -> new NethenetteRifle(5.0875f, 6000, 5, 0.85f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> NETHENGEIC_SLUGGER = registerWeapon("nethengeic_slugger", () -> new NethengeicSlugger(6.1875f, 3120, 8, 0.75f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> OVERSHOT = registerWeapon("overshot", () -> new Overshot(1.625f, 3960, 4, 2.1f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> PRECASIAN_SLUGGER = registerWeapon("precasian_slugger", () -> new PrecasianSlugger(8.1125f, 5960, 8, 0.5f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> PREDATOR = registerWeapon("predator", () -> new Predator(6.375f, 5920, 7, 0.45f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> PREDIGUN = registerWeapon("predigun", () -> new Predigun(1f, 6120, 1, 1f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> PULSATOR = registerWeapon("pulsator", () -> new Pulsator(6.25f, 4760, 7, 0.5f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> PURITY_RIFLE = registerWeapon("purity_rifle", () -> new PurityRifle(4.5f, 4800, 5, 0.75f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> ROCKER_RIFLE = registerWeapon("rocker_rifle", () -> new RockerRifle(2.5f, 2520, 4, 1f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> ROULETTE = registerWeapon("roulette", () -> new Roulette(6.1875f, 5880, 6, 0.85f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> SHOE_FLINGER = registerWeapon("shoe_flinger", () -> new ShoeFlinger(6f, 1600, 6, 1f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> SKULLETTE = registerWeapon("skullette", () -> new Skullette(6.4625f, 6320, 6, 0.85f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> SKULLIFACT = registerWeapon("skullifact", () -> new Skullifact(10f, 6280, 5, 0.45f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> SPECTACLE = registerWeapon("spectacle", () -> new Spectacle(2.75f, 3520, 4, 0.85f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> SPINE_GUN = registerWeapon("spine_gun", () -> new SpineGun(2.875f, 6040, 3, 0.85f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> SQUAD_GUN = registerWeapon("squad_gun", () -> new SquadGun(2.625f, 4840, 3, 0.85f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> STAMPEDE = registerWeapon("stampede", () -> new Stampede(3.3f, 1200, 6, 1f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> STORMER = registerWeapon("stormer", () -> new Stormer(8f, 3600, 5, 0.45f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> SUBLIMUS = registerWeapon("sublimus", () -> new Sublimus(2.75f, 6120,3, 0.9f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> TIGER_TOMMY = registerWeapon("tiger_tommy", () -> new TigerTommy(2.875f, 5960, 3, 0.7f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> TOMMY = registerWeapon("tommy", () -> new Tommy(1.5f, 1320, 3, 1.3f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> VILE_VANQUISHER = registerWeapon("vile_vanquisher", () -> new VileVanquisher(2.75f, 3320, 4, 1f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> WART_GUN = registerWeapon("wart_gun", () -> new WartGun(4.5375f, 2320, 7, 0.2f), AoACreativeModeTabs.GUNS.getKey());
	public static final DeferredHolder<Item, Item> WRECKER = registerWeapon("wrecker", () -> new Wrecker(2.375f, 3680, 3, 1.1f), AoACreativeModeTabs.GUNS.getKey());
	
	public static final DeferredHolder<Item, Item> ABYSSRO = registerWeapon("abyssro", () -> new BaseShotgun(18.5f, 2, 1100, 46, 0.3f, 0.2f), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredHolder<Item, Item> AMPLIFIER = registerWeapon("amplifier", () -> new Amplifier(9.0f, 5, 1100, 56, 0.2f, 0.7f), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredHolder<Item, Item> BLAST_BARREL = registerWeapon("blast_barrel", () -> new BlastBarrel(13.0f, 3, 740, 62, 0.4f, 0.4f), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredHolder<Item, Item> BLUE_BARREL = registerWeapon("blue_barrel", () -> new BaseShotgun(14.5f, 3, 1120, 54, 0.4f, 0.4f), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredHolder<Item, Item> BOULDER = registerWeapon("boulder", () -> new BaseShotgun(11.5f, 4,1080, 58, 0.4f, 0.5f), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredHolder<Item, Item> BROWN_BLASTER = registerWeapon("brown_blaster", () -> new BaseShotgun(6.0f, 3, 300, 54, 0.4f, 0.9f), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredHolder<Item, Item> DEMOLISHER = registerWeapon("demolisher", () -> new Demolisher(8.5f, 4, 730, 58, 0.4f, 0.65f), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredHolder<Item, Item> DESTRUCTION_SHOTGUN = registerWeapon("destruction_shotgun", () -> new DestructionShotgun(10.5f, 3, 690, 56, 0.4f, 0.45f), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredHolder<Item, Item> DISCHARGE_SHOTGUN = registerWeapon("discharge_shotgun", () -> new DischargeShotgun(0.0f, 4, 160, 55, 0f, 13f), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredHolder<Item, Item> GIMMICK = registerWeapon("gimmick", () -> new Gimmick(4.5f, 10, 800, 68, 0.2f, 1.3f), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredHolder<Item, Item> GINGER_BLASTER = registerWeapon("ginger_blaster", () -> new GingerBlaster(7.0f, 5, 720, 60, 0.4f, 0.75f), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredHolder<Item, Item> LONG_SHOT = registerWeapon("long_shot", () -> new LongShot(15.5f, 2, 730, 54, 0.2f, 0.3f), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredHolder<Item, Item> MECHYRO = registerWeapon("mechyro", () -> new Mechyro(13.0f, 2, 720, 46, 0.3f, 0.3f), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredHolder<Item, Item> PURITY_SHOTGUN = registerWeapon("purity_shotgun", () -> new PurityShotgun(14.0f, 3, 1090, 56, 0.4f, 0.25f), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredHolder<Item, Item> PURPLE_PUNISHER = registerWeapon("purple_punisher", () -> new BaseShotgun(20.5f, 2, 1120, 52, 0.785f, 0.2f), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredHolder<Item, Item> RED_ROCKET = registerWeapon("red_rocket", () -> new BaseShotgun(11.5f, 2, 500, 52, 0.785f, 0.4f), AoACreativeModeTabs.SHOTGUNS.getKey());
	public static final DeferredHolder<Item, Item> VIVO = registerWeapon("vivo", () -> new Vivo(7.0f, 3, 710, 36, 0.3f, 0.8f), AoACreativeModeTabs.SHOTGUNS.getKey());

	public static final DeferredHolder<Item, Item> BARON_SSR = registerWeapon("baron_ssr", () -> new BaronSSR(35.0f, 240, 88, 0.05f), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredHolder<Item, Item> BAYONETTE_SR = registerWeapon("bayonette_sr", () -> new BayonetteSR(33.0f, 300, 86, 0.06f), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredHolder<Item, Item> BOLT_RIFLE = registerWeapon("bolt_rifle", () -> new BoltRifle(30.0f, 100, 100, 0.06f), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredHolder<Item, Item> CAMO_RIFLE = registerWeapon("camo_rifle", () -> new CamoRifle(31.5f, 150, 84, 0.06f), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredHolder<Item, Item> CLOWN_CRACKER = registerWeapon("clown_cracker", () -> new ClownCracker(33.5f, 305, 84, 0.05f), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredHolder<Item, Item> CLOWNIMATOR = registerWeapon("clownimator", () -> new Clownimator(49.5f, 545, 95, 0.035f), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredHolder<Item, Item> CRYSTANEER = registerWeapon("crystaneer", () -> new Crystaneer(37.5f, 345, 88, 0.042f), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredHolder<Item, Item> DARK_BEAST = registerWeapon("dark_beast", () -> new DarkBeast(50.5f, 560, 96, 0.035f), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredHolder<Item, Item> DEADLOCK = registerWeapon("deadlock", () -> new Deadlock(25.5f, 120, 90, 0.09f), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredHolder<Item, Item> DECIMATOR = registerWeapon("decimator", () -> new Decimator(33.0f, 180, 95, 0.05f), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredHolder<Item, Item> DISCHARGE_SNIPER = registerWeapon("discharge_sniper", () -> new DischargeSniper(10.0f, 540, 24, 0.4f), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredHolder<Item, Item> DUAL_SIGHT = registerWeapon("dual_sight", () -> new DualSight(38.5f, 350, 91, 0.042f), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredHolder<Item, Item> DUSTER = registerWeapon("duster", () -> new Duster(21.0f, 170, 60, 0.09f), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredHolder<Item, Item> FLORO500 = registerWeapon("floro500", () -> new Floro500(37.0f, 550, 70, 0.042f), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredHolder<Item, Item> HEAD_HUNTER = registerWeapon("head_hunter", () -> new HeadHunter(41.5f, 380, 92, 0.035f), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredHolder<Item, Item> HIVE_CRACKER = registerWeapon("hive_cracker", () -> new HiveCracker(44.0f, 555, 84, 0.035f), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredHolder<Item, Item> KA_500 = registerWeapon("ka_500", () -> new Ka500(30.0f, 360, 70, 0.06f), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredHolder<Item, Item> MARK_MAKER = registerWeapon("mark_maker", () -> new MarkMaker(36.5f, 530, 70, 0.05f), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredHolder<Item, Item> MINERAL = registerWeapon("mineral", () -> new Mineral(58.5f, 560, 112, 0.035f), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredHolder<Item, Item> MONSTER = registerWeapon("monster", () -> new Monster(38.0f, 250, 96, 0.05f), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredHolder<Item, Item> MOON_MAKER = registerWeapon("moon_maker", () -> new MoonMaker(38.5f, 570, 70, 0.05f), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredHolder<Item, Item> ROSID_RIFLE = registerWeapon("rosid_rifle", () -> new RosidRifle(45.5f, 405, 102, 0.035f), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredHolder<Item, Item> SABBATH = registerWeapon("sabbath", () -> new Sabbath(44.0f, 450, 97, 0.035f), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredHolder<Item, Item> SLUDGE_SNIPER = registerWeapon("sludge_sniper", () -> new SludgeSniper(37.0f, 350, 87, 0.05f), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredHolder<Item, Item> SWEET_TOOTH = registerWeapon("sweet_tooth", () -> new SweetTooth(32.5f, 460, 77, 0.05f), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredHolder<Item, Item> TERMINATOR = registerWeapon("terminator", () -> new Terminator(53.0f, 470, 112, 0.035f), AoACreativeModeTabs.SNIPERS.getKey());
	public static final DeferredHolder<Item, Item> VIPER_1 = registerWeapon("viper_1", () -> new Viper1(30.0f, 185, 89, 0.06f), AoACreativeModeTabs.SNIPERS.getKey());

	public static final DeferredHolder<Item, Item> ANCIENT_BOMBER = registerWeapon("ancient_bomber", () -> new AncientBomber(23.5f, 855, 28, 0.175f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> ANCIENT_DISCHARGER = registerWeapon("ancient_discharger", () -> new AncientDischarger(0.0f, 850, 20, 13f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> AQUA_CANNON = registerWeapon("aqua_cannon", () -> new AquaCannon(14.0f, 300, 35, 0.21f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> BALLOON_BOMBER = registerWeapon("balloon_bomber", () -> new BalloonBomber(12.5f, 505, 24, 0.22f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> BIG_BLAST = registerWeapon("big_blast", () -> new BigBlast(28.0f, 550, 60, 0.12f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> BLAST_CANNON = registerWeapon("blast_cannon", () -> new BlastCannon(17.0f, 510, 27, 0.21f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> BLISSFUL_BLAST = registerWeapon("blissful_blast", () -> new BlissfulBlast(33.5f, 835, 60, 0.09f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> BOMB_LAUNCHER = registerWeapon("bomb_launcher", () -> new BombLauncher(23.0f, 840, 27, 0.175f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> BOOM_BOOM = registerWeapon("boom_boom", () -> new BoomBoom(18.5f, 390, 36, 0.21f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> BOOM_CANNON = registerWeapon("boom_cannon", () -> new BoomCannon(17.5f, 510, 28, 0.21f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> BOULDER_BOMBER = registerWeapon("boulder_bomber", () -> new BoulderBomber(18.5f,475, 62, 0.21f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> BOZO_BLASTER = registerWeapon("bozo_blaster", () -> new BozoBlaster(12.5f, 505, 20, 0.21f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> BULB_CANNON = registerWeapon("bulb_cannon", () -> new BulbCannon(25.0f, 860, 30, 0.15f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> CARROT_CANNON = registerWeapon("carrot_cannon", () -> new CarrotCannon(10.0f, 520, 16, 0.4f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> CLOWN_CANNON = registerWeapon("clown_cannon", () -> new ClownCannon(22.5f, 570, 32, 0.18f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> CLOWNO_PULSE = registerWeapon("clowno_pulse", () -> new ClownoPulse(35.5f, 845, 42, 0.09f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> CORAL_CANNON = registerWeapon("coral_cannon", () -> new CoralCannon(12.0f, 300, 15, 0.35f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> DISCHARGE_CANNON = registerWeapon("discharge_cannon", () -> new DischargeCannon(0.0f, 400, 20, 6.0f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> ENERGY_CANNON = registerWeapon("energy_cannon", () -> new EnergyCannon(18.5f, 610, 25, 0.21f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> EREBON_STICKLER = registerWeapon("erebon_stickler", () -> new ErebonStickler(35.0f, 750, 48, 0.09f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> FLORO_RPG = registerWeapon("floro_rpg", () -> new FloroRPG(18.0f, 830, 50, 0.21f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> FLOWER_CANNON = registerWeapon("flower_cannon", () -> new FlowerCannon(14.5f, 510, 23, 0.21f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> FUNGAL_CANNON = registerWeapon("fungal_cannon", () -> new FungalCannon(19.5f, 850, 23, 0.2f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> GHAST_BLASTER = registerWeapon("ghast_blaster", () -> new GhastBlaster(20.0f, 600, 28, 0.2f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> GHOUL_CANNON = registerWeapon("ghoul_cannon", () -> new GhoulCannon(25.5f, 590, 34, 0.15f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> GIGA_CANNON = registerWeapon("giga_cannon", () -> new GigaCannon(25.5f, 700, 30, 0.15f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> GOLDER_BOMBER = registerWeapon("golder_bomber", () -> new GolderBomber(26.0f, 840, 62, 0.15f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> HIVE_BLASTER = registerWeapon("hive_blaster", () -> new HiveBlaster(20.5f, 850, 24, 0.2f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> HIVE_HOWITZER = registerWeapon("hive_howitzer", () -> new HiveHowitzer(13.0f, 375, 24, 0.35f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> IRO_CANNON = registerWeapon("iro_cannon", () -> new IroCannon(25.5f, 580, 36, 0.15f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> JACK_FUNGER = registerWeapon("jack_funger", () -> new JackFunger(17.0f, 860, 20, 0.21f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> JACK_ROCKER = registerWeapon("jack_rocker", () -> new JackRocker(10.5f, 400, 20, 0.4f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> LUXON_STICKLER = registerWeapon("luxon_stickler", () -> new LuxonStickler(35.0f, 750, 48, 0.09f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> MECHA_CANNON = registerWeapon("mecha_cannon", () -> new MechaCannon(26.5f, 525, 42, 0.15f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> MINI_CANNON = registerWeapon("mini_cannon", () -> new MiniCannon(15.0f, 415, 30, 0.21f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> MISSILE_MAKER = registerWeapon("missile_maker", () -> new MissileMaker(0.0f, 495, 60, 7f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> MOON_CANNON = registerWeapon("moon_cannon", () -> new MoonCannon(21.0f, 855, 25, 0.18f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> PLUTON_STICKLER = registerWeapon("pluton_stickler", () -> new PlutonStickler(35.0f, 750, 48, 0.09f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> PREDATORIAN_BLASTER = registerWeapon("predatorian_blaster", () -> new PredatorianBlaster(23.5f, 845, 28, 0.175f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> PULSE_CANNON = registerWeapon("pulse_cannon", () -> new PulseCannon(26.0f, 510, 42, 0.15f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> RPG = registerWeapon("rpg", () -> new RPG(8, 320, 50, 0.35f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> SELYAN_STICKLER = registerWeapon("selyan_stickler", () -> new SelyanStickler(35.0f, 750, 48, 0.09f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> SHADOW_BLASTER = registerWeapon("shadow_blaster", () -> new ShadowBlaster(15.0f, 515, 24, 0.21f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> SHYRE_BLASTER = registerWeapon("shyre_blaster", () -> new ShyreBlaster(25.5f, 850, 30, 0.15f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> SMILE_BLASTER = registerWeapon("smile_blaster", () -> new SmileBlaster(20.5f, 840, 24, 0.2f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> SUPER_CANNON = registerWeapon("super_cannon", () -> new SuperCannon(18.5f, 510, 30, 0.21f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> ULTRA_CANNON = registerWeapon("ultra_cannon", () -> new UltraCannon(22.5f, 605, 30, 0.18f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> VOX_CANNON = registerWeapon("vox_cannon", () -> new VoxCannon(15.0f, 440, 26, 0.21f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> WATER_BALLOON_BOMBER = registerWeapon("water_balloon_bomber", () -> new WaterBalloonBomber(20.5f, 855, 24, 0.2f), AoACreativeModeTabs.CANNONS.getKey());
	public static final DeferredHolder<Item, Item> WITHER_CANNON = registerWeapon("wither_cannon", () -> new WitherCannon(17.0f, 460, 30, 0.21f), AoACreativeModeTabs.CANNONS.getKey());

	public static final DeferredHolder<Item, Grenade> GRENADE = registerWeapon("grenade", Grenade::new, AoACreativeModeTabs.THROWN_WEAPONS.getKey());
	public static final DeferredHolder<Item, SliceStar> SLICE_STAR = registerWeapon("slice_star", SliceStar::new, AoACreativeModeTabs.THROWN_WEAPONS.getKey());
	public static final DeferredHolder<Item, Chakram> CHAKRAM = registerWeapon("chakram", Chakram::new, AoACreativeModeTabs.THROWN_WEAPONS.getKey());
	public static final DeferredHolder<Item, GooBall> GOO_BALL = registerWeapon("goo_ball", GooBall::new, AoACreativeModeTabs.THROWN_WEAPONS.getKey());
	public static final DeferredHolder<Item, Vulkram> VULKRAM = registerWeapon("vulkram", Vulkram::new, AoACreativeModeTabs.THROWN_WEAPONS.getKey());
	public static final DeferredHolder<Item, Hellfire> HELLFIRE = registerWeapon("hellfire", Hellfire::new, AoACreativeModeTabs.THROWN_WEAPONS.getKey());
	public static final DeferredHolder<Item, RunicBomb> RUNIC_BOMB = registerWeapon("runic_bomb", RunicBomb::new, AoACreativeModeTabs.THROWN_WEAPONS.getKey());
	public static final DeferredHolder<Item, HardenedParapiranha> HARDENED_PARAPIRANHA = registerWeapon("hardened_parapiranha", HardenedParapiranha::new, AoACreativeModeTabs.THROWN_WEAPONS.getKey());

	public static final DeferredHolder<Item, Item> VULCANE = registerWeapon("vulcane", () -> new Vulcane(10, 50), AoACreativeModeTabs.VULCANES.getKey());
	public static final DeferredHolder<Item, Item> BATTLE_VULCANE = registerWeapon("battle_vulcane", () -> new BattleVulcane(10, 75), AoACreativeModeTabs.VULCANES.getKey());
	public static final DeferredHolder<Item, Item> EQUALITY_VULCANE = registerWeapon("equality_vulcane", () -> new EqualityVulcane(10, 75), AoACreativeModeTabs.VULCANES.getKey());
	public static final DeferredHolder<Item, Item> FIRE_VULCANE = registerWeapon("fire_vulcane", () -> new FireVulcane(10, 75), AoACreativeModeTabs.VULCANES.getKey());
	public static final DeferredHolder<Item, Item> IMPAIRMENT_VULCANE = registerWeapon("impairment_vulcane", () -> new ImpairmentVulcane(10, 75), AoACreativeModeTabs.VULCANES.getKey());
	public static final DeferredHolder<Item, Item> POISON_VULCANE = registerWeapon("poison_vulcane", () -> new PoisonVulcane(10, 75), AoACreativeModeTabs.VULCANES.getKey());
	public static final DeferredHolder<Item, Item> POWER_VULCANE = registerWeapon("power_vulcane", () -> new PowerVulcane(10, 75), AoACreativeModeTabs.VULCANES.getKey());
	public static final DeferredHolder<Item, Item> WITHER_VULCANE = registerWeapon("wither_vulcane", () -> new WitherVulcane(10, 75), AoACreativeModeTabs.VULCANES.getKey());
	
	public static final DeferredHolder<Item, Item> ALACRITY_BOW = registerWeapon("alacrity_bow", () -> new BaseBow(9.5f, 1f, 600), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> ANCIENT_BOW = registerWeapon("ancient_bow", () -> new BaseBow(22.0f, 1f, 1510), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> ATLANTIC_BOW = registerWeapon("atlantic_bow", () -> new BaseBow(24.5f, 0.9f, 1480), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> BARON_BOW = registerWeapon("baron_bow", () -> new BaronBow(12.0f, 1.1f, 3000), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> BOREIC_BOW = registerWeapon("boreic_bow", () -> new BoreicBow(14.0f, 1.3f, 1190), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> DAYBREAKER_BOW = registerWeapon("daybreaker_bow", () -> new DaybreakerBow(17.5f, 1f, 1180), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> DEEP_BOW = registerWeapon("deep_bow", () -> new DeepBow(15.5f, 0.85f, 700), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> EXPLOSIVE_BOW = registerWeapon("explosive_bow", () -> new ExplosiveBow(17.0f, 0.8f, 900), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> HAUNTED_BOW = registerWeapon("haunted_bow", () -> new HauntedBow(17.0f,1f, 920), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> ICE_BOW = registerWeapon("ice_bow", () -> new IceBow(8.5f, 1f, 580), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> INFERNAL_BOW = registerWeapon("infernal_bow", () -> new InfernalBow(11.5f, 1f, 710), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> JUSTICE_BOW = registerWeapon("justice_bow", () -> new JusticeBow(14.5f,1f, 920), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> LUNAR_BOW = registerWeapon("lunar_bow", () -> new LunarBow(17.5f, 1f, 900), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> MECHA_BOW = registerWeapon("mecha_bow", () -> new BaseBow(20.5f,0.75f, 930), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> NIGHTMARE_BOW = registerWeapon("nightmare_bow", () -> new NightmareBow(13.5f,1f, 890), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> POISON_BOW = registerWeapon("poison_bow", () -> new PoisonBow(15.0f, 1f, 950), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> PREDATIOUS_BOW = registerWeapon("predatious_bow", () -> new PredatiousBow(14.0f, 0.9f, 690), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> PRIMORDIAL_BOW = registerWeapon("primordial_bow", () -> new PrimordialBow(18.5f,1f, 1350), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> ROSIDIAN_BOW = registerWeapon("rosidian_bow", () -> new RosidianBow(15.5f, 1f, 900), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> RUNIC_BOW = registerWeapon("runic_bow", () -> new RunicBow(20.5f,1f, 1320), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> SCREAMER_BOW = registerWeapon("screamer_bow", () -> new ScreamerBow(12.0f, 1f, 665), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> SHYREGEM_BOW = registerWeapon("shyregem_bow", () -> new ShyregemBow(7.5f, 3.0f, 1500), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> SKELETAL_BOW = registerWeapon("skeletal_bow", () -> new BaseBow(8.5f, 1.5f, 720), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> SKYDRIVER_BOW = registerWeapon("skydriver_bow", () -> new SkydriverBow(14.5f, 1f, 850), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> SLINGSHOT = registerWeapon("slingshot", () -> new Slingshot(17.0f, 1f, 1200), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> SOULFIRE_BOW = registerWeapon("soulfire_bow", () -> new SoulfireBow(23.5f, 0.75f, 1100), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> SPECTRAL_BOW = registerWeapon("spectral_bow", () -> new SpectralBow(12.0f, 1.3f, 900), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> SPEED_BOW = registerWeapon("speed_bow", () -> new BaseBow(8.0f, 2, 930), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> SUNSHINE_BOW = registerWeapon("sunshine_bow", () -> new SunshineBow(27.0f, 0.8f, 1530), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> TOXIN_BOW = registerWeapon("toxin_bow", () -> new ToxinBow(14.0f, 0.85f, 900), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> VOID_BOW = registerWeapon("void_bow", () -> new BaseBow(9.0f, 1.2f, 600), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> WEAKEN_BOW = registerWeapon("weaken_bow", () -> new WeakenBow(12.5f, 1f, 700), AoACreativeModeTabs.BOWS.getKey());
	public static final DeferredHolder<Item, Item> WITHER_BOW = registerWeapon("wither_bow", () -> new WitherBow(13.5f, 1f, 835), AoACreativeModeTabs.BOWS.getKey());
	
	public static final DeferredHolder<Item, Item> CORAL_CROSSBOW = registerWeapon("coral_crossbow", () -> new CoralCrossbow(17f, 1080), AoACreativeModeTabs.CROSSBOWS.getKey());
	public static final DeferredHolder<Item, Item> LUNAR_CROSSBOW = registerWeapon("lunar_crossbow", () -> new LunarCrossbow(16.5f, 1100), AoACreativeModeTabs.CROSSBOWS.getKey());
	public static final DeferredHolder<Item, Item> MECHA_CROSSBOW = registerWeapon("mecha_crossbow", () -> new BaseCrossbow(15f, 930), AoACreativeModeTabs.CROSSBOWS.getKey());
	public static final DeferredHolder<Item, Item> PYRO_CROSSBOW = registerWeapon("pyro_crossbow", () -> new PyroCrossbow(12f, 800), AoACreativeModeTabs.CROSSBOWS.getKey());
	public static final DeferredHolder<Item, Item> ROSIDIAN_CROSSBOW = registerWeapon("rosidian_crossbow", () -> new RosidianCrossbow(14.5f, 900), AoACreativeModeTabs.CROSSBOWS.getKey());
	public static final DeferredHolder<Item, Item> SKELETAL_CROSSBOW = registerWeapon("skeletal_crossbow", () -> new BaseCrossbow(12.5f, 860), AoACreativeModeTabs.CROSSBOWS.getKey());
	public static final DeferredHolder<Item, Item> SPECTRAL_CROSSBOW = registerWeapon("spectral_crossbow", () -> new SpectralCrossbow(15f, 1030), AoACreativeModeTabs.CROSSBOWS.getKey());
	public static final DeferredHolder<Item, Item> TROLLS_CROSSBOW = registerWeapon("trolls_crossbow", () -> new BaseCrossbow(10.5f, 700), AoACreativeModeTabs.CROSSBOWS.getKey());
	public static final DeferredHolder<Item, Item> VIRAL_CROSSBOW = registerWeapon("viral_crossbow", () -> new ViralCrossbow(11f, 780), AoACreativeModeTabs.CROSSBOWS.getKey());

	public static final DeferredHolder<Item, Item> AQUATIC_STAFF = registerWeapon("aquatic_staff", () -> new AquaticStaff(1220), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> ATLANTIC_STAFF = registerWeapon("atlantic_staff", () -> new AtlanticStaff(1250), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> BARON_STAFF = registerWeapon("baron_staff", () -> new BaronStaff(1200), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> CANDY_STAFF = registerWeapon("candy_staff", () -> new CandyStaff(950), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> CELESTIAL_STAFF = registerWeapon("celestial_staff", () -> new CelestialStaff(1150), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> CONCUSSION_STAFF = registerWeapon("concussion_staff", () -> new ConcussionStaff(1150), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> CORAL_STAFF = registerWeapon("coral_staff", () -> new CoralStaff(950), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> CRYSTAL_STAFF = registerWeapon("crystal_staff", () -> new CrystalStaff(1230), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> CRYSTIK_STAFF = registerWeapon("crystik_staff", () -> new CrystikStaff(1140), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> CRYSTON_STAFF = registerWeapon("cryston_staff", () -> new CrystonStaff(1240), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> DESTRUCTION_STAFF = registerWeapon("destruction_staff", () -> new DestructionStaff(1170), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> EMBER_STAFF = registerWeapon("ember_staff", () -> new EmberStaff(1400), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> EVERFIGHT_STAFF = registerWeapon("everfight_staff", () -> new EverfightStaff(1050), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> EVERMIGHT_STAFF = registerWeapon("evermight_staff", () -> new EvermightStaff(1050), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> FIRE_STAFF = registerWeapon("fire_staff", () -> new FireStaff(850), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> FIREFLY_STAFF = registerWeapon("firefly_staff", () -> new FireflyStaff(1230), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> FIRESTORM_STAFF = registerWeapon("firestorm_staff", () -> new FirestormStaff(990), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> FUNGAL_STAFF = registerWeapon("fungal_staff", () -> new FungalStaff(1130), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> GHOUL_STAFF = registerWeapon("ghoul_staff", () -> new GhoulStaff(400), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> HAUNTERS_STAFF = registerWeapon("haunters_staff", () -> new HauntersStaff(1225), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> HIVE_STAFF = registerWeapon("hive_staff", () -> new HiveStaff(1130), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> JOKER_STAFF = registerWeapon("joker_staff", () -> new JokerStaff(300), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> AMBER_STAFF = registerWeapon("amber_staff", () -> new AmberStaff(900), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> LIGHTNING_STAFF = registerWeapon("lightning_staff", () -> new LightningStaff(1070), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> LIGHTSHINE = registerWeapon("lightshine", () -> new Lightshine(700), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> LUNAR_STAFF = registerWeapon("lunar_staff", () -> new LunarStaff(1250), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> LYONIC_STAFF = registerWeapon("lyonic_staff", () -> new LyonicStaff(1100), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> MECHA_STAFF = registerWeapon("mecha_staff", () -> new MechaStaff(1110), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> METEOR_STAFF = registerWeapon("meteor_staff", () -> new MeteorStaff(1190), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> MOONLIGHT_STAFF = registerWeapon("moonlight_staff", () -> new MoonlightStaff(1130), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> NATURE_STAFF = registerWeapon("nature_staff", () -> new NatureStaff(1450), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> NIGHTMARE_STAFF = registerWeapon("nightmare_staff", () -> new NightmareStaff(1200), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> NOXIOUS_STAFF = registerWeapon("noxious_staff", () -> new NoxiousStaff(1210), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> PHANTOM_STAFF = registerWeapon("phantom_staff", () -> new PhantomStaff(1060), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> POISON_STAFF = registerWeapon("poison_staff", () -> new PoisonStaff(850), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> POWER_STAFF = registerWeapon("power_staff", () -> new PowerStaff(1010), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> PRIMORDIAL_STAFF = registerWeapon("primordial_staff", () -> new PrimordialStaff(1230), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> REEF_STAFF = registerWeapon("reef_staff", () -> new ReefStaff(1230), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> REJUVENATION_STAFF = registerWeapon("rejuvenation_staff", () -> new RejuvenationStaff(870), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> ROSIDIAN_STAFF = registerWeapon("rosidian_staff", () -> new RosidianStaff(1180), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> RUNIC_STAFF = registerWeapon("runic_staff", () -> new RunicStaff(1000), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> SHADOWLORD_STAFF = registerWeapon("shadowlord_staff", () -> new ShadowlordStaff(1200), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> SHOW_STAFF = registerWeapon("show_staff", () -> new ShowStaff(900), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> SHYRE_STAFF = registerWeapon("shyre_staff", () -> new ShyreStaff(1380), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> SKY_STAFF = registerWeapon("sky_staff", () -> new SkyStaff(1480), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> STRIKER_STAFF = registerWeapon("striker_staff", () -> new StrikerStaff(850), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> SUN_STAFF = registerWeapon("sun_staff", () -> new SunStaff(960), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> SURGE_STAFF = registerWeapon("surge_staff", () -> new SurgeStaff(1270), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> TANGLE_STAFF = registerWeapon("tangle_staff", () -> new TangleStaff(1140), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> ULTIMATUM_STAFF = registerWeapon("ultimatum_staff", () -> new UltimatumStaff(750), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> UNDERWORLD_STAFF = registerWeapon("underworld_staff", () -> new UnderworldStaff(1140), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> WARLOCK_STAFF = registerWeapon("warlock_staff", () -> new WarlockStaff(1050), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> WATER_STAFF = registerWeapon("water_staff", () -> new WaterStaff(850), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> WEB_STAFF = registerWeapon("web_staff", () -> new WebStaff(1420), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> WIND_STAFF = registerWeapon("wind_staff", () -> new WindStaff(850), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> WITHER_STAFF = registerWeapon("wither_staff", () -> new WitherStaff(850), AoACreativeModeTabs.STAVES.getKey());
	public static final DeferredHolder<Item, Item> WIZARDS_STAFF = registerWeapon("wizards_staff", () -> new WizardsStaff(800), AoACreativeModeTabs.STAVES.getKey());

	public static final DeferredHolder<Item, Item> APOCO_SHOWER = registerWeapon("apoco_shower", () -> new ApocoShower(0.0f, 3760, 10, 80f), AoACreativeModeTabs.BLASTERS.getKey());// TODO
	public static final DeferredHolder<Item, Item> ATOMIZER = registerWeapon("atomizer", () -> new Atomizer(11.0f, 3150, 8, 15f), AoACreativeModeTabs.BLASTERS.getKey());// TODO
	public static final DeferredHolder<Item, Item> BEAMER = registerWeapon("beamer", () -> new Beamer(1.0f, 3240, 1, 3f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> BLAST_CHILLER = registerWeapon("blast_chiller", () -> new BlastChiller(4.0f, 1750, 6, 20f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> BLOOD_DRAINER = registerWeapon("blood_drainer", () -> new BloodDrainer(0.1f, 2750, 1, 2.5f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> BONE_BLASTER = registerWeapon("bone_blaster", () -> new BoneBlaster(6.0f, 2430, 6, 20f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> BUBBLE_HORN = registerWeapon("bubble_horn", () -> new BubbleHorn(11.0f, 3200, 8, 15.5f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> COLOUR_CANNON = registerWeapon("colour_cannon", () -> new ColourCannon(45.0f, 1000, 40, 110f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> CONFETTI_CANNON = registerWeapon("confetti_cannon", () -> new ConfettiCannon(0.0f, 1000, 10, 0f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> CONFETTI_CLUSTER = registerWeapon("confetti_cluster", () -> new ConfettiCluster(0.0f, 1500, 5, 0f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> DARK_DESTROYER = registerWeapon("dark_destroyer", () -> new DarkDestroyer(0.0f, 3180, 100, 80f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> DARKLY_GUSTER = registerWeapon("darkly_guster", () -> new DarklyGuster(8.0f, 3790,5, 7f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> DEATH_RAY = registerWeapon("death_ray", () -> new DeathRay(19f, 3840, 12, 17f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> DOOM_BRINGER = registerWeapon("doom_bringer", () -> new DoomBringer(0.0f, 2820, 3, 15.5f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> ERADICATOR = registerWeapon("eradicator", () -> new Eradicator(1.0f, 2790, 1, 2f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> EXPERIMENT_W_801 = registerWeapon("experiment_w_801", () -> new ExperimentW801(37.0f, 5000, 50, 90.0f), (ResourceKey<CreativeModeTab>[])null);
	public static final DeferredHolder<Item, Item> FLOWERCORNE = registerWeapon("flowercorne", () -> new Flowercorne(2.5f, 2910, 4, 20f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> FRAGMENT = registerWeapon("fragment", () -> new Fragment(3.0f, 3830,2, 2.5f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> FROSTER = registerWeapon("froster", () -> new Froster(3.5f, 2800, 3, 7.5f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> GAS_BLASTER = registerWeapon("gas_blaster", () -> new GasBlaster(0.0f, 2860, 1, 0.5f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> GHOUL_GASSER = registerWeapon("ghoul_gasser", () -> new GhoulGasser(0.0f, 3210, 1, 1f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> GOLD_BRINGER = registerWeapon("gold_bringer", () -> new GoldBringer(0.0f, 3830, 3, 12.5f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> GRAVITY_BLASTER = registerWeapon("gravity_blaster", () -> new GravityBlaster(4.0f, 600, 1, 120f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> HELL_HORN = registerWeapon("hell_horn", () -> new HellHorn(12.5f, 3800, 8, 11.5f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> ILLUSION_REVOLVER = registerWeapon("illusion_revolver", () -> new IllusionRevolver(14.0f, 3200, 10, 20f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> ILLUSION_SMG = registerWeapon("illusion_smg", () -> new IllusionSMG(4.0f, 3240, 3, 7f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> ION_BLASTER = registerWeapon("ion_blaster", () -> new IonBlaster(13.0f, 2810, 11, 28.5f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> IRO_MINER = registerWeapon("iro_miner", () -> new IroMiner(4.0f, 3060, 4, 7f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> LASER_BLASTER = registerWeapon("laser_blaster", () -> new LaserBlaster(1.2f, 2840, 1, 20, 2.5f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> LIGHT_BLASTER = registerWeapon("light_blaster", () -> new LightBlaster(22.5f, 3810, 14, 20.5f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> LIGHT_SPARK = registerWeapon("light_spark", () -> new LightSpark(0.0f, 7, 1, 0f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> LUNA_BLASTER = registerWeapon("luna_blaster", () -> new LunaBlaster(3.0f, 3200, 2, 4f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> MECHA_BLASTER = registerWeapon("mecha_blaster", () -> new MechaBlaster(36.0f, 2770, 30, 80f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> MIND_BLASTER = registerWeapon("mind_blaster", () -> new MindBlaster(19.5f, 3180, 14, 27.5f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> MOON_DESTROYER = registerWeapon("moon_destroyer", () -> new MoonDestroyer(0.0f, 3750, 100, 60f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> MOON_SHINER = registerWeapon("moon_shiner", () -> new MoonShiner(3.5f, 1810, 5, 17.5f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> ODIOUS = registerWeapon("odious", () -> new Odious(1.0f, 3190, 1, 1.5f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> ORBOCRON = registerWeapon("orbocron", () -> new Orbocron(18.5f,  3230, 13, 26.5f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> PARALYZER = registerWeapon("paralyzer", () -> new Paralyzer(1.5f, 3900, 1, 1.5f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> PARTY_POPPER = registerWeapon("party_popper", () -> new PartyPopper(1.5f, 2810, 1, 3f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> POISON_PLUNGER = registerWeapon("poison_plunger", () -> new PoisonPlunger(0.0f, 2600, 20, 50f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> POWER_RAY = registerWeapon("power_ray", () -> new PowerRay(12.5f, 2490, 12, 38.5f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> PROTON = registerWeapon("proton", () -> new Proton(2.5f, 3000, 2, 4.5f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> REEFER = registerWeapon("reefer", () -> new Reefer(5.0f, 3600, 4, 7f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> REVOLUTION = registerWeapon("revolution", () -> new Revolution(0.0f, 2800, 20, 66f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> SEAOCRON = registerWeapon("seaocron", () -> new Seaocron(20.5f, 3800, 13, 18.5f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> SKULLO_BLASTER = registerWeapon("skullo_blaster", () -> new SkulloBlaster(3.5f, 3780, 2, 3f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> SOUL_DRAINER = registerWeapon("soul_drainer", () -> new SoulDrainer(0.2f, 3770, 1, 2f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> SOUL_SPARK = registerWeapon("soul_spark", () -> new SoulSpark(0.0f, 5, 1, 0f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> SOUL_STORM = registerWeapon("soul_storm", () -> new SoulStorm(1.5f, 3190, 1, 2f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> SPIRIT_SHOWER = registerWeapon("spirit_shower", () -> new SpiritShower(0.0f, 2870, 10, 100f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> SWARMOTRON = registerWeapon("swarmotron", () -> new Swarmotron(2.0f, 2400, 12, 33f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> TOXIC_TERRORIZER = registerWeapon("toxic_terrorizer", () -> new ToxicTerrorizer(0.0f, 2760, 7, 22f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> VORTEX_BLASTER = registerWeapon("vortex_blaster", () -> new VortexBlaster(0.0f, 2870, 1, 130f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> WHIMSY_WINDER = registerWeapon("whimsy_winder", () -> new WhimsyWinder(6.0f, 2830,5, 13f), AoACreativeModeTabs.BLASTERS.getKey());
	public static final DeferredHolder<Item, Item> WITHERS_WRATH = registerWeapon("withers_wrath", () -> new WithersWrath(7.5f, 800, 7, 21f), AoACreativeModeTabs.BLASTERS.getKey());

	private static <T extends Item> DeferredHolder<Item, T> registerWeapon(String registryName, Supplier<T> item, @Nullable ResourceKey<CreativeModeTab>... creativeTabs) {
		return AoAItems.registerItem(registryName, item, creativeTabs);
	}
}
