package net.tslat.aoa3.worldgen.structures.abyss;

import net.minecraft.block.BlockState;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.IWorld;
import net.tslat.aoa3.common.registration.AoABlocks;
import net.tslat.aoa3.worldgen.structures.AoAStructure;

import java.util.Random;

public class ShadeTree2 extends AoAStructure { //StructureSize: 7x35x7
	private static final BlockState shadowLeaves = AoABlocks.SHADOW_LEAVES.get().getDefaultState();
	private static final BlockState shadowLog = AoABlocks.SHADOW_LOG.get().getDefaultState();

	public ShadeTree2() {
		super("ShadeTree2");
	}

	@Override
	protected void build(IWorld world, Random rand, BlockPos basePos) {
		addBlock(world, basePos, 3, 0, 3, shadowLog);
		addBlock(world, basePos, 3, 1, 3, shadowLog);
		addBlock(world, basePos, 3, 2, 3, shadowLog);
		addBlock(world, basePos, 3, 3, 3, shadowLog);
		addBlock(world, basePos, 3, 4, 3, shadowLog);
		addBlock(world, basePos, 3, 5, 3, shadowLog);
		addBlock(world, basePos, 3, 6, 3, shadowLog);
		addBlock(world, basePos, 3, 7, 3, shadowLog);
		addBlock(world, basePos, 3, 8, 3, shadowLog);
		addBlock(world, basePos, 3, 9, 3, shadowLog);
		addBlock(world, basePos, 3, 10, 3, shadowLog);
		addBlock(world, basePos, 3, 11, 3, shadowLog);
		addBlock(world, basePos, 3, 12, 3, shadowLog);
		addBlock(world, basePos, 3, 13, 3, shadowLog);
		addBlock(world, basePos, 3, 14, 3, shadowLog);
		addBlock(world, basePos, 3, 15, 3, shadowLog);
		addBlock(world, basePos, 3, 16, 3, shadowLog);
		addBlock(world, basePos, 3, 17, 3, shadowLog);
		addBlock(world, basePos, 3, 18, 3, shadowLog);
		addBlock(world, basePos, 3, 19, 3, shadowLog);
		addBlock(world, basePos, 3, 20, 3, shadowLog);
		addBlock(world, basePos, 3, 21, 3, shadowLog);
		addBlock(world, basePos, 3, 22, 3, shadowLog);
		addBlock(world, basePos, 0, 23, 2, shadowLeaves);
		addBlock(world, basePos, 0, 23, 3, shadowLeaves);
		addBlock(world, basePos, 0, 23, 4, shadowLeaves);
		addBlock(world, basePos, 1, 23, 1, shadowLeaves);
		addBlock(world, basePos, 1, 23, 2, shadowLeaves);
		addBlock(world, basePos, 1, 23, 3, shadowLeaves);
		addBlock(world, basePos, 1, 23, 4, shadowLeaves);
		addBlock(world, basePos, 1, 23, 5, shadowLeaves);
		addBlock(world, basePos, 2, 23, 0, shadowLeaves);
		addBlock(world, basePos, 2, 23, 1, shadowLeaves);
		addBlock(world, basePos, 2, 23, 2, shadowLeaves);
		addBlock(world, basePos, 2, 23, 3, shadowLeaves);
		addBlock(world, basePos, 2, 23, 4, shadowLeaves);
		addBlock(world, basePos, 2, 23, 5, shadowLeaves);
		addBlock(world, basePos, 2, 23, 6, shadowLeaves);
		addBlock(world, basePos, 3, 23, 0, shadowLeaves);
		addBlock(world, basePos, 3, 23, 1, shadowLeaves);
		addBlock(world, basePos, 3, 23, 2, shadowLeaves);
		addBlock(world, basePos, 3, 23, 3, shadowLog);
		addBlock(world, basePos, 3, 23, 4, shadowLeaves);
		addBlock(world, basePos, 3, 23, 5, shadowLeaves);
		addBlock(world, basePos, 3, 23, 6, shadowLeaves);
		addBlock(world, basePos, 4, 23, 0, shadowLeaves);
		addBlock(world, basePos, 4, 23, 1, shadowLeaves);
		addBlock(world, basePos, 4, 23, 2, shadowLeaves);
		addBlock(world, basePos, 4, 23, 3, shadowLeaves);
		addBlock(world, basePos, 4, 23, 4, shadowLeaves);
		addBlock(world, basePos, 4, 23, 5, shadowLeaves);
		addBlock(world, basePos, 4, 23, 6, shadowLeaves);
		addBlock(world, basePos, 5, 23, 1, shadowLeaves);
		addBlock(world, basePos, 5, 23, 2, shadowLeaves);
		addBlock(world, basePos, 5, 23, 3, shadowLeaves);
		addBlock(world, basePos, 5, 23, 4, shadowLeaves);
		addBlock(world, basePos, 5, 23, 5, shadowLeaves);
		addBlock(world, basePos, 6, 23, 2, shadowLeaves);
		addBlock(world, basePos, 6, 23, 3, shadowLeaves);
		addBlock(world, basePos, 6, 23, 4, shadowLeaves);
		addBlock(world, basePos, 3, 24, 3, shadowLog);
		addBlock(world, basePos, 0, 25, 2, shadowLeaves);
		addBlock(world, basePos, 0, 25, 3, shadowLeaves);
		addBlock(world, basePos, 0, 25, 4, shadowLeaves);
		addBlock(world, basePos, 1, 25, 1, shadowLeaves);
		addBlock(world, basePos, 1, 25, 2, shadowLeaves);
		addBlock(world, basePos, 1, 25, 3, shadowLeaves);
		addBlock(world, basePos, 1, 25, 4, shadowLeaves);
		addBlock(world, basePos, 1, 25, 5, shadowLeaves);
		addBlock(world, basePos, 2, 25, 0, shadowLeaves);
		addBlock(world, basePos, 2, 25, 1, shadowLeaves);
		addBlock(world, basePos, 2, 25, 2, shadowLeaves);
		addBlock(world, basePos, 2, 25, 3, shadowLeaves);
		addBlock(world, basePos, 2, 25, 4, shadowLeaves);
		addBlock(world, basePos, 2, 25, 5, shadowLeaves);
		addBlock(world, basePos, 2, 25, 6, shadowLeaves);
		addBlock(world, basePos, 3, 25, 0, shadowLeaves);
		addBlock(world, basePos, 3, 25, 1, shadowLeaves);
		addBlock(world, basePos, 3, 25, 2, shadowLeaves);
		addBlock(world, basePos, 3, 25, 3, shadowLog);
		addBlock(world, basePos, 3, 25, 4, shadowLeaves);
		addBlock(world, basePos, 3, 25, 5, shadowLeaves);
		addBlock(world, basePos, 3, 25, 6, shadowLeaves);
		addBlock(world, basePos, 4, 25, 0, shadowLeaves);
		addBlock(world, basePos, 4, 25, 1, shadowLeaves);
		addBlock(world, basePos, 4, 25, 2, shadowLeaves);
		addBlock(world, basePos, 4, 25, 3, shadowLeaves);
		addBlock(world, basePos, 4, 25, 4, shadowLeaves);
		addBlock(world, basePos, 4, 25, 5, shadowLeaves);
		addBlock(world, basePos, 4, 25, 6, shadowLeaves);
		addBlock(world, basePos, 5, 25, 1, shadowLeaves);
		addBlock(world, basePos, 5, 25, 2, shadowLeaves);
		addBlock(world, basePos, 5, 25, 3, shadowLeaves);
		addBlock(world, basePos, 5, 25, 4, shadowLeaves);
		addBlock(world, basePos, 5, 25, 5, shadowLeaves);
		addBlock(world, basePos, 6, 25, 2, shadowLeaves);
		addBlock(world, basePos, 6, 25, 3, shadowLeaves);
		addBlock(world, basePos, 6, 25, 4, shadowLeaves);
		addBlock(world, basePos, 3, 26, 3, shadowLog);
		addBlock(world, basePos, 1, 27, 2, shadowLeaves);
		addBlock(world, basePos, 1, 27, 3, shadowLeaves);
		addBlock(world, basePos, 1, 27, 4, shadowLeaves);
		addBlock(world, basePos, 2, 27, 1, shadowLeaves);
		addBlock(world, basePos, 2, 27, 2, shadowLeaves);
		addBlock(world, basePos, 2, 27, 3, shadowLeaves);
		addBlock(world, basePos, 2, 27, 4, shadowLeaves);
		addBlock(world, basePos, 2, 27, 5, shadowLeaves);
		addBlock(world, basePos, 3, 27, 1, shadowLeaves);
		addBlock(world, basePos, 3, 27, 2, shadowLeaves);
		addBlock(world, basePos, 3, 27, 3, shadowLog);
		addBlock(world, basePos, 3, 27, 4, shadowLeaves);
		addBlock(world, basePos, 3, 27, 5, shadowLeaves);
		addBlock(world, basePos, 4, 27, 1, shadowLeaves);
		addBlock(world, basePos, 4, 27, 2, shadowLeaves);
		addBlock(world, basePos, 4, 27, 3, shadowLeaves);
		addBlock(world, basePos, 4, 27, 4, shadowLeaves);
		addBlock(world, basePos, 4, 27, 5, shadowLeaves);
		addBlock(world, basePos, 5, 27, 2, shadowLeaves);
		addBlock(world, basePos, 5, 27, 3, shadowLeaves);
		addBlock(world, basePos, 5, 27, 4, shadowLeaves);
		addBlock(world, basePos, 3, 28, 3, shadowLog);
		addBlock(world, basePos, 1, 29, 2, shadowLeaves);
		addBlock(world, basePos, 1, 29, 3, shadowLeaves);
		addBlock(world, basePos, 1, 29, 4, shadowLeaves);
		addBlock(world, basePos, 2, 29, 1, shadowLeaves);
		addBlock(world, basePos, 2, 29, 2, shadowLeaves);
		addBlock(world, basePos, 2, 29, 3, shadowLeaves);
		addBlock(world, basePos, 2, 29, 4, shadowLeaves);
		addBlock(world, basePos, 2, 29, 5, shadowLeaves);
		addBlock(world, basePos, 3, 29, 1, shadowLeaves);
		addBlock(world, basePos, 3, 29, 2, shadowLeaves);
		addBlock(world, basePos, 3, 29, 3, shadowLog);
		addBlock(world, basePos, 3, 29, 4, shadowLeaves);
		addBlock(world, basePos, 3, 29, 5, shadowLeaves);
		addBlock(world, basePos, 4, 29, 1, shadowLeaves);
		addBlock(world, basePos, 4, 29, 2, shadowLeaves);
		addBlock(world, basePos, 4, 29, 3, shadowLeaves);
		addBlock(world, basePos, 4, 29, 4, shadowLeaves);
		addBlock(world, basePos, 4, 29, 5, shadowLeaves);
		addBlock(world, basePos, 5, 29, 2, shadowLeaves);
		addBlock(world, basePos, 5, 29, 3, shadowLeaves);
		addBlock(world, basePos, 5, 29, 4, shadowLeaves);
		addBlock(world, basePos, 3, 30, 3, shadowLog);
		addBlock(world, basePos, 2, 31, 2, shadowLeaves);
		addBlock(world, basePos, 2, 31, 3, shadowLeaves);
		addBlock(world, basePos, 2, 31, 4, shadowLeaves);
		addBlock(world, basePos, 3, 31, 2, shadowLeaves);
		addBlock(world, basePos, 3, 31, 3, shadowLog);
		addBlock(world, basePos, 3, 31, 4, shadowLeaves);
		addBlock(world, basePos, 4, 31, 2, shadowLeaves);
		addBlock(world, basePos, 4, 31, 3, shadowLeaves);
		addBlock(world, basePos, 4, 31, 4, shadowLeaves);
		addBlock(world, basePos, 3, 32, 3, shadowLog);
		addBlock(world, basePos, 2, 33, 3, shadowLeaves);
		addBlock(world, basePos, 3, 33, 2, shadowLeaves);
		addBlock(world, basePos, 3, 33, 3, shadowLeaves);
		addBlock(world, basePos, 3, 33, 4, shadowLeaves);
		addBlock(world, basePos, 4, 33, 3, shadowLeaves);
		addBlock(world, basePos, 3, 34, 3, shadowLeaves);
	}
}
