package net.nevermine.structures.dustopia;

import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenerator;
import net.nevermine.izer.Blockizer;

import java.util.Random;

public class PrimordialShrine extends WorldGenerator {
	public boolean generate(final World world, final Random rand, final int i, final int j, final int k) {
		if (world.getBlock(i + 3, j - 1, k + 4) != Blockizer.GrassDustopia) {
			return false;
		}
		world.setBlock(i + 0, j + 0, k + 0, Blockizer.StoneDustopia);
		world.setBlock(i + 0, j + 0, k + 1, Blockizer.StoneDustopia);
		world.setBlock(i + 0, j + 0, k + 2, Blockizer.StoneDustopia);
		world.setBlock(i + 0, j + 0, k + 3, Blockizer.StoneDustopia);
		world.setBlock(i + 0, j + 0, k + 4, Blockizer.StoneDustopia);
		world.setBlock(i + 0, j + 0, k + 5, Blockizer.StoneDustopia);
		world.setBlock(i + 0, j + 0, k + 6, Blockizer.StoneDustopia);
		world.setBlock(i + 0, j + 0, k + 7, Blockizer.StoneDustopia);
		world.setBlock(i + 0, j + 0, k + 8, Blockizer.StoneDustopia);
		world.setBlock(i + 0, j + 0, k + 9, Blockizer.StoneDustopia);
		world.setBlock(i + 0, j + 0, k + 10, Blockizer.StoneDustopia);
		world.setBlock(i + 0, j + 1, k + 0, Blockizer.DawnwoodBars);
		world.setBlock(i + 0, j + 1, k + 10, Blockizer.DawnwoodBars);
		world.setBlock(i + 0, j + 2, k + 0, Blockizer.DustopianLampOff);
		world.setBlock(i + 0, j + 2, k + 10, Blockizer.DustopianLampOff);
		world.setBlock(i + 1, j + 0, k + 0, Blockizer.StoneDustopia);
		world.setBlock(i + 1, j + 0, k + 1, Blockizer.StoneDustopia);
		world.setBlock(i + 1, j + 0, k + 2, Blockizer.StoneDustopia);
		world.setBlock(i + 1, j + 0, k + 3, Blockizer.StoneDustopia);
		world.setBlock(i + 1, j + 0, k + 4, Blockizer.StoneDustopia);
		world.setBlock(i + 1, j + 0, k + 5, Blockizer.StoneDustopia);
		world.setBlock(i + 1, j + 0, k + 6, Blockizer.StoneDustopia);
		world.setBlock(i + 1, j + 0, k + 7, Blockizer.StoneDustopia);
		world.setBlock(i + 1, j + 0, k + 8, Blockizer.StoneDustopia);
		world.setBlock(i + 1, j + 0, k + 9, Blockizer.StoneDustopia);
		world.setBlock(i + 1, j + 0, k + 10, Blockizer.StoneDustopia);
		world.setBlock(i + 2, j + 0, k + 0, Blockizer.StoneDustopia);
		world.setBlock(i + 2, j + 0, k + 1, Blockizer.StoneDustopia);
		world.setBlock(i + 2, j + 0, k + 2, Blockizer.StoneDustopia);
		world.setBlock(i + 2, j + 0, k + 3, Blockizer.StoneDustopia);
		world.setBlock(i + 2, j + 0, k + 4, Blockizer.StoneDustopia);
		world.setBlock(i + 2, j + 0, k + 5, Blockizer.StoneDustopia);
		world.setBlock(i + 2, j + 0, k + 6, Blockizer.StoneDustopia);
		world.setBlock(i + 2, j + 0, k + 7, Blockizer.StoneDustopia);
		world.setBlock(i + 2, j + 0, k + 8, Blockizer.StoneDustopia);
		world.setBlock(i + 2, j + 0, k + 9, Blockizer.StoneDustopia);
		world.setBlock(i + 2, j + 0, k + 10, Blockizer.StoneDustopia);
		world.setBlock(i + 2, j + 1, k + 1, Blockizer.DawnwoodBars);
		world.setBlock(i + 2, j + 1, k + 9, Blockizer.DawnwoodBars);
		world.setBlock(i + 2, j + 2, k + 1, Blockizer.DustopianLampOff);
		world.setBlock(i + 2, j + 2, k + 9, Blockizer.DustopianLampOff);
		world.setBlock(i + 3, j + 0, k + 0, Blockizer.StoneDustopia);
		world.setBlock(i + 3, j + 0, k + 1, Blockizer.StoneDustopia);
		world.setBlock(i + 3, j + 0, k + 2, Blockizer.StoneDustopia);
		world.setBlock(i + 3, j + 0, k + 3, Blockizer.StoneDustopia);
		world.setBlock(i + 3, j + 0, k + 4, Blockizer.StoneDustopia);
		world.setBlock(i + 3, j + 0, k + 5, Blockizer.StoneDustopia);
		world.setBlock(i + 3, j + 0, k + 6, Blockizer.StoneDustopia);
		world.setBlock(i + 3, j + 0, k + 7, Blockizer.StoneDustopia);
		world.setBlock(i + 3, j + 0, k + 8, Blockizer.StoneDustopia);
		world.setBlock(i + 3, j + 0, k + 9, Blockizer.StoneDustopia);
		world.setBlock(i + 3, j + 0, k + 10, Blockizer.StoneDustopia);
		world.setBlock(i + 3, j + 1, k + 3, Blockizer.DawnwoodPlanks);
		world.setBlock(i + 3, j + 1, k + 4, Blockizer.DawnwoodPlanks);
		world.setBlock(i + 3, j + 1, k + 5, Blockizer.PrimordialShrine);
		world.setBlock(i + 3, j + 1, k + 6, Blockizer.DawnwoodPlanks);
		world.setBlock(i + 3, j + 1, k + 7, Blockizer.DawnwoodPlanks);
		world.setBlock(i + 4, j + 0, k + 0, Blockizer.StoneDustopia);
		world.setBlock(i + 4, j + 0, k + 1, Blockizer.StoneDustopia);
		world.setBlock(i + 4, j + 0, k + 2, Blockizer.StoneDustopia);
		world.setBlock(i + 4, j + 0, k + 3, Blockizer.StoneDustopia);
		world.setBlock(i + 4, j + 0, k + 4, Blockizer.StoneDustopia);
		world.setBlock(i + 4, j + 0, k + 5, Blockizer.StoneDustopia);
		world.setBlock(i + 4, j + 0, k + 6, Blockizer.StoneDustopia);
		world.setBlock(i + 4, j + 0, k + 7, Blockizer.StoneDustopia);
		world.setBlock(i + 4, j + 0, k + 8, Blockizer.StoneDustopia);
		world.setBlock(i + 4, j + 0, k + 9, Blockizer.StoneDustopia);
		world.setBlock(i + 4, j + 0, k + 10, Blockizer.StoneDustopia);
		world.setBlock(i + 4, j + 1, k + 2, Blockizer.DawnwoodPlanks);
		world.setBlock(i + 4, j + 1, k + 3, Blockizer.DawnwoodPlanks);
		world.setBlock(i + 4, j + 1, k + 4, Blockizer.DawnwoodPlanks);
		world.setBlock(i + 4, j + 1, k + 5, Blockizer.DawnwoodPlanks);
		world.setBlock(i + 4, j + 1, k + 6, Blockizer.DawnwoodPlanks);
		world.setBlock(i + 4, j + 1, k + 7, Blockizer.DawnwoodPlanks);
		world.setBlock(i + 4, j + 1, k + 8, Blockizer.DawnwoodPlanks);
		world.setBlock(i + 4, j + 2, k + 2, Blockizer.DawnwoodBars);
		world.setBlock(i + 4, j + 2, k + 3, Blockizer.DawnwoodPlanks);
		world.setBlock(i + 4, j + 2, k + 4, Blockizer.DawnwoodPlanks);
		world.setBlock(i + 4, j + 2, k + 5, Blockizer.DawnwoodPlanks);
		world.setBlock(i + 4, j + 2, k + 6, Blockizer.DawnwoodPlanks);
		world.setBlock(i + 4, j + 2, k + 7, Blockizer.DawnwoodPlanks);
		world.setBlock(i + 4, j + 2, k + 8, Blockizer.DawnwoodBars);
		world.setBlock(i + 4, j + 3, k + 2, Blockizer.DawnwoodBars);
		world.setBlock(i + 4, j + 3, k + 4, Blockizer.DawnwoodPlanks);
		world.setBlock(i + 4, j + 3, k + 6, Blockizer.DawnwoodPlanks);
		world.setBlock(i + 4, j + 3, k + 8, Blockizer.DawnwoodBars);
		world.setBlock(i + 4, j + 4, k + 2, Blockizer.DustopianLampOff);
		world.setBlock(i + 4, j + 4, k + 4, Blockizer.DawnwoodBars);
		world.setBlock(i + 4, j + 4, k + 6, Blockizer.DawnwoodBars);
		world.setBlock(i + 4, j + 4, k + 8, Blockizer.DustopianLampOff);
		world.setBlock(i + 4, j + 5, k + 4, Blockizer.DawnwoodBars);
		world.setBlock(i + 4, j + 5, k + 6, Blockizer.DawnwoodBars);
		world.setBlock(i + 4, j + 6, k + 4, Blockizer.DustopianLampOff);
		world.setBlock(i + 4, j + 6, k + 6, Blockizer.DustopianLampOff);
		return true;
	}
}
